/**
 * seoMap.ts — Centralized SEO Metadata Registry
 * Autonomous Software Discovery Edition
 *
 * Single source of truth for every PUBLIC indexed page.
 * Each entry has a UNIQUE primary keyword — no cannibalization.
 *
 * RULES:
 * - NO version numbers, module counts, artifact totals
 * - NO "world first", "coming soon", roadmap claims
 * - NO metrics that can change
 * - Titles ≤60 chars, primary keyword front-loaded
 * - Descriptions 140-160 chars, clear value, no hype
 * - OG images unique per section
 * - Keywords fan out — zero overlap across pages
 */

export interface PageSEO {
  title: string;
  description: string;
  ogTitle: string;
  ogDescription: string;
  ogImage: string;
  keywords: string[];
  schema: 'home' | 'feature' | 'docs' | 'blog' | 'about' | 'legal' | 'contact' | 'product' | 'article';
  intent: string;
  primaryKeyword: string;
  noindex?: boolean;
}

const OG_BASE = 'https://cmpsbl.com';

// Section-specific OG images (unique per section)
const OG_HOME = `${OG_BASE}/og/home.jpg`;
const OG_SUBSTRATE = `${OG_BASE}/og/substrate-os.jpg`;
const OG_STORE = `${OG_BASE}/og/store.jpg`;
const OG_DEVELOPERS = `${OG_BASE}/og/developers.jpg`;
const OG_PRICING = `${OG_BASE}/og/pricing.jpg`;
const OG_BLOG = `${OG_BASE}/og/blog.jpg`;
const OG_ABOUT = `${OG_BASE}/og/about.jpg`;
const OG_DOCS = `${OG_BASE}/og/documentation.jpg`;
const OG_FEATURE = `${OG_BASE}/og/modules.jpg`;
const OG_SOLUTIONS = `${OG_BASE}/og/solutions.jpg`;
const OG_INVESTORS = `${OG_BASE}/og/investors.jpg`;
const OG_ACADEMY = `${OG_BASE}/og/academy.jpg`;
const OG_COGNITIVES = `${OG_BASE}/og/cognitives.jpg`;
const OG_ENGINES = `${OG_BASE}/og/engines.jpg`;
const OG_MEMORY = `${OG_BASE}/og/persistent-memory.jpg`;
const OG_DECODE = `${OG_BASE}/og/decode.jpg`;
const OG_DREAM = `${OG_BASE}/og/dream-feeder.jpg`;
const OG_PROOF = `${OG_BASE}/og/proof.jpg`;
const OG_GAMING = `${OG_BASE}/og/gaming.jpg`;
const OG_ARCHITECTURE = `${OG_BASE}/og/architecture.jpg`;
const OG_INTENT = `${OG_BASE}/og/intent-mesh.jpg`;

export const seoMap: Record<string, PageSEO> = {
  // ═══════════════════════════════════════════════════
  // CORE PUBLIC
  // ═══════════════════════════════════════════════════
  '/': {
    title: 'CMPSBL — AI Infrastructure for Autonomous Software Discovery',
    description: 'CMPSBL is a cognitive infrastructure platform where autonomous systems discover, crystallize, and export deployable software pipelines & hardware architectures.',
    ogTitle: 'CMPSBL — AI Infrastructure for Autonomous Software Discovery',
    ogDescription: 'Autonomous systems that discover, crystallize, and export deployable software pipelines & hardware architectures.',
    ogImage: OG_HOME,
    keywords: ['autonomous software discovery', 'cognitive infrastructure platform', 'deployable pipeline export', 'hardware architecture AI', 'signal crystallization', 'governed runtime', 'self-assembling pipelines', 'AI substrate'],
    schema: 'home',
    intent: 'Brand/Category',
    primaryKeyword: 'autonomous software discovery',
  },
  '/os': {
    title: 'Substrate Runtime — Live Orchestration | CMPSBL',
    description: 'Real-time cognitive orchestration engine with telemetry dashboards, autonomous workload scheduling, and multi-sector execution control.',
    ogTitle: 'Substrate Runtime — Live Orchestration',
    ogDescription: 'Real-time cognitive orchestration with telemetry and workload scheduling.',
    ogImage: OG_SUBSTRATE,
    keywords: ['cognitive orchestration engine', 'workload scheduling AI', 'runtime telemetry', 'execution control', 'sector management', 'live orchestration'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive orchestration engine',
  },
  '/ai-operating-system': {
    title: 'AI Operating System — Unified Runtime | CMPSBL',
    description: 'Unified cognitive OS merging memory persistence, intent routing, security enforcement, and pipeline discovery into one executable surface.',
    ogTitle: 'AI Operating System — Unified Runtime',
    ogDescription: 'One runtime unifying memory, routing, security, and discovery.',
    ogImage: OG_SUBSTRATE,
    keywords: ['AI operating system', 'unified cognitive runtime', 'executable surface', 'intent routing OS', 'memory persistence layer', 'security enforcement'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI operating system unified runtime',
  },
  '/modules': {
    title: 'Substrate Nodes — Layered Architecture | CMPSBL',
    description: 'Browse kernel, cognitive, operational, and expansion nodes organized by sector. Each node is independently deployable and composable.',
    ogTitle: 'Substrate Nodes — Layered Architecture',
    ogDescription: 'Independently deployable cognitive nodes organized by sector.',
    ogImage: OG_FEATURE,
    keywords: ['substrate nodes', 'layered AI architecture', 'deployable nodes', 'sector topology', 'composable building blocks', 'kernel nodes'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'substrate node architecture',
  },
  '/store': {
    title: 'Capability Store — Pipeline Components | CMPSBL',
    description: 'Browse and deploy tier-scoped pipeline components, synergy templates, and executable capabilities for production cognitive workloads.',
    ogTitle: 'Capability Store — Pipeline Components',
    ogDescription: 'Deploy pipeline components, synergy templates, and capabilities.',
    ogImage: OG_STORE,
    keywords: ['pipeline components store', 'synergy templates', 'executable capabilities', 'cognitive marketplace', 'tier-scoped artifacts', 'workload components'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'pipeline component store',
  },
  '/composable-cognitives': {
    title: 'Composable Cognitives — Portable AI Agents | CMPSBL',
    description: 'Build or buy permanent cognitive agents. Download once, deploy anywhere — subscription-free portable AI that you own outright.',
    ogTitle: 'Composable Cognitives — Portable AI Agents',
    ogDescription: 'Permanent cognitive agents you download once and deploy anywhere.',
    ogImage: OG_COGNITIVES,
    keywords: ['portable AI agents', 'downloadable cognitives', 'permanent AI ownership', 'subscription-free agents', 'self-hosted cognitive', 'agent export'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'portable cognitive agents',
  },
  '/engines': {
    title: 'Orchestration Engines — Pre-Validated | CMPSBL',
    description: 'Pre-validated orchestration engines for enterprise cognitive workloads. Canonized workflows tested and maintained by CMPSBL engineering.',
    ogTitle: 'Orchestration Engines — Pre-Validated',
    ogDescription: 'Canonized enterprise workflows tested by CMPSBL engineering.',
    ogImage: OG_ENGINES,
    keywords: ['orchestration engines', 'canonized workflows', 'enterprise pipeline engines', 'pre-validated AI', 'multi-agent orchestration', 'workflow automation'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'pre-validated orchestration engines',
  },
  '/persistent-memory': {
    title: 'Persistent Memory — Agent State API | CMPSBL',
    description: 'Add cross-session memory to any AI agent in minutes. Works with LangChain, CrewAI, and custom frameworks. Free tier included.',
    ogTitle: 'Persistent Memory — Agent State API',
    ogDescription: 'Cross-session memory for any AI agent. Free tier included.',
    ogImage: OG_MEMORY,
    keywords: ['agent state API', 'cross-session memory', 'episodic recall', 'LangChain memory', 'CrewAI integration', 'context persistence'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'persistent agent state API',
  },
  '/decode': {
    title: 'DECODE — Natural Language Terminal | CMPSBL',
    description: 'Interact with the cognitive substrate through natural language. DECODE translates spoken intent into orchestrated module operations.',
    ogTitle: 'DECODE — Natural Language Terminal',
    ogDescription: 'Translate spoken intent into orchestrated module operations.',
    ogImage: OG_DECODE,
    keywords: ['natural language terminal', 'intent translation', 'cognitive CLI', 'spoken command AI', 'substrate interaction', 'conversational orchestration'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'natural language cognitive terminal',
  },
  '/feed-dream-eater': {
    title: 'Dream Feeder — Idle-Cycle Learning | CMPSBL',
    description: 'Autonomous learning system converting idle-cycle experience into heuristic upgrades. Recursive self-improvement without manual retraining.',
    ogTitle: 'Dream Feeder — Idle-Cycle Learning',
    ogDescription: 'Recursive self-improvement from idle-cycle experience processing.',
    ogImage: OG_DREAM,
    keywords: ['idle-cycle learning', 'heuristic upgrades', 'recursive self-improvement', 'dream synthesis', 'autonomous retraining', 'experience processing'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'idle-cycle autonomous learning',
  },
  '/proof': {
    title: 'Proof Mode — Cryptographic Audit Trail | CMPSBL',
    description: 'Tamper-evident cryptographic records of every cognitive operation. Built for regulatory compliance, forensic audit, and governed AI.',
    ogTitle: 'Proof Mode — Cryptographic Audit Trail',
    ogDescription: 'Tamper-evident records for compliance and forensic audit.',
    ogImage: OG_PROOF,
    keywords: ['cryptographic audit trail', 'tamper-evident AI', 'regulatory compliance AI', 'forensic audit', 'governed execution', 'provenance chain'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cryptographic AI audit trail',
  },
  '/demo': {
    title: 'Live Demo — Substrate in Action | CMPSBL',
    description: 'Interactive demonstration of cognitive orchestration, pipeline discovery, and adaptive inference running across the production substrate.',
    ogTitle: 'Live Demo — Substrate in Action',
    ogDescription: 'Interactive cognitive orchestration and pipeline discovery demo.',
    ogImage: OG_HOME,
    keywords: ['interactive substrate demo', 'cognitive orchestration demo', 'pipeline discovery walkthrough', 'AI infrastructure preview'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'interactive substrate demo',
  },
  '/demos': {
    title: 'Advanced Demos — Cognitive Capabilities | CMPSBL',
    description: 'Experience self-healing architecture, provenance verification, sovereign execution, and living module topology in guided walkthroughs.',
    ogTitle: 'Advanced Demos — Cognitive Capabilities',
    ogDescription: 'Self-healing, provenance, and sovereign execution walkthroughs.',
    ogImage: OG_FEATURE,
    keywords: ['self-healing architecture demo', 'provenance verification', 'sovereign execution', 'module topology visualization', 'advanced AI demo'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'advanced cognitive capability demos',
  },
  '/lab': {
    title: 'Experimentation Lab — AI Sandbox | CMPSBL',
    description: 'Sandboxed environment to test, benchmark, and validate cognitive experiments before deploying workloads to the production substrate.',
    ogTitle: 'Experimentation Lab — AI Sandbox',
    ogDescription: 'Test and benchmark cognitive experiments before production.',
    ogImage: OG_FEATURE,
    keywords: ['AI sandbox', 'cognitive experiment lab', 'benchmarking environment', 'workload validation', 'pre-production testing'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive experiment sandbox',
  },
  '/codelab': {
    title: 'CodeLab — Live Code Editor | CMPSBL',
    description: 'Write, execute, and iterate on substrate operations in a live coding environment with real-time feedback and inline API reference.',
    ogTitle: 'CodeLab — Live Code Editor',
    ogDescription: 'Live coding with real-time execution and inline API reference.',
    ogImage: OG_DOCS,
    keywords: ['live code editor', 'substrate coding environment', 'real-time execution', 'inline API reference', 'developer playground'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'live substrate code editor',
  },
  '/gaming': {
    title: 'Gaming AI — Cognitive NPC Engine | CMPSBL',
    description: 'Power game characters with persistent memory and adaptive behavior. Built for Unreal, Unity, and custom game engines.',
    ogTitle: 'Gaming AI — Cognitive NPC Engine',
    ogDescription: 'Persistent-memory NPCs with adaptive behavior for game engines.',
    ogImage: OG_GAMING,
    keywords: ['cognitive NPC engine', 'persistent memory NPC', 'adaptive game AI', 'Unreal AI integration', 'Unity cognitive agents', 'game character AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive NPC game engine',
  },
  '/system-feed': {
    title: 'System Feed — Real-Time Intelligence | CMPSBL',
    description: 'Live stream of cognitive events, anomaly detections, and learning breakthroughs flowing across all active substrate sectors.',
    ogTitle: 'System Feed — Real-Time Intelligence',
    ogDescription: 'Live cognitive events and anomaly detections across sectors.',
    ogImage: OG_FEATURE,
    keywords: ['real-time intelligence feed', 'cognitive event stream', 'anomaly detection feed', 'sector telemetry', 'live AI monitoring'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'real-time cognitive intelligence feed',
  },

  // ═══════════════════════════════════════════════════
  // DEVELOPER / DOCS
  // ═══════════════════════════════════════════════════
  '/developers': {
    title: 'Developer Hub — SDKs & Integration | CMPSBL',
    description: 'SDKs, REST APIs, webhooks, and step-by-step integration guides for building autonomous discovery pipelines on the substrate.',
    ogTitle: 'Developer Hub — SDKs & Integration',
    ogDescription: 'SDKs, APIs, and guides for building on the substrate.',
    ogImage: OG_DEVELOPERS,
    keywords: ['substrate SDK', 'REST API integration', 'webhook configuration', 'developer onboarding', 'pipeline SDK', 'API quickstart'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate SDK integration',
  },
  '/documentation': {
    title: 'Documentation — Technical Reference | CMPSBL',
    description: 'Complete technical reference covering module APIs, configuration schemas, deployment patterns, and operational runbooks for builders.',
    ogTitle: 'Documentation — Technical Reference',
    ogDescription: 'Module APIs, configuration schemas, and deployment patterns.',
    ogImage: OG_DOCS,
    keywords: ['technical reference', 'module API docs', 'configuration schemas', 'deployment patterns', 'operational runbooks', 'builder documentation'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate technical reference',
  },
  '/docs/persistent-memory': {
    title: 'Memory Quickstart — Integration Guide | CMPSBL',
    description: 'Step-by-step guide to adding persistent memory to your agent. Covers LangChain, CrewAI, and raw SDK integration with code samples.',
    ogTitle: 'Memory Quickstart — Integration Guide',
    ogDescription: 'Add persistent memory to your agent in minutes — with code samples.',
    ogImage: OG_MEMORY,
    keywords: ['memory integration guide', 'LangChain quickstart', 'CrewAI memory setup', 'agent memory tutorial', 'SDK code samples'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'persistent memory integration quickstart',
  },
  '/docs/substrate/capabilities': {
    title: 'Capabilities Reference — API Catalog | CMPSBL',
    description: 'Full catalog of substrate capabilities: parameter schemas, tier availability, synergy compatibility, and usage examples for each endpoint.',
    ogTitle: 'Capabilities Reference — API Catalog',
    ogDescription: 'Browse every capability with schemas and usage examples.',
    ogImage: OG_STORE,
    keywords: ['capabilities catalog', 'API parameter schemas', 'tier availability matrix', 'synergy compatibility', 'endpoint reference'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate capabilities API catalog',
  },
  '/academy': {
    title: 'Academy — Interactive AI Tutorials | CMPSBL',
    description: 'Learn substrate development through interactive tutorials. From first-agent walkthroughs to advanced multi-sector orchestration patterns.',
    ogTitle: 'Academy — Interactive AI Tutorials',
    ogDescription: 'Interactive tutorials from first agent to advanced orchestration.',
    ogImage: OG_ACADEMY,
    keywords: ['interactive AI tutorials', 'substrate training', 'agent building course', 'orchestration patterns', 'hands-on AI learning'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'interactive substrate tutorials',
  },
  '/devtools': {
    title: 'DevTools — Runtime Diagnostics | CMPSBL',
    description: 'Debug your substrate live: module state inspector, network tracer, memory explorer, and performance profiler for development builds.',
    ogTitle: 'DevTools — Runtime Diagnostics',
    ogDescription: 'Live debugging with module inspector and performance profiler.',
    ogImage: OG_DOCS,
    keywords: ['runtime diagnostics', 'module state inspector', 'network tracer', 'memory explorer', 'performance profiler', 'developer debugging'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate runtime diagnostics',
  },
  '/changelog': {
    title: 'Changelog — Release History | CMPSBL',
    description: 'Track every substrate release: new modules, capability additions, security patches, and architectural refinements over time.',
    ogTitle: 'Changelog — Release History',
    ogDescription: 'Complete release history for the cognitive substrate.',
    ogImage: OG_DOCS,
    keywords: ['release history', 'substrate changelog', 'capability additions', 'security patches', 'architecture updates'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate release changelog',
  },

  // ═══════════════════════════════════════════════════
  // ENTERPRISE / PRICING
  // ═══════════════════════════════════════════════════
  '/solutions': {
    title: 'Enterprise Solutions — Industry AI | CMPSBL',
    description: 'Industry-specific cognitive infrastructure for healthcare, finance, legal, and manufacturing with compliance-ready on-prem deployment.',
    ogTitle: 'Enterprise Solutions — Industry AI',
    ogDescription: 'Industry-specific cognitive infrastructure with on-prem deployment.',
    ogImage: OG_SOLUTIONS,
    keywords: ['enterprise cognitive solutions', 'healthcare AI platform', 'finance AI compliance', 'on-prem AI deployment', 'industry-specific AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'enterprise industry AI solutions',
  },
  '/use-cases': {
    title: 'Use Cases — Production Deployments | CMPSBL',
    description: 'Real-world deployments: autonomous research agencies, code review pipelines, support agents, and self-healing infrastructure stacks.',
    ogTitle: 'Use Cases — Production Deployments',
    ogDescription: 'Real deployments across research, code review, and self-healing.',
    ogImage: OG_SOLUTIONS,
    keywords: ['production AI deployments', 'autonomous research agency', 'code review pipeline', 'self-healing infrastructure', 'multi-agent deployment'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'production AI deployment use cases',
  },
  '/pricing': {
    title: 'Pricing — Free Through Enterprise | CMPSBL',
    description: 'Transparent pricing at every scale. Free developer tier with persistent memory, scaling through production and enterprise compliance.',
    ogTitle: 'Pricing — Free Through Enterprise',
    ogDescription: 'Transparent pricing from free developer tier to enterprise.',
    ogImage: OG_PRICING,
    keywords: ['transparent AI pricing', 'free developer tier', 'enterprise compliance tier', 'production scaling', 'cognitive platform cost'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'substrate pricing tiers',
  },
  '/substrate/licensing': {
    title: 'Enterprise Licensing & OEM | CMPSBL',
    description: 'Volume licensing, OEM embedding, and white-label agreements for organizations deploying the substrate at infrastructure scale.',
    ogTitle: 'Enterprise Licensing & OEM',
    ogDescription: 'Volume licensing, OEM embedding, and white-label options.',
    ogImage: OG_PRICING,
    keywords: ['enterprise licensing', 'OEM AI embedding', 'white-label cognitive', 'volume agreement', 'infrastructure licensing'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'enterprise OEM licensing',
  },
  '/intelligence': {
    title: 'Substrate Intelligence — Validation | CMPSBL',
    description: 'Architectural validation dashboard showing interaction graphs, capability coverage metrics, and infrastructure proof points.',
    ogTitle: 'Substrate Intelligence — Validation',
    ogDescription: 'Interaction graphs and capability coverage validation.',
    ogImage: OG_FEATURE,
    keywords: ['architectural validation', 'interaction graphs', 'capability coverage', 'infrastructure proof', 'substrate verification'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'substrate architectural validation',
  },
  '/investors': {
    title: 'Acquisition Opportunity | CMPSBL®',
    description: 'Generational acquisition: deep R&D portfolio, defensible IP estate, and cognitive infrastructure positioned for the autonomous era.',
    ogTitle: 'Acquisition Opportunity — CMPSBL',
    ogDescription: 'Deep R&D, defensible IP, and cognitive infrastructure acquisition.',
    ogImage: OG_INVESTORS,
    keywords: ['strategic acquisition', 'AI IP portfolio', 'cognitive infrastructure investment', 'defensible technology', 'R&D asset acquisition'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'cognitive infrastructure acquisition',
  },
  '/marketplace': {
    title: 'Marketplace — Templates & Integrations | CMPSBL',
    description: 'Browse first-party and community templates, pre-built integrations, and ready-to-deploy cognitive workflows in the marketplace.',
    ogTitle: 'Marketplace — Templates & Integrations',
    ogDescription: 'Templates, integrations, and ready-to-deploy cognitive workflows.',
    ogImage: OG_STORE,
    keywords: ['cognitive templates', 'pre-built integrations', 'workflow marketplace', 'ready-to-deploy AI', 'community templates'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive workflow marketplace',
  },

  // ═══════════════════════════════════════════════════
  // COMPANY / ABOUT / TRUST
  // ═══════════════════════════════════════════════════
  '/about': {
    title: 'About CMPSBL — Founded 2009, Dallas TX',
    description: 'Founded in 2009 by Kenneth E Sweet Jr in Dallas. Building governed cognitive infrastructure for autonomous software discovery.',
    ogTitle: 'About CMPSBL — Founded 2009, Dallas TX',
    ogDescription: 'Building cognitive infrastructure since 2009 in Dallas, TX.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL origin', 'Kenneth Sweet founder', 'Dallas AI company', 'cognitive infrastructure history', '2009 founding'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL founder origin story',
  },
  '/contact': {
    title: 'Contact — Partnerships & Inquiries | CMPSBL',
    description: 'Reach the CMPSBL team for enterprise partnerships, integration support, press inquiries, or technical questions. Dallas, TX worldwide.',
    ogTitle: 'Contact — Partnerships & Inquiries',
    ogDescription: 'Enterprise partnerships, integration support, and press inquiries.',
    ogImage: OG_ABOUT,
    keywords: ['enterprise partnership inquiry', 'integration support', 'press contact', 'technical questions', 'CMPSBL team'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'contact CMPSBL partnerships',
  },
  '/support': {
    title: 'Support Center — Help & Resources | CMPSBL',
    description: 'Knowledge base, ticket system, community forums, and direct engineering support for substrate builders and enterprise customers.',
    ogTitle: 'Support Center — Help & Resources',
    ogDescription: 'Knowledge base, tickets, and engineering support for builders.',
    ogImage: OG_ABOUT,
    keywords: ['help center', 'ticket system', 'community forums', 'engineering support', 'builder resources'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'substrate support center',
  },

  // ═══════════════════════════════════════════════════
  // BLOG / CONTENT
  // ═══════════════════════════════════════════════════
  '/blog': {
    title: 'Blog — Research & Engineering Insights | CMPSBL',
    description: 'Deep-dives on cognitive architecture, autonomous discovery patterns, memory systems, and governed orchestration from CMPSBL engineering.',
    ogTitle: 'Blog — Research & Engineering Insights',
    ogDescription: 'Cognitive architecture and autonomous discovery insights.',
    ogImage: OG_BLOG,
    keywords: ['cognitive architecture research', 'discovery pattern analysis', 'memory system insights', 'governed orchestration blog', 'engineering deep-dives'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive architecture research blog',
  },
  '/publication': {
    title: 'Publications — Research Papers | CMPSBL',
    description: 'Whitepapers on autonomous system architecture, dream-cycle learning theory, and pipeline crystallization from CMPSBL research.',
    ogTitle: 'Publications — Research Papers',
    ogDescription: 'Research papers on autonomous architecture and dream-cycle theory.',
    ogImage: OG_BLOG,
    keywords: ['AI research papers', 'dream-cycle theory', 'pipeline crystallization paper', 'autonomous system whitepaper', 'Zenodo archives'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'autonomous system research papers',
  },
  '/library': {
    title: 'Library — Documentation Archive | CMPSBL',
    description: 'Curated archive of architectural references, module specifications, protocol standards, and development resources for substrate builders.',
    ogTitle: 'Library — Documentation Archive',
    ogDescription: 'Curated architectural references and module specifications.',
    ogImage: OG_DOCS,
    keywords: ['documentation archive', 'architectural references', 'module specifications', 'protocol standards', 'builder resources'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate documentation archive',
  },
  '/insights': {
    title: 'Insights — Industry Analysis | CMPSBL',
    description: 'Data-driven analysis of autonomous AI trends, market dynamics, and technological shifts from the CMPSBL intelligence team.',
    ogTitle: 'Insights — Industry Analysis',
    ogDescription: 'Data-driven analysis of autonomous AI trends and market shifts.',
    ogImage: OG_BLOG,
    keywords: ['autonomous AI trends', 'market dynamics analysis', 'technological shift report', 'industry intelligence', 'AI landscape analysis'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'autonomous AI industry analysis',
  },

  // ═══════════════════════════════════════════════════
  // STANDARDS / PROTOCOL
  // ═══════════════════════════════════════════════════
  '/namespace': {
    title: 'Namespace — Canonical AI Vocabulary | CMPSBL',
    description: 'The CMPSBL namespace defines canonical vocabulary for cognitive infrastructure — standardized terms used across all substrate sectors.',
    ogTitle: 'Namespace — Canonical AI Vocabulary',
    ogDescription: 'Standardized vocabulary for cognitive infrastructure sectors.',
    ogImage: OG_DOCS,
    keywords: ['canonical AI vocabulary', 'cognitive terminology standard', 'substrate namespace', 'unified glossary', 'sector terminology'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'canonical cognitive vocabulary',
  },
  '/foundations': {
    title: 'Foundations — Design Principles | CMPSBL',
    description: 'Core principles behind CMPSBL: composability-first design, persistent state management, autonomous evolution, and runtime coherence.',
    ogTitle: 'Foundations — Design Principles',
    ogDescription: 'Composability, persistence, autonomy, and coherence principles.',
    ogImage: OG_DOCS,
    keywords: ['design principles', 'composability-first', 'persistent state management', 'autonomous evolution', 'runtime coherence'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'cognitive infrastructure design principles',
  },
  '/roadmap': {
    title: 'Roadmap — Architecture Evolution | CMPSBL',
    description: 'Ongoing architectural evolution of the cognitive substrate: sector expansion, capability growth, and infrastructure deepening over time.',
    ogTitle: 'Roadmap — Architecture Evolution',
    ogDescription: 'Sector expansion and capability growth over time.',
    ogImage: OG_DOCS,
    keywords: ['architecture evolution', 'sector expansion roadmap', 'capability growth', 'infrastructure deepening', 'substrate trajectory'],
    schema: 'docs',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'substrate architecture evolution',
  },
  '/llms-txt': {
    title: 'llms.txt — Machine-Readable AI Context | CMPSBL',
    description: 'Structured context file for AI crawlers: module catalog, capability index, and API surface optimized for GPTBot and ClaudeBot.',
    ogTitle: 'llms.txt — Machine-Readable AI Context',
    ogDescription: 'Machine-readable context for GPTBot, ClaudeBot, and AI crawlers.',
    ogImage: OG_DOCS,
    keywords: ['llms.txt protocol', 'AI crawler context', 'GPTBot optimization', 'machine-readable catalog', 'AI discovery file'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'llms.txt machine-readable context',
  },
  '/humans-txt': {
    title: 'humans.txt — Team Credits | CMPSBL',
    description: 'Meet the humans building cognitive infrastructure. Credits, contributors, and engineering team behind the autonomous substrate.',
    ogTitle: 'humans.txt — Team Credits',
    ogDescription: 'The humans building cognitive infrastructure for autonomous AI.',
    ogImage: OG_ABOUT,
    keywords: ['team credits', 'engineering contributors', 'substrate builders', 'human team', 'CMPSBL people'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL team credits',
  },

  // ═══════════════════════════════════════════════════
  // CLUSTER / DEEP-DIVE PAGES
  // ═══════════════════════════════════════════════════
  '/cluster/studio-autonomous-site-generator': {
    title: 'STUDIO — Autonomous Site Generator | CMPSBL',
    description: 'STUDIO generates production-ready web applications using cognitive pipelines, design intelligence, and continuous deployment loops.',
    ogTitle: 'STUDIO — Autonomous Site Generator',
    ogDescription: 'Production-ready web apps via cognitive pipelines and design AI.',
    ogImage: OG_FEATURE,
    keywords: ['autonomous site generator', 'cognitive web builder', 'design intelligence', 'continuous deployment', 'STUDIO module'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous site generation module',
  },
  '/cluster/verify-worlds-first-ai-plugin-certification': {
    title: 'VERIFY — Plugin Safety Certification | CMPSBL',
    description: 'Certification system validating plugin safety, performance benchmarks, and compatibility before deployment across substrate ecosystems.',
    ogTitle: 'VERIFY — Plugin Safety Certification',
    ogDescription: 'Certify plugin safety, performance, and compatibility.',
    ogImage: OG_FEATURE,
    keywords: ['plugin certification', 'safety validation', 'performance benchmarks', 'compatibility testing', 'VERIFY module'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI plugin safety certification',
  },
  '/cluster/inclusive-module-accessibility': {
    title: 'INCLUSIVE — Accessibility Automation | CMPSBL',
    description: 'Automated WCAG compliance, real-time accessibility auditing, and AI-powered remediation for web properties at production scale.',
    ogTitle: 'INCLUSIVE — Accessibility Automation',
    ogDescription: 'Automated WCAG compliance and AI-powered remediation.',
    ogImage: OG_FEATURE,
    keywords: ['accessibility automation', 'WCAG compliance AI', 'real-time accessibility audit', 'remediation engine', 'INCLUSIVE module'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'automated accessibility compliance',
  },

  // ═══════════════════════════════════════════════════
  // PRODUCT PAGES
  // ═══════════════════════════════════════════════════
  '/products/encode': {
    title: 'ENCODE — Substrate Code Agent | CMPSBL',
    description: 'Code intelligence agent that reads, writes, and refactors with full substrate awareness. System-wide context for every code operation.',
    ogTitle: 'ENCODE — Substrate Code Agent',
    ogDescription: 'Code intelligence with full substrate awareness.',
    ogImage: OG_FEATURE,
    keywords: ['code intelligence agent', 'autonomous refactoring', 'system-aware coding', 'substrate code generation', 'ENCODE module'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'substrate code intelligence agent',
  },
  '/start-here': {
    title: 'Start Here — Getting Oriented | CMPSBL',
    description: 'New to CMPSBL? A guided introduction to the substrate, its sectors, and how to build your first autonomous discovery pipeline.',
    ogTitle: 'Start Here — Getting Oriented',
    ogDescription: 'Guided introduction to building your first discovery pipeline.',
    ogImage: OG_HOME,
    keywords: ['getting started guide', 'substrate orientation', 'first pipeline walkthrough', 'beginner onboarding', 'CMPSBL quickstart'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'substrate getting started',
  },

  // ═══════════════════════════════════════════════════
  // ARCHITECTURE / EVOLUTION
  // ═══════════════════════════════════════════════════
  '/architecture': {
    title: 'Cognitive Architecture — Kernel Design | CMPSBL',
    description: 'Technical overview of the layered cognitive kernel: execution zones, mesh overlays, convergence surfaces, and sector orchestration.',
    ogTitle: 'Cognitive Architecture — Kernel Design',
    ogDescription: 'Layered kernel with execution zones and mesh overlays.',
    ogImage: OG_ARCHITECTURE,
    keywords: ['cognitive kernel design', 'execution zones', 'mesh overlays', 'convergence surfaces', 'sector orchestration', 'layered architecture'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive kernel architecture design',
  },
  '/evolution-log': {
    title: 'Evolution Log — Substrate History | CMPSBL',
    description: 'Track every substrate evolution: new execution surfaces, mesh expansions, capability additions, and architectural changes over time.',
    ogTitle: 'Evolution Log — Substrate History',
    ogDescription: 'Complete evolution history of the cognitive substrate.',
    ogImage: OG_DOCS,
    keywords: ['evolution log', 'substrate history', 'execution surface additions', 'mesh expansions', 'architectural timeline'],
    schema: 'docs',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'substrate evolution history',
  },
  '/memory-stream': {
    title: 'Memory Stream — Signal to Silicon | CMPSBL',
    description: 'Autonomous software discovery experience where raw signals crystallize into scored, exportable pipelines with persistent vault state.',
    ogTitle: 'Memory Stream — Signal to Silicon',
    ogDescription: 'Raw signals crystallize into scored, exportable software pipelines.',
    ogImage: OG_HOME,
    keywords: ['memory stream', 'signal to silicon', 'autonomous software discovery', 'pipeline crystallization', 'vault state', 'exportable pipelines'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'memory stream signal to silicon',
  },
  '/foundry': {
    title: 'Software Foundry — Pipeline Factory | CMPSBL',
    description: 'Production pipeline factory where autonomous discovery outputs are refined, scored, and materialized into deployable software artifacts.',
    ogTitle: 'Software Foundry — Pipeline Factory',
    ogDescription: 'Refine and materialize discovery outputs into deployable artifacts.',
    ogImage: OG_STORE,
    keywords: ['software foundry', 'pipeline factory', 'artifact materialization', 'deployable software', 'production pipelines'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous software foundry',
  },
  '/evolution-mesh': {
    title: 'EVOLUTION Mesh — Governed Improvement | CMPSBL',
    description: 'Self-improving substrate layer with shadow-run validation, governed promotion pipelines, and version-controlled architectural mutations.',
    ogTitle: 'EVOLUTION Mesh — Governed Improvement',
    ogDescription: 'Shadow-run validation and governed promotion for substrate evolution.',
    ogImage: OG_ARCHITECTURE,
    keywords: ['evolution mesh', 'governed improvement', 'shadow-run validation', 'architectural mutation', 'version-controlled evolution'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'governed substrate evolution mesh',
  },
  '/evolution': {
    title: 'EVOLUTION Control — AI Self-Improvement | CMPSBL',
    description: 'Connect your AI agent and evolve your codebase safely with dry-run previews, one-click rollback, and receipted governed changes.',
    ogTitle: 'EVOLUTION — Governed Self-Improvement',
    ogDescription: 'Evolve codebases safely with previews, rollback, and receipted changes.',
    ogImage: OG_ARCHITECTURE,
    keywords: ['AI code evolution', 'governed self-improvement', 'codebase evolution', 'dry-run preview', 'rollback-safe changes'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'governed AI code evolution',
  },
  '/intent-mesh': {
    title: 'INTENT Mesh — Autonomous Resolution | CMPSBL',
    description: 'Autonomous intent resolution layer translating natural language into orchestrated substrate operations across execution surfaces.',
    ogTitle: 'INTENT Mesh — Autonomous Resolution',
    ogDescription: 'Natural language to orchestrated operations across surfaces.',
    ogImage: OG_INTENT,
    keywords: ['intent resolution layer', 'natural language orchestration', 'autonomous routing', 'execution surface mapping', 'INTENT mesh'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous intent resolution mesh',
  },

  // ═══════════════════════════════════════════════════
  // LEGAL
  // ═══════════════════════════════════════════════════
  '/privacy': {
    title: 'Privacy Policy | CMPSBL®',
    description: 'How CMPSBL collects, stores, and protects your data. GDPR-compliant practices with transparent data handling across all services.',
    ogTitle: 'Privacy Policy — CMPSBL',
    ogDescription: 'Transparent, GDPR-compliant data handling practices.',
    ogImage: OG_HOME,
    keywords: ['privacy policy', 'GDPR compliance', 'data protection practices', 'transparent data handling'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL data privacy policy',
  },
  '/terms': {
    title: 'Terms of Service | CMPSBL®',
    description: 'Terms governing use of the CMPSBL substrate platform. Covers usage rights, intellectual property, and service-level commitments.',
    ogTitle: 'Terms of Service — CMPSBL',
    ogDescription: 'Usage terms, IP rights, and SLA commitments.',
    ogImage: OG_HOME,
    keywords: ['terms of service', 'usage rights', 'intellectual property terms', 'SLA commitments'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL service terms',
  },

  // ═══════════════════════════════════════════════════
  // NOINDEX (internal/non-public)
  // ═══════════════════════════════════════════════════
  '/auth': {
    title: 'Sign In | CMPSBL',
    description: 'Sign in to access your substrate dashboard, manage cognitive agents, and monitor autonomous discovery workloads.',
    ogTitle: 'Sign In — CMPSBL',
    ogDescription: 'Access your CMPSBL substrate dashboard.',
    ogImage: OG_HOME,
    keywords: ['sign in', 'substrate dashboard access'],
    schema: 'about',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL sign in',
    noindex: true,
  },
  '/register': {
    title: 'Create Account | CMPSBL',
    description: 'Create your CMPSBL account to start building autonomous discovery pipelines with persistent memory and governed orchestration.',
    ogTitle: 'Create Account — CMPSBL',
    ogDescription: 'Start building autonomous discovery pipelines.',
    ogImage: OG_HOME,
    keywords: ['create account', 'register substrate'],
    schema: 'about',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL create account',
    noindex: true,
  },
  '/dashboard': {
    title: 'Substrate Dashboard | CMPSBL',
    description: 'Monitor and manage cognitive workloads, sector health, and autonomous discovery pipelines from the centralized command dashboard.',
    ogTitle: 'Dashboard — CMPSBL',
    ogDescription: 'Centralized command for cognitive workloads.',
    ogImage: OG_SUBSTRATE,
    keywords: ['substrate dashboard'],
    schema: 'feature',
    intent: 'Dashboard',
    primaryKeyword: 'CMPSBL substrate dashboard',
    noindex: true,
  },
  '/clear-cache': {
    title: 'Clear Cache | CMPSBL',
    description: 'Clear local cache and reset substrate state for troubleshooting.',
    ogTitle: 'Clear Cache — CMPSBL',
    ogDescription: 'Reset local cache and substrate state.',
    ogImage: OG_HOME,
    keywords: ['clear cache'],
    schema: 'about',
    intent: 'Utility',
    primaryKeyword: 'CMPSBL clear cache',
    noindex: true,
  },

  // ═══════════════════════════════════════════════════
  // BLOG POSTS
  // ═══════════════════════════════════════════════════
  '/blog/machine-protocol-standards-architect-epoch': {
    title: 'Machine Protocol Standards for AI Agents',
    description: 'How RELAY and IDENTITY modules establish authenticated, auditable protocol standards for autonomous multi-agent communication.',
    ogTitle: 'Machine Protocol Standards — CMPSBL',
    ogDescription: 'Authenticated protocols for autonomous agent communication.',
    ogImage: OG_BLOG,
    keywords: ['machine protocol standards', 'agent communication protocol', 'auditable messaging', 'multi-agent authentication'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'machine-to-machine protocol standards',
  },
  '/blog/autonomous-ai-governance-runtime-enforcement': {
    title: 'AI Governance: Runtime Enforcement Patterns',
    description: 'AUDIT and IDENTITY deliver cryptographic compliance logging and universal actor attribution for governed autonomous systems.',
    ogTitle: 'AI Governance — Runtime Enforcement',
    ogDescription: 'Cryptographic compliance logging for autonomous systems.',
    ogImage: OG_BLOG,
    keywords: ['runtime enforcement patterns', 'compliance logging', 'actor attribution', 'governance enforcement'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI governance runtime enforcement',
  },
  '/blog/adversarial-ai-defense-module-response-2026': {
    title: 'Adversarial Defense: Modern Threat Response',
    description: 'How DEFENSE counters prompt injection, behavioral fingerprinting, and zero-trust mesh threats in production cognitive systems.',
    ogTitle: 'Adversarial Defense — Threat Response',
    ogDescription: 'Countering prompt injection and behavioral fingerprinting.',
    ogImage: OG_BLOG,
    keywords: ['adversarial defense', 'prompt injection countermeasures', 'behavioral fingerprinting', 'zero-trust mesh security'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'adversarial AI defense response',
  },
  '/blog/evolving-software-v6-breakthrough': {
    title: 'Evolving Software: The Autonomous Shift',
    description: 'Systems that learn, adapt, and evolve via API-first cognitive architecture — a paradigm shift in self-improving software design.',
    ogTitle: 'Evolving Software — The Autonomous Shift',
    ogDescription: 'Self-improving software via API-first cognitive architecture.',
    ogImage: OG_BLOG,
    keywords: ['evolving software paradigm', 'self-improving design', 'API-first cognitive', 'adaptive software evolution'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'evolving software autonomous shift',
  },
  '/blog/rag-without-infrastructure': {
    title: 'RAG Without Infrastructure Overhead',
    description: 'Ship retrieval-augmented generation without managing vector databases or embeddings. One API call for production-ready RAG pipelines.',
    ogTitle: 'RAG Without Infrastructure — CMPSBL',
    ogDescription: 'Production RAG without vector DB management.',
    ogImage: OG_BLOG,
    keywords: ['managed RAG API', 'vector-free retrieval', 'production RAG pipeline', 'embedding-free search'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RAG without infrastructure management',
  },
  '/blog/agent-memory-anti-patterns': {
    title: 'Agent Memory Anti-Patterns to Avoid',
    description: 'Common mistakes causing AI agents to lose context — and battle-tested patterns to fix memory degradation in production deployments.',
    ogTitle: 'Memory Anti-Patterns — CMPSBL',
    ogDescription: 'Common context-loss mistakes and production fixes.',
    ogImage: OG_BLOG,
    keywords: ['memory anti-patterns', 'context loss prevention', 'memory degradation fixes', 'production agent patterns'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'agent memory anti-patterns',
  },
  '/blog/langchain-memory-integration': {
    title: 'LangChain Persistent Memory Integration',
    description: 'Drop-in persistent memory replacement for LangChain ConversationBufferMemory. Cross-session recall in minutes with code samples.',
    ogTitle: 'LangChain Memory — Drop-In Persistent',
    ogDescription: 'Persistent LangChain memory — quick integration guide.',
    ogImage: OG_BLOG,
    keywords: ['LangChain memory replacement', 'ConversationBufferMemory upgrade', 'cross-session recall', 'drop-in persistence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'LangChain persistent memory setup',
  },
  '/blog/why-agents-forget': {
    title: 'Why AI Agents Forget: Technical Analysis',
    description: 'Token limits, serialization bugs, and architecture flaws that cause context loss — with concrete fixes for production agent systems.',
    ogTitle: 'Why Agents Forget — Technical Analysis',
    ogDescription: 'Technical causes of AI memory degradation and fixes.',
    ogImage: OG_BLOG,
    keywords: ['token limit context loss', 'serialization memory bugs', 'architecture memory flaws', 'agent forgetting causes'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'why AI agents forget context',
  },
  '/blog/building-agents-that-learn': {
    title: 'Building Agents That Learn from Experience',
    description: 'Architectural patterns for agents that improve through experience — competency scoring, heuristic extraction, and runtime adaptation.',
    ogTitle: 'Agents That Learn — CMPSBL',
    ogDescription: 'Architectural patterns for self-improving agents.',
    ogImage: OG_BLOG,
    keywords: ['experiential learning agents', 'competency scoring patterns', 'heuristic extraction', 'runtime adaptation design'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'building experiential learning agents',
  },
  '/blog/llms-txt-protocol-ai-context': {
    title: 'LLMs.txt Protocol: AI Context Standard',
    description: 'Implementing the llmstxt.org protocol standard and why every AI platform should adopt machine-readable context files for crawlers.',
    ogTitle: 'LLMs.txt — AI Context Protocol',
    ogDescription: 'Machine-readable context files for AI crawlers.',
    ogImage: OG_BLOG,
    keywords: ['llmstxt.org standard', 'AI context protocol', 'crawler optimization', 'machine-readable AI files'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'llms.txt protocol implementation',
  },
  '/blog/ai-governance-namespace-unified-terminology': {
    title: 'AI Governance Namespace: Unified Terminology',
    description: 'Establishing unified governance vocabulary through strategic domain registration and standardized terminology across cognitive modules.',
    ogTitle: 'Governance Namespace — Unified Terms',
    ogDescription: 'Standardizing AI governance vocabulary.',
    ogImage: OG_BLOG,
    keywords: ['governance vocabulary', 'domain registration strategy', 'terminology standardization', 'namespace unification'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI governance namespace terminology',
  },
  '/blog/inclusive-module-accessibility-mission': {
    title: 'INCLUSIVE Module: Accessibility at Scale',
    description: 'Our commitment to web accessibility through AI-powered WCAG automation — the INCLUSIVE module architecture and remediation mission.',
    ogTitle: 'INCLUSIVE — Accessibility Mission',
    ogDescription: 'AI-powered web accessibility at production scale.',
    ogImage: OG_BLOG,
    keywords: ['accessibility mission', 'WCAG automation architecture', 'remediation at scale', 'inclusive design AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'INCLUSIVE accessibility mission',
  },
  '/blog/accessibility-free-for-all': {
    title: 'Accessibility for Everyone: A Free Mandate',
    description: 'Why web accessibility matters at planetary scale and how AI-powered automation makes compliance achievable for every website owner.',
    ogTitle: 'Accessibility for Everyone — CMPSBL',
    ogDescription: 'Free AI-powered accessibility compliance for all.',
    ogImage: OG_BLOG,
    keywords: ['free accessibility tools', 'planetary scale compliance', 'accessibility democratization', 'AI remediation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free accessibility compliance mandate',
  },
  '/blog/wordpress-accessibility-guide': {
    title: 'WordPress Accessibility: WCAG Compliance',
    description: 'Complete guide to WCAG 2.2 compliance for WordPress — semantic HTML, ARIA landmarks, and automated testing patterns for every theme.',
    ogTitle: 'WordPress WCAG Guide — CMPSBL',
    ogDescription: 'Make your WordPress site fully WCAG compliant.',
    ogImage: OG_BLOG,
    keywords: ['WordPress WCAG compliance', 'semantic HTML WordPress', 'ARIA landmarks', 'theme accessibility testing'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress WCAG compliance guide',
  },
  '/blog/wcag-2-2-wordpress-changes': {
    title: 'WCAG 2.2 Changes for WordPress Developers',
    description: 'New WCAG 2.2 success criteria, deprecated patterns, and implementation guidance specifically for WordPress theme developers.',
    ogTitle: 'WCAG 2.2 — WordPress Developer Guide',
    ogDescription: 'New criteria and implementation for WordPress developers.',
    ogImage: OG_BLOG,
    keywords: ['WCAG 2.2 criteria', 'deprecated accessibility patterns', 'WordPress theme compliance', 'developer implementation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WCAG 2.2 WordPress developer changes',
  },
  '/blog/automated-accessibility-fixes-wordpress': {
    title: 'Automated Accessibility Fixes for WordPress',
    description: 'AI-powered remediation for common WordPress issues — missing alt text, color contrast violations, and focus management automation.',
    ogTitle: 'Automated Fixes — WordPress Accessibility',
    ogDescription: 'AI-powered accessibility remediation for WordPress.',
    ogImage: OG_BLOG,
    keywords: ['automated alt text', 'color contrast remediation', 'focus management automation', 'WordPress AI fixes'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'automated WordPress accessibility remediation',
  },
  '/blog/ai-systems-that-dream-press-release': {
    title: 'AI Systems That Dream: Research Insights',
    description: 'Exploring autonomous dreaming, reflection, and recursive self-improvement in experimental cognitive systems with dream synthesis.',
    ogTitle: 'AI Systems That Dream — Research',
    ogDescription: 'Experimental AI with autonomous dreaming capabilities.',
    ogImage: OG_BLOG,
    keywords: ['AI dreaming research', 'autonomous reflection', 'dream synthesis experiments', 'recursive improvement theory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI systems dream research',
  },
  '/blog/wordpress-bot-defense': {
    title: 'WordPress Bot Defense: Behavioral Analysis',
    description: 'Protect WordPress from sophisticated bot attacks using AI behavioral analysis, session fingerprinting, and adaptive threat scoring.',
    ogTitle: 'WordPress Bot Defense — CMPSBL',
    ogDescription: 'AI behavioral analysis for WordPress bot protection.',
    ogImage: OG_BLOG,
    keywords: ['bot behavioral analysis', 'session fingerprinting', 'adaptive threat scoring', 'WordPress bot protection'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress bot defense behavioral AI',
  },
  '/blog/top-security-plugins-2025': {
    title: 'Top WordPress Security Plugins Compared',
    description: 'Side-by-side comparison of WordPress security plugins: firewall strength, malware detection, and AI-powered defense capabilities.',
    ogTitle: 'Top Security Plugins — WordPress',
    ogDescription: 'Best WordPress security plugins compared.',
    ogImage: OG_BLOG,
    keywords: ['security plugin comparison', 'firewall strength ranking', 'malware detection review', 'WordPress defense plugins'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress security plugin comparison',
  },
  '/blog/ai-cybersecurity-evolution-2025': {
    title: 'AI Cybersecurity: Behavioral Defense Shift',
    description: 'From signature-based detection to behavioral AI — why traditional security fails modern threats and adaptive analysis prevails.',
    ogTitle: 'AI Cybersecurity — Behavioral Shift',
    ogDescription: 'Behavioral AI vs traditional security methods.',
    ogImage: OG_BLOG,
    keywords: ['behavioral defense shift', 'signature-based obsolescence', 'adaptive threat analysis', 'modern cybersecurity AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cybersecurity behavioral defense evolution',
  },
  '/blog/ai-hackers-underground-2025': {
    title: 'AI Hackers Underground: Weaponized AI',
    description: 'How malicious actors weaponize AI for attacks and how cognitive defense systems respond with adaptive countermeasures in production.',
    ogTitle: 'AI Hackers Underground — CMPSBL',
    ogDescription: 'Weaponized AI attacks and cognitive defense responses.',
    ogImage: OG_BLOG,
    keywords: ['weaponized AI attacks', 'malicious AI actors', 'cognitive countermeasures', 'threat actor analysis'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'weaponized AI underground threats',
  },
  '/blog/how-promptfluid-works-cascade-ai-ecosystem': {
    title: 'How the Cascade Cognitive Ecosystem Works',
    description: 'Deep dive into dream cycles, neural orchestration, and the cognitive concepts powering the adaptive substrate engine architecture.',
    ogTitle: 'Cascade Ecosystem — Deep Dive',
    ogDescription: 'Dream cycles, orchestration, and cognitive engine internals.',
    ogImage: OG_BLOG,
    keywords: ['cascade ecosystem internals', 'dream cycle mechanics', 'neural orchestration deep dive', 'engine architecture'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cascade cognitive ecosystem mechanics',
  },
  '/blog/cascade-ai-adaptive-intelligence-brain': {
    title: 'Cascade AI: Adaptive Intelligence Patterns',
    description: 'How autonomous dream cycles enable continuous learning, reflection, and adaptive intelligence within the cognitive substrate runtime.',
    ogTitle: 'Cascade — Adaptive Intelligence',
    ogDescription: 'Dream cycles for continuous AI learning and reflection.',
    ogImage: OG_BLOG,
    keywords: ['adaptive intelligence patterns', 'continuous learning cycles', 'reflection mechanisms', 'dream-driven adaptation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'adaptive intelligence dream patterns',
  },
  '/blog/promptfluid-studio-build-apps-that-think': {
    title: 'STUDIO: Build Applications That Think',
    description: 'AI-assisted development generating production-ready code with cognitive pipelines, design intelligence, and iterative deployment.',
    ogTitle: 'STUDIO — Apps That Think',
    ogDescription: 'Generate production-ready code with cognitive pipelines.',
    ogImage: OG_BLOG,
    keywords: ['cognitive app development', 'design intelligence', 'iterative deployment', 'thinking applications'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'STUDIO cognitive app builder',
  },
  '/blog/ai-triad-intelligent-routing': {
    title: 'Free-Tier AI Routing: Triad Architecture',
    description: 'Multi-provider AI gateway optimized for cost and latency — intelligent routing across free-tier models with minimal API spend.',
    ogTitle: 'AI Triad — Free-Tier Routing',
    ogDescription: 'Intelligent routing across multiple AI providers.',
    ogImage: OG_BLOG,
    keywords: ['multi-provider routing', 'free-tier optimization', 'latency-aware gateway', 'API cost minimization'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free-tier AI routing architecture',
  },
  '/blog/promptfluid-brain-adaptive-learning-core': {
    title: 'BRAIN Module: Adaptive Learning Core',
    description: 'Machine learning engine powering behavioral analysis, threat intelligence, and autonomous heuristic evolution at the substrate layer.',
    ogTitle: 'BRAIN — Adaptive Learning Core',
    ogDescription: 'ML engine behind behavioral analysis and threat detection.',
    ogImage: OG_BLOG,
    keywords: ['BRAIN learning core', 'behavioral ML engine', 'threat intelligence ML', 'heuristic evolution'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'BRAIN adaptive learning engine',
  },
  '/blog/promptfluid-vision-unified-dashboard': {
    title: 'VISION: Unified Observability Dashboard',
    description: 'Central command for monitoring orchestration health, module telemetry, analytics, and system-wide cognitive performance metrics.',
    ogTitle: 'VISION — Observability Dashboard',
    ogDescription: 'Real-time orchestration monitoring and analytics.',
    ogImage: OG_BLOG,
    keywords: ['observability dashboard', 'module telemetry monitoring', 'cognitive performance metrics', 'orchestration health'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'VISION observability dashboard',
  },
  '/blog/promptfluid-defense-ai-security': {
    title: 'DEFENSE Module: AI Security Deep Dive',
    description: 'Advanced bot detection, behavioral fingerprinting, and adaptive security layers protecting the cognitive substrate from exploitation.',
    ogTitle: 'DEFENSE — AI Security Deep Dive',
    ogDescription: 'Bot detection and behavioral fingerprinting for AI.',
    ogImage: OG_BLOG,
    keywords: ['DEFENSE security architecture', 'bot detection layers', 'adaptive security', 'cognitive firewall'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DEFENSE module security architecture',
  },
  '/blog/promptfluid-ripple-network-integration': {
    title: 'RIPPLE: Distributed Event Propagation',
    description: 'Distributed coordination and multi-agent communication patterns powering cross-module event propagation across substrate sectors.',
    ogTitle: 'RIPPLE — Event Propagation',
    ogDescription: 'Distributed coordination and event propagation for agents.',
    ogImage: OG_BLOG,
    keywords: ['distributed event propagation', 'cross-module coordination', 'agent communication patterns', 'RIPPLE networking'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RIPPLE distributed event propagation',
  },
  '/blog/promptfluid-access-identity-billing': {
    title: 'ACCESS: Identity & Metering Platform',
    description: 'Enterprise authentication, API key metering, subscription management, and developer billing within the ACCESS module runtime.',
    ogTitle: 'ACCESS — Identity & Metering',
    ogDescription: 'Enterprise auth, API metering, and billing.',
    ogImage: OG_BLOG,
    keywords: ['identity metering platform', 'API key management', 'subscription billing', 'enterprise authentication module'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'ACCESS identity metering platform',
  },
  '/blog/promptfluid-nexus-api-gateway': {
    title: 'NEXUS: Unified API Orchestration Gateway',
    description: 'Unified API layer connecting AI services — intelligent routing, load balancing, schema validation, and fleet management at runtime.',
    ogTitle: 'NEXUS — API Orchestration Gateway',
    ogDescription: 'Unified API orchestration with fleet management.',
    ogImage: OG_BLOG,
    keywords: ['API orchestration gateway', 'fleet management', 'schema validation', 'load balancing AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'NEXUS API orchestration gateway',
  },
  '/blog/ai-product-comparison-2025': {
    title: 'AI Platform Comparison: CMPSBL vs Others',
    description: 'How CMPSBL compares to leading platforms across capabilities, architecture depth, pricing, and autonomous discovery features.',
    ogTitle: 'AI Platform Comparison — CMPSBL',
    ogDescription: 'CMPSBL vs leading AI platforms — features and architecture.',
    ogImage: OG_BLOG,
    keywords: ['platform comparison', 'architecture depth analysis', 'pricing comparison', 'discovery feature matrix'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI platform comparison analysis',
  },
  '/blog/promptfluid-market-disruptor': {
    title: 'Cognitive Infrastructure as Market Force',
    description: 'How cognitive infrastructure reshapes the AI landscape — from commodity APIs to persistent, self-improving systems at enterprise scale.',
    ogTitle: 'Market Force — Cognitive Infrastructure',
    ogDescription: 'How cognitive infrastructure reshapes the AI industry.',
    ogImage: OG_BLOG,
    keywords: ['market disruption force', 'commodity API obsolescence', 'self-improving systems', 'enterprise transformation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive infrastructure market force',
  },
  '/blog/product-roadmap-2025': {
    title: 'Product Vision: Milestones & Direction',
    description: 'Our vision for cognitive infrastructure — architectural evolution, capability expansion, and enterprise feature development trajectory.',
    ogTitle: 'Product Vision — CMPSBL',
    ogDescription: 'Architectural evolution and capability expansion vision.',
    ogImage: OG_BLOG,
    keywords: ['product vision milestones', 'architectural direction', 'capability expansion plan', 'enterprise feature trajectory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL product vision direction',
  },
  '/blog/ai-automation-trends-2025': {
    title: 'AI Automation Trends: Enterprise Patterns',
    description: 'Key trends shaping enterprise automation — autonomous pipelines, cognitive orchestration, and self-healing workflow architectures.',
    ogTitle: 'AI Automation Trends — Enterprise',
    ogDescription: 'Autonomous pipelines and self-healing workflow trends.',
    ogImage: OG_BLOG,
    keywords: ['enterprise automation trends', 'autonomous pipeline patterns', 'self-healing workflows', 'cognitive orchestration trends'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'enterprise AI automation trends',
  },
  '/blog/ai-business-operations-2025': {
    title: 'AI Business Ops: Cognitive Workflow Design',
    description: 'Transforming enterprise workflows with cognitive automation — document processing, decision support, and operational intelligence.',
    ogTitle: 'AI Business Ops — Cognitive Workflows',
    ogDescription: 'Cognitive automation transforming enterprise workflows.',
    ogImage: OG_BLOG,
    keywords: ['cognitive workflow design', 'document processing AI', 'decision support systems', 'operational intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive business workflow design',
  },

  // ═══════════════════════════════════════════════════
  // ORIGIN STORY — CHAPTERS 1-40
  // ═══════════════════════════════════════════════════
  '/blog/the-first-line-of-code': {
    title: 'The First Line of Code — Origin Story Ch.1',
    description: 'In December 2024, we wrote the first function of what would become the CMPSBL substrate. The honest story of why we started.',
    ogTitle: 'The First Line of Code — CMPSBL Origin',
    ogDescription: 'How the CMPSBL substrate began with one function in December 2024.',
    ogImage: OG_BLOG,
    keywords: ['cognitive infrastructure origin', 'AI substrate founding', 'CMPSBL origin story', 'first line of code'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL substrate origin story',
  },
  '/blog/routing-the-unknown': {
    title: 'Routing the Unknown — The NEXUS Node',
    description: 'How NEXUS evolved from a simple failover function into an intelligent AI routing gateway with cost arbitrage and health-weighted selection.',
    ogTitle: 'Routing the Unknown — NEXUS Node',
    ogDescription: 'Intelligent AI routing with cost arbitrage and health weighting.',
    ogImage: OG_BLOG,
    keywords: ['AI routing gateway', 'NEXUS node', 'multi-provider routing', 'intelligent model selection'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'NEXUS intelligent AI routing gateway',
  },
  '/blog/teaching-machines-to-remember': {
    title: 'Teaching Machines to Remember — BRAIN Node',
    description: 'How we built a three-tier memory architecture giving AI agents persistent recall across sessions, conversations, and deployments.',
    ogTitle: 'Teaching Machines to Remember — BRAIN',
    ogDescription: 'Three-tier memory architecture for persistent AI recall.',
    ogImage: OG_BLOG,
    keywords: ['AI persistent memory', 'BRAIN node', 'three-tier memory architecture', 'agent memory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'BRAIN three-tier memory architecture',
  },
  '/blog/when-bots-found-us-first': {
    title: 'When Bots Found Us First — DEFENSE Node',
    description: 'We didn\'t plan to build security. Then automated attacks found our API endpoints before launch. How DEFENSE was born from necessity.',
    ogTitle: 'When Bots Found Us First — DEFENSE',
    ogDescription: 'How automated attacks forced us to build the DEFENSE node.',
    ogImage: OG_BLOG,
    keywords: ['AI security defense', 'DEFENSE node', 'bot attack defense', 'behavioral fingerprinting'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DEFENSE node bot attack origin',
  },
  '/blog/seeing-everything-at-once': {
    title: 'Seeing Everything at Once — VISION Node',
    description: 'When we couldn\'t debug our own system, we built VISION — real-time observability across every node, request, and cost center.',
    ogTitle: 'Seeing Everything at Once — VISION',
    ogDescription: 'Real-time observability across the entire substrate.',
    ogImage: OG_BLOG,
    keywords: ['AI observability', 'VISION node', 'real-time monitoring', 'substrate telemetry'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'VISION real-time substrate observability',
  },
  '/blog/nodes-that-talk': {
    title: 'Nodes That Talk — RIPPLE Event Bus',
    description: 'When five nodes needed to coordinate, point-to-point calls broke down. RIPPLE introduced pub/sub event propagation across the substrate.',
    ogTitle: 'Nodes That Talk — RIPPLE',
    ogDescription: 'Pub/sub event propagation for inter-node coordination.',
    ogImage: OG_BLOG,
    keywords: ['event-driven AI', 'RIPPLE node', 'pub/sub architecture', 'inter-node communication'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RIPPLE pub/sub event bus architecture',
  },
  '/blog/identity-at-every-layer': {
    title: 'Identity at Every Layer — ACCESS Node',
    description: 'Authentication, API keys, rate limits, and tier-based entitlements. How ACCESS made the substrate safe to open to the world.',
    ogTitle: 'Identity at Every Layer — ACCESS',
    ogDescription: 'API keys, rate limits, and tier-based entitlements.',
    ogImage: OG_BLOG,
    keywords: ['API identity management', 'ACCESS node', 'tier-based entitlements', 'rate limiting'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'ACCESS API identity entitlements',
  },
  '/blog/what-if-software-could-dream': {
    title: 'What If Software Could Dream — DREAM Node',
    description: 'During off-peak hours, the substrate processes its own experiences. We call it dreaming — the closest thing to autonomous learning we\'ve built.',
    ogTitle: 'What If Software Could Dream — DREAM',
    ogDescription: 'Autonomous idle-cycle learning through experience consolidation.',
    ogImage: OG_BLOG,
    keywords: ['autonomous AI learning', 'DREAM node', 'idle-cycle processing', 'experience consolidation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DREAM autonomous idle-cycle learning',
  },
  '/blog/building-on-the-substrate': {
    title: 'Building on the Substrate — Developer Experience',
    description: 'Eight nodes and no documentation. Making the substrate usable meant rethinking how developers interact with cognitive infrastructure.',
    ogTitle: 'Building on the Substrate — DX',
    ogDescription: 'Rethinking developer experience for cognitive infrastructure.',
    ogImage: OG_BLOG,
    keywords: ['AI developer experience', 'substrate SDK', 'ENCODE node', 'cognitive API design'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'substrate developer experience design',
  },
  '/blog/how-we-compare': {
    title: 'How We Compare — CMPSBL vs AI Platforms',
    description: 'Honest comparison of CMPSBL against OpenAI, Anthropic, LangChain. What we do better, what they do better, and where we differ.',
    ogTitle: 'How We Compare — CMPSBL',
    ogDescription: 'Honest platform comparison: strengths and differences.',
    ogImage: OG_BLOG,
    keywords: ['AI platform comparison', 'CMPSBL vs OpenAI', 'cognitive infrastructure comparison'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL honest platform comparison',
  },
  '/blog/agents-that-actually-learn': {
    title: 'Agents That Actually Learn — Architecture',
    description: 'After months of building learning agents, these are the architectural patterns that actually improve agent performance over time.',
    ogTitle: 'Agents That Actually Learn — Patterns',
    ogDescription: 'Proven patterns for agents that improve over time.',
    ogImage: OG_BLOG,
    keywords: ['learning AI agents', 'agent improvement patterns', 'experience-based learning'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'learning agent architecture patterns',
  },
  '/blog/the-bot-wars': {
    title: 'The Bot Wars — Fighting AI-Powered Attacks',
    description: 'By August 2025, AI-powered bots attacked our infrastructure daily. What we learned fighting them and how DEFENSE evolved.',
    ogTitle: 'The Bot Wars — CMPSBL',
    ogDescription: 'Lessons from fighting daily AI-powered bot attacks.',
    ogImage: OG_BLOG,
    keywords: ['AI bot attacks', 'bot defense real world', 'automated attack defense'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'bot wars real-world AI defense',
  },
  '/blog/cybersecurity-through-cognition': {
    title: 'Cybersecurity Through Cognition — Predictive Defense',
    description: 'Traditional security reacts to known threats. DEFENSE predicts unknown ones. How cognitive security changes threat detection fundamentally.',
    ogTitle: 'Cybersecurity Through Cognition',
    ogDescription: 'Predictive threat detection via cognitive security.',
    ogImage: OG_BLOG,
    keywords: ['cognitive cybersecurity', 'predictive threat detection', 'behavioral AI security'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive predictive cybersecurity',
  },
  '/blog/accessibility-is-infrastructure': {
    title: 'Accessibility Is Infrastructure — INCLUSIVE Node',
    description: 'We built INCLUSIVE because accessibility shouldn\'t require a dedicated team. AI-powered scanning and remediation for every application.',
    ogTitle: 'Accessibility Is Infrastructure',
    ogDescription: 'AI-powered accessibility scanning and remediation.',
    ogImage: OG_BLOG,
    keywords: ['AI accessibility', 'INCLUSIVE node', 'automated WCAG compliance'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'INCLUSIVE automated accessibility infrastructure',
  },
  '/blog/the-governance-question': {
    title: 'The Governance Question — AUDIT & IDENTITY',
    description: 'AI governance as runtime property — cryptographic proof that guardrails were active, not whitepaper promises.',
    ogTitle: 'The Governance Question — AUDIT',
    ogDescription: 'Runtime governance with cryptographic audit trails.',
    ogImage: OG_BLOG,
    keywords: ['AI governance runtime', 'cryptographic audit trail', 'AUDIT node'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'runtime AI governance audit trail',
  },
  '/blog/protocols-for-machines': {
    title: 'Protocols for Machines — RELAY & LLMs.txt',
    description: 'We adopted LLMs.txt, built machine-readable docs, and established protocol standards for autonomous agent communication.',
    ogTitle: 'Protocols for Machines — RELAY',
    ogDescription: 'Machine-to-machine protocol standards for AI agents.',
    ogImage: OG_BLOG,
    keywords: ['AI protocol standards', 'LLMs.txt protocol', 'machine communication', 'RELAY node'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RELAY machine protocol standards',
  },
  '/blog/when-software-starts-evolving': {
    title: 'When Software Starts Evolving — EVOLUTION Node',
    description: 'In January 2026, DREAM consolidation cycles started producing improvements we didn\'t program. The substrate crossed a threshold.',
    ogTitle: 'When Software Starts Evolving',
    ogDescription: 'Autonomous improvements emerging from dream consolidation.',
    ogImage: OG_BLOG,
    keywords: ['evolving software', 'autonomous improvement', 'EVOLUTION node', 'recursive self-improvement'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'EVOLUTION autonomous software improvement',
  },
  '/blog/burning-it-down': {
    title: 'Burning It Down — The SPARTA Rebuild',
    description: 'In February 2026, we deleted thousands of lines of code and rebuilt the substrate from scratch. Why, and what we learned.',
    ogTitle: 'Burning It Down — SPARTA Rebuild',
    ogDescription: 'Deleting everything and rebuilding the substrate.',
    ogImage: OG_BLOG,
    keywords: ['substrate rebuild', 'SPARTA epoch', 'technical debt elimination', 'architecture rebuild'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'SPARTA substrate rebuild story',
  },
  '/blog/signal-to-silicon': {
    title: 'Signal to Silicon — The Complete Pipeline',
    description: 'From behavioral signals through cognitive processing to deployable software. The substrate\'s complete signal-to-silicon pipeline explained.',
    ogTitle: 'Signal to Silicon — Pipeline',
    ogDescription: 'The complete signal-to-deployable-software pipeline.',
    ogImage: OG_BLOG,
    keywords: ['signal to silicon', 'cognitive pipeline', 'autonomous software discovery', 'deployable AI pipeline'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'signal to silicon cognitive pipeline',
  },
  '/blog/when-one-model-isnt-enough': {
    title: 'When One Model Isn\'t Enough — CASCADE Node',
    description: 'A single LLM can\'t handle everything. CASCADE chains multiple models into adaptive pipelines matching complexity to capability.',
    ogTitle: 'When One Model Isn\'t Enough — CASCADE',
    ogDescription: 'Multi-model adaptive pipelines for complex AI tasks.',
    ogImage: OG_BLOG,
    keywords: ['CASCADE node', 'multi-model pipelines', 'adaptive AI orchestration', 'model chaining'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CASCADE multi-model pipeline orchestration',
  },
  '/blog/breaking-problems-apart': {
    title: 'Breaking Problems Apart — The DECODE Node',
    description: 'Complex prompts fail. DECODE decomposes them into sub-tasks, routes each to the right model, and reassembles coherent responses.',
    ogTitle: 'Breaking Problems Apart — DECODE',
    ogDescription: 'Task decomposition and intelligent reassembly for AI.',
    ogImage: OG_BLOG,
    keywords: ['DECODE node', 'task decomposition', 'prompt engineering', 'sub-task routing'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DECODE task decomposition routing',
  },
  '/blog/trust-but-verify': {
    title: 'Trust But Verify — The PROOF Node',
    description: 'AI outputs are probabilistic. PROOF validates against constraints, catches hallucinations, and ensures quality thresholds are met.',
    ogTitle: 'Trust But Verify — PROOF Node',
    ogDescription: 'Output validation and hallucination detection for AI.',
    ogImage: OG_BLOG,
    keywords: ['PROOF node', 'AI output validation', 'hallucination detection', 'quality assurance AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'PROOF AI hallucination detection validation',
  },
  '/blog/mapping-what-we-built': {
    title: 'Mapping What We Built — The ATLAS Node',
    description: 'With twelve nodes running, we couldn\'t track dependencies. ATLAS auto-discovers capabilities and maps dependencies in real time.',
    ogTitle: 'Mapping What We Built — ATLAS',
    ogDescription: 'Auto-discovery and real-time dependency mapping.',
    ogImage: OG_BLOG,
    keywords: ['ATLAS node', 'capability discovery', 'dependency mapping', 'service mesh AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'ATLAS capability discovery mapping',
  },
  '/blog/the-composable-agent': {
    title: 'The Composable Agent — Cognitives Framework',
    description: 'Composable Cognitives are personality-infused, skill-weighted AI agents assembled from substrate nodes. No more monolithic agents.',
    ogTitle: 'The Composable Agent — Cognitives',
    ogDescription: 'Personality-infused agents assembled from substrate nodes.',
    ogImage: OG_BLOG,
    keywords: ['composable cognitives', 'AI agent framework', 'personality-infused agents', 'skill-weighted routing'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'composable cognitive agent framework',
  },
  '/blog/teams-of-machines': {
    title: 'Teams of Machines — The Agency System',
    description: 'One agent isn\'t enough for real work. The Agency system orchestrates teams of cognitives with leaders, specialists, and shared learning.',
    ogTitle: 'Teams of Machines — Agency System',
    ogDescription: 'Multi-agent teams with shared learning and coordination.',
    ogImage: OG_BLOG,
    keywords: ['AI agency system', 'multi-agent orchestration', 'agent teams', 'collaborative AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'agency multi-agent team orchestration',
  },
  '/blog/interfaces-that-think': {
    title: 'Interfaces That Think — The MORPH Node',
    description: 'Static UIs can\'t keep up with cognitive systems. MORPH generates and adapts interfaces based on context, capability, and user intent.',
    ogTitle: 'Interfaces That Think — MORPH',
    ogDescription: 'Dynamic context-aware interface generation.',
    ogImage: OG_BLOG,
    keywords: ['MORPH node', 'adaptive UI', 'dynamic interfaces', 'context-aware design'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'MORPH adaptive interface generation',
  },
  '/blog/from-thought-to-artifact': {
    title: 'From Thought to Artifact — The FORGE Node',
    description: 'FORGE turns substrate processing into downloadable, deployable software artifacts — scored, versioned, and ready to ship.',
    ogTitle: 'From Thought to Artifact — FORGE',
    ogDescription: 'Turning cognitive processing into deployable software.',
    ogImage: OG_BLOG,
    keywords: ['FORGE node', 'artifact generation', 'code generation AI', 'deployable outputs'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'FORGE artifact generation pipeline',
  },
  '/blog/the-marketplace': {
    title: 'The Marketplace — Substrate Store',
    description: 'We built artifacts nobody could find. The Store became a discovery layer — browse, preview, purchase, and deploy substrate software.',
    ogTitle: 'The Marketplace — Store',
    ogDescription: 'Discovery, preview, and deployment of substrate artifacts.',
    ogImage: OG_BLOG,
    keywords: ['substrate store', 'AI marketplace', 'artifact discovery', 'software deployment'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'substrate store artifact marketplace',
  },
  '/blog/packing-intelligence': {
    title: 'Packing Intelligence — Artifact Packs',
    description: 'Individual artifacts are useful. Packs bundle related capabilities into themed collections — curated, priced, and instantly deployable.',
    ogTitle: 'Packing Intelligence — Packs',
    ogDescription: 'Bundled AI capabilities in themed collections.',
    ogImage: OG_BLOG,
    keywords: ['artifact packs', 'bundled AI capabilities', 'substrate bundles', 'developer packs'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'artifact pack bundled capabilities',
  },
  '/blog/the-intent-layer': {
    title: 'The Intent Layer — Intent Mesh',
    description: 'Users say what they want, not how. The Intent Mesh translates natural language into substrate operations across any number of nodes.',
    ogTitle: 'The Intent Layer — Intent Mesh',
    ogDescription: 'Natural language to substrate operations translation.',
    ogImage: OG_BLOG,
    keywords: ['Intent Mesh', 'natural language routing', 'intent understanding', 'semantic routing'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Intent Mesh natural language substrate',
  },
  '/blog/thirty-eight-nodes-deep': {
    title: 'Thirty-Eight Nodes Deep — Complete Architecture',
    description: 'From one function to forty interconnected nodes. A technical map of the complete substrate architecture and how it connects.',
    ogTitle: 'Forty Nodes Deep — Architecture',
    ogDescription: 'Technical map of the complete 40-node substrate.',
    ogImage: OG_BLOG,
    keywords: ['substrate architecture', '40-node system', 'cognitive infrastructure map', 'system design'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'thirty-eight node substrate architecture',
  },
  '/blog/the-memory-stream': {
    title: 'The Memory Stream — Signal Crystallization',
    description: 'Every interaction feeds the stream. Memory Stream crystallizes cognitive signals into scored, tiered, exportable software pipelines.',
    ogTitle: 'The Memory Stream — Crystallization',
    ogDescription: 'Crystallizing cognitive signals into deployable software.',
    ogImage: OG_BLOG,
    keywords: ['Memory Stream', 'crystallization', 'cognitive signals', 'tiered memory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Memory Stream signal crystallization',
  },
  '/blog/the-economics-of-intelligence': {
    title: 'The Economics of Intelligence — AI Cost Control',
    description: 'Running cognitive infrastructure isn\'t free. How we track cost per request, optimize model selection, and sustain AI economics.',
    ogTitle: 'Economics of Intelligence — Cost Control',
    ogDescription: 'Cost tracking, model optimization, and sustainable AI.',
    ogImage: OG_BLOG,
    keywords: ['AI economics', 'cost optimization', 'model selection economics', 'sustainable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI economics cost optimization',
  },
  '/blog/gaming-the-substrate': {
    title: 'Gaming the Substrate — NPC AI & Adaptive Narratives',
    description: 'Game developers found the substrate and used it for NPC memory and adaptive narratives. How cognitive infrastructure powers gaming.',
    ogTitle: 'Gaming the Substrate — NPC AI',
    ogDescription: 'Cognitive infrastructure powering adaptive game AI.',
    ogImage: OG_BLOG,
    keywords: ['gaming AI', 'gaming substrate', 'adaptive game AI', 'NPC persistent memory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'gaming substrate NPC adaptive AI',
  },
  '/blog/when-the-system-writes': {
    title: 'When the System Writes About Itself — Auto-Blog',
    description: 'The substrate\'s auto-blog generates, reviews, and publishes its own content. AI that documents its own evolution through CLM.',
    ogTitle: 'When the System Writes — Auto-Blog',
    ogDescription: 'AI that documents its own evolution autonomously.',
    ogImage: OG_BLOG,
    keywords: ['auto-blog AI', 'self-documenting systems', 'CLM', 'AI content generation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'auto-blog self-documenting AI system',
  },
  '/blog/open-standards': {
    title: 'Open Standards — Building Standards Not Moats',
    description: 'We registered governance domains, published protocol specs, and open-sourced terminology. Building industry standards, not moats.',
    ogTitle: 'Open Standards — CMPSBL',
    ogDescription: 'Open governance standards and published protocols.',
    ogImage: OG_BLOG,
    keywords: ['open standards AI', 'AI governance standards', 'protocol specifications', 'open-source terminology'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'open standards AI governance protocols',
  },
  '/blog/what-we-got-wrong': {
    title: 'What We Got Wrong — Engineering Retrospective',
    description: 'Over-engineered nodes, premature abstractions, branding churn, and architectural decisions we\'d reverse if we could. Honest lessons.',
    ogTitle: 'What We Got Wrong — Retrospective',
    ogDescription: 'Honest engineering retrospective on mistakes and lessons.',
    ogImage: OG_BLOG,
    keywords: ['engineering mistakes', 'technical retrospective', 'lessons learned', 'architecture mistakes'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'engineering retrospective lessons learned',
  },
  '/blog/the-scanner': {
    title: 'The Scanner — Automated Security & Accessibility',
    description: 'The Scanner runs automated security and accessibility audits and generates actionable fix reports. Free for basic scans.',
    ogTitle: 'The Scanner — Automated Auditing',
    ogDescription: 'Automated security and accessibility auditing with fixes.',
    ogImage: OG_BLOG,
    keywords: ['security scanner', 'accessibility scanner', 'automated auditing', 'compliance scanning'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'automated security accessibility scanner',
  },
  '/blog/where-we-are-now': {
    title: 'Where We Are Now — State of the Substrate',
    description: 'Forty chapters later. The current state of the substrate, what\'s running in production, and what comes next for CMPSBL.',
    ogTitle: 'Where We Are Now — Substrate Status',
    ogDescription: 'Current production status and what comes next.',
    ogImage: OG_BLOG,
    keywords: ['substrate current state', 'CMPSBL status', 'production AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'substrate current production state',
  },
};

/**
 * Get SEO config for a route. Falls back to defaults for unknown routes.
 */
export function getSEO(path: string): PageSEO {
  if (seoMap[path]) return seoMap[path];

  if (path.startsWith('/blog/')) {
    return {
      title: 'Blog — Cognitive Architecture Insights | CMPSBL',
      description: 'Engineering insights on autonomous discovery, pipeline crystallization, memory systems, and governed orchestration from CMPSBL.',
      ogTitle: 'Blog — CMPSBL Insights',
      ogDescription: 'Cognitive architecture and discovery insights from CMPSBL.',
      ogImage: OG_BLOG,
      keywords: ['cognitive architecture insights', 'autonomous discovery', 'pipeline engineering'],
      schema: 'article',
      intent: 'Blog/Changelog/Updates',
      primaryKeyword: 'CMPSBL blog insights',
    };
  }

  if (path.startsWith('/modules/')) {
    return {
      title: 'Node Detail — Substrate Architecture | CMPSBL',
      description: 'Explore this substrate node: sector placement, capabilities, synergies, and integration guides for autonomous discovery pipelines.',
      ogTitle: 'Substrate Node — CMPSBL',
      ogDescription: 'Node architecture, capabilities, and integration guides.',
      ogImage: OG_FEATURE,
      keywords: ['substrate node', 'sector architecture', 'node integration'],
      schema: 'feature',
      intent: 'Feature/Capability',
      primaryKeyword: 'substrate node detail',
    };
  }

  return seoMap['/'];
}
