/**
 * seoMap.ts — Centralized SEO Metadata Registry
 * v9.1.0 ARCHITECT Epoch
 *
 * Single source of truth for every PUBLIC indexed page.
 * Each entry has a UNIQUE primary keyword — no cannibalization.
 */

export interface PageSEO {
  title: string;            // ≤60 chars, primary keyword early
  description: string;      // 140-160 chars, intent-matched
  ogTitle: string;           // social-optimized (can differ from title)
  ogDescription: string;    // social-friendly (can differ from description)
  ogImage: string;
  keywords: string[];        // 6-10 unique per page
  schema: 'home' | 'feature' | 'docs' | 'blog' | 'about' | 'legal' | 'contact' | 'product' | 'article';
  intent: string;
  primaryKeyword: string;
  noindex?: boolean;
}

const OG_BASE = 'https://cmpsbl.com';
const OG_DEFAULT = `${OG_BASE}/og-default.jpg`;
const OG_FEATURE = `${OG_BASE}/og-feature.jpg`;
const OG_DOCS = `${OG_BASE}/og-docs.jpg`;
const OG_BLOG = `${OG_BASE}/og-blog.jpg`;
const OG_ABOUT = `${OG_BASE}/og-about.jpg`;

/**
 * Master SEO map keyed by route path.
 * RULES:
 * - Every primaryKeyword is UNIQUE across the entire map
 * - Every title is UNIQUE
 * - Every description is UNIQUE
 */
export const seoMap: Record<string, PageSEO> = {
  // ═══════════════════════════════════════════════════
  // CORE PUBLIC
  // ═══════════════════════════════════════════════════
  '/': {
    title: 'CMPSBL® — Cognitive Infrastructure for AI',
    description: 'CMPSBL is the cognitive infrastructure layer powering persistent memory, self-learning, and multi-provider routing. 21 modules, 400+ capabilities.',
    ogTitle: 'CMPSBL — Where Machines Learn To Think',
    ogDescription: 'The AI operating system with persistent memory, dream cycles, and 21 integrated modules.',
    ogImage: OG_DEFAULT,
    keywords: ['cognitive infrastructure', 'AI operating system', 'persistent memory AI', 'self-learning AI', 'CMPSBL substrate', 'AI memory layer', 'multi-provider routing'],
    schema: 'home',
    intent: 'Brand/Category',
    primaryKeyword: 'cognitive infrastructure for AI',
  },
  '/os': {
    title: 'Substrate OS v9.1.0 — AI Operating System',
    description: 'Explore the CMPSBL Substrate OS: 21 runtime modules, real-time telemetry, and autonomous orchestration powering cognitive workloads.',
    ogTitle: 'Substrate OS — The Engine Behind Cognitive AI',
    ogDescription: 'Real-time telemetry, module health, and autonomous orchestration inside the AI operating system.',
    ogImage: OG_FEATURE,
    keywords: ['substrate OS', 'AI runtime', 'cognitive orchestration', 'module telemetry', 'AI workload management', 'substrate dashboard'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate operating system',
  },
  '/ai-operating-system': {
    title: 'What Is an AI Operating System? — CMPSBL',
    description: 'The definitive guide to AI operating systems: how CMPSBL orchestrates memory, learning, defense, and 400+ capabilities in a unified runtime.',
    ogTitle: 'The AI Operating System — Explained',
    ogDescription: 'How a cognitive runtime orchestrates memory, learning, and multi-provider AI in one unified layer.',
    ogImage: OG_FEATURE,
    keywords: ['AI operating system definition', 'cognitive runtime', 'AI OS architecture', 'what is AI OS', 'unified AI platform', 'AIDO'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI operating system',
  },
  '/modules': {
    title: '21 Substrate Modules — AI Architecture | CMPSBL',
    description: 'Browse all 21 core modules across 6 layers: Kernel, Cognitive, Operational, Administrative, Orchestrator, and Infrastructure.',
    ogTitle: '21 Modules Powering the Substrate',
    ogDescription: 'Explore every module from BRAIN to DEFENSE — organized by architectural layer.',
    ogImage: OG_FEATURE,
    keywords: ['substrate modules', 'AI architecture layers', 'BRAIN module', 'DEFENSE module', 'cognitive layer', 'kernel modules', 'AI module catalog'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate modules',
  },
  '/store': {
    title: 'Composable Artifacts — Capabilities & Pipelines',
    description: 'Access 400+ tier-scoped capabilities, synergy pipelines, and templates in the CMPSBL artifact marketplace.',
    ogTitle: 'Artifact Marketplace — 400+ AI Capabilities',
    ogDescription: 'Browse and deploy capabilities, templates, and synergy pipelines for your cognitive workloads.',
    ogImage: OG_FEATURE,
    keywords: ['AI capabilities marketplace', 'synergy pipelines', 'composable artifacts', 'AI templates', 'capability depot', 'CMPSBL store'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'composable AI artifacts',
  },
  '/composable-cognitives': {
    title: 'Composable Cognitives — Own Your AI Agents',
    description: 'Build, buy, and deploy superpowered cognitive agents you own forever. Download once, run anywhere, no subscriptions.',
    ogTitle: 'Composable Cognitives — AI Agents You Own',
    ogDescription: 'Superpowered agents downloaded once and run anywhere — no lock-in, no subscriptions.',
    ogImage: OG_FEATURE,
    keywords: ['composable cognitives', 'AI agents download', 'own your AI', 'cognitive agents', 'portable AI agents', 'agent marketplace'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'composable cognitive agents',
  },
  '/engines': {
    title: 'Engines — Canonized Orchestrations',
    description: 'First-party canonized orchestration engines: pre-built AI workflows validated and versioned by CMPSBL engineering.',
    ogTitle: 'Engines — OEM Orchestrations',
    ogDescription: 'Pre-validated orchestration engines for enterprise AI workloads.',
    ogImage: OG_FEATURE,
    keywords: ['AI engines', 'orchestration engines', 'canonized workflows', 'OEM AI engines', 'pre-built AI pipelines'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI orchestration engines',
  },
  '/persistent-memory': {
    title: 'Persistent Memory for AI Agents — Free Tier',
    description: 'Add persistent memory to any AI agent in under an hour. Free tier available. Works with LangChain, CrewAI, and custom frameworks.',
    ogTitle: 'Persistent Memory — Add Memory to Any Agent',
    ogDescription: 'Give your AI agent a permanent memory in under an hour. Free.',
    ogImage: OG_FEATURE,
    keywords: ['persistent memory AI', 'agent memory', 'AI memory API', 'LangChain memory', 'free AI memory', 'agent state persistence'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'persistent memory for AI agents',
  },
  '/decode': {
    title: 'Decode Engine — Natural Language Terminal',
    description: 'Interact with the CMPSBL substrate through natural language commands. The Decode Engine translates intent into module actions.',
    ogTitle: 'Decode — Talk to Your Substrate',
    ogDescription: 'A natural language terminal that translates intent into substrate operations.',
    ogImage: OG_FEATURE,
    keywords: ['Decode engine', 'natural language terminal', 'AI CLI', 'substrate commands', 'intent-to-action', 'cognitive terminal'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'natural language AI terminal',
  },
  '/feed-dream-eater': {
    title: 'Dream Feeder — Autonomous Learning Cycles',
    description: 'Feed the Dream Eater: CMPSBL\'s autonomous learning system that processes experience data into heuristic improvements during idle cycles.',
    ogTitle: 'Dream Feeder — AI That Learns While Idle',
    ogDescription: 'Autonomous dream cycles that convert experience into intelligence.',
    ogImage: OG_FEATURE,
    keywords: ['dream cycles AI', 'autonomous learning', 'AI dream feeder', 'heuristic improvement', 'idle learning AI', 'self-improving AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI autonomous dream cycles',
  },
  '/proof': {
    title: 'Proof Mode — Verifiable AI Execution',
    description: 'Cryptographic proof of every AI operation. Proof Mode generates tamper-evident execution records for audit and compliance.',
    ogTitle: 'Proof Mode — Verifiable AI',
    ogDescription: 'Tamper-evident proof of every cognitive operation for enterprise compliance.',
    ogImage: OG_FEATURE,
    keywords: ['AI proof mode', 'verifiable AI', 'execution proof', 'AI audit trail', 'cryptographic AI logging', 'compliance AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'verifiable AI execution proof',
  },
  '/demo': {
    title: 'Live Demo — CMPSBL Substrate in Action',
    description: 'See the CMPSBL substrate in action: live module orchestration, dream cycles, and cognitive inference in a guided interactive demo.',
    ogTitle: 'See CMPSBL in Action — Live Demo',
    ogDescription: 'Interactive demo of the AI operating system with live orchestration.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL demo', 'AI demo', 'substrate demo', 'live AI demo', 'cognitive infrastructure demo'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate live demo',
  },
  '/demos': {
    title: 'S-Tier Demos — Crown Jewel Showcases | CMPSBL',
    description: 'Experience unprecedented AI capabilities: self-healing architecture, cognitive provenance, sovereign execution, and the living module map.',
    ogTitle: 'S-Tier Demos — Unprecedented AI Capabilities',
    ogDescription: 'Self-healing, provenance chains, sovereign execution — see what no other platform can do.',
    ogImage: OG_DEFAULT,
    keywords: ['AI self-healing demo', 'cognitive provenance', 'sovereign AI execution', 'living architecture', 'S-tier AI showcase'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'S-tier AI capability demos',
  },
  '/lab': {
    title: 'Experimentation Lab — Test AI Hypotheses',
    description: 'A sandboxed environment to test, benchmark, and validate cognitive experiments before deploying to production substrate.',
    ogTitle: 'AI Experimentation Lab',
    ogDescription: 'Sandbox for testing cognitive experiments before production deployment.',
    ogImage: OG_FEATURE,
    keywords: ['AI experimentation lab', 'cognitive sandbox', 'AI benchmarking', 'test AI hypotheses', 'substrate lab'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI experimentation lab',
  },
  '/codelab': {
    title: 'CodeLab — Execute & Test in Real-Time',
    description: 'Write, execute, and test substrate operations in a live coding environment with real-time feedback and inline documentation.',
    ogTitle: 'CodeLab — Live AI Coding Environment',
    ogDescription: 'Write and test substrate code with real-time execution and inline docs.',
    ogImage: OG_DOCS,
    keywords: ['AI CodeLab', 'live coding AI', 'substrate code editor', 'real-time AI testing', 'interactive AI IDE'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI live coding environment',
  },
  '/forge': {
    title: 'Cognitive Forge — Build Custom AI Agents',
    description: 'Design, train, and deploy custom cognitive agents in the Forge. Drag-and-drop skill composition with automatic competency tracking.',
    ogTitle: 'Cognitive Forge — Build Your AI Agent',
    ogDescription: 'Drag-and-drop agent builder with skill composition and competency tracking.',
    ogImage: OG_FEATURE,
    keywords: ['cognitive forge', 'AI agent builder', 'custom AI agents', 'drag drop AI', 'agent composition tool', 'build AI agents'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'custom AI agent builder',
  },
  '/agency': {
    title: 'Agency Mint — Deploy AI Teams',
    description: 'Mint multi-agent AI teams from templates. Each agency includes coordinated roles, shared memory, and economic tracking.',
    ogTitle: 'Agency Mint — Launch AI Teams',
    ogDescription: 'Deploy coordinated multi-agent teams with shared memory and economics.',
    ogImage: OG_FEATURE,
    keywords: ['AI agency mint', 'multi-agent teams', 'AI team deployment', 'agent coordination', 'shared AI memory teams'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'multi-agent AI team deployment',
  },
  '/gaming': {
    title: 'Gaming AI — Cognitive NPC & Game Logic',
    description: 'Power game NPCs with persistent memory, adaptive behavior, and dream-cycle learning. Built for Unreal, Unity, and custom engines.',
    ogTitle: 'Gaming AI — NPCs That Learn',
    ogDescription: 'Cognitive NPC engines with persistent memory and adaptive behavior for games.',
    ogImage: OG_FEATURE,
    keywords: ['gaming AI', 'cognitive NPC', 'AI game logic', 'persistent NPC memory', 'adaptive game AI', 'Unity AI NPC'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive gaming AI NPCs',
  },
  '/system-feed': {
    title: 'System Intelligence Feed — Real-Time Insights',
    description: 'Live feed of system-wide cognitive events, anomalies, and learning breakthroughs across all active substrate modules.',
    ogTitle: 'System Feed — Live AI Intelligence',
    ogDescription: 'Real-time cognitive events and anomalies from across the substrate.',
    ogImage: OG_FEATURE,
    keywords: ['AI system feed', 'real-time AI events', 'cognitive anomaly detection', 'substrate monitoring', 'AI intelligence feed'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'real-time AI system intelligence feed',
  },

  // ═══════════════════════════════════════════════════
  // DEVELOPER / DOCS
  // ═══════════════════════════════════════════════════
  '/developers': {
    title: 'Developer Hub — SDKs, APIs & Integrations',
    description: 'Everything developers need: SDKs, REST APIs, webhooks, and integration guides for building on the CMPSBL substrate.',
    ogTitle: 'CMPSBL Developer Hub',
    ogDescription: 'SDKs, APIs, webhooks, and integration guides for building on the substrate.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL developer hub', 'AI SDK', 'substrate API', 'AI integration guide', 'developer portal AI', 'cognitive API'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL developer SDK and API',
  },
  '/documentation': {
    title: 'Documentation — CMPSBL Developer Guide',
    description: 'Complete technical documentation for the CMPSBL substrate: module reference, API specs, configuration, and deployment guides.',
    ogTitle: 'CMPSBL Documentation',
    ogDescription: 'Complete API reference, module docs, and deployment guides for the substrate.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL documentation', 'substrate docs', 'AI API reference', 'module documentation', 'technical guide AI'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL technical documentation',
  },
  '/docs/persistent-memory': {
    title: 'Persistent Memory Quickstart — Integration Guide',
    description: 'Step-by-step guide to integrating persistent memory into your AI agent. Covers LangChain, CrewAI, and raw SDK approaches.',
    ogTitle: 'Persistent Memory Quickstart',
    ogDescription: 'Add persistent memory to your agent in 15 minutes — step-by-step guide.',
    ogImage: OG_DOCS,
    keywords: ['persistent memory quickstart', 'AI memory integration', 'LangChain memory guide', 'CrewAI memory', 'agent memory tutorial'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'persistent memory integration guide',
  },
  '/docs/substrate/capabilities': {
    title: 'Capabilities Reference — 400+ AI Functions',
    description: 'Complete reference for all 400+ substrate capabilities: parameters, tier availability, synergy compatibility, and usage examples.',
    ogTitle: 'Capability Reference — 400+ Functions',
    ogDescription: 'Browse the full catalog of AI capabilities with parameters and examples.',
    ogImage: OG_DOCS,
    keywords: ['AI capabilities reference', 'substrate functions', 'capability catalog', 'AI function reference', 'API capability docs'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI capabilities reference documentation',
  },
  '/academy': {
    title: 'Developer Academy — Interactive AI Tutorials',
    description: 'Learn to build on the substrate with interactive, AI-powered tutorials. From beginner agent builders to advanced orchestration.',
    ogTitle: 'Developer Academy — Learn AI Building',
    ogDescription: 'Interactive tutorials from beginner to advanced substrate development.',
    ogImage: OG_DOCS,
    keywords: ['AI developer academy', 'interactive AI tutorials', 'learn AI building', 'substrate training', 'cognitive development course'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'interactive AI developer tutorials',
  },
  '/devtools': {
    title: 'DevTools — Diagnostics & Developer Utilities',
    description: 'Debug and inspect your substrate in real-time: module state inspector, network tracer, memory explorer, and performance profiler.',
    ogTitle: 'CMPSBL DevTools — Debug Your AI',
    ogDescription: 'Real-time diagnostics and debugging utilities for the substrate.',
    ogImage: OG_DOCS,
    keywords: ['AI DevTools', 'substrate debugger', 'AI diagnostics', 'module inspector', 'cognitive performance profiler'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI substrate developer tools',
  },
  '/changelog': {
    title: 'Changelog — Substrate Version History',
    description: 'Track every update to the CMPSBL substrate: new modules, capabilities, patches, and architecture changes from v1.0 to v9.1.0.',
    ogTitle: 'Changelog — What\'s New in CMPSBL',
    ogDescription: 'Complete version history from v1.0 to v9.1.0 ARCHITECT Epoch.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL changelog', 'substrate updates', 'version history AI', 'AI platform changelog', 'v9.1.0 release notes'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL substrate changelog',
  },

  // ═══════════════════════════════════════════════════
  // ENTERPRISE / PRICING
  // ═══════════════════════════════════════════════════
  '/solutions': {
    title: 'Enterprise AI Solutions — Industry Applications',
    description: 'Enterprise-ready cognitive infrastructure for healthcare, finance, legal, and manufacturing. SOC 2 compliant, on-prem available.',
    ogTitle: 'Enterprise AI Solutions by CMPSBL',
    ogDescription: 'Industry-specific cognitive infrastructure with compliance and on-prem deployment.',
    ogImage: OG_FEATURE,
    keywords: ['enterprise AI solutions', 'industry AI applications', 'SOC 2 AI', 'healthcare AI', 'finance AI platform', 'on-prem AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'enterprise AI solutions',
  },
  '/use-cases': {
    title: 'Use Cases — How Teams Deploy CMPSBL',
    description: 'Real-world use cases: autonomous research agencies, code review pipelines, customer support agents, and self-healing infrastructure.',
    ogTitle: 'AI Use Cases — Real Deployments',
    ogDescription: 'See how teams deploy autonomous research, code review, and self-healing AI.',
    ogImage: OG_FEATURE,
    keywords: ['AI use cases', 'autonomous research AI', 'code review AI', 'customer support AI agents', 'self-healing AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI use cases and deployments',
  },
  '/pricing': {
    title: 'Pricing — Free, Builder, Pro & Enterprise Tiers',
    description: 'Transparent pricing for every team size. Free tier with persistent memory, Builder for production, Pro for scale, Enterprise for compliance.',
    ogTitle: 'CMPSBL Pricing — Start Free',
    ogDescription: 'Free tier to Enterprise: transparent pricing for cognitive infrastructure.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL pricing', 'AI platform pricing', 'free AI tier', 'enterprise AI pricing', 'cognitive infrastructure cost'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'CMPSBL pricing plans',
  },
  '/substrate/licensing': {
    title: 'Licensing — Enterprise Agreements & OEM',
    description: 'Enterprise licensing for the CMPSBL substrate: volume agreements, OEM embedding, white-label options, and dedicated support.',
    ogTitle: 'Enterprise Licensing — CMPSBL',
    ogDescription: 'Volume licensing, OEM embedding, and white-label agreements for enterprises.',
    ogImage: OG_FEATURE,
    keywords: ['AI enterprise licensing', 'OEM AI agreement', 'white-label AI', 'substrate licensing', 'volume AI license'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'enterprise AI licensing agreement',
  },
  '/intelligence': {
    title: 'Substrate Intelligence — Technology Proof',
    description: 'Deep-dive into the substrate\'s architectural proof: benchmarks, module interaction graphs, and capability coverage analysis.',
    ogTitle: 'Substrate Intelligence — Proof of Architecture',
    ogDescription: 'Benchmarks, interaction graphs, and capability coverage for the substrate.',
    ogImage: OG_FEATURE,
    keywords: ['substrate intelligence', 'AI architecture proof', 'AI benchmarks', 'capability coverage', 'technology validation AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI architecture intelligence proof',
  },
  '/investors': {
    title: 'Acquisition Opportunity — CMPSBL® Substrate',
    description: 'CMPSBL represents a generational acquisition opportunity: 17 years of R&D, 21 modules, 400+ capabilities, and defensible IP.',
    ogTitle: 'Investment & Acquisition — CMPSBL',
    ogDescription: '17 years of R&D, 21 modules, 400+ capabilities — a generational acquisition opportunity.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL acquisition', 'AI startup investment', 'cognitive infrastructure acquisition', 'AI IP portfolio', 'strategic AI acquisition'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL acquisition opportunity',
  },
  '/marketplace': {
    title: 'Marketplace — AI Templates & Integrations',
    description: 'Browse community and first-party templates, integrations, and pre-built cognitive workflows in the CMPSBL marketplace.',
    ogTitle: 'CMPSBL Marketplace',
    ogDescription: 'Templates, integrations, and pre-built cognitive workflows.',
    ogImage: OG_FEATURE,
    keywords: ['AI marketplace', 'cognitive templates', 'AI integrations marketplace', 'pre-built AI workflows', 'CMPSBL marketplace'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI templates marketplace',
  },

  // ═══════════════════════════════════════════════════
  // COMPANY / ABOUT / TRUST
  // ═══════════════════════════════════════════════════
  '/about': {
    title: 'About CMPSBL — Founded 2009, Dallas TX',
    description: 'CMPSBL was founded in 2009 by Kenneth E Sweet Jr. From Dallas, TX to a 21-module cognitive infrastructure powering the future of AI.',
    ogTitle: 'About CMPSBL — Our Origin Story',
    ogDescription: 'From 2009 to 21 modules — the story of building cognitive infrastructure for AI.',
    ogImage: OG_ABOUT,
    keywords: ['about CMPSBL', 'Kenneth Sweet', 'CMPSBL founder', 'Dallas AI company', 'cognitive infrastructure story', 'AI startup Texas'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'about CMPSBL founder story',
  },
  '/contact': {
    title: 'Contact CMPSBL — Get in Touch',
    description: 'Reach the CMPSBL team for partnerships, enterprise inquiries, support, or press. Based in Dallas, TX — serving teams worldwide.',
    ogTitle: 'Contact CMPSBL',
    ogDescription: 'Get in touch for partnerships, enterprise inquiries, or press.',
    ogImage: OG_ABOUT,
    keywords: ['contact CMPSBL', 'AI partnership inquiry', 'enterprise AI contact', 'CMPSBL support', 'Dallas AI company contact'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'contact CMPSBL team',
  },
  '/support': {
    title: 'Support — Help & Resources | CMPSBL',
    description: 'Get help with the CMPSBL substrate: knowledge base, ticket system, community forums, and direct engineering support for Enterprise tier.',
    ogTitle: 'CMPSBL Support Center',
    ogDescription: 'Knowledge base, tickets, and direct engineering support.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL support', 'AI platform help', 'substrate troubleshooting', 'CMPSBL knowledge base', 'AI support tickets'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'CMPSBL support center',
  },

  // ═══════════════════════════════════════════════════
  // BLOG / CONTENT
  // ═══════════════════════════════════════════════════
  '/blog': {
    title: 'Blog — AI Infrastructure Research & Insights',
    description: 'Research, deep-dives, and engineering insights on cognitive infrastructure, AI memory, governance, and the ARCHITECT Epoch.',
    ogTitle: 'CMPSBL Blog — AI Research & Insights',
    ogDescription: 'Deep-dives on cognitive infrastructure, AI memory, and substrate engineering.',
    ogImage: OG_BLOG,
    keywords: ['CMPSBL blog', 'AI infrastructure blog', 'cognitive AI research', 'AI memory insights', 'substrate engineering blog'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI infrastructure research blog',
  },
  '/publication': {
    title: 'Publication — Research Papers & Whitepapers',
    description: 'Peer-reviewed research and whitepapers on cognitive infrastructure, dream-cycle learning, and autonomous system architecture.',
    ogTitle: 'CMPSBL Publications',
    ogDescription: 'Research papers on cognitive infrastructure and autonomous AI systems.',
    ogImage: OG_BLOG,
    keywords: ['AI research papers', 'cognitive infrastructure whitepaper', 'dream cycle research', 'autonomous AI paper', 'CMPSBL publications'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI cognitive infrastructure research papers',
  },
  '/library': {
    title: 'Library — Documentation & Knowledge Archive',
    description: 'Curated archive of substrate documentation, architectural references, module specifications, and development resources.',
    ogTitle: 'CMPSBL Library',
    ogDescription: 'Curated documentation archive and architectural references.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL library', 'AI documentation archive', 'substrate knowledge base', 'module specifications', 'AI architecture reference'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI documentation knowledge archive',
  },
  '/insights': {
    title: 'Insights — AI Industry Analysis | CMPSBL',
    description: 'Data-driven analysis of AI industry trends, market dynamics, and technological shifts from the CMPSBL intelligence team.',
    ogTitle: 'AI Industry Insights by CMPSBL',
    ogDescription: 'Data-driven analysis of AI trends and market dynamics.',
    ogImage: OG_BLOG,
    keywords: ['AI industry insights', 'AI market analysis', 'cognitive AI trends', 'AI technology shifts', 'CMPSBL intelligence'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI industry analysis insights',
  },

  // ═══════════════════════════════════════════════════
  // STANDARDS / PROTOCOL
  // ═══════════════════════════════════════════════════
  '/namespace': {
    title: 'Namespace — Unified AI Terminology Standard',
    description: 'The CMPSBL namespace defines the canonical vocabulary for cognitive infrastructure: 600+ terms, standardized across all 21 modules.',
    ogTitle: 'Namespace — AI Terminology Standard',
    ogDescription: 'Canonical vocabulary for cognitive infrastructure with 600+ standardized terms.',
    ogImage: OG_DOCS,
    keywords: ['AI namespace', 'cognitive terminology', 'AI vocabulary standard', 'substrate namespace', 'unified AI terminology'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'unified AI terminology namespace',
  },
  '/foundations': {
    title: 'Foundations — Core Principles & Architecture',
    description: 'The foundational principles behind CMPSBL: composability, persistent state, autonomous evolution, and cognitive coherence.',
    ogTitle: 'CMPSBL Foundations — Core Principles',
    ogDescription: 'The architectural principles behind cognitive infrastructure.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL foundations', 'AI architecture principles', 'cognitive composability', 'autonomous evolution', 'AI design principles'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'cognitive infrastructure foundations',
  },
  '/roadmap': {
    title: 'Roadmap — What\'s Coming to CMPSBL',
    description: 'See what\'s next for the substrate: upcoming modules, capability expansions, enterprise features, and the path to v10.0.',
    ogTitle: 'CMPSBL Roadmap — What\'s Next',
    ogDescription: 'Upcoming modules, capabilities, and the path to v10.0.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL roadmap', 'AI platform roadmap', 'substrate future plans', 'upcoming AI features', 'v10 roadmap'],
    schema: 'docs',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL substrate roadmap',
  },
  '/llms-txt': {
    title: 'llms.txt — Machine-Readable AI Context',
    description: 'CMPSBL\'s llms.txt provides structured context for AI crawlers: module catalog, capability index, and API surface for GPTBot and ClaudeBot.',
    ogTitle: 'llms.txt — AI Crawler Context',
    ogDescription: 'Machine-readable context file for GPTBot, ClaudeBot, and AI crawlers.',
    ogImage: OG_DOCS,
    keywords: ['llms.txt', 'AI crawler context', 'GPTBot', 'ClaudeBot', 'machine-readable AI', 'AI discovery optimization'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'llms.txt AI crawler protocol',
  },
  '/humans-txt': {
    title: 'humans.txt — The Team Behind CMPSBL',
    description: 'Meet the humans building cognitive infrastructure. Credits, contributors, and the engineering team behind the substrate.',
    ogTitle: 'humans.txt — Meet the Team',
    ogDescription: 'The humans building cognitive infrastructure for AI.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL team', 'humans.txt', 'AI engineering team', 'substrate contributors'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL engineering team credits',
  },

  // ═══════════════════════════════════════════════════
  // CLUSTER / DEEP-DIVE PAGES
  // ═══════════════════════════════════════════════════
  '/cluster/studio-autonomous-site-generator': {
    title: 'STUDIO Module — Autonomous Site Generation',
    description: 'STUDIO generates production-ready web applications autonomously using cognitive pipelines, design intelligence, and real-time deployment.',
    ogTitle: 'STUDIO — Autonomous Site Generator',
    ogDescription: 'AI-powered site generation with design intelligence and instant deployment.',
    ogImage: OG_FEATURE,
    keywords: ['STUDIO module', 'autonomous site generator', 'AI web builder', 'cognitive site generation', 'AI design intelligence'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous AI site generator module',
  },
  '/cluster/verify-worlds-first-ai-plugin-certification': {
    title: 'VERIFY Module — AI Plugin Certification',
    description: 'The world\'s first AI plugin certification system. VERIFY validates safety, performance, and compatibility before deployment.',
    ogTitle: 'VERIFY — First AI Plugin Certification',
    ogDescription: 'Certify AI plugin safety, performance, and compatibility before deployment.',
    ogImage: OG_FEATURE,
    keywords: ['VERIFY module', 'AI plugin certification', 'AI safety validation', 'plugin compatibility testing', 'AI certification system'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI plugin certification system',
  },
  '/cluster/inclusive-module-accessibility': {
    title: 'INCLUSIVE Module — AI Accessibility Engine',
    description: 'INCLUSIVE delivers automated WCAG compliance, real-time accessibility auditing, and AI-powered remediation for any web property.',
    ogTitle: 'INCLUSIVE — AI Accessibility Engine',
    ogDescription: 'Automated WCAG compliance and AI-powered accessibility remediation.',
    ogImage: OG_FEATURE,
    keywords: ['INCLUSIVE module', 'AI accessibility', 'WCAG compliance AI', 'automated accessibility', 'accessibility engine'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI-powered accessibility compliance engine',
  },

  // ═══════════════════════════════════════════════════
  // PRODUCT PAGES
  // ═══════════════════════════════════════════════════
  '/products/encode': {
    title: 'ENCODE — The Substrate Code Agent',
    description: 'ENCODE is the substrate\'s code intelligence agent: reads, writes, and refactors code with full system awareness across all 21 modules.',
    ogTitle: 'ENCODE — Code Intelligence Agent',
    ogDescription: 'The substrate\'s code agent with full system awareness across 21 modules.',
    ogImage: OG_FEATURE,
    keywords: ['ENCODE agent', 'AI code agent', 'substrate code intelligence', 'autonomous coding AI', 'system-aware code agent'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'ENCODE AI code intelligence agent',
  },
  '/start-here': {
    title: 'Start Here — Get Oriented with CMPSBL',
    description: 'New to CMPSBL? Start here for a guided introduction to the substrate, its modules, and how to build your first cognitive application.',
    ogTitle: 'Start Here — Your CMPSBL Journey',
    ogDescription: 'Guided introduction to the substrate and building your first AI application.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL getting started', 'substrate onboarding', 'first AI app guide', 'beginner AI platform', 'CMPSBL quickstart'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL getting started guide',
  },

  // ═══════════════════════════════════════════════════
  // LEGAL
  // ═══════════════════════════════════════════════════
  '/privacy': {
    title: 'Privacy Policy — CMPSBL®',
    description: 'CMPSBL privacy policy: how we collect, store, and protect your data. GDPR-compliant, transparent data practices.',
    ogTitle: 'Privacy Policy — CMPSBL',
    ogDescription: 'How CMPSBL handles your data — transparent, GDPR-compliant practices.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL privacy policy', 'AI data privacy', 'GDPR compliant AI', 'data protection policy'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL privacy policy',
  },
  '/terms': {
    title: 'Terms of Service — CMPSBL®',
    description: 'Terms of service for the CMPSBL substrate platform. Covers usage rights, intellectual property, and service-level commitments.',
    ogTitle: 'Terms of Service — CMPSBL',
    ogDescription: 'Usage terms, IP rights, and SLA commitments for the substrate.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL terms of service', 'AI platform terms', 'substrate usage terms', 'service agreement AI'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL terms of service',
  },

  // ═══════════════════════════════════════════════════
  // NOINDEX PAGES (utility, admin, auth)
  // ═══════════════════════════════════════════════════
  '/auth': {
    title: 'Sign In — CMPSBL',
    description: 'Sign in to your CMPSBL account to access the substrate dashboard, cognitive agents, and enterprise tools.',
    ogTitle: 'Sign In — CMPSBL',
    ogDescription: 'Access your substrate dashboard and cognitive tools.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL login', 'sign in AI platform'],
    schema: 'legal',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL sign in',
    noindex: true,
  },
  '/register': {
    title: 'Register — Create Your CMPSBL Account',
    description: 'Create a free CMPSBL account to start building with cognitive infrastructure. Access persistent memory, Decode, and 400+ capabilities.',
    ogTitle: 'Register — Join CMPSBL',
    ogDescription: 'Create your free account and start building with cognitive infrastructure.',
    ogImage: OG_DEFAULT,
    keywords: ['CMPSBL register', 'create AI account', 'free AI platform signup'],
    schema: 'legal',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL register account',
    noindex: true,
  },
  '/clear-cache': {
    title: 'Clear Cache — CMPSBL',
    description: 'Clear local cache and reset substrate state.',
    ogTitle: 'Clear Cache',
    ogDescription: 'Reset local state and cache.',
    ogImage: OG_DEFAULT,
    keywords: ['clear cache'],
    schema: 'legal',
    intent: 'Utility',
    primaryKeyword: 'clear cache utility',
    noindex: true,
  },
  '/substrate': {
    title: 'Substrate Dashboard — Command Center',
    description: 'Your cognitive command center: module health, agent status, dream cycles, and real-time system telemetry.',
    ogTitle: 'Substrate Dashboard',
    ogDescription: 'Your cognitive AI command center.',
    ogImage: OG_FEATURE,
    keywords: ['substrate dashboard', 'AI command center', 'module health dashboard'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate command center dashboard',
    noindex: true,
  },
  '/audit': {
    title: 'Audit Trail — Substrate Operations Log',
    description: 'Complete audit trail of all substrate operations with cryptographic integrity verification and compliance filtering.',
    ogTitle: 'Audit Trail — CMPSBL',
    ogDescription: 'Cryptographic audit log for all substrate operations.',
    ogImage: OG_FEATURE,
    keywords: ['AI audit trail', 'substrate operations log', 'cryptographic audit'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate audit trail',
    noindex: true,
  },
  // ═══════════════════════════════════════════════════
  // BLOG POSTS — Individual articles (unique per post)
  // ═══════════════════════════════════════════════════
  '/blog/machine-protocol-standards-architect-epoch': {
    title: 'Machine-to-Machine Protocol Standards | CMPSBL',
    description: 'How RELAY and IDENTITY modules establish authenticated, auditable protocol standards for autonomous multi-agent communication in the ARCHITECT Epoch.',
    ogTitle: 'Machine Protocol Standards — ARCHITECT Epoch',
    ogDescription: 'Authenticated protocols for autonomous agent communication.',
    ogImage: OG_BLOG,
    keywords: ['machine protocol standards', 'agent communication protocol', 'AI relay module', 'IDENTITY attribution', 'multi-agent messaging'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'machine-to-machine AI protocol standards',
  },
  '/blog/autonomous-ai-governance-runtime-enforcement': {
    title: 'Autonomous AI Governance: Runtime Enforcement | CMPSBL',
    description: 'AUDIT and IDENTITY modules deliver cryptographic compliance logging and universal actor attribution for enterprise AI governance.',
    ogTitle: 'AI Governance — Runtime Enforcement',
    ogDescription: 'Cryptographic compliance logging for autonomous AI systems.',
    ogImage: OG_BLOG,
    keywords: ['AI governance runtime', 'compliance logging AI', 'audit module', 'actor attribution', 'SOC 2 AI compliance'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'autonomous AI governance runtime enforcement',
  },
  '/blog/adversarial-ai-defense-module-response-2026': {
    title: 'Adversarial AI in 2026: DEFENSE Module Response | CMPSBL',
    description: 'How the DEFENSE module counters prompt injection, behavioral fingerprinting attacks, and zero-trust mesh threats in the ARCHITECT Epoch.',
    ogTitle: 'Adversarial AI — DEFENSE Module Response',
    ogDescription: 'Countering prompt injection and behavioral fingerprinting in 2026.',
    ogImage: OG_BLOG,
    keywords: ['adversarial AI 2026', 'prompt injection defense', 'behavioral fingerprinting', 'zero-trust AI mesh', 'DEFENSE module'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'adversarial AI defense module 2026',
  },
  '/blog/evolving-software-v6-breakthrough': {
    title: 'Evolving Software v6: The Breakthrough | CMPSBL',
    description: 'CMPSBL v6.x.x represents a paradigm shift — systems that learn, adapt, and evolve autonomously via API-first cognitive architecture.',
    ogTitle: 'Evolving Software v6 — The Breakthrough',
    ogDescription: 'AI systems that learn, adapt, and evolve autonomously.',
    ogImage: OG_BLOG,
    keywords: ['evolving software', 'self-evolving AI', 'autonomous software evolution', 'v6 breakthrough', 'adaptive AI systems'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'evolving software v6 autonomous breakthrough',
  },
  '/blog/rag-without-infrastructure': {
    title: 'RAG Without Infrastructure Overhead | CMPSBL',
    description: 'Ship retrieval-augmented generation without managing vector databases, embeddings pipelines, or Pinecone. One API call.',
    ogTitle: 'RAG Without Infrastructure',
    ogDescription: 'Retrieval-augmented generation without vector DB management.',
    ogImage: OG_BLOG,
    keywords: ['RAG without infrastructure', 'managed RAG API', 'vector search API', 'simple RAG', 'no Pinecone RAG'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RAG without infrastructure management',
  },
  '/blog/agent-memory-anti-patterns': {
    title: 'Agent Memory Anti-Patterns to Avoid | CMPSBL',
    description: 'Common mistakes that cause AI agents to lose context — and battle-tested patterns to fix memory degradation in production.',
    ogTitle: 'Agent Memory Anti-Patterns',
    ogDescription: 'Common mistakes causing AI context loss and how to fix them.',
    ogImage: OG_BLOG,
    keywords: ['agent memory anti-patterns', 'AI context loss', 'memory degradation', 'agent state bugs', 'production AI memory'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI agent memory anti-patterns',
  },
  '/blog/langchain-memory-integration': {
    title: 'LangChain Persistent Memory Integration | CMPSBL',
    description: 'Add persistent, cross-session memory to your LangChain agents in under an hour with a drop-in replacement for ConversationBufferMemory.',
    ogTitle: 'LangChain Memory — Drop-In Persistent',
    ogDescription: 'Persistent LangChain memory in under an hour.',
    ogImage: OG_BLOG,
    keywords: ['LangChain persistent memory', 'LangChain memory replacement', 'cross-session agent memory', 'ConversationBufferMemory alternative'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'LangChain persistent memory integration',
  },
  '/blog/why-agents-forget': {
    title: 'Why AI Agents Forget: Technical Causes | CMPSBL',
    description: 'The technical reasons behind context loss and memory degradation — from token limits to serialization bugs in AI agent systems.',
    ogTitle: 'Why Agents Forget — Technical Deep Dive',
    ogDescription: 'Technical causes of AI memory degradation explained.',
    ogImage: OG_BLOG,
    keywords: ['why agents forget', 'AI memory loss causes', 'context window limits', 'agent serialization bugs', 'token limit problems'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'why AI agents forget context',
  },
  '/blog/building-agents-that-learn': {
    title: 'Building Agents That Learn from Experience | CMPSBL',
    description: 'Architectural patterns for AI systems that improve through experience — from competency scoring to heuristic extraction.',
    ogTitle: 'Building Agents That Learn',
    ogDescription: 'Architectural patterns for self-improving AI agents.',
    ogImage: OG_BLOG,
    keywords: ['building learning agents', 'self-improving AI', 'competency scoring', 'heuristic extraction', 'experience-driven AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'building AI agents that learn experience',
  },
  '/blog/llms-txt-protocol-ai-context': {
    title: 'LLMs.txt Protocol: AI Context Standard | CMPSBL',
    description: 'How we follow the llmstxt.org protocol standard and why every AI platform should adopt machine-readable context files.',
    ogTitle: 'LLMs.txt — The AI Context Protocol',
    ogDescription: 'Machine-readable context files for AI crawlers.',
    ogImage: OG_BLOG,
    keywords: ['llms.txt protocol', 'AI context standard', 'machine-readable context', 'GPTBot context', 'AI discovery protocol'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'llms.txt protocol AI context standard',
  },
  '/blog/ai-governance-namespace-unified-terminology': {
    title: 'AI Governance Namespace: Unified Terminology | CMPSBL',
    description: 'How we established unified AI governance vocabulary through strategic domain registration and 600+ standardized terms.',
    ogTitle: 'AI Governance Namespace — Unified Terms',
    ogDescription: 'Standardizing AI governance vocabulary across the industry.',
    ogImage: OG_BLOG,
    keywords: ['AI governance namespace', 'unified AI terminology', 'AI vocabulary standard', 'governance vocabulary', 'domain strategy AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI governance unified terminology namespace',
  },
  '/blog/inclusive-module-accessibility-mission': {
    title: 'INCLUSIVE Module: Accessibility Mission | CMPSBL',
    description: 'Our commitment to making the web accessible through AI-powered WCAG automation — the INCLUSIVE module story.',
    ogTitle: 'INCLUSIVE Module — Accessibility Mission',
    ogDescription: 'AI-powered web accessibility at scale.',
    ogImage: OG_BLOG,
    keywords: ['INCLUSIVE module', 'AI accessibility mission', 'WCAG automation', 'web accessibility AI', 'accessible web commitment'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'INCLUSIVE module accessibility mission',
  },
  '/blog/accessibility-free-for-all': {
    title: 'Accessibility for Everyone: A Free Mandate | CMPSBL',
    description: 'Why web accessibility matters at planetary scale and how AI-powered automation makes compliance achievable for every website.',
    ogTitle: 'Accessibility for Everyone',
    ogDescription: 'Why accessibility should be free and AI-powered.',
    ogImage: OG_BLOG,
    keywords: ['free accessibility', 'accessibility for everyone', 'AI accessibility tools', 'WCAG compliance free', 'universal web access'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free web accessibility for everyone',
  },
  '/blog/wordpress-accessibility-guide': {
    title: 'WordPress Accessibility Guide: WCAG Compliance | CMPSBL',
    description: 'Complete guide to making your WordPress site WCAG 2.2 compliant — from semantic HTML to ARIA roles and automated testing.',
    ogTitle: 'WordPress Accessibility — Complete Guide',
    ogDescription: 'Make your WordPress site WCAG compliant.',
    ogImage: OG_BLOG,
    keywords: ['WordPress accessibility guide', 'WCAG WordPress', 'WordPress ARIA roles', 'accessible WordPress theme', 'WordPress compliance'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress accessibility WCAG compliance guide',
  },
  '/blog/wcag-2-2-wordpress-changes': {
    title: 'WCAG 2.2 Changes for WordPress Developers | CMPSBL',
    description: 'What the latest WCAG 2.2 updates mean for WordPress developers — new success criteria, deprecated patterns, and implementation guidance.',
    ogTitle: 'WCAG 2.2 — What Changed for WordPress',
    ogDescription: 'New WCAG 2.2 criteria and WordPress implementation.',
    ogImage: OG_BLOG,
    keywords: ['WCAG 2.2 changes', 'WordPress WCAG 2.2', 'new accessibility criteria', 'WCAG update 2025', 'WordPress developer accessibility'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WCAG 2.2 changes WordPress developers',
  },
  '/blog/automated-accessibility-fixes-wordpress': {
    title: 'Automated Accessibility Fixes for WordPress | CMPSBL',
    description: 'AI-powered remediation for common WordPress accessibility issues — from missing alt text to color contrast and focus management.',
    ogTitle: 'Automated Accessibility Fixes — WordPress',
    ogDescription: 'AI-powered accessibility remediation for WordPress.',
    ogImage: OG_BLOG,
    keywords: ['automated accessibility fixes', 'WordPress accessibility AI', 'alt text automation', 'color contrast fix', 'focus management WordPress'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'automated WordPress accessibility fixes AI',
  },
  '/blog/ai-systems-that-dream-press-release': {
    title: 'AI Systems That Dream: Experimental Research | CMPSBL',
    description: 'Cascade and SimNap explore autonomous dreaming, reflection, and self-improvement in experimental cognitive AI systems.',
    ogTitle: 'AI Systems That Dream — Research',
    ogDescription: 'Experimental AI systems with autonomous dreaming capabilities.',
    ogImage: OG_BLOG,
    keywords: ['AI dreaming systems', 'Cascade AI dreams', 'SimNap reflection', 'autonomous AI dreaming', 'cognitive dream cycles'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'experimental AI systems that dream',
  },
  '/blog/wordpress-bot-defense': {
    title: 'WordPress Bot Defense: AI Behavioral Analysis | CMPSBL',
    description: 'Protect your WordPress site from sophisticated bot attacks using AI-powered behavioral analysis and session fingerprinting.',
    ogTitle: 'WordPress Bot Defense Guide',
    ogDescription: 'AI behavioral analysis for WordPress bot protection.',
    ogImage: OG_BLOG,
    keywords: ['WordPress bot defense', 'AI bot detection', 'behavioral analysis security', 'session fingerprinting', 'WordPress anti-bot'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress bot defense behavioral analysis',
  },
  '/blog/top-security-plugins-2025': {
    title: 'Top WordPress Security Plugins 2025 | CMPSBL',
    description: 'Comprehensive comparison of WordPress security plugins including AI-powered defense, firewall strength, and malware detection in 2025.',
    ogTitle: 'Top Security Plugins 2025',
    ogDescription: 'Best WordPress security plugins compared for 2025.',
    ogImage: OG_BLOG,
    keywords: ['WordPress security plugins 2025', 'best security plugins', 'WordPress firewall comparison', 'malware detection WordPress'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'top WordPress security plugins 2025',
  },
  '/blog/ai-cybersecurity-evolution-2025': {
    title: 'AI Cybersecurity Evolution: Behavioral Defense | CMPSBL',
    description: 'From signature-based detection to behavioral AI — why traditional security methods fail against modern threats and how adaptive analysis wins.',
    ogTitle: 'AI Cybersecurity Evolution 2025',
    ogDescription: 'Behavioral AI vs traditional security methods.',
    ogImage: OG_BLOG,
    keywords: ['AI cybersecurity evolution', 'behavioral security AI', 'adaptive threat detection', 'signature-based vs behavioral', 'cybersecurity 2025'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI cybersecurity evolution behavioral defense',
  },
  '/blog/ai-hackers-underground-2025': {
    title: 'AI Hackers Underground: Weaponized Intelligence | CMPSBL',
    description: 'Inside look at how malicious actors weaponize AI for sophisticated attacks — and how cognitive defense systems respond.',
    ogTitle: 'AI Hackers Underground 2025',
    ogDescription: 'How attackers weaponize AI and how defense systems respond.',
    ogImage: OG_BLOG,
    keywords: ['AI hackers underground', 'weaponized AI attacks', 'AI threat actors', 'malicious AI tools', 'AI attack vectors 2025'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI hackers underground weaponized intelligence',
  },
  '/blog/how-promptfluid-works-cascade-ai-ecosystem': {
    title: 'How the Cascade AI Ecosystem Works | CMPSBL',
    description: 'Deep dive into dream cycles, neural orchestration, and the experimental AI concepts powering the cognitive substrate engine.',
    ogTitle: 'How Cascade AI Works — Deep Dive',
    ogDescription: 'Dream cycles, neural orchestration, and cognitive AI internals.',
    ogImage: OG_BLOG,
    keywords: ['Cascade AI ecosystem', 'dream cycle architecture', 'neural orchestration', 'cognitive substrate internals', 'AI engine deep dive'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Cascade AI ecosystem dream cycles',
  },
  '/blog/cascade-ai-adaptive-intelligence-brain': {
    title: 'Cascade AI: Adaptive Intelligence Architecture | CMPSBL',
    description: 'How autonomous dream cycles enable continuous learning, reflection, and adaptive intelligence in the cognitive substrate.',
    ogTitle: 'Cascade AI — Adaptive Intelligence',
    ogDescription: 'Autonomous dream cycles for continuous AI learning.',
    ogImage: OG_BLOG,
    keywords: ['Cascade adaptive intelligence', 'autonomous dream learning', 'continuous AI learning', 'adaptive AI brain', 'reflection AI systems'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Cascade AI adaptive intelligence brain',
  },
  '/blog/promptfluid-studio-build-apps-that-think': {
    title: 'STUDIO Module: Build Apps That Think | CMPSBL',
    description: 'AI-assisted development platform generating production-ready code with cognitive pipelines, design intelligence, and real-time deployment.',
    ogTitle: 'STUDIO — Build Apps That Think',
    ogDescription: 'AI-powered app development with cognitive pipelines.',
    ogImage: OG_BLOG,
    keywords: ['STUDIO module apps', 'AI app development', 'cognitive code generation', 'AI-powered development', 'production-ready AI apps'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'STUDIO module build cognitive apps',
  },
  '/blog/ai-triad-intelligent-routing': {
    title: 'Free-Tier AI Routing: The Triad Architecture | CMPSBL',
    description: 'Multi-provider AI gateway optimized for cost and performance — intelligent routing across free-tier models with zero API spend.',
    ogTitle: 'AI Triad — Free-Tier Routing',
    ogDescription: 'Zero-cost AI routing across multiple providers.',
    ogImage: OG_BLOG,
    keywords: ['AI triad routing', 'free-tier AI gateway', 'multi-provider routing', 'zero-cost AI', 'intelligent model routing'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free-tier AI intelligent routing triad',
  },
  '/blog/promptfluid-brain-adaptive-learning-core': {
    title: 'BRAIN Module: Adaptive Learning Core | CMPSBL',
    description: 'Machine learning engine powering behavioral analysis, threat intelligence, and autonomous heuristic evolution in the substrate.',
    ogTitle: 'BRAIN Module — Adaptive Learning Core',
    ogDescription: 'The ML engine behind behavioral analysis and threat detection.',
    ogImage: OG_BLOG,
    keywords: ['BRAIN module', 'adaptive learning core', 'behavioral analysis ML', 'threat intelligence engine', 'heuristic evolution'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'BRAIN adaptive learning core module',
  },
  '/blog/promptfluid-vision-unified-dashboard': {
    title: 'VISION Module: Unified Command Dashboard | CMPSBL',
    description: 'Central command for monitoring AI orchestration, module telemetry, analytics, and system-wide cognitive health in real-time.',
    ogTitle: 'VISION — Unified Command Center',
    ogDescription: 'Real-time AI orchestration monitoring and analytics.',
    ogImage: OG_BLOG,
    keywords: ['VISION module dashboard', 'AI command center', 'module telemetry', 'cognitive health monitoring', 'orchestration analytics'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'VISION unified command dashboard module',
  },
  '/blog/promptfluid-defense-ai-security': {
    title: 'DEFENSE Module: AI Security Deep Dive | CMPSBL',
    description: 'Advanced bot detection, behavioral fingerprinting, and adaptive security layers protecting the cognitive substrate from emerging threats.',
    ogTitle: 'DEFENSE Module — AI Security',
    ogDescription: 'Bot detection and behavioral fingerprinting for AI systems.',
    ogImage: OG_BLOG,
    keywords: ['DEFENSE module security', 'AI bot detection', 'behavioral fingerprinting defense', 'adaptive security AI', 'substrate protection'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DEFENSE module AI security deep dive',
  },
  '/blog/promptfluid-ripple-network-integration': {
    title: 'RIPPLE Module: Network Integration Patterns | CMPSBL',
    description: 'Distributed AI coordination and multi-agent communication patterns powering cross-module event propagation in the substrate.',
    ogTitle: 'RIPPLE — Network Integration',
    ogDescription: 'Distributed coordination and event propagation for AI.',
    ogImage: OG_BLOG,
    keywords: ['RIPPLE module network', 'distributed AI coordination', 'multi-agent communication', 'event propagation', 'substrate networking'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RIPPLE network integration distributed AI',
  },
  '/blog/promptfluid-access-identity-billing': {
    title: 'ACCESS Module: Identity & Billing Platform | CMPSBL',
    description: 'Enterprise-grade authentication, API key metering, subscription management, and developer billing in the ACCESS module.',
    ogTitle: 'ACCESS — Identity & Billing',
    ogDescription: 'Enterprise auth, API metering, and subscription management.',
    ogImage: OG_BLOG,
    keywords: ['ACCESS module billing', 'API key metering', 'enterprise authentication', 'subscription management AI', 'developer billing platform'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'ACCESS identity billing module platform',
  },
  '/blog/promptfluid-nexus-api-gateway': {
    title: 'NEXUS Module: Unified API Gateway | CMPSBL',
    description: 'Unified API orchestration layer connecting AI services — intelligent routing, load balancing, and schema validation in the NEXUS module.',
    ogTitle: 'NEXUS — API Gateway',
    ogDescription: 'Unified API orchestration with intelligent routing.',
    ogImage: OG_BLOG,
    keywords: ['NEXUS API gateway', 'unified API orchestration', 'intelligent API routing', 'AI service gateway', 'schema validation API'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'NEXUS unified API gateway module',
  },
  '/blog/ai-product-comparison-2025': {
    title: 'AI Product Comparison 2025: CMPSBL vs Competitors',
    description: 'How CMPSBL compares to OpenAI, Anthropic, LangChain, and other AI platforms across capabilities, pricing, and architecture.',
    ogTitle: 'AI Platform Comparison — 2025',
    ogDescription: 'CMPSBL vs OpenAI, Anthropic, and LangChain.',
    ogImage: OG_BLOG,
    keywords: ['AI product comparison 2025', 'CMPSBL vs OpenAI', 'AI platform comparison', 'LangChain vs CMPSBL', 'best AI platform 2025'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI product comparison 2025 platforms',
  },
  '/blog/promptfluid-market-disruptor': {
    title: 'Cognitive Infrastructure as Market Disruptor | CMPSBL',
    description: 'How cognitive infrastructure is reshaping the AI landscape — from commodity APIs to persistent, self-improving systems.',
    ogTitle: 'Market Disruptor — Cognitive Infrastructure',
    ogDescription: 'How cognitive infrastructure reshapes the AI industry.',
    ogImage: OG_BLOG,
    keywords: ['AI market disruption', 'cognitive infrastructure disruption', 'AI landscape shift', 'self-improving AI market', 'AI industry transformation'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive infrastructure AI market disruptor',
  },
  '/blog/product-roadmap-2025': {
    title: 'Product Roadmap 2025: Vision & Milestones | CMPSBL',
    description: 'Our vision for the next year of cognitive infrastructure — upcoming modules, capability expansions, and enterprise features.',
    ogTitle: 'CMPSBL Roadmap 2025',
    ogDescription: 'Upcoming modules and enterprise capabilities.',
    ogImage: OG_BLOG,
    keywords: ['CMPSBL product roadmap', 'AI roadmap 2025', 'upcoming AI features', 'cognitive infrastructure roadmap', 'substrate milestones'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL product roadmap 2025 milestones',
  },
  '/blog/ai-automation-trends-2025': {
    title: 'AI Automation Trends 2025: Enterprise Patterns | CMPSBL',
    description: 'Key trends shaping enterprise AI automation — from autonomous pipelines to cognitive orchestration and self-healing workflows.',
    ogTitle: 'AI Automation Trends 2025',
    ogDescription: 'Enterprise automation trends from pipelines to self-healing.',
    ogImage: OG_BLOG,
    keywords: ['AI automation trends 2025', 'enterprise AI automation', 'autonomous pipelines', 'self-healing workflows', 'cognitive orchestration trends'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI automation enterprise trends 2025',
  },
  '/blog/ai-business-operations-2025': {
    title: 'AI Business Operations: Cognitive Workflows | CMPSBL',
    description: 'Transforming enterprise workflows with cognitive automation — from document processing to decision support and operational intelligence.',
    ogTitle: 'AI Business Operations 2025',
    ogDescription: 'Cognitive automation transforming enterprise workflows.',
    ogImage: OG_BLOG,
    keywords: ['AI business operations', 'cognitive enterprise workflows', 'AI document processing', 'operational intelligence', 'AI decision support'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI business operations cognitive workflows',
  },
};

/**
 * Get SEO config for a route. Falls back to defaults for unknown routes.
 */
export function getSEO(path: string): PageSEO {
  // Exact match first
  if (seoMap[path]) return seoMap[path];

  // Check blog posts — return generic blog SEO for unmatched blog routes
  if (path.startsWith('/blog/')) {
    return {
      title: 'CMPSBL Blog',
      description: 'AI infrastructure insights and engineering deep-dives from the CMPSBL team.',
      ogTitle: 'CMPSBL Blog',
      ogDescription: 'AI infrastructure insights from the CMPSBL team.',
      ogImage: OG_BLOG,
      keywords: ['CMPSBL blog', 'AI insights'],
      schema: 'article',
      intent: 'Blog/Changelog/Updates',
      primaryKeyword: 'CMPSBL blog post',
    };
  }

  // Check module detail pages
  if (path.startsWith('/modules/')) {
    return {
      title: 'Module Detail — CMPSBL Substrate',
      description: 'Explore this substrate module: architecture, capabilities, synergies, and integration guides.',
      ogTitle: 'Substrate Module — CMPSBL',
      ogDescription: 'Architecture, capabilities, and integration for this substrate module.',
      ogImage: OG_FEATURE,
      keywords: ['substrate module', 'AI module detail', 'module architecture'],
      schema: 'feature',
      intent: 'Feature/Capability',
      primaryKeyword: 'substrate module detail',
    };
  }

  // Default fallback
  return seoMap['/'];
}
