/**
 * seoMap.ts — Centralized SEO Metadata Registry
 * ARCHITECT Epoch — Evergreen Authority Edition
 *
 * Single source of truth for every PUBLIC indexed page.
 * Each entry has a UNIQUE primary keyword — no cannibalization.
 *
 * RULES:
 * - NO version numbers, module counts, artifact totals
 * - NO "world first", "coming soon", roadmap claims
 * - NO metrics that can change
 * - Titles ≤60 chars, primary keyword first when possible
 * - Descriptions 140-160 chars, clear value, no hype
 */

export interface PageSEO {
  title: string;
  description: string;
  ogTitle: string;
  ogDescription: string;
  ogImage: string;
  keywords: string[];
  schema: 'home' | 'feature' | 'docs' | 'blog' | 'about' | 'legal' | 'contact' | 'product' | 'article';
  intent: string;
  primaryKeyword: string;
  noindex?: boolean;
}

const OG_BASE = 'https://cmpsbl.com';

// Section-specific OG images (unique per section)
const OG_HOME = `${OG_BASE}/og/home.jpg`;
const OG_SUBSTRATE = `${OG_BASE}/og/substrate-os.jpg`;
const OG_STORE = `${OG_BASE}/og/store.jpg`;
const OG_DEVELOPERS = `${OG_BASE}/og/developers.jpg`;
const OG_PRICING = `${OG_BASE}/og/pricing.jpg`;
const OG_BLOG = `${OG_BASE}/og/blog.jpg`;
const OG_ABOUT = `${OG_BASE}/og/about.jpg`;
const OG_DOCS = `${OG_BASE}/og/documentation.jpg`;
const OG_FEATURE = `${OG_BASE}/og/modules.jpg`;
const OG_SOLUTIONS = `${OG_BASE}/og/solutions.jpg`;
const OG_INVESTORS = `${OG_BASE}/og/investors.jpg`;
const OG_ACADEMY = `${OG_BASE}/og/academy.jpg`;
const OG_COGNITIVES = `${OG_BASE}/og/cognitives.jpg`;
const OG_ENGINES = `${OG_BASE}/og/engines.jpg`;
const OG_MEMORY = `${OG_BASE}/og/persistent-memory.jpg`;
const OG_DECODE = `${OG_BASE}/og/decode.jpg`;
const OG_DREAM = `${OG_BASE}/og/dream-feeder.jpg`;
const OG_PROOF = `${OG_BASE}/og/proof.jpg`;
const OG_GAMING = `${OG_BASE}/og/gaming.jpg`;

export const seoMap: Record<string, PageSEO> = {
  // ═══════════════════════════════════════════════════
  // CORE PUBLIC
  // ═══════════════════════════════════════════════════
  '/': {
    title: 'Composable AI Infrastructure | CMPSBL',
    description: 'CMPSBL is governed cognitive infrastructure where intelligence persists, adapts, and compounds. Modular AI substrate for self-improving systems.',
    ogTitle: 'Composable AI Infrastructure — CMPSBL',
    ogDescription: 'Governed cognitive architecture where intelligence persists and compounds.',
    ogImage: OG_HOME,
    keywords: ['composable AI', 'cognitive infrastructure', 'AI substrate', 'self-improving software', 'governed AI', 'adaptive intelligence', 'modular AI systems'],
    schema: 'home',
    intent: 'Brand/Category',
    primaryKeyword: 'composable AI infrastructure',
  },
  '/os': {
    title: 'AI Substrate Runtime — Cognitive Orchestration',
    description: 'Explore the CMPSBL substrate: real-time telemetry, autonomous orchestration, and modular cognitive workload management at runtime.',
    ogTitle: 'AI Substrate — Cognitive Runtime',
    ogDescription: 'Real-time telemetry and autonomous orchestration for cognitive workloads.',
    ogImage: OG_SUBSTRATE,
    keywords: ['AI substrate', 'cognitive orchestration', 'AI runtime', 'module telemetry', 'AI workload management', 'autonomous orchestration'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate runtime',
  },
  '/ai-operating-system': {
    title: 'AI Operating System — Cognitive Runtime | CMPSBL',
    description: 'The definitive guide to AI operating systems: how CMPSBL orchestrates memory, learning, defense, and recursive improvement in one runtime.',
    ogTitle: 'The AI Operating System — Explained',
    ogDescription: 'How a cognitive runtime orchestrates memory, learning, and multi-provider AI.',
    ogImage: OG_SUBSTRATE,
    keywords: ['AI operating system', 'cognitive runtime', 'AI OS architecture', 'unified AI platform', 'AI orchestration', 'modular AI systems'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI operating system',
  },
  '/modules': {
    title: 'Substrate Modules — Modular AI Architecture',
    description: 'Browse core modules across kernel, cognitive, operational, and infrastructure layers. Composable AI architecture built for governed evolution.',
    ogTitle: 'Substrate Modules — AI Architecture',
    ogDescription: 'Explore every module from BRAIN to DEFENSE — organized by architectural layer.',
    ogImage: OG_FEATURE,
    keywords: ['substrate modules', 'modular AI architecture', 'AI architecture layers', 'cognitive layer', 'kernel modules', 'composable AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'modular AI substrate architecture',
  },
  '/store': {
    title: 'Composable AI Artifacts — Capabilities & Pipelines',
    description: 'Access tier-scoped capabilities, synergy pipelines, and templates in the CMPSBL artifact store. Composable AI building blocks for any workload.',
    ogTitle: 'Composable Artifact Store — CMPSBL',
    ogDescription: 'Browse and deploy capabilities, templates, and synergy pipelines.',
    ogImage: OG_STORE,
    keywords: ['composable AI artifacts', 'AI capabilities', 'synergy pipelines', 'AI templates', 'composable AI', 'artifact store'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'composable AI artifacts store',
  },
  '/composable-cognitives': {
    title: 'Composable Cognitives — AI Agents You Own',
    description: 'Build, buy, and deploy cognitive agents you own permanently. Download once, run anywhere — portable, subscription-free AI agents.',
    ogTitle: 'Composable Cognitives — Own Your AI Agents',
    ogDescription: 'Portable cognitive agents you download once and run anywhere.',
    ogImage: OG_COGNITIVES,
    keywords: ['composable cognitives', 'AI agents download', 'own your AI', 'portable AI agents', 'cognitive agents', 'self-improving software'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'composable cognitive agents',
  },
  '/engines': {
    title: 'AI Orchestration Engines — Canonized Workflows',
    description: 'Pre-validated orchestration engines for enterprise AI workloads. Canonized workflows built, tested, and maintained by CMPSBL engineering.',
    ogTitle: 'AI Orchestration Engines — CMPSBL',
    ogDescription: 'Pre-validated orchestration engines for enterprise cognitive workloads.',
    ogImage: OG_ENGINES,
    keywords: ['AI orchestration engines', 'canonized workflows', 'enterprise AI engines', 'pre-built AI pipelines', 'composable AI'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI orchestration engines',
  },
  '/persistent-memory': {
    title: 'Persistent Memory for AI Agents — Free Tier',
    description: 'Add persistent memory to any AI agent in under an hour. Free tier available. Compatible with LangChain, CrewAI, and custom frameworks.',
    ogTitle: 'Persistent Memory — Add Memory to Any Agent',
    ogDescription: 'Give your AI agent permanent memory in under an hour. Free tier included.',
    ogImage: OG_MEMORY,
    keywords: ['persistent memory AI', 'agent memory', 'AI memory API', 'LangChain memory', 'agent state persistence', 'adaptive intelligence'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'persistent memory for AI agents',
  },
  '/decode': {
    title: 'Decode Engine — Natural Language AI Terminal',
    description: 'Interact with the cognitive substrate through natural language commands. Decode translates intent into orchestrated module actions.',
    ogTitle: 'Decode — Talk to Your Substrate',
    ogDescription: 'A natural language terminal that translates intent into substrate operations.',
    ogImage: OG_DECODE,
    keywords: ['Decode engine', 'natural language terminal', 'AI CLI', 'substrate commands', 'cognitive terminal', 'AI orchestration'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'natural language AI terminal',
  },
  '/feed-dream-eater': {
    title: 'Dream Feeder — Autonomous Learning Cycles',
    description: 'Autonomous learning system that processes experience data into heuristic improvements during idle cycles. Recursive improvement built in.',
    ogTitle: 'Dream Feeder — AI That Learns While Idle',
    ogDescription: 'Autonomous dream cycles that convert experience into intelligence.',
    ogImage: OG_DREAM,
    keywords: ['autonomous learning', 'AI dream cycles', 'recursive improvement', 'heuristic improvement', 'self-improving software', 'adaptive intelligence'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous AI dream learning cycles',
  },
  '/proof': {
    title: 'Proof Mode — Verifiable AI Execution',
    description: 'Cryptographic proof of every AI operation. Proof Mode generates tamper-evident execution records for governed AI audit and compliance.',
    ogTitle: 'Proof Mode — Verifiable AI',
    ogDescription: 'Tamper-evident proof of every cognitive operation for compliance.',
    ogImage: OG_PROOF,
    keywords: ['verifiable AI', 'AI proof mode', 'execution proof', 'AI audit trail', 'governed AI', 'compliance AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'verifiable AI execution proof',
  },
  '/demo': {
    title: 'Live Demo — CMPSBL Substrate in Action',
    description: 'See the cognitive substrate in action: live module orchestration, dream cycles, and adaptive inference in a guided interactive demo.',
    ogTitle: 'See CMPSBL in Action — Live Demo',
    ogDescription: 'Interactive demo of modular cognitive orchestration.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL demo', 'AI substrate demo', 'cognitive infrastructure demo', 'AI orchestration demo', 'composable AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate live demo',
  },
  '/demos': {
    title: 'Advanced Demos — Cognitive Architecture | CMPSBL',
    description: 'Experience advanced cognitive capabilities: self-healing architecture, provenance chains, sovereign execution, and living module maps.',
    ogTitle: 'Advanced Demos — Cognitive Architecture',
    ogDescription: 'Self-healing, provenance chains, and sovereign execution demos.',
    ogImage: OG_HOME,
    keywords: ['AI self-healing demo', 'cognitive provenance', 'sovereign AI execution', 'cognitive architecture', 'composable AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive architecture demos',
  },
  '/lab': {
    title: 'AI Experimentation Lab — Test & Validate',
    description: 'Sandboxed environment to test, benchmark, and validate cognitive experiments before deploying to production substrate workloads.',
    ogTitle: 'AI Experimentation Lab',
    ogDescription: 'Sandbox for testing cognitive experiments before production.',
    ogImage: OG_FEATURE,
    keywords: ['AI experimentation lab', 'cognitive sandbox', 'AI benchmarking', 'AI substrate', 'modular AI systems'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI experimentation lab',
  },
  '/codelab': {
    title: 'CodeLab — Execute & Test in Real-Time',
    description: 'Write, execute, and test substrate operations in a live coding environment with real-time feedback and inline documentation.',
    ogTitle: 'CodeLab — Live AI Coding Environment',
    ogDescription: 'Write and test substrate code with real-time execution.',
    ogImage: OG_DOCS,
    keywords: ['AI CodeLab', 'live coding AI', 'substrate code editor', 'real-time AI testing', 'AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI live coding environment',
  },
  '/gaming': {
    title: 'Gaming AI — Cognitive NPC & Game Logic',
    description: 'Power game NPCs with persistent memory, adaptive behavior, and dream-cycle learning. Built for Unreal, Unity, and custom engines.',
    ogTitle: 'Gaming AI — NPCs That Learn',
    ogDescription: 'Cognitive NPC engines with persistent memory and adaptive behavior.',
    ogImage: OG_GAMING,
    keywords: ['gaming AI', 'cognitive NPC', 'AI game logic', 'adaptive game AI', 'persistent NPC memory', 'self-improving software'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'cognitive gaming AI NPCs',
  },
  '/system-feed': {
    title: 'System Intelligence Feed — Real-Time Insights',
    description: 'Live feed of system-wide cognitive events, anomalies, and learning breakthroughs across all active substrate modules in real time.',
    ogTitle: 'System Feed — Live AI Intelligence',
    ogDescription: 'Real-time cognitive events and anomalies from across the substrate.',
    ogImage: OG_FEATURE,
    keywords: ['AI system feed', 'real-time AI events', 'cognitive anomaly detection', 'substrate monitoring', 'AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'real-time AI system intelligence feed',
  },

  // ═══════════════════════════════════════════════════
  // DEVELOPER / DOCS
  // ═══════════════════════════════════════════════════
  '/developers': {
    title: 'Developer Hub — SDKs, APIs & Integrations',
    description: 'Everything developers need: SDKs, REST APIs, webhooks, and integration guides for building on the composable AI substrate.',
    ogTitle: 'CMPSBL Developer Hub',
    ogDescription: 'SDKs, APIs, webhooks, and integration guides for the substrate.',
    ogImage: OG_DEVELOPERS,
    keywords: ['AI developer hub', 'AI SDK', 'substrate API', 'AI integration guide', 'cognitive API', 'AI infrastructure'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL developer SDK and API',
  },
  '/documentation': {
    title: 'Documentation — CMPSBL Developer Guide',
    description: 'Complete technical documentation for the substrate: module reference, API specs, configuration, and deployment guides for developers.',
    ogTitle: 'CMPSBL Documentation',
    ogDescription: 'Complete API reference, module docs, and deployment guides.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL documentation', 'substrate docs', 'AI API reference', 'module documentation', 'composable AI'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL technical documentation',
  },
  '/docs/persistent-memory': {
    title: 'Persistent Memory Quickstart — Integration Guide',
    description: 'Step-by-step guide to integrating persistent memory into your AI agent. Covers LangChain, CrewAI, and raw SDK integration approaches.',
    ogTitle: 'Persistent Memory Quickstart',
    ogDescription: 'Add persistent memory to your agent in minutes — step-by-step guide.',
    ogImage: OG_MEMORY,
    keywords: ['persistent memory quickstart', 'AI memory integration', 'LangChain memory guide', 'CrewAI memory', 'agent memory tutorial'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'persistent memory integration guide',
  },
  '/docs/substrate/capabilities': {
    title: 'Capabilities Reference — AI Functions | CMPSBL',
    description: 'Complete reference for substrate capabilities: parameters, tier availability, synergy compatibility, and usage examples for developers.',
    ogTitle: 'Capability Reference — AI Functions',
    ogDescription: 'Browse the full catalog of AI capabilities with parameters and examples.',
    ogImage: OG_STORE,
    keywords: ['AI capabilities reference', 'substrate functions', 'capability catalog', 'AI function reference', 'composable AI'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI capabilities reference documentation',
  },
  '/academy': {
    title: 'Developer Academy — Interactive AI Tutorials',
    description: 'Learn to build on the substrate with interactive, AI-powered tutorials. From beginner agent builders to advanced orchestration patterns.',
    ogTitle: 'Developer Academy — Learn AI Building',
    ogDescription: 'Interactive tutorials from beginner to advanced substrate development.',
    ogImage: OG_ACADEMY,
    keywords: ['AI developer academy', 'interactive AI tutorials', 'learn AI building', 'substrate training', 'AI infrastructure'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'interactive AI developer tutorials',
  },
  '/devtools': {
    title: 'DevTools — Diagnostics & Developer Utilities',
    description: 'Debug and inspect your substrate in real-time: module state inspector, network tracer, memory explorer, and performance profiler.',
    ogTitle: 'CMPSBL DevTools — Debug Your AI',
    ogDescription: 'Real-time diagnostics and debugging utilities for the substrate.',
    ogImage: OG_DOCS,
    keywords: ['AI DevTools', 'substrate debugger', 'AI diagnostics', 'module inspector', 'cognitive architecture'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI substrate developer tools',
  },
  '/changelog': {
    title: 'Changelog — Substrate Update History | CMPSBL',
    description: 'Track every update to the CMPSBL substrate: new modules, capabilities, patches, and cognitive architecture changes over time.',
    ogTitle: 'Changelog — What\'s New in CMPSBL',
    ogDescription: 'Complete update history for the cognitive substrate.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL changelog', 'substrate updates', 'AI platform changelog', 'cognitive architecture updates'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL substrate changelog',
  },

  // ═══════════════════════════════════════════════════
  // ENTERPRISE / PRICING
  // ═══════════════════════════════════════════════════
  '/solutions': {
    title: 'Enterprise AI Solutions — Industry Applications',
    description: 'Enterprise-ready cognitive infrastructure for healthcare, finance, legal, and manufacturing. Compliance-ready with on-prem deployment.',
    ogTitle: 'Enterprise AI Solutions — CMPSBL',
    ogDescription: 'Industry-specific cognitive infrastructure with compliance and on-prem.',
    ogImage: OG_SOLUTIONS,
    keywords: ['enterprise AI solutions', 'governed AI', 'healthcare AI', 'finance AI platform', 'on-prem AI', 'AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'enterprise AI solutions',
  },
  '/use-cases': {
    title: 'Use Cases — How Teams Deploy CMPSBL',
    description: 'Real-world use cases: autonomous research agencies, code review pipelines, customer support agents, and self-healing infrastructure.',
    ogTitle: 'AI Use Cases — Real Deployments',
    ogDescription: 'See how teams deploy autonomous research, code review, and self-healing AI.',
    ogImage: OG_SOLUTIONS,
    keywords: ['AI use cases', 'autonomous research AI', 'code review AI', 'self-improving software', 'AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI use cases and deployments',
  },
  '/pricing': {
    title: 'Pricing — Free Through Enterprise Tiers',
    description: 'Transparent pricing for every team size. Free tier with persistent memory, scaling through production and enterprise compliance tiers.',
    ogTitle: 'CMPSBL Pricing — Start Free',
    ogDescription: 'Transparent pricing for cognitive infrastructure at every scale.',
    ogImage: OG_PRICING,
    keywords: ['CMPSBL pricing', 'AI platform pricing', 'free AI tier', 'enterprise AI pricing', 'AI infrastructure'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'CMPSBL pricing plans',
  },
  '/substrate/licensing': {
    title: 'Licensing — Enterprise Agreements & OEM',
    description: 'Enterprise licensing for the CMPSBL substrate: volume agreements, OEM embedding, white-label options, and dedicated engineering support.',
    ogTitle: 'Enterprise Licensing — CMPSBL',
    ogDescription: 'Volume licensing, OEM embedding, and white-label agreements.',
    ogImage: OG_PRICING,
    keywords: ['AI enterprise licensing', 'OEM AI agreement', 'white-label AI', 'substrate licensing', 'AI infrastructure'],
    schema: 'product',
    intent: 'Pricing/Plans',
    primaryKeyword: 'enterprise AI licensing agreement',
  },
  '/intelligence': {
    title: 'Substrate Intelligence — Architecture Validation',
    description: 'Architectural validation of the cognitive substrate: interaction graphs, capability coverage analysis, and infrastructure proof points.',
    ogTitle: 'Substrate Intelligence — Proof of Architecture',
    ogDescription: 'Interaction graphs and capability coverage for the substrate.',
    ogImage: OG_FEATURE,
    keywords: ['substrate intelligence', 'cognitive architecture', 'AI architecture proof', 'capability coverage', 'AI infrastructure'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI architecture intelligence proof',
  },
  '/investors': {
    title: 'Acquisition Opportunity — CMPSBL® Substrate',
    description: 'CMPSBL represents a generational acquisition opportunity: deep R&D, defensible IP, and composable cognitive infrastructure for the AI era.',
    ogTitle: 'Investment & Acquisition — CMPSBL',
    ogDescription: 'Deep R&D, defensible IP, and cognitive infrastructure — a strategic acquisition.',
    ogImage: OG_INVESTORS,
    keywords: ['CMPSBL acquisition', 'AI startup investment', 'cognitive infrastructure acquisition', 'AI IP portfolio', 'AI substrate'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL acquisition opportunity',
  },
  '/marketplace': {
    title: 'Marketplace — AI Templates & Integrations',
    description: 'Browse community and first-party templates, integrations, and pre-built cognitive workflows in the composable AI marketplace.',
    ogTitle: 'CMPSBL Marketplace',
    ogDescription: 'Templates, integrations, and pre-built cognitive workflows.',
    ogImage: OG_STORE,
    keywords: ['AI marketplace', 'cognitive templates', 'AI integrations', 'composable AI', 'pre-built AI workflows'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI templates marketplace',
  },

  // ═══════════════════════════════════════════════════
  // COMPANY / ABOUT / TRUST
  // ═══════════════════════════════════════════════════
  '/about': {
    title: 'About CMPSBL — Founded 2009, Dallas TX',
    description: 'CMPSBL was founded in 2009 by Kenneth E Sweet Jr. From Dallas, TX — building governed, composable AI infrastructure for the industry.',
    ogTitle: 'About CMPSBL — Our Origin Story',
    ogDescription: 'From 2009 — the story of building cognitive infrastructure for AI.',
    ogImage: OG_ABOUT,
    keywords: ['about CMPSBL', 'Kenneth Sweet', 'CMPSBL founder', 'Dallas AI company', 'cognitive infrastructure', 'AI substrate'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'about CMPSBL founder story',
  },
  '/contact': {
    title: 'Contact CMPSBL — Get in Touch',
    description: 'Reach the CMPSBL team for partnerships, enterprise inquiries, support, or press. Based in Dallas, TX — serving teams worldwide.',
    ogTitle: 'Contact CMPSBL',
    ogDescription: 'Get in touch for partnerships, enterprise inquiries, or press.',
    ogImage: OG_ABOUT,
    keywords: ['contact CMPSBL', 'AI partnership inquiry', 'enterprise AI contact', 'CMPSBL support', 'AI infrastructure'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'contact CMPSBL team',
  },
  '/support': {
    title: 'Support — Help & Resources | CMPSBL',
    description: 'Get help with the CMPSBL substrate: knowledge base, ticket system, community forums, and direct engineering support for enterprise tiers.',
    ogTitle: 'CMPSBL Support Center',
    ogDescription: 'Knowledge base, tickets, and direct engineering support.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL support', 'AI platform help', 'substrate troubleshooting', 'AI infrastructure', 'AI support'],
    schema: 'contact',
    intent: 'Contact',
    primaryKeyword: 'CMPSBL support center',
  },

  // ═══════════════════════════════════════════════════
  // BLOG / CONTENT
  // ═══════════════════════════════════════════════════
  '/blog': {
    title: 'Blog — AI Infrastructure Research & Insights',
    description: 'Research, deep-dives, and engineering insights on cognitive architecture, AI memory, governed systems, and adaptive intelligence.',
    ogTitle: 'CMPSBL Blog — AI Research & Insights',
    ogDescription: 'Deep-dives on cognitive architecture, AI memory, and substrate engineering.',
    ogImage: OG_BLOG,
    keywords: ['AI infrastructure blog', 'cognitive AI research', 'AI memory insights', 'composable AI', 'self-improving software'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI infrastructure research blog',
  },
  '/publication': {
    title: 'Publications — Research Papers & Whitepapers',
    description: 'Research and whitepapers on cognitive infrastructure, dream-cycle learning, and autonomous system architecture from CMPSBL engineering.',
    ogTitle: 'CMPSBL Publications',
    ogDescription: 'Research papers on cognitive infrastructure and autonomous AI systems.',
    ogImage: OG_BLOG,
    keywords: ['AI research papers', 'cognitive infrastructure whitepaper', 'autonomous AI paper', 'adaptive intelligence', 'AI substrate'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI cognitive infrastructure research papers',
  },
  '/library': {
    title: 'Library — Documentation & Knowledge Archive',
    description: 'Curated archive of substrate documentation, architectural references, module specifications, and development resources for builders.',
    ogTitle: 'CMPSBL Library',
    ogDescription: 'Curated documentation archive and architectural references.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL library', 'AI documentation archive', 'substrate knowledge base', 'cognitive architecture', 'AI infrastructure'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'AI documentation knowledge archive',
  },
  '/insights': {
    title: 'Insights — AI Industry Analysis | CMPSBL',
    description: 'Data-driven analysis of AI industry trends, market dynamics, and technological shifts from the CMPSBL intelligence team.',
    ogTitle: 'AI Industry Insights — CMPSBL',
    ogDescription: 'Data-driven analysis of AI trends and market dynamics.',
    ogImage: OG_BLOG,
    keywords: ['AI industry insights', 'AI market analysis', 'cognitive AI trends', 'AI infrastructure', 'adaptive intelligence'],
    schema: 'blog',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI industry analysis insights',
  },

  // ═══════════════════════════════════════════════════
  // STANDARDS / PROTOCOL
  // ═══════════════════════════════════════════════════
  '/namespace': {
    title: 'Namespace — Unified AI Terminology Standard',
    description: 'The CMPSBL namespace defines canonical vocabulary for cognitive infrastructure — standardized terms across all substrate modules.',
    ogTitle: 'Namespace — AI Terminology Standard',
    ogDescription: 'Canonical vocabulary for cognitive infrastructure.',
    ogImage: OG_DOCS,
    keywords: ['AI namespace', 'cognitive terminology', 'AI vocabulary standard', 'composable AI', 'unified AI terminology'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'unified AI terminology namespace',
  },
  '/foundations': {
    title: 'Foundations — Core Principles & Architecture',
    description: 'The foundational principles behind CMPSBL: composability, persistent state, autonomous evolution, and cognitive coherence at runtime.',
    ogTitle: 'CMPSBL Foundations — Core Principles',
    ogDescription: 'The architectural principles behind cognitive infrastructure.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL foundations', 'cognitive architecture', 'composable AI', 'autonomous evolution', 'AI substrate'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'cognitive infrastructure foundations',
  },
  '/roadmap': {
    title: 'Roadmap — Cognitive Architecture Evolution',
    description: 'The CMPSBL substrate roadmap: architectural evolution, capability expansion, and the ongoing development of composable AI infrastructure.',
    ogTitle: 'CMPSBL Roadmap — Architecture Evolution',
    ogDescription: 'Ongoing architectural evolution of the cognitive substrate.',
    ogImage: OG_DOCS,
    keywords: ['CMPSBL roadmap', 'AI substrate', 'cognitive architecture', 'composable AI', 'recursive improvement'],
    schema: 'docs',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL substrate roadmap',
  },
  '/llms-txt': {
    title: 'llms.txt — Machine-Readable AI Context',
    description: 'Structured context for AI crawlers: module catalog, capability index, and API surface for GPTBot, ClaudeBot, and other AI agents.',
    ogTitle: 'llms.txt — AI Crawler Context',
    ogDescription: 'Machine-readable context file for AI crawlers and agents.',
    ogImage: OG_DOCS,
    keywords: ['llms.txt', 'AI crawler context', 'GPTBot', 'machine-readable AI', 'AI discovery', 'AI infrastructure'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'llms.txt AI crawler protocol',
  },
  '/humans-txt': {
    title: 'humans.txt — The Team Behind CMPSBL',
    description: 'Meet the humans building cognitive infrastructure. Credits, contributors, and the engineering team behind the composable AI substrate.',
    ogTitle: 'humans.txt — Meet the Team',
    ogDescription: 'The humans building cognitive infrastructure for AI.',
    ogImage: OG_ABOUT,
    keywords: ['CMPSBL team', 'humans.txt', 'AI engineering team', 'cognitive infrastructure'],
    schema: 'about',
    intent: 'About/Trust',
    primaryKeyword: 'CMPSBL engineering team credits',
  },

  // ═══════════════════════════════════════════════════
  // CLUSTER / DEEP-DIVE PAGES
  // ═══════════════════════════════════════════════════
  '/cluster/studio-autonomous-site-generator': {
    title: 'STUDIO Module — Autonomous Site Generation',
    description: 'STUDIO generates production-ready web applications autonomously using cognitive pipelines, design intelligence, and real-time deployment.',
    ogTitle: 'STUDIO — Autonomous Site Generator',
    ogDescription: 'AI-powered site generation with design intelligence and deployment.',
    ogImage: OG_FEATURE,
    keywords: ['STUDIO module', 'autonomous site generator', 'AI web builder', 'cognitive architecture', 'composable AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'autonomous AI site generator module',
  },
  '/cluster/verify-worlds-first-ai-plugin-certification': {
    title: 'VERIFY Module — AI Plugin Certification',
    description: 'AI plugin certification system that validates safety, performance, and compatibility before deployment across the substrate ecosystem.',
    ogTitle: 'VERIFY — AI Plugin Certification',
    ogDescription: 'Certify AI plugin safety, performance, and compatibility.',
    ogImage: OG_FEATURE,
    keywords: ['VERIFY module', 'AI plugin certification', 'AI safety validation', 'governed AI', 'composable AI'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI plugin certification system',
  },
  '/cluster/inclusive-module-accessibility': {
    title: 'INCLUSIVE Module — AI Accessibility Engine',
    description: 'Automated WCAG compliance, real-time accessibility auditing, and AI-powered remediation for any web property at scale.',
    ogTitle: 'INCLUSIVE — AI Accessibility Engine',
    ogDescription: 'Automated WCAG compliance and AI-powered accessibility remediation.',
    ogImage: OG_FEATURE,
    keywords: ['INCLUSIVE module', 'AI accessibility', 'WCAG compliance AI', 'automated accessibility', 'modular AI systems'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI-powered accessibility compliance engine',
  },

  // ═══════════════════════════════════════════════════
  // PRODUCT PAGES
  // ═══════════════════════════════════════════════════
  '/products/encode': {
    title: 'ENCODE — The Substrate Code Agent',
    description: 'ENCODE is the substrate\'s code intelligence agent: reads, writes, and refactors code with full system awareness across all modules.',
    ogTitle: 'ENCODE — Code Intelligence Agent',
    ogDescription: 'The substrate\'s code agent with full system awareness.',
    ogImage: OG_FEATURE,
    keywords: ['ENCODE agent', 'AI code agent', 'substrate code intelligence', 'autonomous coding AI', 'composable AI'],
    schema: 'product',
    intent: 'Feature/Capability',
    primaryKeyword: 'ENCODE AI code intelligence agent',
  },
  '/start-here': {
    title: 'Start Here — Get Oriented with CMPSBL',
    description: 'New to CMPSBL? Start here for a guided introduction to the substrate, its modules, and how to build your first cognitive application.',
    ogTitle: 'Start Here — Your CMPSBL Journey',
    ogDescription: 'Guided introduction to composable AI and building your first app.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL getting started', 'substrate onboarding', 'composable AI', 'beginner AI platform', 'AI infrastructure'],
    schema: 'docs',
    intent: 'Docs/Developer',
    primaryKeyword: 'CMPSBL getting started guide',
  },

  // ═══════════════════════════════════════════════════
  // LEGAL
  // ═══════════════════════════════════════════════════
  '/privacy': {
    title: 'Privacy Policy — CMPSBL®',
    description: 'CMPSBL privacy policy: how we collect, store, and protect your data. GDPR-compliant, transparent data practices across all services.',
    ogTitle: 'Privacy Policy — CMPSBL',
    ogDescription: 'How CMPSBL handles your data — transparent, GDPR-compliant practices.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL privacy policy', 'AI data privacy', 'GDPR compliant AI', 'data protection policy'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL privacy policy',
  },
  '/terms': {
    title: 'Terms of Service — CMPSBL®',
    description: 'Terms of service for the CMPSBL substrate platform. Covers usage rights, intellectual property, and service-level commitments.',
    ogTitle: 'Terms of Service — CMPSBL',
    ogDescription: 'Usage terms, IP rights, and SLA commitments for the substrate.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL terms of service', 'AI platform terms', 'substrate usage terms', 'service agreement AI'],
    schema: 'legal',
    intent: 'Legal',
    primaryKeyword: 'CMPSBL terms of service',
  },

  // ═══════════════════════════════════════════════════
  // NOINDEX PAGES
  // ═══════════════════════════════════════════════════
  '/auth': {
    title: 'Sign In — CMPSBL',
    description: 'Sign in to your CMPSBL account to access the substrate dashboard, cognitive agents, and enterprise tools.',
    ogTitle: 'Sign In — CMPSBL',
    ogDescription: 'Access your substrate dashboard and cognitive tools.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL login', 'sign in AI platform'],
    schema: 'legal',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL sign in',
    noindex: true,
  },
  '/register': {
    title: 'Register — Create Your CMPSBL Account',
    description: 'Create a free CMPSBL account to start building with cognitive infrastructure. Access persistent memory, Decode, and composable AI tools.',
    ogTitle: 'Register — Join CMPSBL',
    ogDescription: 'Create your free account and start building with cognitive infrastructure.',
    ogImage: OG_HOME,
    keywords: ['CMPSBL register', 'create AI account', 'composable AI'],
    schema: 'legal',
    intent: 'Auth',
    primaryKeyword: 'CMPSBL register account',
    noindex: true,
  },
  '/clear-cache': {
    title: 'Clear Cache — CMPSBL',
    description: 'Clear local cache and reset substrate state.',
    ogTitle: 'Clear Cache',
    ogDescription: 'Reset local state and cache.',
    ogImage: OG_HOME,
    keywords: ['clear cache'],
    schema: 'legal',
    intent: 'Utility',
    primaryKeyword: 'clear cache utility',
    noindex: true,
  },
  '/substrate': {
    title: 'Substrate Dashboard — Command Center',
    description: 'Your cognitive command center: module health, agent status, dream cycles, and real-time system telemetry at a glance.',
    ogTitle: 'Substrate Dashboard',
    ogDescription: 'Your cognitive AI command center.',
    ogImage: OG_FEATURE,
    keywords: ['substrate dashboard', 'AI command center', 'cognitive architecture'],
    schema: 'feature',
    intent: 'Feature/Capability',
    primaryKeyword: 'AI substrate command center dashboard',
    noindex: true,
  },

  // ═══════════════════════════════════════════════════
  // BLOG POSTS
  // ═══════════════════════════════════════════════════
  '/blog/machine-protocol-standards-architect-epoch': {
    title: 'Machine-to-Machine Protocol Standards | CMPSBL',
    description: 'How RELAY and IDENTITY modules establish authenticated, auditable protocol standards for autonomous multi-agent communication.',
    ogTitle: 'Machine Protocol Standards — Cognitive Architecture',
    ogDescription: 'Authenticated protocols for autonomous agent communication.',
    ogImage: OG_BLOG,
    keywords: ['machine protocol standards', 'agent communication protocol', 'AI orchestration', 'multi-agent messaging', 'governed AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'machine-to-machine AI protocol standards',
  },
  '/blog/autonomous-ai-governance-runtime-enforcement': {
    title: 'Autonomous AI Governance: Runtime Enforcement',
    description: 'AUDIT and IDENTITY modules deliver cryptographic compliance logging and universal actor attribution for governed AI systems.',
    ogTitle: 'AI Governance — Runtime Enforcement',
    ogDescription: 'Cryptographic compliance logging for autonomous AI systems.',
    ogImage: OG_BLOG,
    keywords: ['AI governance runtime', 'compliance logging AI', 'governed AI', 'actor attribution', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'autonomous AI governance runtime enforcement',
  },
  '/blog/adversarial-ai-defense-module-response-2026': {
    title: 'Adversarial AI Defense: Countering Modern Threats',
    description: 'How the DEFENSE module counters prompt injection, behavioral fingerprinting attacks, and zero-trust mesh threats in production AI systems.',
    ogTitle: 'Adversarial AI — DEFENSE Module Response',
    ogDescription: 'Countering prompt injection and behavioral fingerprinting.',
    ogImage: OG_BLOG,
    keywords: ['adversarial AI defense', 'prompt injection defense', 'behavioral fingerprinting', 'governed AI', 'AI substrate'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'adversarial AI defense module response',
  },
  '/blog/evolving-software-v6-breakthrough': {
    title: 'Evolving Software: The Autonomous Breakthrough',
    description: 'Systems that learn, adapt, and evolve autonomously via API-first cognitive architecture — a paradigm shift in self-improving software.',
    ogTitle: 'Evolving Software — The Breakthrough',
    ogDescription: 'AI systems that learn, adapt, and evolve autonomously.',
    ogImage: OG_BLOG,
    keywords: ['evolving software', 'self-improving software', 'autonomous evolution', 'adaptive AI systems', 'cognitive architecture'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'evolving software autonomous breakthrough',
  },
  '/blog/rag-without-infrastructure': {
    title: 'RAG Without Infrastructure Overhead | CMPSBL',
    description: 'Ship retrieval-augmented generation without managing vector databases or embeddings pipelines. One API call for composable RAG.',
    ogTitle: 'RAG Without Infrastructure',
    ogDescription: 'Retrieval-augmented generation without vector DB management.',
    ogImage: OG_BLOG,
    keywords: ['RAG without infrastructure', 'managed RAG API', 'vector search API', 'composable AI', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RAG without infrastructure management',
  },
  '/blog/agent-memory-anti-patterns': {
    title: 'Agent Memory Anti-Patterns to Avoid | CMPSBL',
    description: 'Common mistakes that cause AI agents to lose context — and battle-tested patterns to fix memory degradation in production systems.',
    ogTitle: 'Agent Memory Anti-Patterns',
    ogDescription: 'Common mistakes causing AI context loss and how to fix them.',
    ogImage: OG_BLOG,
    keywords: ['agent memory anti-patterns', 'AI context loss', 'memory degradation', 'persistent memory AI', 'self-improving software'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI agent memory anti-patterns',
  },
  '/blog/langchain-memory-integration': {
    title: 'LangChain Persistent Memory Integration | CMPSBL',
    description: 'Add persistent, cross-session memory to your LangChain agents with a drop-in replacement for ConversationBufferMemory. Quick setup.',
    ogTitle: 'LangChain Memory — Drop-In Persistent',
    ogDescription: 'Persistent LangChain memory — quick integration guide.',
    ogImage: OG_BLOG,
    keywords: ['LangChain persistent memory', 'LangChain memory replacement', 'cross-session agent memory', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'LangChain persistent memory integration',
  },
  '/blog/why-agents-forget': {
    title: 'Why AI Agents Forget: Technical Causes | CMPSBL',
    description: 'The technical reasons behind context loss and memory degradation — from token limits to serialization bugs in AI agent systems.',
    ogTitle: 'Why Agents Forget — Technical Deep Dive',
    ogDescription: 'Technical causes of AI memory degradation explained.',
    ogImage: OG_BLOG,
    keywords: ['why agents forget', 'AI memory loss causes', 'context window limits', 'persistent memory AI', 'self-improving software'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'why AI agents forget context',
  },
  '/blog/building-agents-that-learn': {
    title: 'Building Agents That Learn from Experience',
    description: 'Architectural patterns for AI systems that improve through experience — from competency scoring to heuristic extraction at runtime.',
    ogTitle: 'Building Agents That Learn',
    ogDescription: 'Architectural patterns for self-improving AI agents.',
    ogImage: OG_BLOG,
    keywords: ['building learning agents', 'self-improving software', 'competency scoring', 'recursive improvement', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'building AI agents that learn experience',
  },
  '/blog/llms-txt-protocol-ai-context': {
    title: 'LLMs.txt Protocol: AI Context Standard | CMPSBL',
    description: 'How we implement the llmstxt.org protocol standard and why every AI platform should adopt machine-readable context files.',
    ogTitle: 'LLMs.txt — The AI Context Protocol',
    ogDescription: 'Machine-readable context files for AI crawlers.',
    ogImage: OG_BLOG,
    keywords: ['llms.txt protocol', 'AI context standard', 'machine-readable context', 'AI infrastructure', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'llms.txt protocol AI context standard',
  },
  '/blog/ai-governance-namespace-unified-terminology': {
    title: 'AI Governance Namespace: Unified Terminology',
    description: 'How we established unified AI governance vocabulary through strategic domain registration and standardized terminology across modules.',
    ogTitle: 'AI Governance Namespace — Unified Terms',
    ogDescription: 'Standardizing AI governance vocabulary across the industry.',
    ogImage: OG_BLOG,
    keywords: ['AI governance namespace', 'unified AI terminology', 'governed AI', 'governance vocabulary', 'cognitive architecture'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI governance unified terminology namespace',
  },
  '/blog/inclusive-module-accessibility-mission': {
    title: 'INCLUSIVE Module: Accessibility Mission | CMPSBL',
    description: 'Our commitment to making the web accessible through AI-powered WCAG automation — the INCLUSIVE module story and architecture.',
    ogTitle: 'INCLUSIVE Module — Accessibility Mission',
    ogDescription: 'AI-powered web accessibility at scale.',
    ogImage: OG_BLOG,
    keywords: ['INCLUSIVE module', 'AI accessibility mission', 'WCAG automation', 'modular AI systems', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'INCLUSIVE module accessibility mission',
  },
  '/blog/accessibility-free-for-all': {
    title: 'Accessibility for Everyone: A Free Mandate',
    description: 'Why web accessibility matters at planetary scale and how AI-powered automation makes compliance achievable for every website owner.',
    ogTitle: 'Accessibility for Everyone',
    ogDescription: 'Why accessibility should be free and AI-powered.',
    ogImage: OG_BLOG,
    keywords: ['free accessibility', 'accessibility for everyone', 'AI accessibility tools', 'WCAG compliance', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free web accessibility for everyone',
  },
  '/blog/wordpress-accessibility-guide': {
    title: 'WordPress Accessibility Guide: WCAG Compliance',
    description: 'Complete guide to making your WordPress site WCAG 2.2 compliant — from semantic HTML to ARIA roles and automated testing patterns.',
    ogTitle: 'WordPress Accessibility — Complete Guide',
    ogDescription: 'Make your WordPress site WCAG compliant.',
    ogImage: OG_BLOG,
    keywords: ['WordPress accessibility guide', 'WCAG WordPress', 'WordPress ARIA roles', 'accessible WordPress theme'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress accessibility WCAG compliance guide',
  },
  '/blog/wcag-2-2-wordpress-changes': {
    title: 'WCAG 2.2 Changes for WordPress Developers',
    description: 'What the latest WCAG 2.2 updates mean for WordPress developers — new success criteria, deprecated patterns, and implementation guidance.',
    ogTitle: 'WCAG 2.2 — What Changed for WordPress',
    ogDescription: 'New WCAG 2.2 criteria and WordPress implementation.',
    ogImage: OG_BLOG,
    keywords: ['WCAG 2.2 changes', 'WordPress WCAG 2.2', 'new accessibility criteria', 'WordPress developer accessibility'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WCAG 2.2 changes WordPress developers',
  },
  '/blog/automated-accessibility-fixes-wordpress': {
    title: 'Automated Accessibility Fixes for WordPress',
    description: 'AI-powered remediation for common WordPress accessibility issues — from missing alt text to color contrast and focus management.',
    ogTitle: 'Automated Accessibility Fixes — WordPress',
    ogDescription: 'AI-powered accessibility remediation for WordPress.',
    ogImage: OG_BLOG,
    keywords: ['automated accessibility fixes', 'WordPress accessibility AI', 'alt text automation', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'automated WordPress accessibility fixes AI',
  },
  '/blog/ai-systems-that-dream-press-release': {
    title: 'AI Systems That Dream: Experimental Research',
    description: 'Exploring autonomous dreaming, reflection, and self-improvement in experimental cognitive AI systems with recursive improvement loops.',
    ogTitle: 'AI Systems That Dream — Research',
    ogDescription: 'Experimental AI systems with autonomous dreaming capabilities.',
    ogImage: OG_BLOG,
    keywords: ['AI dreaming systems', 'autonomous AI dreaming', 'cognitive dream cycles', 'recursive improvement', 'self-improving software'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'experimental AI systems that dream',
  },
  '/blog/wordpress-bot-defense': {
    title: 'WordPress Bot Defense: AI Behavioral Analysis',
    description: 'Protect your WordPress site from sophisticated bot attacks using AI-powered behavioral analysis and session fingerprinting techniques.',
    ogTitle: 'WordPress Bot Defense Guide',
    ogDescription: 'AI behavioral analysis for WordPress bot protection.',
    ogImage: OG_BLOG,
    keywords: ['WordPress bot defense', 'AI bot detection', 'behavioral analysis security', 'governed AI', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'WordPress bot defense behavioral analysis',
  },
  '/blog/top-security-plugins-2025': {
    title: 'Top WordPress Security Plugins Compared | CMPSBL',
    description: 'Comprehensive comparison of WordPress security plugins including AI-powered defense, firewall strength, and malware detection capabilities.',
    ogTitle: 'Top Security Plugins — WordPress',
    ogDescription: 'Best WordPress security plugins compared.',
    ogImage: OG_BLOG,
    keywords: ['WordPress security plugins', 'best security plugins', 'WordPress firewall comparison', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'top WordPress security plugins comparison',
  },
  '/blog/ai-cybersecurity-evolution-2025': {
    title: 'AI Cybersecurity: Behavioral Defense Evolution',
    description: 'From signature-based detection to behavioral AI — why traditional security fails against modern threats and how adaptive analysis wins.',
    ogTitle: 'AI Cybersecurity Evolution',
    ogDescription: 'Behavioral AI vs traditional security methods.',
    ogImage: OG_BLOG,
    keywords: ['AI cybersecurity evolution', 'behavioral security AI', 'adaptive threat detection', 'governed AI', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI cybersecurity evolution behavioral defense',
  },
  '/blog/ai-hackers-underground-2025': {
    title: 'AI Hackers Underground: Weaponized Intelligence',
    description: 'Inside look at how malicious actors weaponize AI for sophisticated attacks — and how cognitive defense systems respond in production.',
    ogTitle: 'AI Hackers Underground',
    ogDescription: 'How attackers weaponize AI and how defense systems respond.',
    ogImage: OG_BLOG,
    keywords: ['AI hackers underground', 'weaponized AI attacks', 'AI threat actors', 'governed AI', 'adaptive intelligence'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI hackers underground weaponized intelligence',
  },
  '/blog/how-promptfluid-works-cascade-ai-ecosystem': {
    title: 'How the Cascade AI Ecosystem Works | CMPSBL',
    description: 'Deep dive into dream cycles, neural orchestration, and the cognitive concepts powering the adaptive substrate engine architecture.',
    ogTitle: 'How Cascade AI Works — Deep Dive',
    ogDescription: 'Dream cycles, neural orchestration, and cognitive AI internals.',
    ogImage: OG_BLOG,
    keywords: ['Cascade AI ecosystem', 'dream cycle architecture', 'neural orchestration', 'cognitive architecture', 'self-improving software'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Cascade AI ecosystem dream cycles',
  },
  '/blog/cascade-ai-adaptive-intelligence-brain': {
    title: 'Cascade AI: Adaptive Intelligence Architecture',
    description: 'How autonomous dream cycles enable continuous learning, reflection, and adaptive intelligence in the cognitive substrate runtime.',
    ogTitle: 'Cascade AI — Adaptive Intelligence',
    ogDescription: 'Autonomous dream cycles for continuous AI learning.',
    ogImage: OG_BLOG,
    keywords: ['Cascade adaptive intelligence', 'autonomous dream learning', 'adaptive intelligence', 'recursive improvement', 'AI substrate'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'Cascade AI adaptive intelligence architecture',
  },
  '/blog/promptfluid-studio-build-apps-that-think': {
    title: 'STUDIO Module: Build Apps That Think | CMPSBL',
    description: 'AI-assisted development platform generating production-ready code with cognitive pipelines, design intelligence, and real-time deployment.',
    ogTitle: 'STUDIO — Build Apps That Think',
    ogDescription: 'AI-powered app development with cognitive pipelines.',
    ogImage: OG_BLOG,
    keywords: ['STUDIO module apps', 'AI app development', 'cognitive code generation', 'composable AI', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'STUDIO module build cognitive apps',
  },
  '/blog/ai-triad-intelligent-routing': {
    title: 'Free-Tier AI Routing: Triad Architecture',
    description: 'Multi-provider AI gateway optimized for cost and performance — intelligent routing across free-tier models with minimal API spend.',
    ogTitle: 'AI Triad — Free-Tier Routing',
    ogDescription: 'Intelligent AI routing across multiple providers.',
    ogImage: OG_BLOG,
    keywords: ['AI triad routing', 'free-tier AI gateway', 'multi-provider routing', 'AI orchestration', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'free-tier AI intelligent routing triad',
  },
  '/blog/promptfluid-brain-adaptive-learning-core': {
    title: 'BRAIN Module: Adaptive Learning Core | CMPSBL',
    description: 'Machine learning engine powering behavioral analysis, threat intelligence, and autonomous heuristic evolution in the substrate runtime.',
    ogTitle: 'BRAIN Module — Adaptive Learning Core',
    ogDescription: 'The ML engine behind behavioral analysis and threat detection.',
    ogImage: OG_BLOG,
    keywords: ['BRAIN module', 'adaptive learning core', 'behavioral analysis ML', 'recursive improvement', 'self-improving software'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'BRAIN adaptive learning core module',
  },
  '/blog/promptfluid-vision-unified-dashboard': {
    title: 'VISION Module: Unified Command Dashboard',
    description: 'Central command for monitoring AI orchestration, module telemetry, analytics, and system-wide cognitive health in real-time.',
    ogTitle: 'VISION — Unified Command Center',
    ogDescription: 'Real-time AI orchestration monitoring and analytics.',
    ogImage: OG_BLOG,
    keywords: ['VISION module dashboard', 'AI command center', 'module telemetry', 'cognitive architecture', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'VISION unified command dashboard module',
  },
  '/blog/promptfluid-defense-ai-security': {
    title: 'DEFENSE Module: AI Security Deep Dive | CMPSBL',
    description: 'Advanced bot detection, behavioral fingerprinting, and adaptive security layers protecting the cognitive substrate from emerging threats.',
    ogTitle: 'DEFENSE Module — AI Security',
    ogDescription: 'Bot detection and behavioral fingerprinting for AI systems.',
    ogImage: OG_BLOG,
    keywords: ['DEFENSE module security', 'AI bot detection', 'behavioral fingerprinting', 'governed AI', 'AI substrate'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'DEFENSE module AI security deep dive',
  },
  '/blog/promptfluid-ripple-network-integration': {
    title: 'RIPPLE Module: Network Integration Patterns',
    description: 'Distributed AI coordination and multi-agent communication patterns powering cross-module event propagation in the substrate.',
    ogTitle: 'RIPPLE — Network Integration',
    ogDescription: 'Distributed coordination and event propagation for AI.',
    ogImage: OG_BLOG,
    keywords: ['RIPPLE module network', 'distributed AI coordination', 'multi-agent communication', 'AI orchestration', 'modular AI systems'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'RIPPLE network integration distributed AI',
  },
  '/blog/promptfluid-access-identity-billing': {
    title: 'ACCESS Module: Identity & Billing Platform',
    description: 'Enterprise-grade authentication, API key metering, subscription management, and developer billing in the ACCESS module runtime.',
    ogTitle: 'ACCESS — Identity & Billing',
    ogDescription: 'Enterprise auth, API metering, and subscription management.',
    ogImage: OG_BLOG,
    keywords: ['ACCESS module billing', 'API key metering', 'enterprise authentication', 'AI infrastructure', 'governed AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'ACCESS identity billing module platform',
  },
  '/blog/promptfluid-nexus-api-gateway': {
    title: 'NEXUS Module: Unified API Gateway | CMPSBL',
    description: 'Unified API orchestration layer connecting AI services — intelligent routing, load balancing, and schema validation at runtime.',
    ogTitle: 'NEXUS — API Gateway',
    ogDescription: 'Unified API orchestration with intelligent routing.',
    ogImage: OG_BLOG,
    keywords: ['NEXUS API gateway', 'unified API orchestration', 'intelligent API routing', 'AI orchestration', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'NEXUS unified API gateway module',
  },
  '/blog/ai-product-comparison-2025': {
    title: 'AI Platform Comparison: CMPSBL vs Competitors',
    description: 'How CMPSBL compares to other AI platforms across capabilities, pricing, and cognitive architecture depth for production workloads.',
    ogTitle: 'AI Platform Comparison — CMPSBL',
    ogDescription: 'CMPSBL vs leading AI platforms — capabilities and architecture.',
    ogImage: OG_BLOG,
    keywords: ['AI product comparison', 'AI platform comparison', 'composable AI', 'cognitive architecture', 'AI infrastructure'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI product comparison platforms',
  },
  '/blog/promptfluid-market-disruptor': {
    title: 'Cognitive Infrastructure as Market Disruptor',
    description: 'How cognitive infrastructure is reshaping the AI landscape — from commodity APIs to persistent, self-improving systems at scale.',
    ogTitle: 'Market Disruptor — Cognitive Infrastructure',
    ogDescription: 'How cognitive infrastructure reshapes the AI industry.',
    ogImage: OG_BLOG,
    keywords: ['AI market disruption', 'cognitive infrastructure', 'self-improving software', 'AI infrastructure', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'cognitive infrastructure AI market disruptor',
  },
  '/blog/product-roadmap-2025': {
    title: 'Product Vision: Architecture & Milestones',
    description: 'Our vision for cognitive infrastructure — ongoing architectural evolution, capability expansion, and enterprise-grade feature development.',
    ogTitle: 'CMPSBL Product Vision',
    ogDescription: 'Ongoing cognitive architecture evolution and milestones.',
    ogImage: OG_BLOG,
    keywords: ['CMPSBL product vision', 'cognitive architecture', 'AI infrastructure', 'composable AI', 'recursive improvement'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'CMPSBL product vision milestones',
  },
  '/blog/ai-automation-trends-2025': {
    title: 'AI Automation Trends: Enterprise Patterns',
    description: 'Key trends shaping enterprise AI automation — from autonomous pipelines to cognitive orchestration and self-healing workflows.',
    ogTitle: 'AI Automation Trends — Enterprise',
    ogDescription: 'Enterprise automation trends from pipelines to self-healing.',
    ogImage: OG_BLOG,
    keywords: ['AI automation trends', 'enterprise AI automation', 'autonomous pipelines', 'self-improving software', 'AI orchestration'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI automation enterprise trends',
  },
  '/blog/ai-business-operations-2025': {
    title: 'AI Business Operations: Cognitive Workflows',
    description: 'Transforming enterprise workflows with cognitive automation — from document processing to decision support and operational intelligence.',
    ogTitle: 'AI Business Operations — Cognitive Workflows',
    ogDescription: 'Cognitive automation transforming enterprise workflows.',
    ogImage: OG_BLOG,
    keywords: ['AI business operations', 'cognitive enterprise workflows', 'adaptive intelligence', 'AI infrastructure', 'composable AI'],
    schema: 'article',
    intent: 'Blog/Changelog/Updates',
    primaryKeyword: 'AI business operations cognitive workflows',
  },
};

/**
 * Get SEO config for a route. Falls back to defaults for unknown routes.
 */
export function getSEO(path: string): PageSEO {
  if (seoMap[path]) return seoMap[path];

  if (path.startsWith('/blog/')) {
    return {
      title: 'CMPSBL Blog — AI Infrastructure Insights',
      description: 'AI infrastructure insights and engineering deep-dives on cognitive architecture, composable AI, and self-improving systems.',
      ogTitle: 'CMPSBL Blog — AI Insights',
      ogDescription: 'AI infrastructure insights from the CMPSBL team.',
      ogImage: OG_BLOG,
      keywords: ['CMPSBL blog', 'AI insights', 'composable AI', 'cognitive architecture'],
      schema: 'article',
      intent: 'Blog/Changelog/Updates',
      primaryKeyword: 'CMPSBL blog post',
    };
  }

  if (path.startsWith('/modules/')) {
    return {
      title: 'Module Detail — Composable AI Substrate',
      description: 'Explore this substrate module: architecture, capabilities, synergies, and integration guides for composable AI systems.',
      ogTitle: 'Substrate Module — CMPSBL',
      ogDescription: 'Architecture, capabilities, and integration for this substrate module.',
      ogImage: OG_FEATURE,
      keywords: ['substrate module', 'composable AI', 'modular AI systems', 'cognitive architecture'],
      schema: 'feature',
      intent: 'Feature/Capability',
      primaryKeyword: 'substrate module detail',
    };
  }

  return seoMap['/'];
}
