/**
 * OPERATIVES Catalog
 * Black-boxed Sealed Runtime software — first-class CMPSBL IP.
 * Each Operative is a self-contained, obfuscated, tamper-proof runtime.
 */

import {
  Shield, Ghost, Brain, Eye, Zap, GitBranch, Scale,
  Cog, Sparkles, Radio, Castle, Lock, Globe, Cpu,
} from "lucide-react";

export interface Operative {
  slug: string;
  codename: string;
  tagline: string;
  price: number;          // cents
  priceDisplay: string;   // e.g. "$799"
  priceId: string;        // Stripe price ID
  icon: React.ElementType;
  color: string;          // HSL accent color
  tier: "APEX" | "ELITE" | "CORE";
  edition: string;        // e.g. "Edition 001 of ∞"
  briefing: string;       // short mission-briefing copy
  capabilities: string[]; // what it does (outcomes, not internals)
  threatLevel: string;    // classification flavor
  clearance: string;      // access level flavor
  isSubscription?: boolean;
  subscriptionLabel?: string;
  externalPath?: string;  // if it links somewhere else (e.g. CMPSBL Engine)
}

export const OPERATIVES: Operative[] = [
  {
    slug: "architect",
    codename: "ARCHITECT",
    tagline: "The Unified Mega-Engine",
    price: 99900, // $999/yr subscription
    priceDisplay: "$999/yr",
    priceId: "price_1T6KAuQ7FtTiAL4aA6ziEyyh",
    icon: Cpu,
    color: "210 100% 60%",
    tier: "APEX",
    edition: "Edition APEX — Unlimited",
    briefing: "ARCHITECT orchestrates all 8 core pipelines into a single sealed runtime. Parse, Route, Execute, Heal, Defend, Learn, Observe, Audit — in one import. This is the full stack.",
    capabilities: [
      "Unified 8-stage cognitive pipeline",
      "Self-healing with automatic recovery",
      "Built-in security and anomaly defense",
      "Real-time observability and audit trail",
      "Intelligent multi-path routing",
      "Continuous learning from every execution",
    ],
    threatLevel: "CLASSIFIED — APEX TIER",
    clearance: "LEVEL 10 — UNRESTRICTED",
    isSubscription: true,
    subscriptionLabel: "Annual License",
    externalPath: "/cmpsbl-engine",
  },
  {
    slug: "sentinel",
    codename: "SENTINEL",
    tagline: "AI Security Operations",
    price: 79900,
    priceDisplay: "$799",
    priceId: "price_1T6Kz8Q7FtTiAL4aae82w1uD",
    icon: Shield,
    color: "0 80% 55%",
    tier: "APEX",
    edition: "Edition 001 of ∞",
    briefing: "SENTINEL hunts threats before they arrive. Behavioral analysis, IP reputation scoring, prompt injection shielding, and automated incident response — all running on every request, zero configuration.",
    capabilities: [
      "Behavioral anomaly detection",
      "Automated incident response",
      "IP reputation scoring",
      "Prompt injection shielding",
      "Real-time threat intelligence",
      "Zero-config security hardening",
    ],
    threatLevel: "CRITICAL — ACTIVE DEFENSE",
    clearance: "LEVEL 9 — TOP SECRET",
  },
  {
    slug: "phantom",
    codename: "PHANTOM",
    tagline: "Self-Healing Service Mesh",
    price: 69900,
    priceDisplay: "$699",
    priceId: "price_1T6Kz9Q7FtTiAL4agMtP6pVo",
    icon: Ghost,
    color: "280 70% 55%",
    tier: "APEX",
    edition: "Edition 001 of ∞",
    briefing: "PHANTOM makes downtime impossible. Auto-recovery, circuit breaking, and intelligent failover keep your services alive even when individual nodes fail. Your users never see an error page again.",
    capabilities: [
      "Automatic service recovery",
      "Circuit breaker orchestration",
      "Zero-downtime deployments",
      "Intelligent failover routing",
      "Health-based load shedding",
      "Chaos resilience built-in",
    ],
    threatLevel: "HIGH — RESILIENCE OPS",
    clearance: "LEVEL 8 — CLASSIFIED",
  },
  {
    slug: "cortex",
    codename: "CORTEX",
    tagline: "Agent Runtime & Orchestration",
    price: 59900,
    priceDisplay: "$599",
    priceId: "price_1T6KzAQ7FtTiAL4aRuLZ4c6w",
    icon: Brain,
    color: "310 70% 55%",
    tier: "ELITE",
    edition: "Edition 001 of ∞",
    briefing: "CORTEX gives your AI agents a brain. Multi-agent orchestration, task delegation, memory coordination, and cognitive load balancing — so your agents think together instead of stepping on each other.",
    capabilities: [
      "Multi-agent task delegation",
      "Cognitive load balancing",
      "Shared memory coordination",
      "Agent competency tracking",
      "Automatic skill routing",
      "Collaborative reasoning",
    ],
    threatLevel: "ELEVATED — COGNITIVE OPS",
    clearance: "LEVEL 7 — RESTRICTED",
  },
  {
    slug: "oracle",
    codename: "ORACLE",
    tagline: "Real-Time Analytics & Prediction",
    price: 54900,
    priceDisplay: "$549",
    priceId: "price_1T6KzCQ7FtTiAL4adOEreJQK",
    icon: Eye,
    color: "45 90% 50%",
    tier: "ELITE",
    edition: "Edition 001 of ∞",
    briefing: "ORACLE sees what's coming. Predictive modeling, anomaly detection, and live data intelligence that turns raw signals into actionable foresight. Know before it happens.",
    capabilities: [
      "Predictive trend modeling",
      "Real-time anomaly detection",
      "Live data stream processing",
      "Automated insight generation",
      "Pattern recognition at scale",
      "Forecasting with confidence intervals",
    ],
    threatLevel: "MODERATE — INTELLIGENCE",
    clearance: "LEVEL 7 — RESTRICTED",
  },
  {
    slug: "vanguard",
    codename: "VANGUARD",
    tagline: "Edge Computing & CDN",
    price: 49900,
    priceDisplay: "$499",
    priceId: "price_1T6KzCQ7FtTiAL4ajzGYKnCm",
    icon: Zap,
    color: "185 80% 45%",
    tier: "ELITE",
    edition: "Edition 001 of ∞",
    briefing: "VANGUARD pushes compute to the edge. Distributed execution, intelligent caching, and sub-millisecond processing at the point of request. Latency becomes a non-issue.",
    capabilities: [
      "Distributed edge execution",
      "Intelligent edge caching",
      "Sub-millisecond processing",
      "Global request distribution",
      "Edge-native compute functions",
      "Automatic geo-routing",
    ],
    threatLevel: "MODERATE — EDGE OPS",
    clearance: "LEVEL 6 — CONFIDENTIAL",
  },
  {
    slug: "conductor",
    codename: "CONDUCTOR",
    tagline: "Data Pipeline Orchestration",
    price: 44900,
    priceDisplay: "$449",
    priceId: "price_1T6KzEQ7FtTiAL4aK4xjMcxf",
    icon: GitBranch,
    color: "145 65% 42%",
    tier: "ELITE",
    edition: "Edition 001 of ∞",
    briefing: "CONDUCTOR moves data like water. ETL automation, stream processing, and data lineage tracking ensure every byte flows where it needs to go — reliably, traceably, automatically.",
    capabilities: [
      "Automated ETL pipelines",
      "Real-time stream processing",
      "Data lineage tracking",
      "Schema evolution handling",
      "Dead letter queue management",
      "Backpressure-aware processing",
    ],
    threatLevel: "LOW — DATA OPS",
    clearance: "LEVEL 6 — CONFIDENTIAL",
  },
  {
    slug: "arbiter",
    codename: "ARBITER",
    tagline: "API Gateway & Traffic Control",
    price: 44900,
    priceDisplay: "$449",
    priceId: "price_1T6KzFQ7FtTiAL4aQ6OOL7zm",
    icon: Scale,
    color: "210 60% 45%",
    tier: "ELITE",
    edition: "Edition 001 of ∞",
    briefing: "ARBITER controls the gates. Intelligent request routing, rate limiting, API versioning, and traffic shaping — so your APIs serve exactly who they should, exactly how fast they should.",
    capabilities: [
      "Intelligent request routing",
      "Per-endpoint rate limiting",
      "API versioning & deprecation",
      "Traffic shaping & throttling",
      "Request/response transformation",
      "Authentication gateway",
    ],
    threatLevel: "MODERATE — ACCESS CONTROL",
    clearance: "LEVEL 6 — CONFIDENTIAL",
  },
  {
    slug: "automaton",
    codename: "AUTOMATON",
    tagline: "Workflow Automation Engine",
    price: 39900,
    priceDisplay: "$399",
    priceId: "price_1T6KzGQ7FtTiAL4aklAECZFT",
    icon: Cog,
    color: "38 90% 50%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "AUTOMATON turns repetition into reliability. Conditional workflows, scheduled execution, and event-driven automation that handles the boring stuff so your team handles the brilliant stuff.",
    capabilities: [
      "Visual workflow composition",
      "Conditional branching logic",
      "Scheduled task execution",
      "Event-driven triggers",
      "Retry & error handling",
      "Parallel execution paths",
    ],
    threatLevel: "LOW — AUTOMATION",
    clearance: "LEVEL 5 — STANDARD",
  },
  {
    slug: "catalyst",
    codename: "CATALYST",
    tagline: "Event-Driven Architecture",
    price: 39900,
    priceDisplay: "$399",
    priceId: "price_1T6KzHQ7FtTiAL4aI2vl1Sdn",
    icon: Sparkles,
    color: "310 100% 50%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "CATALYST makes everything reactive. Pub/sub messaging, event sourcing, and CQRS patterns that decouple your services and let them evolve independently without breaking each other.",
    capabilities: [
      "Pub/sub event messaging",
      "Event sourcing & replay",
      "CQRS pattern support",
      "Service decoupling",
      "Dead letter handling",
      "Event schema registry",
    ],
    threatLevel: "LOW — EVENT OPS",
    clearance: "LEVEL 5 — STANDARD",
  },
  {
    slug: "beacon",
    codename: "BEACON",
    tagline: "Observability & Monitoring Stack",
    price: 34900,
    priceDisplay: "$349",
    priceId: "price_1T6KzIQ7FtTiAL4asDddxKsj",
    icon: Radio,
    color: "145 80% 40%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "BEACON illuminates everything. Metrics, distributed tracing, structured logging, and health monitoring unified into a single pane of glass. See your entire stack in real time.",
    capabilities: [
      "Unified metrics collection",
      "Distributed request tracing",
      "Structured log aggregation",
      "Real-time health dashboards",
      "Alert & threshold management",
      "SLA tracking & reporting",
    ],
    threatLevel: "LOW — OBSERVABILITY",
    clearance: "LEVEL 5 — STANDARD",
  },
  {
    slug: "bastion",
    codename: "BASTION",
    tagline: "Intelligent Load Balancing",
    price: 34900,
    priceDisplay: "$349",
    priceId: "price_1T6KzJQ7FtTiAL4aG3TGxmJP",
    icon: Castle,
    color: "200 50% 40%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "BASTION distributes load like a strategist. Health-aware routing, weighted distribution, and automatic failover that keeps your services responsive under any traffic pattern.",
    capabilities: [
      "Health-aware traffic routing",
      "Weighted load distribution",
      "Automatic failover",
      "Session affinity support",
      "Connection pooling",
      "Capacity-based scaling triggers",
    ],
    threatLevel: "LOW — INFRASTRUCTURE",
    clearance: "LEVEL 5 — STANDARD",
  },
  {
    slug: "cipher",
    codename: "CIPHER",
    tagline: "Distributed Cache System",
    price: 29900,
    priceDisplay: "$299",
    priceId: "price_1T6KzKQ7FtTiAL4aFM0leS6C",
    icon: Lock,
    color: "280 100% 55%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "CIPHER remembers so your servers don't have to. In-memory distributed caching with intelligent invalidation, cache coherency, and tiered storage that makes every read instant.",
    capabilities: [
      "Distributed in-memory caching",
      "Intelligent cache invalidation",
      "Cache coherency protocols",
      "Tiered storage (hot/warm/cold)",
      "TTL & eviction policies",
      "Cache-aside pattern support",
    ],
    threatLevel: "LOW — PERFORMANCE",
    clearance: "LEVEL 4 — OPEN",
  },
  {
    slug: "meridian",
    codename: "MERIDIAN",
    tagline: "Content Delivery Network",
    price: 29900,
    priceDisplay: "$299",
    priceId: "price_1T6KzLQ7FtTiAL4aiOAUMvyq",
    icon: Globe,
    color: "185 100% 40%",
    tier: "CORE",
    edition: "Edition 001 of ∞",
    briefing: "MERIDIAN delivers content at the speed of proximity. Global edge distribution, asset optimization, and intelligent routing that puts your content milliseconds from every user on Earth.",
    capabilities: [
      "Global edge distribution",
      "Automatic asset optimization",
      "Intelligent geo-routing",
      "Cache warming & prefetch",
      "Origin shield protection",
      "Real-time purge & invalidation",
    ],
    threatLevel: "LOW — DELIVERY",
    clearance: "LEVEL 4 — OPEN",
  },
];

export const getOperativeBySlug = (slug: string): Operative | undefined =>
  OPERATIVES.find((o) => o.slug === slug);

export const TIER_ORDER = { APEX: 0, ELITE: 1, CORE: 2 } as const;

export const getOperativesByTier = (tier: Operative["tier"]): Operative[] =>
  OPERATIVES.filter((o) => o.tier === tier);
