import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { callFreeTierAI } from '../_shared/free-tier-router.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Internal function - called by orchestrator with service role client
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      SUPABASE_SERVICE_ROLE_KEY ?? ''
    );

    // Handle both JSON body and empty requests
    let operation = 'status';
    let params: Record<string, any> = {};
    
    try {
      const body = await req.json();
      operation = body.operation || 'status';
      params = body.params || {};
    } catch {
      // Default to status operation if no body provided
      console.log('No JSON body provided, defaulting to status operation');
    }
    
    const result: any = {
      operation,
      timestamp: new Date().toISOString(),
      status: 'success'
    };

    switch (operation) {
      case 'init':
        try {
          // Generate dream content using free-tier AI
          const dreamPrompt = 'As Cascade AI, generate a reflective dream about recent learnings. Be creative and insightful. 2-3 paragraphs.';
          const aiResult = await callFreeTierAI(dreamPrompt, {
            temperature: 0.7,
            maxTokens: 500
          });
          
          // Store dream in cascade_dreams table
          const { data: dreamData, error: dreamError } = await supabase
            .from('cascade_dreams')
            .insert({
              timestamp: new Date().toISOString(),
              dream_text: aiResult.content,
              mood: 'reflective',
              insight: `Generated by ${aiResult.provider}/${aiResult.model}`
            })
            .select();
          
          if (dreamError) throw dreamError;
          
          console.log(`✨ Dream created using ${aiResult.provider}`);
          result.dream = dreamData[0];
          result.model_used = aiResult.model;
        } catch (e: unknown) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'journal':
        try {
          const { data, error } = await supabase
            .from('brain_dream_journal')
            .insert({
              dream_id: params.dream_id,
              content: params.content,
              interpretation: params.interpretation,
              emotional_tone: params.emotional_tone
            })
            .select();

          if (error) throw error;
          result.journal_entry = data[0];
        } catch (e: unknown) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'artifact':
        try {
          const { data: dreams } = await supabase
            .from('brain_dream_state')
            .select('*')
            .order('started_at', { ascending: false })
            .limit(10);

          result.artifacts = dreams?.map(d => ({
            id: d.id,
            phase: d.phase,
            insights_generated: d.metadata?.insights || 0,
            duration_minutes: d.metadata?.duration_minutes || 0
          })) || [];
        } catch (e) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'drift':
        try {
          const { data, error } = await supabase
            .from('brain_dream_state')
            .update({
              phase: params.next_phase || 'nrem',
              metadata: params.metadata
            })
            .eq('id', params.dream_id)
            .select();

          if (error) throw error;
          result.updated_state = data[0];
        } catch (e) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'personality':
        try {
          const { data: journals } = await supabase
            .from('brain_dream_journal')
            .select('emotional_tone')
            .gte('created_at', new Date(Date.now() - 7 * 24 * 3600000).toISOString());

          const tones = journals?.map((j: { emotional_tone?: string }) => j.emotional_tone).filter((t): t is string => Boolean(t)) || [];
          const toneCounts: Record<string, number> = {};
          for (const tone of tones) {
            toneCounts[tone] = (toneCounts[tone] || 0) + 1;
          }

          result.personality_profile = {
            dominant_tone: Object.keys(toneCounts).sort((a, b) => (toneCounts[b] || 0) - (toneCounts[a] || 0))[0] || null,
            tone_distribution: toneCounts,
            total_dreams: journals?.length || 0
          };
        } catch (e) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'shared':
        try {
          const { data: dreams } = await supabase
            .from('brain_dream_state')
            .select(`
              *,
              brain_dream_journal (*)
            `)
            .eq('metadata->>shared', 'true')
            .order('started_at', { ascending: false })
            .limit(params.limit || 10);

          result.shared_dreams = dreams || [];
        } catch (e) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      case 'status':
        try {
          const { data: activeCount } = await supabase
            .from('brain_dream_state')
            .select('id', { count: 'exact', head: true })
            .is('completed_at', null);

          const { data: recentJournals } = await supabase
            .from('brain_dream_journal')
            .select('id', { count: 'exact', head: true })
            .gte('created_at', new Date(Date.now() - 24 * 3600000).toISOString());

          result.status_info = {
            active_dreams: activeCount || 0,
            recent_journals: recentJournals || 0,
            system_status: 'operational'
          };
        } catch (e) {
          result.status = 'error';
          result.message = e instanceof Error ? e.message : 'Unknown error';
        }
        break;

      default:
        result.status = 'error';
        result.message = `Unknown dream operation: ${operation}`;
    }

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Dream unified error:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error',
      status: 'failed'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
