/**
 * pf-forge-mint — Cognitive Bot Minting API
 * Mints cognitive research bots with configurable attributes
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface BotConfig {
  bot_name: string;
  bot_type: 'Research' | 'Analyst' | 'Planner' | 'Strategist' | 'Hybrid';
  memory_mode: 'Stateless' | 'Episodic' | 'Persistent';
  provider_stack: string[];
  capabilities: string[];
  delivery_format: 'Repo' | 'Download';
}

const CAPABILITY_TEMPLATES: Record<string, string> = {
  'Research / Web': `
  async research(query: string): Promise<string> {
    // Web research using configured providers
    return await this.nexus.search(query);
  }`,
  'Summarize': `
  async summarize(content: string): Promise<string> {
    return await this.nexus.text(\`Summarize: \${content}\`);
  }`,
  'Compare Sources': `
  async compareSources(sources: string[]): Promise<string> {
    return await this.nexus.text(\`Compare these sources: \${sources.join(', ')}\`);
  }`,
  'Write Reports': `
  async writeReport(topic: string, data: unknown): Promise<string> {
    return await this.nexus.text(\`Write a report about \${topic} using: \${JSON.stringify(data)}\`);
  }`,
  'Track Threads': `
  async trackThreads(threadIds: string[]): Promise<void> {
    await this.memory.store('tracked_threads', threadIds);
  }`,
  'Build Knowledge Graph': `
  async buildGraph(): Promise<void> {
    await this.brain.graphBuild();
  }`,
  'Continuous Learning': `
  async enableLearning(): Promise<void> {
    await this.brain.continuousLearn(true);
  }`,
  'Long-Term Retention': `
  async remember(content: string): Promise<void> {
    await this.brain.remember(content, 'persistent', 0.9);
  }`,
};

function generateBotSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function generateBotConfig(config: BotConfig): string {
  return `# Cognitive Bot Configuration
# Generated by promptfluid® Forge

name: "${config.bot_name}"
type: ${config.bot_type}
version: "1.0.0"

memory:
  mode: ${config.memory_mode}
  ${config.memory_mode === 'Persistent' ? 'tables:\n    - brain_memory_hot\n    - brain_memory_cold' : ''}
  ${config.memory_mode === 'Episodic' ? 'session_ttl: 3600' : ''}

providers:
${config.provider_stack.map(p => `  - ${p.toLowerCase()}`).join('\n')}

capabilities:
${config.capabilities.map(c => `  - "${c}"`).join('\n')}

nexus:
  fallback_enabled: true
  max_retries: 3
  timeout_ms: 30000
`;
}

function generateBotCode(config: BotConfig): string {
  const capabilityMethods = config.capabilities
    .filter(c => CAPABILITY_TEMPLATES[c])
    .map(c => CAPABILITY_TEMPLATES[c])
    .join('\n');

  return `/**
 * ${config.bot_name} — ${config.bot_type} Cognitive Bot
 * Generated by promptfluid® Forge
 */

import { substrate, brain, nexus } from '@promptfluid/substrate';

interface BotMemory {
  store: (key: string, value: unknown) => Promise<void>;
  retrieve: (key: string) => Promise<unknown>;
  clear: () => Promise<void>;
}

class ${config.bot_name.replace(/[^a-zA-Z0-9]/g, '')}Bot {
  private nexus = nexus;
  private brain = brain;
  private memory: BotMemory;
  
  constructor() {
    this.memory = this.initMemory('${config.memory_mode}');
  }
  
  private initMemory(mode: string): BotMemory {
    const store: Record<string, unknown> = {};
    
    switch (mode) {
      case 'Stateless':
        return {
          store: async () => {},
          retrieve: async () => null,
          clear: async () => {},
        };
      case 'Episodic':
        return {
          store: async (k, v) => { store[k] = v; },
          retrieve: async (k) => store[k],
          clear: async () => { Object.keys(store).forEach(k => delete store[k]); },
        };
      case 'Persistent':
        return {
          store: async (k, v) => { 
            await brain.remember(JSON.stringify({ key: k, value: v }), 'bot_memory');
          },
          retrieve: async (k) => {
            const result = await brain.recall(k, 1);
            return result.data;
          },
          clear: async () => {},
        };
      default:
        return {
          store: async () => {},
          retrieve: async () => null,
          clear: async () => {},
        };
    }
  }
  ${capabilityMethods}
  
  async run(task: string): Promise<string> {
    console.log(\`[\${this.constructor.name}] Running task: \${task}\`);
    
    // Use configured providers through Nexus
    const result = await this.nexus.text(task);
    
    if (result.success && result.data) {
      return String(result.data);
    }
    
    return 'Task processing failed';
  }
}

export const bot = new ${config.bot_name.replace(/[^a-zA-Z0-9]/g, '')}Bot();
export default bot;
`;
}

function generatePackageJson(config: BotConfig): string {
  return JSON.stringify({
    name: `@cognitive/${generateBotSlug(config.bot_name)}`,
    version: '1.0.0',
    description: `${config.bot_type} Cognitive Bot - ${config.bot_name}`,
    main: 'src/index.ts',
    scripts: {
      start: 'ts-node src/index.ts',
      build: 'tsc',
      test: 'vitest',
    },
    dependencies: {
      '@promptfluid/substrate': '^2026.01',
    },
    devDependencies: {
      typescript: '^5.0.0',
      'ts-node': '^10.9.0',
      vitest: '^1.0.0',
    },
    keywords: ['cognitive', 'ai', 'bot', config.bot_type.toLowerCase()],
    author: 'promptfluid® Forge',
    license: 'MIT',
  }, null, 2);
}

function generateReadme(config: BotConfig): string {
  return `# ${config.bot_name}

A **${config.bot_type}** cognitive bot generated by promptfluid® Forge.

## Configuration

- **Memory Mode**: ${config.memory_mode}
- **Providers**: ${config.provider_stack.join(', ')}
- **Capabilities**: ${config.capabilities.join(', ')}

## Quick Start

\`\`\`typescript
import bot from './src/index';

// Run a task
const result = await bot.run('Analyze market trends for Q1 2026');
console.log(result);
\`\`\`

## Capabilities

${config.capabilities.map(c => `- ${c}`).join('\n')}

## Memory

This bot uses **${config.memory_mode}** memory:
${config.memory_mode === 'Stateless' ? '- No state persisted between calls' : ''}
${config.memory_mode === 'Episodic' ? '- State persisted during session only' : ''}
${config.memory_mode === 'Persistent' ? '- State persisted to brain_memory tables' : ''}

## Providers

Configured to use the following AI providers through Nexus:
${config.provider_stack.map(p => `- ${p}`).join('\n')}

---
Generated by promptfluid® Cognitive Forge
`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get auth token
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ success: false, error: 'Authentication required' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Verify user
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) {
      return new Response(
        JSON.stringify({ success: false, error: 'Invalid authentication' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const body = await req.json() as BotConfig;

    // Validate config
    const errors: string[] = [];
    if (!body.bot_name?.trim()) errors.push('Bot name is required');
    if (!body.bot_type) errors.push('Bot type is required');
    if (!body.memory_mode) errors.push('Memory mode is required');
    if (!body.provider_stack?.length) errors.push('At least one provider is required');
    if (!body.capabilities?.length) errors.push('At least one capability is required');
    if (!body.delivery_format) errors.push('Delivery format is required');

    if (body.memory_mode === 'Persistent') {
      // Warn about persistent tables
      console.log('Note: Persistent memory requires brain_memory tables');
    }

    if (errors.length > 0) {
      return new Response(
        JSON.stringify({ success: false, errors }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const slug = generateBotSlug(body.bot_name);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const exportPath = `/exports/bots/${slug}/${timestamp}`;

    // Generate artifacts
    const configYaml = generateBotConfig(body);
    const botCode = generateBotCode(body);
    const packageJson = generatePackageJson(body);
    const readme = generateReadme(body);

    const artifacts = {
      'bot.yaml': configYaml,
      'src/index.ts': botCode,
      'package.json': packageJson,
      'README.md': readme,
    };

    // Store bot in database
    const { data: bot, error: insertError } = await supabase
      .from('bots')
      .insert({
        name: body.bot_name,
        type: body.bot_type,
        config: { yaml: configYaml },
        memory_mode: body.memory_mode,
        providers: body.provider_stack,
        capabilities: body.capabilities,
        delivery_format: body.delivery_format,
        slug,
        export_path: exportPath,
        user_id: user.id,
      })
      .select()
      .single();

    if (insertError) {
      console.error('Failed to store bot:', insertError);
      return new Response(
        JSON.stringify({ success: false, error: 'Failed to store bot configuration' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Log event
    await supabase.from('brain_events').insert({
      module: 'forge',
      event_type: 'bot_minted',
      data: {
        bot_id: bot.id,
        bot_name: body.bot_name,
        bot_type: body.bot_type,
        memory_mode: body.memory_mode,
        providers: body.provider_stack,
        capabilities: body.capabilities,
      },
      outcome: 'success',
    });

    return new Response(
      JSON.stringify({
        success: true,
        data: {
          bot,
          artifacts,
          exportPath,
          repoSlug: body.delivery_format === 'Repo' ? `${slug}-cognitive` : null,
        },
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Forge mint error:', error);
    return new Response(
      JSON.stringify({ success: false, error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
