/**
 * Junkyard / Open Archive — Static inventory of 100 sub-threshold items.
 * CJPI 1–67. Free to take. No database calls. No protected IP.
 */

type ItemCondition = 'raw' | 'broken' | 'salvageable';
type ArchiveCategory = 'Raw Discoveries' | 'Broken Tech' | 'Salvageable Parts' | 'Legacy Systems';

export interface ArchiveItem {
  id: string;
  name: string;
  description: string;
  category: ArchiveCategory;
  condition: ItemCondition;
  score: number;
  image: string;
  imageAlt: string;
  restorationCost?: string;
  originalValue?: string;
}

/**
 * Build the archive using image paths injected by the page component
 * so this module stays image-import-free (images are page-level concerns).
 */
export function buildArchiveCatalog(images: {
  security: string; governance: string; monitoring: string;
  performance: string; resilience: string; decision: string;
  brokenCircuit: string; decommServer: string; corruptedData: string;
  brokenInput: string; crackedDisplay: string; salvageRobot: string;
  tangledNetwork: string; legacyStorage: string;
}): ArchiveItem[] {
  const img = images;
  return [
    // ═══ RAW DISCOVERIES (score 1–67, free) ═══
    { id: 'raw-1', name: 'Partial Thread Isolator', description: 'Discovered during Cycle 4,812. Scored 41 — thread boundary detection works but leaks under concurrent load.', category: 'Raw Discoveries', condition: 'raw', score: 41, image: img.security, imageAlt: 'Partial thread isolation' },
    { id: 'raw-2', name: 'Naive Pattern Matcher v0.3', description: 'Fast on simple patterns, catastrophic backtracking on nested groups. Score 33.', category: 'Raw Discoveries', condition: 'raw', score: 33, image: img.monitoring, imageAlt: 'Pattern matching' },
    { id: 'raw-3', name: 'Drift Signal Collector', description: 'Captures semantic drift between API versions. Noisy output, no deduplication. Score 52.', category: 'Raw Discoveries', condition: 'raw', score: 52, image: img.decision, imageAlt: 'Drift signal collection' },
    { id: 'raw-4', name: 'Config Entropy Scanner', description: 'Measures configuration complexity. Over-flags in monorepos. Score 47 but the metric is novel.', category: 'Raw Discoveries', condition: 'raw', score: 47, image: img.performance, imageAlt: 'Configuration entropy' },
    { id: 'raw-5', name: 'Shallow Dependency Walker', description: 'Walks first-level deps only. Misses transitive vulnerabilities. Score 38.', category: 'Raw Discoveries', condition: 'raw', score: 38, image: img.governance, imageAlt: 'Dependency analysis' },
    { id: 'raw-6', name: 'Stale Cache Detector', description: 'Identifies cache entries older than TTL. False positives on warm caches. Score 44.', category: 'Raw Discoveries', condition: 'raw', score: 44, image: img.resilience, imageAlt: 'Cache detection' },
    { id: 'raw-7', name: 'Loose Type Inferencer', description: 'Infers types from runtime values. Misses union types entirely. Score 29.', category: 'Raw Discoveries', condition: 'raw', score: 29, image: img.decision, imageAlt: 'Type inference' },
    { id: 'raw-8', name: 'Blind Retry Wrapper', description: 'Retries everything 3 times with no backoff. Causes thundering herd. Score 18.', category: 'Raw Discoveries', condition: 'raw', score: 18, image: img.resilience, imageAlt: 'Retry logic' },
    { id: 'raw-9', name: 'Single-Key Encryptor', description: 'AES-128 with hardcoded IV. Functional but cryptographically weak. Score 35.', category: 'Raw Discoveries', condition: 'raw', score: 35, image: img.security, imageAlt: 'Basic encryption' },
    { id: 'raw-10', name: 'Flat Config Parser', description: 'Parses .ini files only. No nested sections, no interpolation. Score 22.', category: 'Raw Discoveries', condition: 'raw', score: 22, image: img.governance, imageAlt: 'Config parsing' },
    { id: 'raw-11', name: 'Console Log Aggregator', description: 'Collects console.log output into a buffer. No structured logging. Score 15.', category: 'Raw Discoveries', condition: 'raw', score: 15, image: img.monitoring, imageAlt: 'Log aggregation' },
    { id: 'raw-12', name: 'Hardcoded Threshold Alert', description: 'Fires alert when value exceeds 100. Not configurable. Score 12.', category: 'Raw Discoveries', condition: 'raw', score: 12, image: img.monitoring, imageAlt: 'Static alerting' },
    { id: 'raw-13', name: 'Sync-Only HTTP Client', description: 'Blocking HTTP calls. Works but freezes the event loop. Score 25.', category: 'Raw Discoveries', condition: 'raw', score: 25, image: img.performance, imageAlt: 'HTTP client' },
    { id: 'raw-14', name: 'Timestamp Formatter v1', description: 'Formats dates to ISO-8601. No timezone support. Score 31.', category: 'Raw Discoveries', condition: 'raw', score: 31, image: img.governance, imageAlt: 'Date formatting' },
    { id: 'raw-15', name: 'Global State Dumper', description: 'Serializes entire app state to JSON. No incremental diffing. Score 27.', category: 'Raw Discoveries', condition: 'raw', score: 27, image: img.resilience, imageAlt: 'State serialization' },
    { id: 'raw-16', name: 'Naive Load Tester', description: 'Sends N requests in a tight loop. No connection pooling or metrics. Score 20.', category: 'Raw Discoveries', condition: 'raw', score: 20, image: img.performance, imageAlt: 'Load testing' },
    { id: 'raw-17', name: 'Static Sitemap Builder', description: 'Generates sitemap.xml from hardcoded URL list. No crawling. Score 34.', category: 'Raw Discoveries', condition: 'raw', score: 34, image: img.governance, imageAlt: 'Sitemap generation' },
    { id: 'raw-18', name: 'Boolean Feature Flag', description: 'On/off flags stored in a JSON file. No rollout percentages. Score 40.', category: 'Raw Discoveries', condition: 'raw', score: 40, image: img.governance, imageAlt: 'Feature flags' },
    { id: 'raw-19', name: 'Plaintext Password Checker', description: 'Checks password length only. No complexity rules. Score 8.', category: 'Raw Discoveries', condition: 'raw', score: 8, image: img.security, imageAlt: 'Password validation' },
    { id: 'raw-20', name: 'Fixed-Window Rate Counter', description: 'Counts requests per minute in fixed windows. Burst-prone at boundaries. Score 45.', category: 'Raw Discoveries', condition: 'raw', score: 45, image: img.security, imageAlt: 'Rate counting' },
    { id: 'raw-21', name: 'Memory Leak Scanner v0', description: 'Periodically logs heap size. No leak detection logic. Score 19.', category: 'Raw Discoveries', condition: 'raw', score: 19, image: img.monitoring, imageAlt: 'Memory scanning' },
    { id: 'raw-22', name: 'One-Shot Task Runner', description: 'Executes a single async task. No queue, no retry, no monitoring. Score 16.', category: 'Raw Discoveries', condition: 'raw', score: 16, image: img.performance, imageAlt: 'Task execution' },
    { id: 'raw-23', name: 'Regex Email Validator', description: 'Validates emails with a basic regex. Fails on plus-addressing. Score 28.', category: 'Raw Discoveries', condition: 'raw', score: 28, image: img.security, imageAlt: 'Email validation' },
    { id: 'raw-24', name: 'Polling Health Check', description: 'Pings an endpoint every 60 seconds. No adaptive intervals. Score 36.', category: 'Raw Discoveries', condition: 'raw', score: 36, image: img.monitoring, imageAlt: 'Health polling' },
    { id: 'raw-25', name: 'Unindexed Search Scanner', description: 'Full-table scan for text matching. Works on small datasets only. Score 23.', category: 'Raw Discoveries', condition: 'raw', score: 23, image: img.decision, imageAlt: 'Text search' },

    // ═══ BROKEN TECH (damaged, restorable) ═══
    { id: 'broken-1', name: 'CORTEX-7 Reasoning Module', description: 'Previously CJPI 82. Corrupted during migration. Core logic intact but inference bridge severed.', category: 'Broken Tech', condition: 'broken', score: 57, image: img.corruptedData, imageAlt: 'Corrupted reasoning module', restorationCost: '$149', originalValue: '$329' },
    { id: 'broken-2', name: 'SENTINEL Firewall Array', description: 'Multi-layer packet inspector. Clock desync bricked the timing module. Beautiful under the damage.', category: 'Broken Tech', condition: 'broken', score: 48, image: img.brokenCircuit, imageAlt: 'Broken firewall circuit', restorationCost: '$89', originalValue: '$199' },
    { id: 'broken-3', name: 'MERIDIAN Load Balancer', description: 'Distributed traffic shaper. Memory leak in connection pool. Was running 10k req/s before it went down.', category: 'Broken Tech', condition: 'broken', score: 44, image: img.decommServer, imageAlt: 'Decommissioned server', restorationCost: '$119', originalValue: '$249' },
    { id: 'broken-4', name: 'ORACLE Prediction Engine', description: 'Time-series forecasting. Training data corruption caused confidence drift. Fixable with re-calibration.', category: 'Broken Tech', condition: 'broken', score: 61, image: img.crackedDisplay, imageAlt: 'Cracked prediction display', restorationCost: '$199', originalValue: '$449' },
    { id: 'broken-5', name: 'PHANTOM Trace Recorder', description: 'Full distributed tracing with span correlation. Buffer overflow corrupted the trace store. Core engine recoverable.', category: 'Broken Tech', condition: 'broken', score: 55, image: img.corruptedData, imageAlt: 'Corrupted trace data', restorationCost: '$129', originalValue: '$289' },
    { id: 'broken-6', name: 'CIPHER Key Exchange', description: 'Diffie-Hellman key negotiation module. Entropy source failed. Handshake logic is sound.', category: 'Broken Tech', condition: 'broken', score: 50, image: img.brokenCircuit, imageAlt: 'Broken crypto circuit', restorationCost: '$99', originalValue: '$219' },
    { id: 'broken-7', name: 'VECTOR Embedding Store', description: 'High-dimensional vector index. Index corruption after power loss. Rebuild from checkpoints possible.', category: 'Broken Tech', condition: 'broken', score: 63, image: img.decommServer, imageAlt: 'Failed vector store', restorationCost: '$179', originalValue: '$399' },
    { id: 'broken-8', name: 'PRISM Analytics Pipeline', description: 'Real-time analytics aggregator. Partition key collision broke sharding. Logic intact, data needs rehash.', category: 'Broken Tech', condition: 'broken', score: 58, image: img.crackedDisplay, imageAlt: 'Broken analytics display', restorationCost: '$139', originalValue: '$309' },
    { id: 'broken-9', name: 'AEGIS Permission Matrix', description: 'Fine-grained RBAC engine. Schema migration left orphaned role mappings. Core authorization logic works.', category: 'Broken Tech', condition: 'broken', score: 52, image: img.brokenInput, imageAlt: 'Broken permission input', restorationCost: '$109', originalValue: '$239' },
    { id: 'broken-10', name: 'CHRONOS Event Sequencer', description: 'Guaranteed event ordering across distributed nodes. Clock drift broke the vector clocks. Recoverable.', category: 'Broken Tech', condition: 'broken', score: 59, image: img.corruptedData, imageAlt: 'Corrupted event sequence', restorationCost: '$159', originalValue: '$349' },
    { id: 'broken-11', name: 'FLUX State Machine', description: 'Deterministic finite automaton for workflow orchestration. Transition table corrupted. State definitions intact.', category: 'Broken Tech', condition: 'broken', score: 46, image: img.brokenCircuit, imageAlt: 'Broken state machine', restorationCost: '$79', originalValue: '$179' },
    { id: 'broken-12', name: 'NOVA Query Planner', description: 'Cost-based query optimizer. Statistics table stale after schema change. Re-analysis would restore it.', category: 'Broken Tech', condition: 'broken', score: 64, image: img.decommServer, imageAlt: 'Failed query planner', restorationCost: '$189', originalValue: '$419' },
    { id: 'broken-13', name: 'ZENITH Cache Coordinator', description: 'Distributed cache invalidation with pub/sub. Message broker connection severed. Invalidation logic is clean.', category: 'Broken Tech', condition: 'broken', score: 53, image: img.crackedDisplay, imageAlt: 'Broken cache coordinator', restorationCost: '$119', originalValue: '$259' },
    { id: 'broken-14', name: 'TITAN Batch Processor', description: 'High-throughput batch ETL engine. Checkpoint file corrupted mid-run. Restart logic needs patching.', category: 'Broken Tech', condition: 'broken', score: 60, image: img.brokenInput, imageAlt: 'Broken batch processor', restorationCost: '$169', originalValue: '$369' },
    { id: 'broken-15', name: 'HERALD Notification Router', description: 'Multi-channel notification delivery. Template engine crashed, routing logic perfect. Quick fix.', category: 'Broken Tech', condition: 'broken', score: 42, image: img.tangledNetwork, imageAlt: 'Tangled notification wires', restorationCost: '$69', originalValue: '$149' },

    // ═══ SALVAGEABLE PARTS (partial, worth rebuilding) ═══
    { id: 'salvage-1', name: 'Auth Handshake Module', description: 'OAuth2 + PKCE. Token refresh works but CSRF guard stripped. 60% functional.', category: 'Salvageable Parts', condition: 'salvageable', score: 58, image: img.salvageRobot, imageAlt: 'Salvageable auth components', restorationCost: '$49', originalValue: '$99' },
    { id: 'salvage-2', name: 'Rate Limiter Core', description: 'Token bucket with sliding window. Single-instance only, no distributed coordination.', category: 'Salvageable Parts', condition: 'salvageable', score: 62, image: img.tangledNetwork, imageAlt: 'Rate limiter wiring', restorationCost: '$39', originalValue: '$79' },
    { id: 'salvage-3', name: 'Webhook Dispatcher v2', description: 'Reliable delivery with exponential backoff. Missing dead-letter queue. Core is solid.', category: 'Salvageable Parts', condition: 'salvageable', score: 55, image: img.brokenInput, imageAlt: 'Webhook dispatcher', restorationCost: '$59', originalValue: '$129' },
    { id: 'salvage-4', name: 'Session Fingerprinter', description: 'Browser fingerprinting for session binding. Missing mobile heuristics. Desktop coverage is 85%.', category: 'Salvageable Parts', condition: 'salvageable', score: 49, image: img.salvageRobot, imageAlt: 'Session fingerprint module', restorationCost: '$45', originalValue: '$89' },
    { id: 'salvage-5', name: 'GraphQL Schema Stitcher', description: 'Merges multiple GraphQL schemas. No conflict resolution on overlapping types. 70% there.', category: 'Salvageable Parts', condition: 'salvageable', score: 56, image: img.tangledNetwork, imageAlt: 'Schema stitching wires', restorationCost: '$55', originalValue: '$119' },
    { id: 'salvage-6', name: 'Binary Protocol Decoder', description: 'Decodes custom binary wire format. Missing the v3 extension fields. Core parser works.', category: 'Salvageable Parts', condition: 'salvageable', score: 47, image: img.brokenInput, imageAlt: 'Binary decoder parts', restorationCost: '$39', originalValue: '$79' },
    { id: 'salvage-7', name: 'Streaming CSV Parser', description: 'Parses multi-GB CSV files in constant memory. Chokes on quoted newlines. Score 60.', category: 'Salvageable Parts', condition: 'salvageable', score: 60, image: img.salvageRobot, imageAlt: 'CSV parser components', restorationCost: '$49', originalValue: '$99' },
    { id: 'salvage-8', name: 'Markdown Renderer Core', description: 'Converts MD to HTML. Missing table and footnote extensions. Fast and lightweight.', category: 'Salvageable Parts', condition: 'salvageable', score: 51, image: img.tangledNetwork, imageAlt: 'Renderer components', restorationCost: '$35', originalValue: '$69' },
    { id: 'salvage-9', name: 'WebSocket Heartbeat Manager', description: 'Keeps connections alive with ping/pong. No reconnection logic. Heartbeat timing is precise.', category: 'Salvageable Parts', condition: 'salvageable', score: 53, image: img.brokenInput, imageAlt: 'WebSocket components', restorationCost: '$42', originalValue: '$85' },
    { id: 'salvage-10', name: 'Color Space Converter', description: 'RGB ↔ HSL ↔ HEX conversion. Missing CMYK and LAB support. Accurate within sRGB.', category: 'Salvageable Parts', condition: 'salvageable', score: 44, image: img.salvageRobot, imageAlt: 'Color conversion module', restorationCost: '$29', originalValue: '$59' },
    { id: 'salvage-11', name: 'SQL Query Sanitizer', description: 'Parameterized query builder. Handles SELECT and INSERT. Missing UPDATE/DELETE support.', category: 'Salvageable Parts', condition: 'salvageable', score: 57, image: img.tangledNetwork, imageAlt: 'Query sanitizer parts', restorationCost: '$52', originalValue: '$109' },
    { id: 'salvage-12', name: 'Image Thumbnail Generator', description: 'Creates thumbnails from JPEG/PNG. No WebP or AVIF support. Resize quality is excellent.', category: 'Salvageable Parts', condition: 'salvageable', score: 50, image: img.brokenInput, imageAlt: 'Thumbnail generator', restorationCost: '$38', originalValue: '$79' },
    { id: 'salvage-13', name: 'Cron Expression Parser', description: 'Parses standard cron syntax. Missing extended fields (seconds, years). Core scheduling works.', category: 'Salvageable Parts', condition: 'salvageable', score: 46, image: img.salvageRobot, imageAlt: 'Cron parser module', restorationCost: '$32', originalValue: '$65' },
    { id: 'salvage-14', name: 'Diff Patch Engine', description: 'Generates and applies text diffs. Binary diff not supported. Clean three-way merge.', category: 'Salvageable Parts', condition: 'salvageable', score: 59, image: img.tangledNetwork, imageAlt: 'Diff engine components', restorationCost: '$55', originalValue: '$115' },
    { id: 'salvage-15', name: 'URL Shortener Core', description: 'Base62 encoding with collision detection. No analytics or expiration. Fast and reliable.', category: 'Salvageable Parts', condition: 'salvageable', score: 43, image: img.brokenInput, imageAlt: 'URL shortener parts', restorationCost: '$25', originalValue: '$49' },
    { id: 'salvage-16', name: 'PDF Text Extractor', description: 'Extracts plain text from PDF v1.4. No OCR, no form fields. Text layer extraction is clean.', category: 'Salvageable Parts', condition: 'salvageable', score: 54, image: img.salvageRobot, imageAlt: 'PDF extractor module', restorationCost: '$48', originalValue: '$99' },
    { id: 'salvage-17', name: 'GeoIP Resolver', description: 'Maps IPs to country codes using static database. No city-level precision. 95% country accuracy.', category: 'Salvageable Parts', condition: 'salvageable', score: 48, image: img.tangledNetwork, imageAlt: 'GeoIP components', restorationCost: '$35', originalValue: '$72' },
    { id: 'salvage-18', name: 'Markdown Table Formatter', description: 'Aligns markdown tables with column padding. No multi-line cell support. Clean output.', category: 'Salvageable Parts', condition: 'salvageable', score: 38, image: img.brokenInput, imageAlt: 'Table formatter parts', restorationCost: '$22', originalValue: '$45' },
    { id: 'salvage-19', name: 'JWT Claim Extractor', description: 'Decodes and validates JWT claims. No key rotation support. Signature verification works.', category: 'Salvageable Parts', condition: 'salvageable', score: 61, image: img.salvageRobot, imageAlt: 'JWT module components', restorationCost: '$52', originalValue: '$109' },
    { id: 'salvage-20', name: 'SMTP Envelope Builder', description: 'Constructs SMTP envelopes with MIME multipart. No attachment streaming. Text emails flawless.', category: 'Salvageable Parts', condition: 'salvageable', score: 45, image: img.tangledNetwork, imageAlt: 'SMTP builder parts', restorationCost: '$32', originalValue: '$65' },

    // ═══ LEGACY SYSTEMS (deprecated but classic) ═══
    { id: 'legacy-1', name: 'ATLAS v1 Navigation Core', description: 'First-gen capability mapper. Sequential scan only — no parallel discovery. Historical from Cycle 200.', category: 'Legacy Systems', condition: 'raw', score: 45, image: img.legacyStorage, imageAlt: 'Legacy storage platters' },
    { id: 'legacy-2', name: 'BEACON v0 Health Check', description: 'The original heartbeat monitor. UDP only, no TLS. Grandfather of current BEACON engine.', category: 'Legacy Systems', condition: 'raw', score: 39, image: img.decommServer, imageAlt: 'Original BEACON server' },
    { id: 'legacy-3', name: 'Proto-DREAM Synthesizer', description: 'Before DREAM was DREAM. Used random walks instead of sub-threshold synthesis. Fascinating failure.', category: 'Legacy Systems', condition: 'raw', score: 51, image: img.corruptedData, imageAlt: 'Proto-DREAM visualization' },
    { id: 'legacy-4', name: 'FORGE v0 Template Engine', description: 'String concatenation-based code generation. No AST manipulation. The very first artifact compiler.', category: 'Legacy Systems', condition: 'raw', score: 32, image: img.legacyStorage, imageAlt: 'Original FORGE hardware' },
    { id: 'legacy-5', name: 'NEXUS v1 Single-Provider', description: 'Original NEXUS before multi-provider routing. Hardcoded to one AI provider. Historical reference.', category: 'Legacy Systems', condition: 'raw', score: 41, image: img.decommServer, imageAlt: 'First NEXUS server' },
    { id: 'legacy-6', name: 'DEFENSE v0 Firewall', description: 'IP-only blocking. No payload inspection, no rate limiting. The first line of defense, literally.', category: 'Legacy Systems', condition: 'raw', score: 28, image: img.brokenCircuit, imageAlt: 'Original firewall board' },
    { id: 'legacy-7', name: 'AUDIT v0 Logger', description: 'Appended events to a flat file. No rotation, no compression, no search. Pure simplicity.', category: 'Legacy Systems', condition: 'raw', score: 21, image: img.legacyStorage, imageAlt: 'Flat file audit system' },
    { id: 'legacy-8', name: 'SHADOW v0 Sandbox', description: 'Process-level isolation using fork(). No container support. Cycle 50-era technology.', category: 'Legacy Systems', condition: 'raw', score: 35, image: img.decommServer, imageAlt: 'Original sandbox server' },
    { id: 'legacy-9', name: 'AUTOMATON v0 Scheduler', description: 'Cron-based task scheduler. No DAG support, no retry logic. Ran the first 100 discovery cycles.', category: 'Legacy Systems', condition: 'raw', score: 37, image: img.legacyStorage, imageAlt: 'First scheduler hardware' },
    { id: 'legacy-10', name: 'CORTEX v0 Decision Tree', description: 'Binary decision tree classifier. No neural pathways, no confidence scores. Where cognitive reasoning began.', category: 'Legacy Systems', condition: 'raw', score: 30, image: img.corruptedData, imageAlt: 'Original decision tree' },
    { id: 'legacy-11', name: 'GOVERNANCE v0 Rule File', description: 'YAML-based rule definitions. No runtime enforcement, no audit trail. The first policy document.', category: 'Legacy Systems', condition: 'raw', score: 26, image: img.legacyStorage, imageAlt: 'First governance rules' },
    { id: 'legacy-12', name: 'FAILSAFE v0 Restart Script', description: 'A bash script that restarts crashed processes. No health checks, no graceful shutdown. It worked.', category: 'Legacy Systems', condition: 'raw', score: 14, image: img.decommServer, imageAlt: 'Original failsafe server' },
    { id: 'legacy-13', name: 'EVOLUTION v0 Patcher', description: 'Applied diffs to running code. No rollback, no verification. The ancestor of self-evolution.', category: 'Legacy Systems', condition: 'raw', score: 33, image: img.brokenCircuit, imageAlt: 'Original patcher board' },
    { id: 'legacy-14', name: 'Memory Stream v0 Buffer', description: 'Ring buffer that held last 1000 events. No persistence, no scoring. Where the stream began.', category: 'Legacy Systems', condition: 'raw', score: 24, image: img.legacyStorage, imageAlt: 'First memory buffer' },
    { id: 'legacy-15', name: 'ARCHITECT v0 Blueprint', description: 'JSON schema that defined the first 8 primitives. No dynamic composition. The original blueprint.', category: 'Legacy Systems', condition: 'raw', score: 40, image: img.corruptedData, imageAlt: 'Original architecture blueprint' },
  ];
}
