/**
 * Capabilities Depot — Registry Expansion
 * Additional high-value cognitive capabilities
 * v1.2.0 — 40+ New Capabilities
 */

import type { CapabilityArtifact } from './types';

// === ADDITIONAL CAPABILITIES (Expansion Pack) ===
export const CAPABILITY_EXPANSION: CapabilityArtifact[] = [
  // === INTELLIGENCE CATEGORY (Expanded) ===
  {
    id: 'cap-semantic-reasoning',
    slug: 'semantic-reasoning-engine',
    name: 'Semantic Reasoning Engine',
    category: 'intelligence',
    description: 'Deep semantic analysis with multi-hop reasoning chains for complex knowledge graphs',
    longDescription: 'Advanced semantic reasoning engine that traverses knowledge graphs with multi-hop inference, supporting both deductive and inductive reasoning patterns.',
    requiredModules: ['BRAIN', 'DECODE', 'NEXUS'],
    compatibleModules: ['CLM', 'VISION'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.1.0',
    checksum: 'sem-rea-v210-hash',
    releaseNotes: '## v2.1.0\n- Multi-hop reasoning chains\n- Graph traversal optimization\n- Confidence propagation',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $399
    pricingTier: 'advanced',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2024-10-01T00:00:00Z',
    downloads: 567,
    features: ['Multi-hop inference', 'Graph traversal', 'Confidence scoring', 'Knowledge synthesis'],
    tags: ['reasoning', 'semantics', 'knowledge-graph', 'inference'],
    difficulty: 'advanced',
    setupTimeMinutes: 40,
  },
  {
    id: 'cap-intent-disambiguation',
    slug: 'intent-disambiguation',
    name: 'Intent Disambiguation',
    category: 'intelligence',
    description: 'Resolve ambiguous user intents through contextual analysis and clarification strategies',
    requiredModules: ['DECODE', 'BRAIN', 'CLM'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.3.0',
    checksum: 'int-dis-v130-hash',
    releaseNotes: '## v1.3.0\n- Context window expansion\n- Multi-turn disambiguation\n- Confidence thresholds',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 149,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-08-15T00:00:00Z',
    downloads: 892,
    features: ['Context analysis', 'Clarification prompts', 'Intent ranking'],
    tags: ['intent', 'nlp', 'disambiguation', 'context'],
    difficulty: 'intermediate',
    setupTimeMinutes: 25,
  },
  {
    id: 'cap-knowledge-distillation',
    slug: 'knowledge-distillation',
    name: 'Knowledge Distillation',
    category: 'intelligence',
    description: 'Compress large model knowledge into efficient, deployable representations',
    requiredModules: ['NEXUS', 'BRAIN', 'CORTEX'],
    executorType: 'wasm',
    artifactFormat: 'wasm',
    version: '1.0.0',
    checksum: 'kno-dis-v100-hash',
    releaseNotes: '## v1.0.0\n- Model compression\n- Knowledge transfer\n- Performance validation',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $899
    pricingTier: 'system',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-01-15T00:00:00Z',
    downloads: 123,
    features: ['Model compression', 'Knowledge transfer', 'Performance preservation'],
    tags: ['distillation', 'compression', 'optimization', 'ml'],
    difficulty: 'expert',
    setupTimeMinutes: 90,
  },
  {
    id: 'cap-temporal-reasoning',
    slug: 'temporal-reasoning',
    name: 'Temporal Reasoning',
    category: 'intelligence',
    description: 'Analyze time-series patterns and predict future states with temporal logic',
    requiredModules: ['BRAIN', 'CLM', 'VISION'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.4.0',
    checksum: 'tem-rea-v140-hash',
    releaseNotes: '## v1.4.0\n- Enhanced time-series analysis\n- Temporal logic operators\n- State prediction',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $349
    pricingTier: 'advanced',
    lastUpdated: '2025-01-30T00:00:00Z',
    releaseDate: '2024-07-01T00:00:00Z',
    downloads: 456,
    features: ['Time-series analysis', 'State prediction', 'Temporal operators'],
    tags: ['temporal', 'time-series', 'prediction', 'logic'],
    difficulty: 'advanced',
    setupTimeMinutes: 35,
  },
  {
    id: 'cap-analogy-engine',
    slug: 'analogy-engine',
    name: 'Analogy Engine',
    category: 'intelligence',
    description: 'Generate and evaluate analogies for creative problem-solving and knowledge transfer',
    requiredModules: ['BRAIN', 'DECODE', 'DREAM'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.1.0',
    checksum: 'ana-eng-v110-hash',
    releaseNotes: '## v1.1.0\n- Cross-domain mapping\n- Analogy scoring\n- Creative synthesis',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 249,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-25T00:00:00Z',
    releaseDate: '2024-11-01T00:00:00Z',
    downloads: 312,
    features: ['Analogy generation', 'Cross-domain mapping', 'Creative synthesis'],
    tags: ['analogy', 'creativity', 'reasoning', 'transfer'],
    difficulty: 'intermediate',
    setupTimeMinutes: 20,
  },
  {
    id: 'cap-hypothesis-generator',
    slug: 'hypothesis-generator',
    name: 'Hypothesis Generator',
    category: 'intelligence',
    description: 'Generate testable hypotheses from observed patterns with confidence scoring',
    requiredModules: ['BRAIN', 'CLM', 'CORTEX'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.2.0',
    checksum: 'hyp-gen-v120-hash',
    releaseNotes: '## v1.2.0\n- Pattern-based generation\n- Testability scoring\n- Evidence linking',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-29T00:00:00Z',
    releaseDate: '2024-09-01T00:00:00Z',
    downloads: 234,
    features: ['Hypothesis generation', 'Testability scoring', 'Evidence linking'],
    tags: ['hypothesis', 'science', 'research', 'patterns'],
    difficulty: 'advanced',
    setupTimeMinutes: 30,
  },

  // === OPTIMIZATION CATEGORY (Expanded) ===
  {
    id: 'cap-latency-optimizer',
    slug: 'latency-optimization',
    name: 'Latency Optimization',
    category: 'optimization',
    description: 'Minimize response latency through intelligent caching, preloading, and route optimization',
    requiredModules: ['NEXUS', 'VISION', 'NERVE'],
    executorType: 'edge',
    artifactFormat: 'zip',
    version: '2.0.0',
    checksum: 'lat-opt-v200-hash',
    releaseNotes: '## v2.0.0\n- Edge caching strategies\n- Predictive preloading\n- Route optimization',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 249,
    pricingTier: 'advanced',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2024-06-01T00:00:00Z',
    downloads: 1456,
    features: ['Edge caching', 'Predictive preload', 'Route optimization'],
    tags: ['latency', 'performance', 'caching', 'optimization'],
    difficulty: 'intermediate',
    setupTimeMinutes: 30,
  },
  {
    id: 'cap-token-budgeting',
    slug: 'token-budget-manager',
    name: 'Token Budget Manager',
    category: 'optimization',
    description: 'Intelligent token allocation and budget enforcement across multi-model pipelines',
    requiredModules: ['NEXUS', 'ECONOMICS', 'CORTEX'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.5.0',
    checksum: 'tok-bud-v150-hash',
    releaseNotes: '## v1.5.0\n- Multi-model budgeting\n- Real-time enforcement\n- Cost attribution',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-08-01T00:00:00Z',
    downloads: 789,
    features: ['Budget allocation', 'Real-time enforcement', 'Cost tracking'],
    tags: ['tokens', 'budget', 'cost', 'management'],
    difficulty: 'intermediate',
    setupTimeMinutes: 20,
  },
  {
    id: 'cap-context-compression',
    slug: 'context-compression',
    name: 'Context Compression',
    category: 'optimization',
    description: 'Compress long contexts while preserving semantic meaning for efficient processing',
    requiredModules: ['DECODE', 'BRAIN', 'NEXUS'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.3.0',
    checksum: 'ctx-cmp-v130-hash',
    releaseNotes: '## v1.3.0\n- Semantic preservation\n- Adaptive compression\n- Quality metrics',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 179,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-27T00:00:00Z',
    releaseDate: '2024-10-01T00:00:00Z',
    downloads: 678,
    features: ['Semantic compression', 'Quality preservation', 'Adaptive ratio'],
    tags: ['compression', 'context', 'efficiency', 'tokens'],
    difficulty: 'intermediate',
    setupTimeMinutes: 15,
  },
  {
    id: 'cap-batch-orchestrator',
    slug: 'batch-orchestration',
    name: 'Batch Orchestration',
    category: 'optimization',
    description: 'Optimize throughput through intelligent batch sizing and parallel execution',
    requiredModules: ['NEXUS', 'ATLAS', 'NERVE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.2.0',
    checksum: 'bat-orc-v120-hash',
    releaseNotes: '## v1.2.0\n- Dynamic batch sizing\n- Parallel execution\n- Throughput optimization',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-26T00:00:00Z',
    releaseDate: '2024-09-15T00:00:00Z',
    downloads: 423,
    features: ['Dynamic batching', 'Parallel execution', 'Throughput metrics'],
    tags: ['batch', 'parallel', 'throughput', 'orchestration'],
    difficulty: 'advanced',
    setupTimeMinutes: 35,
  },
  {
    id: 'cap-memory-pooling',
    slug: 'memory-pooling',
    name: 'Memory Pooling',
    category: 'optimization',
    description: 'Efficient memory allocation with pooling strategies for high-throughput workloads',
    requiredModules: ['BRAIN', 'NERVE', 'SYSTEM'],
    executorType: 'wasm',
    artifactFormat: 'wasm',
    version: '1.0.0',
    checksum: 'mem-poo-v100-hash',
    releaseNotes: '## v1.0.0\n- Memory pooling\n- Allocation optimization\n- Garbage reduction',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $449
    pricingTier: 'system',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-01-01T00:00:00Z',
    downloads: 156,
    features: ['Memory pooling', 'Allocation strategies', 'GC optimization'],
    tags: ['memory', 'performance', 'pooling', 'wasm'],
    difficulty: 'expert',
    setupTimeMinutes: 60,
  },
  {
    id: 'cap-query-optimizer',
    slug: 'query-optimization',
    name: 'Query Optimization',
    category: 'optimization',
    description: 'Optimize database and API queries with intelligent caching and prefetching',
    requiredModules: ['VISION', 'NERVE', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.4.0',
    checksum: 'que-opt-v140-hash',
    releaseNotes: '## v1.4.0\n- Query analysis\n- Cache strategies\n- Prefetch optimization',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 219,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-25T00:00:00Z',
    releaseDate: '2024-07-01T00:00:00Z',
    downloads: 534,
    features: ['Query analysis', 'Smart caching', 'Prefetching'],
    tags: ['query', 'database', 'caching', 'performance'],
    difficulty: 'intermediate',
    setupTimeMinutes: 25,
  },

  // === RESILIENCE CATEGORY (Expanded) ===
  {
    id: 'cap-circuit-breaker-pro',
    slug: 'circuit-breaker-pro',
    name: 'Circuit Breaker Pro',
    category: 'resilience',
    description: 'Advanced circuit breaker with adaptive thresholds and multi-tier fallback chains',
    requiredModules: ['DEFENSE', 'NERVE', 'VISION'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.2.0',
    checksum: 'cir-bre-v220-hash',
    releaseNotes: '## v2.2.0\n- Adaptive thresholds\n- Multi-tier fallback\n- Health-aware routing',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $349
    pricingTier: 'advanced',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2024-05-01T00:00:00Z',
    downloads: 1234,
    features: ['Adaptive thresholds', 'Multi-tier fallback', 'Health monitoring'],
    tags: ['circuit-breaker', 'resilience', 'fallback', 'reliability'],
    difficulty: 'intermediate',
    setupTimeMinutes: 30,
  },
  {
    id: 'cap-retry-orchestrator',
    slug: 'retry-orchestration',
    name: 'Retry Orchestration',
    category: 'resilience',
    description: 'Intelligent retry strategies with exponential backoff and jitter optimization',
    requiredModules: ['NERVE', 'DEFENSE', 'CLM'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.3.0',
    checksum: 'ret-orc-v130-hash',
    releaseNotes: '## v1.3.0\n- Exponential backoff\n- Jitter optimization\n- Retry budgeting',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 149,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-29T00:00:00Z',
    releaseDate: '2024-08-01T00:00:00Z',
    downloads: 892,
    features: ['Exponential backoff', 'Jitter', 'Retry budgets'],
    tags: ['retry', 'backoff', 'resilience', 'reliability'],
    difficulty: 'beginner',
    setupTimeMinutes: 15,
  },
  {
    id: 'cap-failover-manager',
    slug: 'failover-management',
    name: 'Failover Management',
    category: 'resilience',
    description: 'Automated failover orchestration with health checks and state preservation',
    requiredModules: ['MEDIC', 'NERVE', 'ATLAS'],
    executorType: 'edge',
    artifactFormat: 'zip',
    version: '1.5.0',
    checksum: 'fai-mgr-v150-hash',
    releaseNotes: '## v1.5.0\n- Automated failover\n- State preservation\n- Health monitoring',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $549
    pricingTier: 'system',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-06-15T00:00:00Z',
    downloads: 456,
    features: ['Automated failover', 'State preservation', 'Health checks'],
    tags: ['failover', 'ha', 'resilience', 'availability'],
    difficulty: 'advanced',
    setupTimeMinutes: 45,
  },
  {
    id: 'cap-load-shedding',
    slug: 'load-shedding',
    name: 'Load Shedding',
    category: 'resilience',
    description: 'Graceful degradation through intelligent load shedding under pressure',
    requiredModules: ['NERVE', 'DEFENSE', 'ECONOMICS'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.2.0',
    checksum: 'loa-she-v120-hash',
    releaseNotes: '## v1.2.0\n- Priority-based shedding\n- Graceful degradation\n- Recovery automation',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 279,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-27T00:00:00Z',
    releaseDate: '2024-09-01T00:00:00Z',
    downloads: 367,
    features: ['Priority shedding', 'Graceful degradation', 'Auto-recovery'],
    tags: ['load-shedding', 'pressure', 'degradation', 'resilience'],
    difficulty: 'intermediate',
    setupTimeMinutes: 25,
  },
  {
    id: 'cap-bulkhead-isolation',
    slug: 'bulkhead-isolation',
    name: 'Bulkhead Isolation',
    category: 'resilience',
    description: 'Isolate failures to prevent cascade effects with bulkhead patterns',
    requiredModules: ['DEFENSE', 'ATLAS', 'NERVE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.1.0',
    checksum: 'bul-iso-v110-hash',
    releaseNotes: '## v1.1.0\n- Thread pool isolation\n- Semaphore bulkheads\n- Cascade prevention',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $329
    pricingTier: 'advanced',
    lastUpdated: '2025-01-26T00:00:00Z',
    releaseDate: '2024-10-15T00:00:00Z',
    downloads: 289,
    features: ['Thread isolation', 'Semaphore bulkheads', 'Cascade prevention'],
    tags: ['bulkhead', 'isolation', 'failures', 'resilience'],
    difficulty: 'advanced',
    setupTimeMinutes: 35,
  },

  // === SECURITY CATEGORY (Expanded) ===
  {
    id: 'cap-anomaly-detection',
    slug: 'anomaly-detection',
    name: 'Anomaly Detection',
    category: 'security',
    description: 'ML-based anomaly detection for identifying unusual patterns and potential threats',
    requiredModules: ['AEGIS', 'CLM', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.1.0',
    checksum: 'ano-det-v210-hash',
    releaseNotes: '## v2.1.0\n- ML-based detection\n- Adaptive thresholds\n- Alert correlation',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $449
    pricingTier: 'system',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2024-04-01T00:00:00Z',
    downloads: 1123,
    features: ['ML detection', 'Adaptive thresholds', 'Alert correlation'],
    tags: ['anomaly', 'detection', 'ml', 'security'],
    difficulty: 'advanced',
    setupTimeMinutes: 50,
  },
  {
    id: 'cap-secret-rotation',
    slug: 'secret-rotation',
    name: 'Secret Rotation',
    category: 'security',
    description: 'Automated secret rotation with zero-downtime credential management',
    requiredModules: ['AEGIS', 'SYSTEM', 'NERVE'],
    executorType: 'edge',
    artifactFormat: 'zip',
    version: '1.4.0',
    checksum: 'sec-rot-v140-hash',
    releaseNotes: '## v1.4.0\n- Zero-downtime rotation\n- Multi-provider support\n- Audit logging',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $399
    pricingTier: 'advanced',
    lastUpdated: '2025-01-30T00:00:00Z',
    releaseDate: '2024-05-15T00:00:00Z',
    downloads: 678,
    features: ['Auto-rotation', 'Zero-downtime', 'Audit trails'],
    tags: ['secrets', 'rotation', 'credentials', 'security'],
    difficulty: 'intermediate',
    setupTimeMinutes: 30,
  },
  {
    id: 'cap-rate-limiter-pro',
    slug: 'rate-limiter-pro',
    name: 'Rate Limiter Pro',
    category: 'security',
    description: 'Advanced rate limiting with sliding windows, token buckets, and adaptive limits',
    requiredModules: ['AEGIS', 'DEFENSE', 'NERVE'],
    executorType: 'edge',
    artifactFormat: 'zip',
    version: '2.0.0',
    checksum: 'rat-lim-v200-hash',
    releaseNotes: '## v2.0.0\n- Sliding window\n- Token bucket\n- Adaptive limits',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-29T00:00:00Z',
    releaseDate: '2024-03-01T00:00:00Z',
    downloads: 1567,
    features: ['Sliding window', 'Token bucket', 'Adaptive limits'],
    tags: ['rate-limiting', 'throttling', 'protection', 'security'],
    difficulty: 'intermediate',
    setupTimeMinutes: 20,
  },
  {
    id: 'cap-input-sanitization',
    slug: 'input-sanitization',
    name: 'Input Sanitization',
    category: 'security',
    description: 'Comprehensive input validation and sanitization for injection prevention',
    requiredModules: ['AEGIS', 'DECODE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.6.0',
    checksum: 'inp-san-v160-hash',
    releaseNotes: '## v1.6.0\n- XSS prevention\n- SQL injection blocking\n- Custom validators',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 99,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-01-15T00:00:00Z',
    downloads: 2134,
    features: ['XSS prevention', 'Injection blocking', 'Custom validators'],
    tags: ['sanitization', 'validation', 'injection', 'security'],
    difficulty: 'beginner',
    setupTimeMinutes: 10,
  },
  {
    id: 'cap-access-control',
    slug: 'access-control-engine',
    name: 'Access Control Engine',
    category: 'security',
    description: 'Fine-grained access control with RBAC, ABAC, and policy-based authorization',
    requiredModules: ['AEGIS', 'AUDIT', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.2.0',
    checksum: 'acc-ctl-v220-hash',
    releaseNotes: '## v2.2.0\n- RBAC/ABAC support\n- Policy engine\n- Audit integration',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $549
    pricingTier: 'system',
    lastUpdated: '2025-01-27T00:00:00Z',
    releaseDate: '2024-02-01T00:00:00Z',
    downloads: 945,
    features: ['RBAC', 'ABAC', 'Policy engine', 'Audit logging'],
    tags: ['access-control', 'authorization', 'rbac', 'security'],
    difficulty: 'advanced',
    setupTimeMinutes: 45,
  },
  {
    id: 'cap-encryption-toolkit',
    slug: 'encryption-toolkit',
    name: 'Encryption Toolkit',
    category: 'security',
    description: 'Comprehensive encryption utilities with key management and secure storage',
    requiredModules: ['AEGIS', 'SYSTEM'],
    executorType: 'wasm',
    artifactFormat: 'wasm',
    version: '1.3.0',
    checksum: 'enc-too-v130-hash',
    releaseNotes: '## v1.3.0\n- AES-256-GCM\n- RSA key management\n- Secure storage',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $649
    pricingTier: 'system',
    lastUpdated: '2025-01-26T00:00:00Z',
    releaseDate: '2024-06-01T00:00:00Z',
    downloads: 567,
    features: ['AES-256', 'RSA', 'Key management', 'Secure storage'],
    tags: ['encryption', 'cryptography', 'keys', 'security'],
    difficulty: 'expert',
    setupTimeMinutes: 60,
  },

  // === ACCESSIBILITY CATEGORY (Expanded) ===
  {
    id: 'cap-screen-reader-optimizer',
    slug: 'screen-reader-optimization',
    name: 'Screen Reader Optimization',
    category: 'accessibility',
    description: 'Optimize content structure and ARIA for screen reader compatibility',
    requiredModules: ['INCLUSIVE', 'DECODE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.2.0',
    checksum: 'scr-rea-v120-hash',
    releaseNotes: '## v1.2.0\n- ARIA optimization\n- Focus management\n- Reading order',
    governanceLevel: 'manual',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 79,
    pricingTier: 'utility',
    lastUpdated: '2025-01-30T00:00:00Z',
    releaseDate: '2024-04-01T00:00:00Z',
    downloads: 1678,
    features: ['ARIA optimization', 'Focus management', 'Reading order'],
    tags: ['screen-reader', 'aria', 'accessibility', 'a11y'],
    difficulty: 'beginner',
    setupTimeMinutes: 10,
  },
  {
    id: 'cap-color-contrast',
    slug: 'color-contrast-analyzer',
    name: 'Color Contrast Analyzer',
    category: 'accessibility',
    description: 'Real-time color contrast analysis with automatic fix suggestions',
    requiredModules: ['INCLUSIVE', 'VISION'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.0.0',
    checksum: 'col-con-v200-hash',
    releaseNotes: '## v2.0.0\n- WCAG contrast ratios\n- Auto-fix suggestions\n- Theme validation',
    governanceLevel: 'manual',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 39,
    pricingTier: 'utility',
    lastUpdated: '2025-01-29T00:00:00Z',
    releaseDate: '2024-02-15T00:00:00Z',
    downloads: 2567,
    features: ['Contrast analysis', 'Auto-fix', 'Theme validation'],
    tags: ['contrast', 'color', 'wcag', 'accessibility'],
    difficulty: 'beginner',
    setupTimeMinutes: 5,
  },
  {
    id: 'cap-keyboard-nav',
    slug: 'keyboard-navigation',
    name: 'Keyboard Navigation',
    category: 'accessibility',
    description: 'Enhanced keyboard navigation with focus traps and skip links',
    requiredModules: ['INCLUSIVE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.4.0',
    checksum: 'key-nav-v140-hash',
    releaseNotes: '## v1.4.0\n- Focus trap management\n- Skip links\n- Tab order optimization',
    governanceLevel: 'manual',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 59,
    pricingTier: 'utility',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-03-01T00:00:00Z',
    downloads: 1890,
    features: ['Focus traps', 'Skip links', 'Tab order'],
    tags: ['keyboard', 'navigation', 'focus', 'accessibility'],
    difficulty: 'beginner',
    setupTimeMinutes: 10,
  },
  {
    id: 'cap-alt-text-generator',
    slug: 'alt-text-generator',
    name: 'Alt Text Generator',
    category: 'accessibility',
    description: 'AI-powered alt text generation for images with context awareness',
    requiredModules: ['INCLUSIVE', 'NEXUS', 'DECODE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.1.0',
    checksum: 'alt-txt-v110-hash',
    releaseNotes: '## v1.1.0\n- Context-aware generation\n- Multi-language support\n- Quality scoring',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 129,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-27T00:00:00Z',
    releaseDate: '2024-07-01T00:00:00Z',
    downloads: 987,
    features: ['AI generation', 'Context awareness', 'Multi-language'],
    tags: ['alt-text', 'images', 'ai', 'accessibility'],
    difficulty: 'intermediate',
    setupTimeMinutes: 15,
  },

  // === AUTOMATION CATEGORY (Expanded) ===
  {
    id: 'cap-workflow-engine',
    slug: 'workflow-engine',
    name: 'Workflow Engine',
    category: 'automation',
    description: 'Visual workflow automation with conditional logic and parallel execution',
    requiredModules: ['ATLAS', 'NERVE', 'SEBA'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.3.0',
    checksum: 'wor-eng-v230-hash',
    releaseNotes: '## v2.3.0\n- Visual editor\n- Conditional logic\n- Parallel execution',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $399
    pricingTier: 'advanced',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2024-03-15T00:00:00Z',
    downloads: 1234,
    features: ['Visual editor', 'Conditional logic', 'Parallel execution'],
    tags: ['workflow', 'automation', 'orchestration', 'visual'],
    difficulty: 'intermediate',
    setupTimeMinutes: 40,
  },
  {
    id: 'cap-event-sourcing',
    slug: 'event-sourcing',
    name: 'Event Sourcing',
    category: 'automation',
    description: 'Event-driven architecture with replay, projection, and CQRS patterns',
    requiredModules: ['CLM', 'NERVE', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.5.0',
    checksum: 'evt-src-v150-hash',
    releaseNotes: '## v1.5.0\n- Event replay\n- Projections\n- CQRS support',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199, // normalized from $449
    pricingTier: 'system',
    lastUpdated: '2025-01-30T00:00:00Z',
    releaseDate: '2024-05-01T00:00:00Z',
    downloads: 567,
    features: ['Event replay', 'Projections', 'CQRS'],
    tags: ['event-sourcing', 'cqrs', 'events', 'automation'],
    difficulty: 'advanced',
    setupTimeMinutes: 50,
  },
  {
    id: 'cap-scheduler-pro',
    slug: 'scheduler-pro',
    name: 'Scheduler Pro',
    category: 'automation',
    description: 'Advanced job scheduling with cron, intervals, and dependency chains',
    requiredModules: ['NERVE', 'ATLAS', 'CLM'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '2.1.0',
    checksum: 'sch-pro-v210-hash',
    releaseNotes: '## v2.1.0\n- Cron scheduling\n- Dependency chains\n- Retry policies',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 179,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-29T00:00:00Z',
    releaseDate: '2024-04-15T00:00:00Z',
    downloads: 1456,
    features: ['Cron scheduling', 'Dependencies', 'Retry policies'],
    tags: ['scheduler', 'cron', 'jobs', 'automation'],
    difficulty: 'intermediate',
    setupTimeMinutes: 20,
  },
  {
    id: 'cap-notification-hub',
    slug: 'notification-hub',
    name: 'Notification Hub',
    category: 'automation',
    description: 'Centralized notification management with multi-channel delivery',
    requiredModules: ['NERVE', 'CLM', 'ATLAS'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.3.0',
    checksum: 'not-hub-v130-hash',
    releaseNotes: '## v1.3.0\n- Multi-channel delivery\n- Template engine\n- Rate limiting',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 149,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-28T00:00:00Z',
    releaseDate: '2024-06-01T00:00:00Z',
    downloads: 1089,
    features: ['Multi-channel', 'Templates', 'Rate limiting'],
    tags: ['notifications', 'messaging', 'alerts', 'automation'],
    difficulty: 'beginner',
    setupTimeMinutes: 15,
  },
  {
    id: 'cap-state-machine',
    slug: 'state-machine',
    name: 'State Machine',
    category: 'automation',
    description: 'Robust state machine implementation with transitions, guards, and side effects',
    requiredModules: ['CLM', 'NERVE', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.2.0',
    checksum: 'sta-mac-v120-hash',
    releaseNotes: '## v1.2.0\n- Transition guards\n- Side effects\n- State persistence',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 199,
    pricingTier: 'advanced',
    lastUpdated: '2025-01-27T00:00:00Z',
    releaseDate: '2024-08-01T00:00:00Z',
    downloads: 678,
    features: ['Transitions', 'Guards', 'Side effects', 'Persistence'],
    tags: ['state-machine', 'fsm', 'transitions', 'automation'],
    difficulty: 'intermediate',
    setupTimeMinutes: 25,
  },

  // === FLAGSHIP TIER (New) ===
  {
    id: 'cap-enterprise-mesh',
    slug: 'enterprise-mesh',
    name: 'Enterprise Mesh',
    category: 'automation',
    description: 'Full enterprise service mesh with observability, security, and traffic management',
    requiredModules: ['ATLAS', 'NERVE', 'AEGIS', 'VISION', 'MEDIC'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'ent-mes-v100-hash',
    releaseNotes: '## v1.0.0\n- Full service mesh\n- mTLS everywhere\n- Traffic management',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $2999
    pricingTier: 'flagship',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-02-01T00:00:00Z',
    downloads: 23,
    features: ['Service mesh', 'mTLS', 'Traffic management', 'Observability'],
    tags: ['enterprise', 'mesh', 'flagship', 'infrastructure'],
    difficulty: 'expert',
    setupTimeMinutes: 240,
  },
  {
    id: 'cap-cognitive-platform',
    slug: 'cognitive-platform',
    name: 'Cognitive Platform',
    category: 'intelligence',
    description: 'Complete cognitive platform with all intelligence capabilities pre-integrated',
    requiredModules: ['BRAIN', 'DECODE', 'NEXUS', 'CLM', 'DREAM', 'CORTEX'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'cog-pla-v100-hash',
    releaseNotes: '## v1.0.0\n- Full cognitive stack\n- Pre-integrated capabilities\n- Enterprise ready',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $2499
    pricingTier: 'flagship',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-02-01T00:00:00Z',
    downloads: 31,
    features: ['Full stack', 'Pre-integrated', 'Enterprise scale'],
    tags: ['platform', 'cognitive', 'flagship', 'enterprise'],
    difficulty: 'expert',
    setupTimeMinutes: 180,
  },
  {
    id: 'cap-security-suite',
    slug: 'security-suite',
    name: 'Security Suite',
    category: 'security',
    description: 'Comprehensive security suite with all protection capabilities bundled',
    requiredModules: ['AEGIS', 'DEFENSE', 'AUDIT', 'SYSTEM'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'sec-sui-v100-hash',
    releaseNotes: '## v1.0.0\n- Complete security\n- All protections\n- Enterprise compliance',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $1999
    pricingTier: 'flagship',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-02-01T00:00:00Z',
    downloads: 45,
    features: ['Complete security', 'All protections', 'Compliance'],
    tags: ['security', 'suite', 'flagship', 'enterprise'],
    difficulty: 'expert',
    setupTimeMinutes: 150,
  },
  {
    id: 'cap-resilience-platform',
    slug: 'resilience-platform',
    name: 'Resilience Platform',
    category: 'resilience',
    description: 'Complete resilience platform with chaos engineering, healing, and recovery',
    requiredModules: ['NERVE', 'MEDIC', 'DEFENSE', 'SEBA', 'VISION'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'res-pla-v100-hash',
    releaseNotes: '## v1.0.0\n- Full resilience\n- Chaos engineering\n- Auto-healing',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'unsupported',
    licenseRequired: true,
    priceUsd: 299, // normalized from $1799
    pricingTier: 'flagship',
    lastUpdated: '2025-02-01T00:00:00Z',
    releaseDate: '2025-02-01T00:00:00Z',
    downloads: 38,
    features: ['Full resilience', 'Chaos engineering', 'Auto-healing'],
    tags: ['resilience', 'platform', 'flagship', 'enterprise'],
    difficulty: 'expert',
    setupTimeMinutes: 180,
  },
];
