/**
 * S-Tier Capabilities — Registry
 * 22 Premium S-tier capabilities for the Capabilities Depot
 * Self-improvement capabilities ranked highest
 *
 */

import type { CapabilityArtifact } from './types';
import { STIER_STRIPE_CONFIG } from './stripe-stier';

/**
 * S-Tier Capability Registry
 * Ordered by value tier (self-improvement first)
 */
export const STIER_CAPABILITIES: CapabilityArtifact[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 🔥 SELF-IMPROVEMENT TIER (Crown-Class - $3,499 to $4,999)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-intelligence-governance-kernel',
    slug: 'intelligence-governance-kernel',
    name: 'Intelligence Governance Kernel',
    category: 'intelligence',
    description: 'Crown-class: Governs all intelligence behavior globally with autonomous evolution',
    longDescription: 'The ultimate self-improvement capability. This crown-class kernel provides complete governance over all intelligent systems, enabling autonomous evolution, self-optimization, and global behavioral coordination. Designed for boards, regulators, and enterprise AI governance teams.',
    requiredModules: ['CORTEX', 'DEFENSE', 'VISION', 'SYSTEM'],
    compatibleModules: ['BRAIN', 'ATLAS', 'DREAM'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'stier-igk-001-hash',
    releaseNotes: '## v1.0.0 — Crown-Class Release\n- Global intelligence governance\n- Autonomous evolution control\n- Self-optimization protocols\n- Behavioral coordination',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-intelligence-governance-kernel'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 12,
    features: ['Global governance', 'Autonomous evolution', 'Self-optimization', 'Behavioral coordination', 'Regulatory compliance'],
    tags: ['crown-class', 'self-improvement', 'governance', 'autonomous', 'enterprise'],
    difficulty: 'expert',
    setupTimeMinutes: 240,
    buyerPersona: 'Boards, Regulators, Enterprise AI Governance',
    salesPitch: 'Who controls the AI?',
  },
  {
    id: 'stier-self-scaling-intelligence-fabric',
    slug: 'self-scaling-intelligence-fabric',
    name: 'Self-Scaling Intelligence Fabric',
    category: 'intelligence',
    description: 'Self-improvement: Intelligence scales itself under load with autonomous capacity expansion',
    longDescription: 'An autonomous self-improvement system that scales cognitive capacity based on demand. The fabric automatically expands and contracts intelligence resources, learning from load patterns to optimize future scaling decisions. True cognitive elasticity.',
    requiredModules: ['SYSTEM', 'VISION', 'CORTEX', 'RIPPLE'],
    compatibleModules: ['NEXUS', 'BRAIN'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'stier-ssif-001-hash',
    releaseNotes: '## v1.0.0\n- Autonomous scaling protocols\n- Load pattern learning\n- Cognitive elasticity\n- Resource optimization',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-self-scaling-intelligence-fabric'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 18,
    features: ['Autonomous scaling', 'Load learning', 'Cognitive elasticity', 'Resource optimization', 'Capacity prediction'],
    tags: ['self-improvement', 'scaling', 'autonomous', 'fabric', 'enterprise'],
    difficulty: 'expert',
    setupTimeMinutes: 180,
    buyerPersona: 'Enterprise Infrastructure, Platform Teams',
    salesPitch: 'Scale cognition, not just servers.',
  },
  {
    id: 'stier-autonomous-ops-steward',
    slug: 'autonomous-ops-steward',
    name: 'Autonomous Ops Steward',
    category: 'automation',
    description: 'Self-improvement: Fully self-maintaining infrastructure with autonomous optimization',
    longDescription: 'A self-improving operations system that autonomously maintains, optimizes, and evolves infrastructure. Combines real-time monitoring with predictive maintenance and self-healing capabilities. Fire half the ops tickets.',
    requiredModules: ['SYSTEM', 'CORTEX', 'VISION', 'EVOLUTION'],
    compatibleModules: ['DEFENSE', 'MEDIC'],
    executorType: 'container',
    artifactFormat: 'container',
    version: '1.0.0',
    checksum: 'stier-aos-001-hash',
    releaseNotes: '## v1.0.0\n- Fully autonomous operations\n- Self-maintaining infrastructure\n- Predictive optimization\n- Guardrailed autonomy',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-autonomous-ops-steward'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 24,
    features: ['Self-maintenance', 'Autonomous optimization', 'Predictive ops', 'Guardrailed autonomy', 'Incident prevention'],
    tags: ['self-improvement', 'autonomous', 'operations', 'infrastructure', 'sre'],
    difficulty: 'expert',
    setupTimeMinutes: 150,
    buyerPersona: 'CTO, SRE, DevOps Leaders',
    salesPitch: 'Fire half the ops tickets.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🧠 INTELLIGENCE × CONTROL ($999 - $1,999)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-strategic-foresight-engine',
    slug: 'strategic-foresight-engine',
    name: 'Strategic Foresight Engine',
    category: 'intelligence',
    description: 'Long-horizon scenario forecasting with confidence weighting for CTOs and Strategy teams',
    longDescription: 'Advanced strategic foresight system combining VISION analytics, DREAM pattern recognition, BRAIN memory, and CORTEX reasoning. Provides long-horizon scenario forecasting with calibrated confidence intervals.',
    requiredModules: ['VISION', 'DREAM', 'BRAIN', 'CORTEX'],
    compatibleModules: ['SYSTEM', 'RIPPLE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-sfe-001-hash',
    releaseNotes: '## v1.0.0\n- Scenario forecasting\n- Confidence weighting\n- Multi-horizon analysis\n- Strategic recommendations',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-strategic-foresight-engine'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 67,
    features: ['Scenario forecasting', 'Confidence weighting', 'Multi-horizon analysis', 'Strategic insights'],
    tags: ['strategy', 'forecasting', 'intelligence', 'enterprise'],
    difficulty: 'advanced',
    setupTimeMinutes: 60,
    buyerPersona: 'CTO, Strategy, Defense',
    salesPitch: 'Tell me what breaks next quarter.',
  },
  {
    id: 'stier-explainable-intelligence-compiler',
    slug: 'explainable-intelligence-compiler',
    name: 'Explainable Intelligence Compiler',
    category: 'intelligence',
    description: 'Turns deep reasoning into exec-ready explanations for boards and compliance',
    longDescription: 'Translates complex AI reasoning chains into clear, executive-ready explanations. Combines DECODE interpretation, CORTEX reasoning traces, BRAIN context, and SYSTEM diagnostics for complete transparency.',
    requiredModules: ['DECODE', 'CORTEX', 'BRAIN', 'SYSTEM'],
    compatibleModules: ['VISION', 'AUDIT'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-eic-001-hash',
    releaseNotes: '## v1.0.0\n- Deep reasoning translation\n- Executive summaries\n- Audit-grade explanations\n- Compliance documentation',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-explainable-intelligence-compiler'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 89,
    features: ['Reasoning translation', 'Executive summaries', 'Audit documentation', 'Compliance reports'],
    tags: ['explainability', 'xai', 'compliance', 'enterprise'],
    difficulty: 'intermediate',
    setupTimeMinutes: 45,
    buyerPersona: 'Executives, Compliance, Board',
    salesPitch: 'I need to explain this to the board.',
  },
  {
    id: 'stier-decision-confidence-governor',
    slug: 'decision-confidence-governor',
    name: 'Decision Confidence Governor',
    category: 'intelligence',
    description: 'Blocks high-impact decisions unless confidence is justified for enterprise AI governance',
    longDescription: 'Governance layer that evaluates decision confidence before allowing high-impact actions. Integrates CORTEX reasoning assessment, VISION performance metrics, and BRAIN historical context to prevent reckless AI decisions.',
    requiredModules: ['CORTEX', 'VISION', 'BRAIN'],
    compatibleModules: ['DEFENSE', 'AUDIT'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-dcg-001-hash',
    releaseNotes: '## v1.0.0\n- Confidence gating\n- Impact assessment\n- Decision blocking\n- Override protocols',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-decision-confidence-governor'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 112,
    features: ['Confidence gating', 'Impact assessment', 'Decision blocking', 'Override protocols'],
    tags: ['governance', 'confidence', 'decisions', 'enterprise'],
    difficulty: 'intermediate',
    setupTimeMinutes: 30,
    buyerPersona: 'Enterprise AI Governance',
    salesPitch: 'No reckless AI decisions.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🔐 SECURITY × TRUST ($999 - $1,999)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-intelligence-containment-engine',
    slug: 'intelligence-containment-engine',
    name: 'Intelligence Containment Engine',
    category: 'security',
    description: 'Prevents learned IP leakage through outputs for enterprise legal protection',
    longDescription: 'Advanced containment system that prevents learned intellectual property from leaking through AI outputs. Combines DEFENSE barriers, BRAIN memory isolation, DECODE output analysis, and SYSTEM monitoring.',
    requiredModules: ['DEFENSE', 'BRAIN', 'DECODE', 'SYSTEM'],
    compatibleModules: ['AUDIT', 'AEGIS'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-ice-001-hash',
    releaseNotes: '## v1.0.0\n- IP leakage prevention\n- Output filtering\n- Memory isolation\n- Containment protocols',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-intelligence-containment-engine'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 45,
    features: ['IP protection', 'Output filtering', 'Memory isolation', 'Containment barriers'],
    tags: ['security', 'ip-protection', 'containment', 'enterprise'],
    difficulty: 'advanced',
    setupTimeMinutes: 90,
    buyerPersona: 'Enterprise Legal, CISO',
    salesPitch: 'Our data never leaves.',
  },
  {
    id: 'stier-emergent-threat-anticipator',
    slug: 'emergent-threat-anticipator',
    name: 'Emergent Threat Anticipator',
    category: 'security',
    description: 'Pre-zero-day defense: Predicts new attack classes before signatures exist',
    longDescription: 'Predictive security system that identifies emerging threat patterns before they crystallize into known attack vectors. Combines VISION pattern analysis, DREAM scenario generation, DEFENSE intelligence, and BRAIN threat memory.',
    requiredModules: ['VISION', 'DREAM', 'DEFENSE', 'BRAIN'],
    compatibleModules: ['AEGIS', 'CORTEX'],
    executorType: 'edge',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-eta-001-hash',
    releaseNotes: '## v1.0.0\n- Pre-zero-day detection\n- Threat pattern prediction\n- Attack class anticipation\n- Proactive defense',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-emergent-threat-anticipator'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 78,
    features: ['Zero-day prediction', 'Threat anticipation', 'Pattern recognition', 'Proactive defense'],
    tags: ['security', 'threats', 'prediction', 'zero-day'],
    difficulty: 'expert',
    setupTimeMinutes: 120,
    buyerPersona: 'Security, CISO',
    salesPitch: 'Pre-zero-day defense.',
  },
  {
    id: 'stier-behavioral-trust-scoring',
    slug: 'behavioral-trust-scoring',
    name: 'Behavioral Trust Scoring',
    category: 'security',
    description: 'Scores system trustworthiness over time for regulated industries',
    longDescription: 'Continuous trust assessment system that scores AI behavior against established baselines. Uses VISION monitoring, BRAIN historical patterns, and ACCESS controls to provide real-time trustworthiness metrics.',
    requiredModules: ['VISION', 'BRAIN', 'ACCESS'],
    compatibleModules: ['AUDIT', 'DEFENSE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-bts-001-hash',
    releaseNotes: '## v1.0.0\n- Continuous trust assessment\n- Behavioral baselines\n- Drift detection\n- Trust metrics',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-behavioral-trust-scoring'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 134,
    features: ['Trust scoring', 'Behavioral analysis', 'Drift detection', 'Compliance metrics'],
    tags: ['trust', 'behavioral', 'compliance', 'regulated'],
    difficulty: 'intermediate',
    setupTimeMinutes: 45,
    buyerPersona: 'Regulated Industries, Compliance',
    salesPitch: 'Can we trust it today?',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ⚙️ AUTONOMY × OPERATIONS ($999 - $1,499)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-autonomy-rollback-authority',
    slug: 'autonomy-rollback-authority',
    name: 'Autonomy Rollback Authority',
    category: 'automation',
    description: 'Kill switch with receipts: One-command rollback of autonomous behavior',
    longDescription: 'Emergency rollback system that can instantly revert autonomous behavior changes with complete audit trails. Integrates CORTEX decision tracking, DEFENSE barriers, RIPPLE propagation control, and SYSTEM state management.',
    requiredModules: ['CORTEX', 'DEFENSE', 'RIPPLE', 'SYSTEM'],
    compatibleModules: ['AUDIT', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-ara-001-hash',
    releaseNotes: '## v1.0.0\n- Instant rollback\n- Complete audit trails\n- State recovery\n- Kill switch protocols',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-autonomy-rollback-authority'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 56,
    features: ['Instant rollback', 'Audit trails', 'State recovery', 'Kill switch'],
    tags: ['autonomy', 'rollback', 'safety', 'governance'],
    difficulty: 'advanced',
    setupTimeMinutes: 60,
    buyerPersona: 'CISO, Legal, Risk',
    salesPitch: 'Kill switch with receipts.',
  },
  {
    id: 'stier-autonomy-budget-manager',
    slug: 'autonomy-budget-manager',
    name: 'Autonomy Budget Manager',
    category: 'automation',
    description: 'Limits how much autonomy a system can spend per day for risk and compliance teams',
    longDescription: 'Autonomy governance system that enforces budgets on autonomous actions. Combines ACCESS controls, CORTEX decision tracking, VISION monitoring, and DEFENSE limits to ensure autonomy stays within bounds.',
    requiredModules: ['ACCESS', 'CORTEX', 'VISION', 'DEFENSE'],
    compatibleModules: ['AUDIT', 'ECONOMICS'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-abm-001-hash',
    releaseNotes: '## v1.0.0\n- Autonomy budgeting\n- Action limits\n- Budget enforcement\n- Compliance tracking',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-autonomy-budget-manager'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 98,
    features: ['Autonomy budgets', 'Action limits', 'Enforcement', 'Usage tracking'],
    tags: ['autonomy', 'budgeting', 'governance', 'compliance'],
    difficulty: 'intermediate',
    setupTimeMinutes: 40,
    buyerPersona: 'Risk, Compliance',
    salesPitch: 'Autonomy isn\'t free.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 💸 COST × PERFORMANCE ($499 - $1,499)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-autonomous-cost-arbitrage-engine',
    slug: 'autonomous-cost-arbitrage-engine',
    name: 'Autonomous Cost Arbitrage Engine',
    category: 'optimization',
    description: 'AI that saves money by itself: Dynamically exploits price/performance gaps',
    longDescription: 'Self-optimizing cost engine that continuously identifies and exploits price/performance opportunities. Combines NEXUS provider routing, ACCESS cost controls, VISION performance metrics, and CORTEX decision making.',
    requiredModules: ['NEXUS', 'ACCESS', 'VISION', 'CORTEX'],
    compatibleModules: ['ECONOMICS', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-acae-001-hash',
    releaseNotes: '## v1.0.0\n- Cost arbitrage\n- Price/performance optimization\n- Dynamic routing\n- Savings tracking',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-autonomous-cost-arbitrage-engine'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 156,
    features: ['Cost arbitrage', 'Price optimization', 'Dynamic routing', 'ROI tracking'],
    tags: ['cost', 'optimization', 'arbitrage', 'finops'],
    difficulty: 'intermediate',
    setupTimeMinutes: 35,
    buyerPersona: 'CFO, FinOps',
    salesPitch: 'AI that saves money by itself.',
  },
  {
    id: 'stier-value-weighted-reasoning-router',
    slug: 'value-weighted-reasoning-router',
    name: 'Value-Weighted Reasoning Router',
    category: 'optimization',
    description: 'Routes expensive reasoning only when payoff justifies it for finance and product teams',
    longDescription: 'Intelligent routing system that evaluates the expected value of reasoning tasks before allocating expensive compute. Combines NEXUS routing, CORTEX value assessment, and BRAIN historical patterns.',
    requiredModules: ['NEXUS', 'CORTEX', 'BRAIN'],
    compatibleModules: ['ECONOMICS', 'VISION'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-vwrr-001-hash',
    releaseNotes: '## v1.0.0\n- Value-weighted routing\n- Payoff assessment\n- Cost-aware decisions\n- ROI optimization',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-value-weighted-reasoning-router'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 189,
    features: ['Value routing', 'Payoff analysis', 'Cost optimization', 'Smart allocation'],
    tags: ['routing', 'value', 'optimization', 'cost'],
    difficulty: 'intermediate',
    setupTimeMinutes: 25,
    buyerPersona: 'Finance, Product',
    salesPitch: 'Spend where it matters.',
  },
  {
    id: 'stier-waste-detection-intelligence',
    slug: 'waste-detection-intelligence',
    name: 'Waste Detection Intelligence',
    category: 'optimization',
    description: 'Stop burning money invisibly: Finds silent compute and logic waste',
    longDescription: 'Deep analysis system that identifies hidden computational waste, inefficient logic patterns, and underutilized resources. Uses VISION metrics, SYSTEM diagnostics, and BRAIN pattern recognition.',
    requiredModules: ['VISION', 'SYSTEM', 'BRAIN'],
    compatibleModules: ['ECONOMICS', 'CORTEX'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-wdi-001-hash',
    releaseNotes: '## v1.0.0\n- Waste detection\n- Silent inefficiency discovery\n- Resource optimization\n- Cost recovery',
    governanceLevel: 'manual',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-waste-detection-intelligence'].priceUsd,
    pricingTier: 'advanced',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 234,
    features: ['Waste detection', 'Inefficiency discovery', 'Resource optimization', 'Cost recovery'],
    tags: ['waste', 'optimization', 'efficiency', 'cost'],
    difficulty: 'beginner',
    setupTimeMinutes: 20,
    buyerPersona: 'Infra, Finance',
    salesPitch: 'Stop burning money invisibly.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🧩 PRODUCT × UX ($499 - $999)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-intent-drift-tracker',
    slug: 'intent-drift-tracker',
    name: 'Intent Drift Tracker',
    category: 'intelligence',
    description: 'Detects when users change goals mid-journey for product teams',
    longDescription: 'Real-time intent analysis that detects when user goals shift during interactions. Combines DECODE interpretation, BRAIN context memory, RIPPLE change propagation, and VISION behavioral metrics.',
    requiredModules: ['DECODE', 'BRAIN', 'RIPPLE', 'VISION'],
    compatibleModules: ['CORTEX'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-idt-001-hash',
    releaseNotes: '## v1.0.0\n- Intent drift detection\n- Goal shift analysis\n- Journey adaptation\n- Real-time tracking',
    governanceLevel: 'manual',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-intent-drift-tracker'].priceUsd,
    pricingTier: 'advanced',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 167,
    features: ['Intent detection', 'Drift analysis', 'Journey tracking', 'Goal adaptation'],
    tags: ['intent', 'product', 'ux', 'analytics'],
    difficulty: 'beginner',
    setupTimeMinutes: 20,
    buyerPersona: 'Product',
    salesPitch: 'The system keeps up with users.',
  },
  {
    id: 'stier-adaptive-product-brain',
    slug: 'adaptive-product-brain',
    name: 'Adaptive Product Brain',
    category: 'intelligence',
    description: 'The product learns: Product behavior evolves with usage patterns for SaaS founders',
    longDescription: 'Self-evolving product intelligence that adapts behavior based on usage patterns. Combines BRAIN learning, VISION usage analytics, and DECODE user understanding for continuous product improvement.',
    requiredModules: ['BRAIN', 'VISION', 'DECODE'],
    compatibleModules: ['DREAM', 'CORTEX'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-apb-001-hash',
    releaseNotes: '## v1.0.0\n- Adaptive behavior\n- Usage learning\n- Pattern evolution\n- Product optimization',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-adaptive-product-brain'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 145,
    features: ['Adaptive learning', 'Usage patterns', 'Behavior evolution', 'Product optimization'],
    tags: ['product', 'learning', 'saas', 'adaptive'],
    difficulty: 'intermediate',
    setupTimeMinutes: 35,
    buyerPersona: 'SaaS Founders',
    salesPitch: 'The product learns.',
  },
  {
    id: 'stier-friction-auto-removal-engine',
    slug: 'friction-auto-removal-engine',
    name: 'Friction Auto-Removal Engine',
    category: 'optimization',
    description: 'Conversion rate that improves itself: Detects and removes UX friction automatically',
    longDescription: 'Autonomous UX optimization that identifies friction points and automatically implements improvements. Uses VISION analytics, CORTEX decision-making, and EVOLUTION code generation.',
    requiredModules: ['VISION', 'CORTEX', 'EVOLUTION'],
    compatibleModules: ['DECODE', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-fare-001-hash',
    releaseNotes: '## v1.0.0\n- Friction detection\n- Auto-removal\n- Conversion optimization\n- A/B testing',
    governanceLevel: 'bounded',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-friction-auto-removal-engine'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 178,
    features: ['Friction detection', 'Auto-removal', 'Conversion boost', 'UX optimization'],
    tags: ['ux', 'conversion', 'friction', 'growth'],
    difficulty: 'intermediate',
    setupTimeMinutes: 40,
    buyerPersona: 'Growth Teams',
    salesPitch: 'Conversion rate that improves itself.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🧬 PLATFORM × SCALE ($999 - $1,499)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-cross-pipeline-arbitration-engine',
    slug: 'cross-pipeline-arbitration-engine',
    name: 'Cross-Pipeline Arbitration Engine',
    category: 'automation',
    description: 'No emergent chaos: Resolves conflicts between autonomous pipelines for platform teams',
    longDescription: 'Conflict resolution system for multi-pipeline environments. Combines CORTEX reasoning, RIPPLE propagation control, and DEFENSE isolation to prevent emergent chaos from pipeline interactions.',
    requiredModules: ['CORTEX', 'RIPPLE', 'DEFENSE'],
    compatibleModules: ['SYSTEM', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-cpae-001-hash',
    releaseNotes: '## v1.0.0\n- Conflict resolution\n- Pipeline arbitration\n- Chaos prevention\n- Priority management',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-cross-pipeline-arbitration-engine'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 67,
    features: ['Conflict resolution', 'Pipeline arbitration', 'Chaos prevention', 'Priority queuing'],
    tags: ['platform', 'arbitration', 'pipelines', 'scale'],
    difficulty: 'advanced',
    setupTimeMinutes: 60,
    buyerPersona: 'Platform Teams',
    salesPitch: 'No emergent chaos.',
  },
  {
    id: 'stier-capability-impact-forecaster',
    slug: 'capability-impact-forecaster',
    name: 'Capability Impact Forecaster',
    category: 'intelligence',
    description: 'Dont break prod later: Predicts second-order effects before enabling features',
    longDescription: 'Impact analysis system that predicts downstream effects of capability changes before deployment. Uses VISION metrics, CORTEX reasoning, and SYSTEM state analysis.',
    requiredModules: ['VISION', 'CORTEX', 'SYSTEM'],
    compatibleModules: ['RIPPLE', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-cif-001-hash',
    releaseNotes: '## v1.0.0\n- Impact prediction\n- Second-order effects\n- Deployment safety\n- Risk assessment',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-capability-impact-forecaster'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 89,
    features: ['Impact prediction', 'Effect analysis', 'Deployment safety', 'Risk scoring'],
    tags: ['impact', 'forecasting', 'platform', 'safety'],
    difficulty: 'intermediate',
    setupTimeMinutes: 35,
    buyerPersona: 'Architects',
    salesPitch: 'Don\'t break prod later.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 🏛️ COMPLIANCE × LEGITIMACY ($999 - $1,499)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'stier-audit-grade-decision-ledger',
    slug: 'audit-grade-decision-ledger',
    name: 'Audit-Grade Decision Ledger',
    category: 'security',
    description: 'Prove why the AI did it: Immutable reasoning and action logs for regulated sectors',
    longDescription: 'Immutable audit system that logs all AI reasoning and actions with cryptographic verification. Combines VISION monitoring, RIPPLE propagation tracking, SYSTEM logging, and DEFENSE integrity checks.',
    requiredModules: ['VISION', 'RIPPLE', 'SYSTEM', 'DEFENSE'],
    compatibleModules: ['AUDIT', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-agdl-001-hash',
    releaseNotes: '## v1.0.0\n- Immutable logging\n- Reasoning trails\n- Cryptographic verification\n- Audit exports',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-audit-grade-decision-ledger'].priceUsd,
    pricingTier: 'flagship',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 123,
    features: ['Immutable logs', 'Reasoning trails', 'Crypto verification', 'Audit exports'],
    tags: ['audit', 'compliance', 'ledger', 'regulated'],
    difficulty: 'intermediate',
    setupTimeMinutes: 45,
    buyerPersona: 'Regulated Sectors',
    salesPitch: 'Prove why the AI did it.',
  },
  {
    id: 'stier-regulatory-mode-switcher',
    slug: 'regulatory-mode-switcher',
    name: 'Regulatory Mode Switcher',
    category: 'security',
    description: 'Same AI everywhere, legal everywhere: One system, many compliance personas',
    longDescription: 'Dynamic compliance system that switches regulatory modes based on jurisdiction and context. Combines ACCESS controls, INCLUSIVE compliance, DECODE context understanding, and CORTEX decision adaptation.',
    requiredModules: ['ACCESS', 'INCLUSIVE', 'DECODE', 'CORTEX'],
    compatibleModules: ['AUDIT', 'DEFENSE'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-rms-001-hash',
    releaseNotes: '## v1.0.0\n- Mode switching\n- Jurisdiction detection\n- Compliance personas\n- Auto-adaptation',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-regulatory-mode-switcher'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 78,
    features: ['Mode switching', 'Jurisdiction handling', 'Compliance personas', 'Auto-adaptation'],
    tags: ['regulatory', 'compliance', 'global', 'enterprise'],
    difficulty: 'intermediate',
    setupTimeMinutes: 50,
    buyerPersona: 'Global Enterprises',
    salesPitch: 'Same AI everywhere, legal everywhere.',
  },
  {
    id: 'stier-policy-aware-intelligence-gate',
    slug: 'policy-aware-intelligence-gate',
    name: 'Policy-Aware Intelligence Gate',
    category: 'security',
    description: 'AI that obeys the rules: Decisions filtered through live policy for governance teams',
    longDescription: 'Policy enforcement gateway that filters all AI decisions through live policy rules. Combines CORTEX reasoning, DEFENSE enforcement, and ACCESS control for complete governance coverage.',
    requiredModules: ['CORTEX', 'DEFENSE', 'ACCESS'],
    compatibleModules: ['AUDIT', 'BRAIN'],
    executorType: 'js',
    artifactFormat: 'zip',
    version: '1.0.0',
    checksum: 'stier-paig-001-hash',
    releaseNotes: '## v1.0.0\n- Policy filtering\n- Live rule enforcement\n- Decision gating\n- Governance compliance',
    governanceLevel: 'governed',
    executionMode: 'local_only',
    supportPolicy: 'licensed_support',
    licenseRequired: true,
    priceUsd: STIER_STRIPE_CONFIG['stier-policy-aware-intelligence-gate'].priceUsd,
    pricingTier: 'system',
    lastUpdated: '2025-02-02T00:00:00Z',
    releaseDate: '2025-02-02T00:00:00Z',
    downloads: 145,
    features: ['Policy filtering', 'Rule enforcement', 'Decision gating', 'Compliance'],
    tags: ['policy', 'governance', 'compliance', 'rules'],
    difficulty: 'intermediate',
    setupTimeMinutes: 40,
    buyerPersona: 'Governance',
    salesPitch: 'AI that obeys the rules.',
  },
];

// Get all S-tier capabilities
export function getAllSTierCapabilities(): CapabilityArtifact[] {
  return STIER_CAPABILITIES;
}

// Get self-improvement capabilities only
export function getSelfImprovementCapabilities(): CapabilityArtifact[] {
  return STIER_CAPABILITIES.filter(cap => 
    cap.tags?.includes('self-improvement') || 
    cap.id.includes('governance-kernel') ||
    cap.id.includes('self-scaling') ||
    cap.id.includes('autonomous-ops')
  );
}

// Get S-tier capability by ID
export function getSTierCapabilityById(id: string): CapabilityArtifact | undefined {
  return STIER_CAPABILITIES.find(cap => cap.id === id);
}

// Get S-tier count
export function getSTierCount(): number {
  return STIER_CAPABILITIES.length;
}
