/**
 * Inside the Autonomous Discovery Engine: How CMPSBL Finds Software in the Stream
 */
import { Link } from "react-router-dom";
import { ArrowLeft, Sparkles, ArrowRight, Cpu, Layers, Zap, Brain, Shield, Network, CheckCircle, Settings, Activity, Code2, Eye } from "lucide-react";
import { SEO } from "@/components/SEO";
import { AuthorBio } from "@/components/AuthorBio";
import { PublicNav } from "@/components/PublicNav";
import { EnhancedFooter } from "@/components/EnhancedFooter";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import heroImage from "@/assets/blog/autonomous-discovery-engine.jpg";

export default function AutonomousDiscoveryEngine() {
  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="Inside the Autonomous Discovery Engine: How CMPSBL Finds Software — CMPSBL"
        description="A technical deep-dive into the autonomous discovery engine that powers the Memory Stream. How the substrate samples behavioral signals, scores quality across five dimensions, and crystallizes production-grade software."
        type="article"
        publishedTime="2026-03-04"
        keywords={['autonomous discovery engine', 'AI software generation', 'memory stream architecture', 'CJPI scoring', 'weighted random selection', 'CMPSBL engine', 'recursive discovery loop']}
      />

      <PublicNav />

      <section className="relative z-10 container mx-auto px-4 pt-20 md:pt-32 pb-12">
        <div className="max-w-4xl mx-auto">
          <Link to="/blog" className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Research
          </Link>

          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">
            <Cpu className="w-3 h-3 mr-1" />
            Pillar Guide
          </Badge>

          <h1 className="text-4xl md:text-5xl font-bold mb-6 text-foreground tracking-tight">
            Inside the Autonomous Discovery Engine: How CMPSBL Finds Software in the Stream
          </h1>

          <p className="text-lg md:text-xl text-muted-foreground mb-8 leading-relaxed">
            The Memory Stream isn't curated. It isn't browsed. It's <em>discovered</em> — by an autonomous engine 
            that samples behavioral signals, evaluates quality across five dimensions, and crystallizes results 
            with weighted probability. This is how it works under the hood.
          </p>

          <AuthorBio publishDate="2026-03-04" readTime="22 min read" />
        </div>
      </section>

      <section className="relative w-full h-[50vh] overflow-hidden">
        <img
          src={heroImage}
          alt="Autonomous discovery engine with recursive orbital loops around a central processing core"
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-background via-transparent to-background" />
      </section>

      <article className="container mx-auto max-w-3xl px-4 py-16 space-y-16">

        {/* Architecture Overview */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">Engine Architecture Overview</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              The discovery engine is a server-side function that orchestrates multiple substrate capabilities in a 
              single atomic operation. When a user triggers crystallization, the engine executes a deterministic pipeline 
              with three phases and multiple quality gates.
            </p>
            <p>
              Unlike most AI generation tools that produce output on demand, the discovery engine operates on a{" "}
              <strong className="text-foreground">sampling model</strong>. It doesn't create software from a prompt — 
              it discovers software that already exists as patterns in the substrate's behavioral data.
            </p>
            <p>
              This distinction is fundamental. The engine is a <strong className="text-foreground">discoverer</strong>, not a generator. 
              It finds viable software patterns the same way a prospector finds mineral deposits — by knowing where to look 
              and having the tools to extract what's valuable.
            </p>
          </div>
        </section>

        {/* Phase 1: Sampling */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">Phase 1: Sampling the Stream</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              The engine begins by sampling the Memory Stream — a continuous substrate of evolving software systems 
              generated by the <Link to="/modules" className="text-primary hover:underline">38-node matrix</Link>. The sampling 
              process is biased toward regions of the stream that exhibit structural coherence:
            </p>
            <ul className="space-y-2 ml-6">
              {[
                "Repeating algorithmic patterns that suggest stable software behavior",
                "Novel data transformations that haven't been previously cataloged",
                "Cross-node collaboration patterns where multiple substrate systems contributed",
                "Anomalous quality signals that suggest above-average architectural coherence",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              The sampling phase is intentionally stochastic. The engine doesn't always look in the same place, 
              which is why successive crystallizations produce different results even when triggered seconds apart.
            </p>
          </div>
        </section>

        {/* Phase 2: Condensation & Scoring */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">Phase 2: Condensation & Scoring</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              Once a viable pattern is sampled, the engine enters the condensation phase. Raw signals are structured 
              into a pipeline specification, and the CJPI scoring system evaluates the result across five dimensions:
            </p>

            <div className="space-y-3">
              {[
                { dim: "Code Completeness", weight: "25%", desc: "Does the pipeline implement its full specification without gaps?" },
                { dim: "Architectural Coherence", weight: "25%", desc: "Are abstractions clean, dependencies minimal, and patterns consistent?" },
                { dim: "Runtime Stability", weight: "20%", desc: "Does the software handle edge cases, errors, and boundary conditions?" },
                { dim: "Innovation Factor", weight: "15%", desc: "Does the solution exhibit novel approaches or creative problem-solving?" },
                { dim: "Security Posture", weight: "15%", desc: "Are there known vulnerabilities, unsafe patterns, or attack surfaces?" },
              ].map((d) => (
                <div key={d.dim} className="flex gap-4 items-start p-4 rounded-lg border border-border bg-card">
                  <Badge variant="outline" className="shrink-0 font-mono">{d.weight}</Badge>
                  <div>
                    <h4 className="font-bold text-foreground text-sm">{d.dim}</h4>
                    <p className="text-xs text-muted-foreground mt-0.5">{d.desc}</p>
                  </div>
                </div>
              ))}
            </div>

            <p>
              The composite score determines the tier. Crucially, the engine enforces a hard quality floor — any 
              pipeline scoring below 68 is rejected and never persisted to the user's Vault.
            </p>
          </div>
        </section>

        {/* Phase 3: Weighted Selection */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">Phase 3: Weighted Tier Selection</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              Here's where the magic happens. The engine uses a <strong className="text-foreground">weighted random selection</strong> algorithm 
              to determine the final tier of the crystallized pipeline. The weights ensure authentic rarity:
            </p>

            <Card className="p-6 bg-muted/30 font-mono text-sm">
              <pre className="text-muted-foreground whitespace-pre-wrap">{`// Tier probability weights (server-enforced)
const TIER_WEIGHTS = {
  mint:   0.65,   // 65% — Score 68-79
  prime:  0.25,   // 25% — Score 80-89
  relic:  0.07,   // 7%  — Score 90-93
  mythic: 0.025,  // 2.5% — Score 94-99
  apex:   0.005,  // 0.5% — Score 100
};

// Cumulative selection
const roll = Math.random();
let cumulative = 0;
for (const [tier, weight] of entries) {
  cumulative += weight;
  if (roll <= cumulative) return tier;
}`}</pre>
            </Card>

            <p>
              Once the tier is selected, a specific CJPI score is generated within that tier's range using a secondary 
              random distribution. For example, a Mint-tier roll will produce a score between 68 and 79, with slight 
              bias toward the middle of the range.
            </p>
            <p>
              The tier selection is <strong className="text-foreground">independent of the user</strong>. There are no 
              user-specific weights, no pay-to-win mechanics, no hidden modifiers. The probability distribution is 
              identical for every crystallization event, regardless of account age, subscription tier, or history.
            </p>
          </div>
        </section>

        {/* The Recursive Loop */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">The Recursive Discovery Loop</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              The engine doesn't just discover software — it <em>learns</em> from what it discovers. The{" "}
              <Link to="/evolution" className="text-primary hover:underline">EVOLUTION</Link> system feeds high-quality 
              crystallization results back into the substrate, improving the stream's overall quality over time.
            </p>
            <p>
              This creates a recursive loop:
            </p>
            <ol className="space-y-3 list-decimal list-outside ml-6">
              <li><strong className="text-foreground">Engine samples the stream</strong> and discovers a pipeline</li>
              <li><strong className="text-foreground">Pipeline is scored</strong> and crystallized to the user's Vault</li>
              <li><strong className="text-foreground">High-scoring patterns</strong> are fed back into the stream via EVOLUTION</li>
              <li><strong className="text-foreground">Stream quality improves</strong>, producing better future discoveries</li>
              <li><strong className="text-foreground">Cycle repeats</strong> — the engine gets better at finding software over time</li>
            </ol>
            <p>
              This is what makes the Memory Stream a <strong className="text-foreground">living system</strong> rather than 
              a static catalog. The 1,143+ programs already discovered represent only the current state — the stream 
              is continuously producing new patterns, and the engine is continuously improving at finding them.
            </p>
          </div>
        </section>

        {/* Governance */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">Governance & Safety</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              The discovery engine operates within strict governance boundaries enforced by the{" "}
              <Link to="/foundations" className="text-primary hover:underline">substrate invariants</Link>:
            </p>
            <ul className="space-y-3 ml-6">
              {[
                "Quality floor (68) is a hard gate — cannot be overridden even by admin access",
                "Tier weights are server-side constants — not configurable per-user",
                "High-Value Bias is force-disabled on public endpoints — admin-only flag",
                "RLS enforces per-user Vault isolation — no cross-user data leakage",
                "Rate limiting prevents abuse — crystallizations are throttled server-side",
                "Provenance is immutable — discovery metadata cannot be edited after creation",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <Shield className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* What's Next */}
        <section>
          <h2 className="text-3xl font-bold mb-6 text-foreground">What's Next for the Engine</h2>
          <div className="space-y-6 text-lg text-muted-foreground leading-relaxed">
            <p>
              The discovery engine is actively evolving. Current areas of development include:
            </p>
            <ul className="space-y-2 ml-6">
              {[
                "Category-aware sampling — biasing toward underrepresented software domains",
                "Multi-pipeline crystallization — discovering pipeline clusters rather than individual programs",
                "Cross-user pattern aggregation — finding trends across the global discovery corpus",
                "Quality dimension expansion — adding new scoring axes for maintainability and documentation",
                "Silicon readiness scoring — identifying which pipelines are candidates for hardware synthesis",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <Zap className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Follow the <Link to="/changelog" className="text-primary hover:underline">Fossil Record</Link> for updates, 
              or explore the <Link to="/overview" className="text-primary hover:underline">System Overview</Link> to see 
              how the engine fits into the broader substrate architecture.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="bg-card border border-border rounded-xl p-8 text-center space-y-4">
          <h3 className="text-2xl font-bold text-foreground">See It in Action</h3>
          <p className="text-muted-foreground max-w-lg mx-auto">
            The discovery engine is live and running. Every crystallization you trigger uses the exact architecture described above.
          </p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Button asChild size="lg">
              <Link to="/foundry">
                <Sparkles className="w-4 h-4 mr-2" />
                Open Memory Stream
              </Link>
            </Button>
            <Button asChild variant="outline" size="lg">
              <Link to="/foundry/demo">
                Watch the Demo
                <ArrowRight className="w-4 h-4 ml-2" />
              </Link>
            </Button>
          </div>
        </section>

        {/* Related */}
        <section>
          <h3 className="text-xl font-bold mb-4 text-foreground">Related Reading</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              { title: "Memory Stream: The Complete Guide", href: "/blog/memory-stream-crystallization-guide" },
              { title: "Signal → Silicon: The Full Narrative", href: "/blog/signal-to-silicon-narrative" },
              { title: "Anatomy of Memory Stream Tiers", href: "/blog/memory-stream-tier-anatomy-rarity" },
              { title: "Your Vault: Pipeline Management", href: "/blog/memory-stream-vault-mastery" },
            ].map((link) => (
              <Link key={link.href} to={link.href} className="block p-4 border border-border rounded-lg hover:border-primary/40 transition-colors">
                <span className="text-sm font-medium text-primary">{link.title}</span>
                <ArrowRight className="w-3 h-3 text-muted-foreground inline ml-2" />
              </Link>
            ))}
          </div>
        </section>
      </article>

      <EnhancedFooter />
    </div>
  );
}
