/**
 * Chapter 29: The Marketplace — October 2025
 */
import { Link } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { BlogArticleJsonLd } from "@/components/blog/BlogArticleJsonLd";
import { BlogArticleLayout } from "@/components/blog/BlogArticleLayout";
import heroImg from "@/assets/blog/artifact-pack-capabilities.jpg";

const SLUG = "the-marketplace";

export default function TheMarketplace() {
  return (
    <BlogArticleLayout
      slug={SLUG}
      title="The Marketplace"
      subtitle="Discovery, preview, and deployment of substrate discoveries"
      date="October 25, 2025"
      readTime="14 min read"
      heroImage={heroImg}
      heroAlt="Substrate Store marketplace"
      chapter={29}
      head={
        <>
          <SEO title="The Marketplace — Substrate Store" description="The Store became a discovery layer — browse, preview, purchase, and deploy substrate-generated software." type="article" image={heroImg} publishedTime="2025-10-25" keywords={["substrate store", "AI marketplace", "capability discovery"]} canonical={`https://cmpsbl.com/blog/${SLUG}`} topicCluster="substrate-platform" breadcrumbs={[{ name: "Home", url: "https://cmpsbl.com" }, { name: "Blog", url: "https://cmpsbl.com/blog" }, { name: "The Marketplace", url: `https://cmpsbl.com/blog/${SLUG}` }]} />
          <BlogArticleJsonLd title="The Marketplace — Substrate Store" description="Discovery, preview, and deployment of substrate capabilities." slug={SLUG} datePublished="2025-10-25" imageUrl={heroImg} keywords={["store", "marketplace", "capabilities"]} />
        </>
      }
    >
      <p className="text-sm sm:text-base leading-relaxed"><Link to="/blog/from-thought-to-artifact" className="text-primary hover:underline">FORGE</Link> could produce discoveries. But they sat in databases, invisible. Customers couldn't browse what the substrate had produced. They couldn't compare, preview, or deploy without talking to us directly.</p>

      <p>We had built a factory with no storefront. FORGE was producing hundreds of discoveries weekly — security tools, accessibility fixers, data processors, content generators — and most of them were used once by the customer who commissioned them and then forgotten. Meanwhile, other customers were requesting almost identical discoveries. We were duplicating work because there was no way to discover what already existed.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">The Store</h2>
      <p>We built the Substrate Store as a discovery layer. Every capability is categorized, scored, and previewable. Security tools, accessibility fixers, data enrichment systems, content generators — all browsable like an app store, but for AI-generated software components.</p>

      <p>The Store's architecture mirrors the substrate itself — it's built on substrate primitives. <Link to="/blog/mapping-what-we-built" className="text-primary hover:underline">ATLAS</Link> provides the capability taxonomy. <Link to="/blog/trust-but-verify" className="text-primary hover:underline">AUDIT</Link> scores quality. <Link to="/blog/teaching-machines-to-remember" className="text-primary hover:underline">BRAIN</Link> powers the search and recommendation engine. Even the Store's UI is partially generated by <Link to="/blog/interfaces-that-think" className="text-primary hover:underline">FORGE</Link>. We eat our own cooking at every level.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">Preview Before Deploy</h2>
      <p>Nobody trusts AI-generated code sight unseen. The Store lets developers preview discovery outputs, inspect the generation process, and verify <Link to="/blog/trust-but-verify" className="text-primary hover:underline">AUDIT scores</Link> before deploying. Transparency builds trust.</p>

      <p>The preview system goes deep. For code discoveries, developers can browse the full source, run tests in a sandbox, and inspect dependency trees. For report discoveries, they can preview the full document with sample data. For workflow discoveries, they can see the execution graph and estimated costs. Every discovery also shows its "lineage" — which primitives produced it, what inputs were used, and how many iterations were required. This level of transparency was a deliberate choice: in a world where AI-generated content is increasingly suspect, showing exactly how something was made is the strongest trust signal available.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">Tiered Access</h2>
      <p>The Store respects <Link to="/blog/identity-at-every-layer" className="text-primary hover:underline">ACCESS tier entitlements</Link>. Free tier users can browse and deploy basic capabilities. Pro tier gets premium capabilities and customization. Enterprise gets white-label deployment and custom capability generation.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">Discovery and Recommendation</h2>
      <p>The Store isn't just a catalog — it's an intelligent discovery engine. Based on your usage patterns, subscription tier, and industry vertical, it recommends capabilities you might not know you need. A customer using DEFENSE for security scanning gets recommended the compliance reporting capability. A customer running content Agencies gets recommended the SEO optimizer capability. These recommendations drive 35% of Store deployments — higher than manual browsing.</p>

      <p>The Store changed our business model. We went from selling API access to selling outcomes. Customers don't care how many NEXUS calls they make — they care that the security audit capability catches real vulnerabilities. <Link to="/blog/packing-intelligence" className="text-primary hover:underline">Packs</Link> took this further by bundling related capabilities together.</p>
    </BlogArticleLayout>
  );
}
