/**
 * Chapter 32: Forty Nodes Deep — December 2025
 */
import { Link } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { BlogArticleJsonLd } from "@/components/blog/BlogArticleJsonLd";
import { BlogArticleLayout } from "@/components/blog/BlogArticleLayout";
import heroImg from "@/assets/blog/what-makes-clockless-different.jpg";

const SLUG = "thirty-eight-nodes-deep";

export default function ThirtyEightNodesDeep() {
  return (
    <BlogArticleLayout slug={SLUG} title="Forty Nodes Deep" subtitle="The complete substrate architecture map" date="December 15, 2025" readTime="22 min read" heroImage={heroImg} heroAlt="Complete substrate architecture — 40 nodes" chapter={32} head={<><SEO title="Forty Nodes Deep — The Complete Architecture" description="From one function to forty interconnected nodes. A technical map of the complete substrate architecture." type="article" image={heroImg} publishedTime="2025-12-15" keywords={["substrate architecture", "40-node system", "cognitive infrastructure"]} canonical={`https://cmpsbl.com/blog/${SLUG}`} topicCluster="substrate-architecture" breadcrumbs={[{ name: "Home", url: "https://cmpsbl.com" }, { name: "Blog", url: "https://cmpsbl.com/blog" }, { name: "Forty Nodes Deep", url: `https://cmpsbl.com/blog/${SLUG}` }]} /><BlogArticleJsonLd title="Forty Nodes Deep" description="The complete substrate architecture map." slug={SLUG} datePublished="2025-12-15" imageUrl={heroImg} keywords={["architecture", "40 nodes", "substrate"]} /></>}>
      <p className="text-lg leading-relaxed">Twelve months. From <Link to="/blog/the-first-line-of-code" className="text-primary hover:underline">one function in December 2024</Link> to forty interconnected nodes by December 2025. This chapter is a map — where every node sits, what it does, and how they connect.</p>
      <p>We didn't plan forty nodes. We planned maybe twelve. The rest emerged from need — each one solving a specific problem that couldn't be addressed by composing existing nodes. When we hit twenty, we questioned whether we were over-engineering. At thirty, we stopped questioning and started documenting. At forty, we looked at the system and realized we'd accidentally built something closer to an operating system than an API.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">The Layers</h2>
      <p>The substrate organizes into four layers. <strong>Ingress</strong>: <Link to="/blog/routing-the-unknown" className="text-primary hover:underline">NEXUS</Link>, <Link to="/blog/identity-at-every-layer" className="text-primary hover:underline">ACCESS</Link>, <Link to="/blog/when-bots-found-us-first" className="text-primary hover:underline">DEFENSE</Link>, <Link to="/blog/the-intent-layer" className="text-primary hover:underline">Intent Mesh</Link>. <strong>Processing</strong>: <Link to="/blog/when-one-model-isnt-enough" className="text-primary hover:underline">CASCADE</Link>, <Link to="/blog/breaking-problems-apart" className="text-primary hover:underline">DECODE</Link>, <Link to="/blog/trust-but-verify" className="text-primary hover:underline">PROOF</Link>, <Link to="/blog/teaching-machines-to-remember" className="text-primary hover:underline">BRAIN</Link>. <strong>Output</strong>: <Link to="/blog/from-thought-to-artifact" className="text-primary hover:underline">FORGE</Link>, <Link to="/blog/interfaces-that-think" className="text-primary hover:underline">MORPH</Link>, <Link to="/blog/protocols-for-machines" className="text-primary hover:underline">RELAY</Link>. <strong>Meta</strong>: <Link to="/blog/seeing-everything-at-once" className="text-primary hover:underline">VISION</Link>, <Link to="/blog/mapping-what-we-built" className="text-primary hover:underline">ATLAS</Link>, <Link to="/blog/what-if-software-could-dream" className="text-primary hover:underline">DREAM</Link>, <Link to="/blog/the-governance-question" className="text-primary hover:underline">AUDIT</Link>.</p>
      <p>The four-layer model isn't just organizational — it defines data flow. Requests enter through the Ingress layer, which handles authentication, threat detection, and intent classification. Validated requests flow into the Processing layer, where the actual cognitive work happens. Results move to the Output layer for formatting, packaging, and delivery. The Meta layer operates orthogonally — observing, mapping, learning from, and governing the other three layers. Every interaction touches at least three layers. Complex operations touch all four.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">The Remaining Nodes</h2>
      <p>Beyond the sixteen core nodes covered in previous chapters, the substrate includes twenty-two specialized nodes. SIGNAL handles event detection and alerting. POOL manages shared resources and rate limiting. ANCHOR provides deterministic outputs for reproducible operations. LENS focuses on data visualization and presentation. GATEWAY manages external API integrations. Each fills a specific gap that the core nodes don't cover.</p>
      <p>Some specialized nodes started as features within core nodes and were extracted when they grew too complex. POOL was originally part of ACCESS — resource management started simple (rate limiting per API key) but grew to handle shared compute budgets, memory quotas, and priority queuing across the entire substrate. Extracting it into its own node simplified both ACCESS and every other node that needed resource management.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">The Connective Tissue</h2>
      <p><Link to="/blog/nodes-that-talk" className="text-primary hover:underline">RIPPLE</Link> connects everything. Every node emits events. Every node can subscribe to events from any other node. This event bus is what makes the substrate a system rather than a collection of services. Without RIPPLE, thirty-eight nodes would be thirty-eight microservices with no shared purpose.</p>
      <p>RIPPLE processes an average of 2.3 million events per day. Peak load during a large enterprise deployment hit 180,000 events per hour. The event bus operates with a median latency of 4ms and a p99 of 23ms. These performance characteristics are critical — the substrate's composability depends on nodes being able to communicate with negligible overhead. If inter-node communication were slow, the cost of composition would outweigh its benefits, and customers would be better off using monolithic models directly.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">What We Didn't Build</h2>
      <p>Some planned nodes never shipped. PREDICT was supposed to forecast user behavior — we realized <Link to="/blog/what-if-software-could-dream" className="text-primary hover:underline">DREAM</Link> handled it better. SYNC was a real-time collaboration node — redundant once RIPPLE matured. MIRROR was an A/B testing node for model outputs — we folded it into CASCADE's stage evaluation. Knowing what not to build saved us as much time as knowing what to build.</p>
      <p>We also killed three nodes post-launch. CACHE was a dedicated caching layer that overlapped too much with BRAIN's memory tiers. TRANSFORM was a data conversion node that <Link to="/blog/breaking-problems-apart" className="text-primary hover:underline">DECODE</Link> absorbed naturally. NOTIFY was a notification system that was too simple to justify as a node — it became a feature within RIPPLE. Removing nodes is harder than adding them because you need to migrate all dependents. Each removal took about a week of engineering time.</p>

      <h2 className="text-2xl font-bold text-foreground mt-8">The Architecture As a Product</h2>
      <p>Thirty-eight nodes sounds overwhelming. But each one is simple. The complexity is in the connections, not the components. That's the whole thesis of <a href="https://en.wikipedia.org/wiki/Composability" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">composable architecture</a> — and it's why we called the company CMPSBL.</p>
      <p>The architecture itself became a selling point. Enterprise customers examining our system invariably comment that individual nodes are understandable — you can explain NEXUS in two minutes, BRAIN in five. The system's intelligence emerges from composition, not from any individual component being brilliant. This is the opposite of the "god model" approach where a single massive model tries to do everything. We have thirty-eight small, focused models of capability that compose into something far more capable than any monolith.</p>
    </BlogArticleLayout>
  );
}
