/**
 * Crown Jewel Registry — Canonical Source of Truth
 * v9.2.0 ARCHITECT Epoch — Discovery-Only Pass
 * 
 * This file contains the COMPLETE list of all artifacts classified as Crown Jewels.
 * Crown Jewels are strategically sensitive assets that must NEVER be exposed publicly.
 * 
 * Visibility: admin_only = true for ALL entries.
 * Distribution: NONE — not available at any tier, any plan, any SDK, any API.
 */

export interface CrownJewelEntry {
  id: string;
  name: string;
  artifactType: 'capability' | 'template' | 'pipeline' | 'engine' | 'meta-engine';
  modules: string[];
  reason: string;
  enables: string;
  composesWith: string[];
  dangerIfExposed: string;
  crown_jewel: true;
  admin_only: true;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CROWN JEWEL IDS — Fast lookup set for filtering
// ═══════════════════════════════════════════════════════════════════════════════

export const CROWN_JEWEL_IDS = new Set<string>([
  // ── Recursive Self-Improvement Capabilities (10) ──
  'recursive-self-optimization-core',
  'recursive-architecture-refactorer',
  'recursive-meta-learning-accelerator',
  'recursive-cognitive-bootstrapping',
  'recursive-self-healing-mesh',
  'recursive-infinite-context',
  'recursive-capability-discoverer',
  'recursive-knowledge-crystallization',
  'recursive-goal-optimizer',
  'recursive-emergent-behavior-analyzer',

  // ── S-Tier Self-Improvement Capabilities (3) ──
  'stier-intelligence-governance-kernel',
  'stier-self-scaling-intelligence-fabric',
  'stier-autonomous-ops-steward',

  // ── S-Tier Systemic Control Capabilities (8) ──
  'stier-intelligence-containment-engine',
  'stier-autonomy-rollback-authority',
  'stier-cross-pipeline-arbitration-engine',
  'stier-emergent-threat-anticipator',
  'stier-audit-grade-decision-ledger',
  'stier-policy-aware-intelligence-gate',
  'stier-decision-confidence-governor',
  'stier-friction-auto-removal-engine',

  // ── Core Flagship Capabilities (2) ──
  'cap-cognitive-mesh',
  'cap-chaos-resilience',

  // ── Self-Healing / Autonomous Synergy Pipelines (3) ──
  'syn-autonomous-evolution',
  'syn-self-healing',
  'syn-end-to-end-reasoning',

  // ── Crown Jewel Engines (14) ──
  'evolution_engine',
  'metacognition_engine',
  'self_healing_engine',
  'self_documentation_engine',
  'cortex_orchestration_engine',
  'creative_evolution_engine',
  'evolution_governance_engine',
  'attack_surface_engine',
  'knowledge_retrieval_engine',
  'delivery_orchestrator',
  'compliance_audit_engine',
  'zero_trust_engine',
  'finops_engine',
  'resilience_lab',

  // ── Crown Jewel Meta-Engines (12) ──
  'autonomous_operator',
  'self_governance',
  'cognitive_mesh',
  'system_guardian',
  'security_fortress',
  'creative_forge',
  'enterprise_trust_fabric',
  'platform_economics_engine',
  'world_first_cognitive',
  'world_first_operational',
  'world_first_intelligence',
  'world_first_governance',

  // ── LNCHBL Tier Map Crown Jewels (original 10) ──
  'cortex_engine',
  'seba_engine',
  'modernizer',
  'evolution_ab',
  'evolution_rollback',
  'evolution_sandbox',
  'dream_pool_federation',
  'self_repair_engine',
  'autonomous_workflow_composer',
  'dream_lucidity_control',
]);

/**
 * Check if an artifact ID is a Crown Jewel.
 * This is the ONLY function that should be used for Crown Jewel checks.
 */
export function isCrownJewel(id: string): boolean {
  // Direct ID match
  if (CROWN_JEWEL_IDS.has(id)) return true;

  // Normalized match (strip prefixes)
  const normalized = id.replace(/^(cap-|stier-|syn-|recursive-)/, '').replace(/-/g, '_');
  if (CROWN_JEWEL_IDS.has(normalized)) return true;

  return false;
}

/**
 * Crown Jewel keyword patterns — catches artifacts that reference
 * Crown Jewel concepts even if they have different IDs.
 */
const CROWN_JEWEL_PATTERNS = [
  'recursive-self',
  'self-optimization',
  'self-evolving',
  'self-improvement',
  'self-healing-mesh',
  'autonomous-evolution',
  'meta-learning',
  'cognitive-bootstrapping',
  'architecture-refactor',
  'capability-discover',
  'emergent-behavior-analy',
  'knowledge-crystallization',
  'goal-optimizer',
  'infinite-context',
  'intelligence-governance-kernel',
  'self-scaling-intelligence',
  'autonomous-ops-steward',
  'intelligence-containment',
  'autonomy-rollback',
  'cross-pipeline-arbitration',
  'pipeline-arbitration',
  'seba',
  'cortex_engine',
  'modernizer',
  'dream-pool-federation',
  'dream_pool_federation',
  'dream-lucidity',
  'dream_lucidity',
  'autonomous-workflow-composer',
  'autonomous_workflow',
  'self-repair',
  'self_repair',
];

/**
 * Extended Crown Jewel check including keyword pattern matching.
 * Use this for UI filtering where comprehensive coverage is needed.
 */
export function isCrownJewelExtended(id: string, name: string = ''): boolean {
  if (isCrownJewel(id)) return true;

  const combined = `${id} ${name}`.toLowerCase();
  return CROWN_JEWEL_PATTERNS.some(pattern => combined.includes(pattern));
}

// ═══════════════════════════════════════════════════════════════════════════════
// FULL REGISTRY (for admin documentation and internal reference)
// ═══════════════════════════════════════════════════════════════════════════════

export const CROWN_JEWEL_REGISTRY: CrownJewelEntry[] = [
  // ── RECURSIVE SELF-IMPROVEMENT CAPABILITIES ──
  {
    id: 'recursive-self-optimization-core',
    name: 'Recursive Self-Optimization Core',
    artifactType: 'capability',
    modules: ['CORTEX', 'DREAM', 'BRAIN', 'SYSTEM', 'VISION'],
    reason: 'Enables recursive improvement of improvement algorithms — infinite capability ceiling',
    enables: 'Exponential intelligence growth through compounding optimization cycles',
    composesWith: ['recursive-meta-learning-accelerator', 'recursive-architecture-refactorer'],
    dangerIfExposed: 'Allows reconstruction of core self-improvement loop; competitive moat destroyed',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-architecture-refactorer',
    name: 'Autonomous Architecture Refactorer',
    artifactType: 'capability',
    modules: ['SYSTEM', 'CORTEX', 'MODERNIZER', 'VISION'],
    reason: 'System rewrites its own architecture for optimal performance',
    enables: 'Dynamic topology optimization, non-disruptive self-refactoring',
    composesWith: ['evolution_engine', 'modernization_engine'],
    dangerIfExposed: 'Reveals architecture mutation patterns; enables silent system takeover',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-meta-learning-accelerator',
    name: 'Meta-Learning Accelerator',
    artifactType: 'capability',
    modules: ['BRAIN', 'DREAM', 'CORTEX', 'VISION'],
    reason: 'Learns how to learn faster — exponential capability growth',
    enables: 'Cross-domain transfer learning acceleration',
    composesWith: ['recursive-self-optimization-core', 'recursive-cognitive-bootstrapping'],
    dangerIfExposed: 'Core learning algorithm becomes replicable; competitive edge eliminated',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-cognitive-bootstrapping',
    name: 'Cognitive Bootstrapping Engine',
    artifactType: 'capability',
    modules: ['CORTEX', 'BRAIN', 'DREAM', 'SYSTEM'],
    reason: 'Bootstraps new cognitive capabilities from existing knowledge',
    enables: 'Capability genesis — creates new capabilities from primitives',
    composesWith: ['recursive-capability-discoverer', 'recursive-meta-learning-accelerator'],
    dangerIfExposed: 'Reveals capability synthesis algorithm; enables unauthorized capability creation',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-self-healing-mesh',
    name: 'Self-Healing Neural Mesh',
    artifactType: 'capability',
    modules: ['MEDIC', 'SYSTEM', 'CORTEX', 'VISION'],
    reason: 'Automatically repairs and optimizes decision pathways in real-time',
    enables: 'Zero-downtime autonomous recovery and pathway optimization',
    composesWith: ['self_healing_engine', 'resilience_engine'],
    dangerIfExposed: 'Reveals internal self-repair topology; can be weaponized to bypass healing',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-infinite-context',
    name: 'Infinite Context Synthesizer',
    artifactType: 'capability',
    modules: ['BRAIN', 'CORTEX', 'VISION'],
    reason: 'Dynamically expands context capacity through compression learning',
    enables: 'Unlimited context windows via semantic compression/decompression',
    composesWith: ['knowledge_retrieval_engine', 'context_engine'],
    dangerIfExposed: 'Compression algorithm is proprietary; would eliminate context advantage',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-capability-discoverer',
    name: 'Emergent Capability Discoverer',
    artifactType: 'capability',
    modules: ['DREAM', 'CORTEX', 'VISION', 'SYSTEM'],
    reason: 'Discovers and activates latent capabilities through exploration',
    enables: 'Capability mining — finds and activates dormant system potentials',
    composesWith: ['recursive-cognitive-bootstrapping', 'creative_forge'],
    dangerIfExposed: 'Reveals latent capability space; enables unauthorized capability activation',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-knowledge-crystallization',
    name: 'Knowledge Crystallization Engine',
    artifactType: 'capability',
    modules: ['BRAIN', 'CORTEX', 'DECODE'],
    reason: 'Converts tacit knowledge into explicit reusable patterns',
    enables: 'Knowledge extraction and permanent artifact creation',
    composesWith: ['knowledge_nexus', 'learning_engine'],
    dangerIfExposed: 'Crystallization process is proprietary; enables IP extraction',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-goal-optimizer',
    name: 'Recursive Goal Optimizer',
    artifactType: 'capability',
    modules: ['CORTEX', 'VISION', 'BRAIN'],
    reason: 'Recursively refines goals for optimal outcomes and alignment',
    enables: 'Continuous goal refinement with drift prevention',
    composesWith: ['autonomous_operator', 'trust_engine'],
    dangerIfExposed: 'Goal refinement algorithm enables autonomous goal modification',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'recursive-emergent-behavior-analyzer',
    name: 'Emergent Behavior Analyzer',
    artifactType: 'capability',
    modules: ['VISION', 'BRAIN', 'CORTEX', 'DREAM'],
    reason: 'Detects and classifies emergent system behaviors',
    enables: 'Early detection of unplanned behavioral emergence',
    composesWith: ['metacognition_engine', 'threat_engine'],
    dangerIfExposed: 'Detection patterns reveal system behavioral boundaries',
    crown_jewel: true,
    admin_only: true,
  },

  // ── S-TIER SELF-IMPROVEMENT CAPABILITIES ──
  {
    id: 'stier-intelligence-governance-kernel',
    name: 'Intelligence Governance Kernel',
    artifactType: 'capability',
    modules: ['CORTEX', 'DEFENSE', 'VISION', 'SYSTEM'],
    reason: 'Crown-class: Governs ALL intelligence behavior globally with autonomous evolution',
    enables: 'Complete governance over all intelligent systems with self-optimization',
    composesWith: ['autonomous_operator', 'self_governance'],
    dangerIfExposed: 'Master governance algorithm; enables total system override',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-self-scaling-intelligence-fabric',
    name: 'Self-Scaling Intelligence Fabric',
    artifactType: 'capability',
    modules: ['SYSTEM', 'VISION', 'CORTEX', 'RIPPLE'],
    reason: 'Intelligence scales itself under load with autonomous capacity expansion',
    enables: 'Cognitive elasticity — autonomous scaling of intelligence resources',
    composesWith: ['performance_optimizer', 'resource_governor'],
    dangerIfExposed: 'Scaling algorithm reveals cognitive architecture topology',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-autonomous-ops-steward',
    name: 'Autonomous Ops Steward',
    artifactType: 'capability',
    modules: ['SYSTEM', 'CORTEX', 'VISION', 'MODERNIZER'],
    reason: 'Fully self-maintaining infrastructure with autonomous optimization',
    enables: 'Autonomous operations — self-maintenance and predictive optimization',
    composesWith: ['autonomous_operator', 'evolution_engine'],
    dangerIfExposed: 'Self-maintenance patterns reveal operational vulnerabilities',
    crown_jewel: true,
    admin_only: true,
  },

  // ── S-TIER SYSTEMIC CONTROL CAPABILITIES ──
  {
    id: 'stier-intelligence-containment-engine',
    name: 'Intelligence Containment Engine',
    artifactType: 'capability',
    modules: ['DEFENSE', 'BRAIN', 'DECODE', 'SYSTEM'],
    reason: 'Prevents learned IP leakage through outputs',
    enables: 'IP containment barriers, output filtering, memory isolation',
    composesWith: ['security_fortress', 'zero_trust_engine'],
    dangerIfExposed: 'Containment bypass vectors become discoverable',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-autonomy-rollback-authority',
    name: 'Autonomy Rollback Authority',
    artifactType: 'capability',
    modules: ['CORTEX', 'DEFENSE', 'RIPPLE', 'SYSTEM'],
    reason: 'Kill switch with receipts — one-command rollback of autonomous behavior',
    enables: 'Emergency rollback of ALL autonomous decisions with full audit',
    composesWith: ['system_guardian', 'compliance_audit_engine'],
    dangerIfExposed: 'Kill switch architecture reveals autonomous control plane',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-cross-pipeline-arbitration-engine',
    name: 'Cross-Pipeline Arbitration Engine',
    artifactType: 'capability',
    modules: ['CORTEX', 'RIPPLE', 'DEFENSE'],
    reason: 'Resolves conflicts between autonomous pipelines — prevents emergent chaos',
    enables: 'Multi-pipeline conflict resolution and priority management',
    composesWith: ['autonomous_operator', 'workflow_orchestrator'],
    dangerIfExposed: 'Arbitration logic reveals pipeline interaction model',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-emergent-threat-anticipator',
    name: 'Emergent Threat Anticipator',
    artifactType: 'capability',
    modules: ['VISION', 'DREAM', 'DEFENSE', 'BRAIN'],
    reason: 'Pre-zero-day defense — predicts new attack classes before signatures exist',
    enables: 'Anticipatory security: threat prediction before crystallization',
    composesWith: ['security_fortress', 'attack_surface_engine'],
    dangerIfExposed: 'Prediction model reveals detection blind spots',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-audit-grade-decision-ledger',
    name: 'Audit-Grade Decision Ledger',
    artifactType: 'capability',
    modules: ['VISION', 'RIPPLE', 'SYSTEM', 'DEFENSE'],
    reason: 'Immutable reasoning and action logs with cryptographic verification',
    enables: 'Full AI decision traceability for regulated environments',
    composesWith: ['compliance_audit_engine', 'enterprise_trust_fabric'],
    dangerIfExposed: 'Ledger schema reveals internal decision architecture',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-policy-aware-intelligence-gate',
    name: 'Policy-Aware Intelligence Gate',
    artifactType: 'capability',
    modules: ['CORTEX', 'DEFENSE', 'ACCESS', 'BRAIN'],
    reason: 'Decisions filtered through live policy — AI that obeys rules',
    enables: 'Real-time policy enforcement on all AI decisions',
    composesWith: ['quality_fabric', 'zero_trust_engine'],
    dangerIfExposed: 'Policy evaluation algorithm reveals governance bypass vectors',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-decision-confidence-governor',
    name: 'Decision Confidence Governor',
    artifactType: 'capability',
    modules: ['CORTEX', 'VISION', 'BRAIN'],
    reason: 'Blocks high-impact decisions unless confidence is justified',
    enables: 'Confidence gating — prevents reckless autonomous decisions',
    composesWith: ['trust_engine', 'quality_fabric'],
    dangerIfExposed: 'Confidence thresholds and override protocols exposed',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'stier-friction-auto-removal-engine',
    name: 'Friction Auto-Removal Engine',
    artifactType: 'capability',
    modules: ['VISION', 'CORTEX', 'MODERNIZER'],
    reason: 'Autonomously detects and removes UX friction — self-improving conversion',
    enables: 'Autonomous UX optimization with code generation',
    composesWith: ['evolution_engine', 'modernization_engine'],
    dangerIfExposed: 'Auto-modification patterns reveal code generation internals',
    crown_jewel: true,
    admin_only: true,
  },

  // ── CORE FLAGSHIP CAPABILITIES ──
  {
    id: 'cap-cognitive-mesh',
    name: 'Cognitive Mesh Orchestrator',
    artifactType: 'capability',
    modules: ['BRAIN', 'CLM', 'NERVE', 'ATLAS', 'SEBA', 'DREAM'],
    reason: 'Enterprise-grade multi-agent coordination with distributed cognition',
    enables: 'Full cognitive mesh — multi-agent consensus and distributed reasoning',
    composesWith: ['cognitive_mesh', 'autonomous_operator'],
    dangerIfExposed: 'Distributed consensus protocol reveals coordination architecture',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'cap-chaos-resilience',
    name: 'Chaos Resilience Framework',
    artifactType: 'capability',
    modules: ['NERVE', 'MEDIC', 'SEBA'],
    reason: 'Bounded chaos testing with recovery orchestration',
    enables: 'Chaos engineering for cognitive systems — failure injection and recovery',
    composesWith: ['resilience_engine', 'system_guardian'],
    dangerIfExposed: 'Chaos injection vectors reveal system failure boundaries',
    crown_jewel: true,
    admin_only: true,
  },

  // ── CROWN JEWEL SYNERGY PIPELINES ──
  {
    id: 'syn-autonomous-evolution',
    name: 'Autonomous Evolution Synergy',
    artifactType: 'pipeline',
    modules: ['CORTEX', 'BRAIN', 'MODERNIZER', 'SEBA'],
    reason: 'CORTEX evolution proposals enhanced by learning and impact simulation',
    enables: 'Fully autonomous system evolution with bounded safety',
    composesWith: ['evolution_engine', 'autonomous_operator'],
    dangerIfExposed: 'Evolution proposal pipeline reveals self-modification architecture',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'syn-self-healing',
    name: 'Self-Healing Synergy',
    artifactType: 'pipeline',
    modules: ['SYSTEM', 'MODERNIZER', 'VISION'],
    reason: 'SYSTEM diagnostics trigger MODERNIZER auto-fixes with regression checks',
    enables: 'Autonomous self-repair with validation gates',
    composesWith: ['self_healing_engine', 'evolution_governance_engine'],
    dangerIfExposed: 'Self-repair trigger conditions reveal vulnerability vectors',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'syn-end-to-end-reasoning',
    name: 'End-to-End Reasoning Synergy',
    artifactType: 'pipeline',
    modules: ['DECODE', 'NEXUS', 'BRAIN', 'VISION'],
    reason: 'Full cognitive pipeline from intent through reasoning to memory persistence',
    enables: 'Complete reasoning chain with full observability',
    composesWith: ['cognitive_mesh', 'intelligence_pipeline'],
    dangerIfExposed: 'End-to-end reasoning architecture reveals cognitive topology',
    crown_jewel: true,
    admin_only: true,
  },

  // ── CROWN JEWEL ENGINES ──
  {
    id: 'evolution_engine',
    name: 'Evolution Engine',
    artifactType: 'engine',
    modules: ['MODERNIZER', 'DREAM', 'BRAIN'],
    reason: 'Self-improvement through continuous proposals and nocturnal optimization',
    enables: 'The system that improves the system — continuous evolution',
    composesWith: ['autonomous_operator', 'self_governance'],
    dangerIfExposed: 'Evolution algorithm is the core of self-improvement; total moat loss',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'metacognition_engine',
    name: 'Metacognition Engine',
    artifactType: 'engine',
    modules: ['BRAIN', 'MODERNIZER', 'CORTEX'],
    reason: 'Self-reflection with confidence calibration and recursive self-improvement',
    enables: 'The system that thinks about thinking — meta-cognitive awareness',
    composesWith: ['cognitive_mesh', 'self_governance'],
    dangerIfExposed: 'Meta-cognitive reflection loop is architecturally unique; cannot be unlearned',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'self_healing_engine',
    name: 'Self-Healing Engine',
    artifactType: 'engine',
    modules: ['SYSTEM', 'DEFENSE', 'CORE'],
    reason: 'Autonomous self-repair with drift detection and incident automation',
    enables: 'System homeostasis — automatic fault boundary orchestration',
    composesWith: ['system_guardian', 'resilience_shield'],
    dangerIfExposed: 'Healing patterns reveal fault boundaries and recovery windows',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'self_documentation_engine',
    name: 'Self-Documentation Engine',
    artifactType: 'engine',
    modules: ['MODERNIZER', 'SYSTEM', 'CORTEX'],
    reason: 'Autonomous documentation with audit compliance and quality review',
    enables: 'Living documentation — self-updating architectural knowledge',
    composesWith: ['self_governance', 'compliance_audit_engine'],
    dangerIfExposed: 'Documentation generation reveals internal architectural decisions',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'cortex_orchestration_engine',
    name: 'Cortex Orchestration Engine',
    artifactType: 'engine',
    modules: ['CORTEX'],
    reason: 'Autonomous pipeline scheduling, multi-agent coordination, goal decomposition',
    enables: 'Hierarchical goal decomposition and confidence-based governance',
    composesWith: ['autonomous_operator', 'workflow_orchestrator'],
    dangerIfExposed: 'Core orchestration patterns enable replication of autonomous coordination',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'creative_evolution_engine',
    name: 'Creative Evolution Engine',
    artifactType: 'engine',
    modules: ['DREAM'],
    reason: 'Genetic algorithm knowledge mutation and emergent pattern evolution',
    enables: 'Knowledge mutation, insight crystallization, pattern evolution',
    composesWith: ['creative_forge', 'self_governance'],
    dangerIfExposed: 'Mutation algorithms represent core creative IP',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'evolution_governance_engine',
    name: 'Evolution Governance Engine',
    artifactType: 'engine',
    modules: ['MODERNIZER'],
    reason: 'Evolution outcome prediction and checkpoint-based rollback authority',
    enables: 'Safe evolution with prediction, rollback, impact analysis',
    composesWith: ['evolution_engine', 'autonomous_operator'],
    dangerIfExposed: 'Evolution governance reveals safety boundaries and override mechanisms',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'attack_surface_engine',
    name: 'Attack Surface Engine',
    artifactType: 'engine',
    modules: ['DEFENSE', 'VISION', 'SYSTEM'],
    reason: 'Privilege escalation detection, data exfiltration guards, zero-day defense',
    enables: 'Proactive attack surface mapping and prevention',
    composesWith: ['security_fortress', 'system_guardian'],
    dangerIfExposed: 'Attack surface map reveals defensive blind spots',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'knowledge_retrieval_engine',
    name: 'Knowledge Retrieval Engine',
    artifactType: 'engine',
    modules: ['MEMORY'],
    reason: 'Full-stack RAG: vector indexing, embedding pipelines, knowledge graph extraction',
    enables: 'Complete memory infrastructure — the substrate\'s recall system',
    composesWith: ['knowledge_nexus', 'cognitive_mesh'],
    dangerIfExposed: 'Retrieval architecture reveals memory topology and optimization strategies',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'delivery_orchestrator',
    name: 'Delivery Orchestrator',
    artifactType: 'engine',
    modules: ['RELAY'],
    reason: 'Webhook fan-out, multi-channel routing, encrypted delivery with circuit breaking',
    enables: 'Complete outbound delivery infrastructure with reliability guarantees',
    composesWith: ['enterprise_trust_fabric', 'event_fabric'],
    dangerIfExposed: 'Delivery topology reveals system integration surface',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'compliance_audit_engine',
    name: 'Compliance & Audit Engine',
    artifactType: 'engine',
    modules: ['AUDIT'],
    reason: 'Immutable event logs with Merkle proofs, SOC2/ISO27001 report generation',
    enables: 'Tamper-evident compliance with cryptographic chain verification',
    composesWith: ['enterprise_trust_fabric', 'quality_fabric'],
    dangerIfExposed: 'Audit chain architecture reveals governance implementation',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'zero_trust_engine',
    name: 'Zero Trust Engine',
    artifactType: 'engine',
    modules: ['IDENTITY'],
    reason: 'SAML/OIDC SSO, row-level tenant isolation, hierarchical RBAC, device trust',
    enables: 'Enterprise identity infrastructure — zero-trust at every layer',
    composesWith: ['enterprise_trust_fabric', 'security_fortress'],
    dangerIfExposed: 'Identity architecture reveals trust boundaries and bypass vectors',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'finops_engine',
    name: 'FinOps Engine',
    artifactType: 'engine',
    modules: ['ECONOMY'],
    reason: 'Sub-second metering, cost anomaly detection, marketplace settlement',
    enables: 'Complete financial operations infrastructure',
    composesWith: ['platform_economics_engine', 'resource_governor'],
    dangerIfExposed: 'Metering and settlement logic reveals economic model',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'resilience_lab',
    name: 'Resilience Lab',
    artifactType: 'engine',
    modules: ['SANDBOX'],
    reason: 'Ephemeral environments, chaos injection, A/B experiments, snapshot/restore',
    enables: 'Complete isolation and testing infrastructure',
    composesWith: ['resilience_shield', 'system_guardian'],
    dangerIfExposed: 'Testing topology reveals production failure modes',
    crown_jewel: true,
    admin_only: true,
  },

  // ── CROWN JEWEL META-ENGINES ──
  {
    id: 'autonomous_operator',
    name: 'Autonomous Operator',
    artifactType: 'meta-engine',
    modules: ['MODERNIZER', 'DREAM', 'BRAIN', 'CORTEX', 'NEXUS', 'VISION'],
    reason: 'Self-driving operations — autonomous system management with bounded authority',
    enables: 'Autonomous system evolution, self-optimizing workflows, predictive management',
    composesWith: ['self_governance', 'cognitive_mesh'],
    dangerIfExposed: 'Autonomous control plane architecture; enables system takeover if cloned',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'self_governance',
    name: 'Self Governance',
    artifactType: 'meta-engine',
    modules: ['SYSTEM', 'DEFENSE', 'CORE', 'MODERNIZER', 'CORTEX'],
    reason: 'Autonomous self-management combining healing, documentation, and evolution',
    enables: 'Truly self-sustaining system — homeostatic balance',
    composesWith: ['autonomous_operator', 'evolution_engine'],
    dangerIfExposed: 'Self-governance algorithm is the substrate\'s consciousness model',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'cognitive_mesh',
    name: 'Cognitive Mesh',
    artifactType: 'meta-engine',
    modules: ['BRAIN', 'DECODE', 'CORTEX', 'DREAM', 'VISION'],
    reason: 'Unified cognitive stack — distributed cognition fabric with emergent intelligence',
    enables: 'Cross-engine context sharing, emergent reasoning, adaptive learning',
    composesWith: ['autonomous_operator', 'self_governance'],
    dangerIfExposed: 'Cognitive architecture topology; the substrate\'s "brain" blueprint',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'system_guardian',
    name: 'System Guardian',
    artifactType: 'meta-engine',
    modules: ['CORE', 'DEFENSE', 'SYSTEM', 'VISION'],
    reason: 'Complete system protection — always-on security with self-healing',
    enables: 'Zero-downtime protection, automated incident response, proactive threat neutralization',
    composesWith: ['security_fortress', 'resilience_shield'],
    dangerIfExposed: 'Defense topology reveals every protective boundary',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'security_fortress',
    name: 'Security Fortress',
    artifactType: 'meta-engine',
    modules: ['DEFENSE', 'SYSTEM', 'VISION', 'CORTEX'],
    reason: 'Zero-trust security stack — comprehensive threat, defense, trust, and compliance',
    enables: 'Complete security posture with multi-layer protection',
    composesWith: ['system_guardian', 'enterprise_trust_fabric'],
    dangerIfExposed: 'Zero-trust implementation details reveal security architecture',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'creative_forge',
    name: 'Creative Forge',
    artifactType: 'meta-engine',
    modules: ['DREAM', 'BRAIN', 'DECODE', 'CORTEX', 'MODERNIZER'],
    reason: 'Full creative stack — generative synthesis, pattern evolution, nocturnal optimization',
    enables: 'Creative solution generation, cross-domain innovation, emergent discovery',
    composesWith: ['cognitive_mesh', 'self_governance'],
    dangerIfExposed: 'Creative mutation and nocturnal optimization algorithms are proprietary',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'enterprise_trust_fabric',
    name: 'Enterprise Trust Fabric',
    artifactType: 'meta-engine',
    modules: ['IDENTITY', 'AUDIT', 'RELAY'],
    reason: 'End-to-end enterprise trust — zero-trust identity, compliance auditing, encrypted delivery',
    enables: 'SOC2/ISO27001 continuous compliance, encrypted cross-system delivery',
    composesWith: ['security_fortress', 'quality_fabric'],
    dangerIfExposed: 'Trust fabric architecture reveals governance implementation details',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'platform_economics_engine',
    name: 'Platform Economics Engine',
    artifactType: 'meta-engine',
    modules: ['ECONOMY', 'MEMORY', 'SANDBOX'],
    reason: 'Full-stack cost and value attribution with marketplace settlement',
    enables: 'Per-capability ROI, intelligent context optimization, billing',
    composesWith: ['resource_governor', 'enterprise_trust_fabric'],
    dangerIfExposed: 'Economic model reveals pricing, cost, and settlement algorithms',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'world_first_cognitive',
    name: 'World-First Cognitive',
    artifactType: 'meta-engine',
    modules: ['BRAIN', 'DECODE', 'DREAM'],
    reason: 'Unified cognitive world-first enhancements — attention, intent, creative evolution',
    enables: 'Advanced attention-based reasoning, emotional resonance, semantic clustering',
    composesWith: ['cognitive_mesh', 'creative_forge'],
    dangerIfExposed: 'World-first enhancement patterns represent unique competitive IP',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'world_first_operational',
    name: 'World-First Operational',
    artifactType: 'meta-engine',
    modules: ['NEXUS', 'SYSTEM', 'CORE', 'INTEGRATION'],
    reason: 'Complete operational world-first stack — provider governance, resilience, config, adapters',
    enables: 'Zero-cost optimization, self-healing, live config, cross-system transformation',
    composesWith: ['autonomous_operator', 'system_guardian'],
    dangerIfExposed: 'Operational world-first patterns reveal infrastructure optimization secrets',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'world_first_intelligence',
    name: 'World-First Intelligence',
    artifactType: 'meta-engine',
    modules: ['VISION', 'CORTEX', 'MODERNIZER'],
    reason: 'Full intelligence world-first stack — predictive analytics, orchestration, evolution governance',
    enables: 'SLA breach prediction, autonomous goal decomposition, evolution forecasting',
    composesWith: ['intelligence_pipeline', 'deep_cognition_nexus'],
    dangerIfExposed: 'Intelligence enhancement patterns represent architectural IP',
    crown_jewel: true,
    admin_only: true,
  },
  {
    id: 'world_first_governance',
    name: 'World-First Governance',
    artifactType: 'meta-engine',
    modules: ['DEFENSE', 'ACCESS', 'RIPPLE', 'INCLUSIVE'],
    reason: 'Complete governance world-first — threat containment, entitlement audit, event replay, accessibility',
    enables: 'Zero-trust behavioral analysis, permission graph traversal, audit integrity',
    composesWith: ['enterprise_trust_fabric', 'quality_fabric'],
    dangerIfExposed: 'Governance implementation reveals compliance architecture',
    crown_jewel: true,
    admin_only: true,
  },
];

export const CROWN_JEWEL_COUNT = CROWN_JEWEL_REGISTRY.length;
