/**
 * Public Capability Manifest — Tier-Safe, Outcome-Oriented
 * 168 Crown Jewels (Wave 1 + 2 + 3 + 4)
 * 
 * RULES:
 * - NO CMPSBL-only Crown Jewels by name or description
 * - NO recursive evolution, self-governance, or meta-engine internals
 * - Outcome language only ("Predict failures") not technical internals
 * - public_safe: true means safe for pricing pages, investor decks
 */

export interface PublicCapability {
  name: string;
  tier: 'creator' | 'architect' | 'enterprise';
  module: string;
  outcome_summary: string;
  category: 'security' | 'intelligence' | 'optimization' | 'compliance' | 'observability';
  public_safe: true;
  is_crown_jewel?: boolean;
}

export const PUBLIC_CAPABILITY_MANIFEST: PublicCapability[] = [
  // ══════════════════════════════════════════════════════
  // CREATOR TIER ($29/mo) — 12 core + 27 crown jewels = 39
  // ══════════════════════════════════════════════════════
  {
    name: 'Knowledge Gap Detection',
    tier: 'creator',
    module: 'MEMORY',
    outcome_summary: 'Automatically identifies stale or incomplete knowledge before it causes errors',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Cost Anomaly Detection',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Predict cost spikes and receive anomaly alerts before they hit your budget',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Value Attribution',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Attribute revenue impact to specific capabilities and features',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'User Journey Mapping',
    tier: 'creator',
    module: 'VISION',
    outcome_summary: 'Reconstruct complete user journeys to find drop-off points and optimize flows',
    category: 'observability',
    public_safe: true,
  },
  {
    name: 'Cohort Analysis',
    tier: 'creator',
    module: 'VISION',
    outcome_summary: 'Segment users into behavioral cohorts and predict retention patterns',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Provider Failure Prediction',
    tier: 'creator',
    module: 'NEXUS',
    outcome_summary: 'Forecast AI provider outages and degrade gracefully before impact',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Architecture Drift Detection',
    tier: 'creator',
    module: 'ENCODE',
    outcome_summary: 'Detect when your codebase drifts from intended design patterns',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Pattern Consolidation',
    tier: 'creator',
    module: 'DREAM',
    outcome_summary: 'Consolidate repeated patterns into reusable, optimized templates',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Channel Optimization',
    tier: 'creator',
    module: 'RELAY',
    outcome_summary: 'Determine the optimal delivery channel for each recipient automatically',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Intent Evolution Tracking',
    tier: 'creator',
    module: 'DECODE',
    outcome_summary: 'Track how user intent evolves over time and predict next actions',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Event Dedup Intelligence',
    tier: 'creator',
    module: 'RIPPLE',
    outcome_summary: 'Semantically deduplicate events beyond exact matches to reduce noise',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Health Prediction',
    tier: 'creator',
    module: 'INTEGRATION',
    outcome_summary: 'Predict connector failures before they impact your integrations',
    category: 'observability',
    public_safe: true,
  },
  // ── NEW Creator Crown Jewels (one per module not yet covered) ──
  {
    name: 'Hot-Path Auto-Recovery',
    tier: 'creator',
    module: 'CORE',
    outcome_summary: 'Automatically detect and recover from module failures without downtime or manual intervention',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Smart Rate Shaping',
    tier: 'creator',
    module: 'ACCESS',
    outcome_summary: 'Intelligently shape API traffic to maximize throughput without exceeding quotas',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Contextual Recall Boost',
    tier: 'creator',
    module: 'BRAIN',
    outcome_summary: 'Automatically surface the most relevant memories based on conversation context and intent',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Autonomous A11y Remediation',
    tier: 'creator',
    module: 'INCLUSIVE',
    outcome_summary: 'Auto-fix common accessibility violations with one-click AI-generated code patches',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Execution Safety Net',
    tier: 'creator',
    module: 'SANDBOX',
    outcome_summary: 'Run untrusted code and experiments in isolated environments with zero production risk',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Compliance Snapshot',
    tier: 'creator',
    module: 'AUDIT',
    outcome_summary: 'Generate point-in-time compliance snapshots for any audit period on demand',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Budget Guardian',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Set spending limits and receive real-time alerts before budgets are exceeded',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ── Wave 2 Creator Crown Jewels ──
  {
    name: 'Semantic Event Routing',
    tier: 'creator',
    module: 'RIPPLE',
    outcome_summary: 'Route events to the right handler based on meaning, not just type strings',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Contextual Humor Calibration',
    tier: 'creator',
    module: 'DECODE',
    outcome_summary: 'Calibrate AI tone and humor to match user preferences and cultural context',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Memory Consolidation',
    tier: 'creator',
    module: 'BRAIN',
    outcome_summary: 'Automatically merge redundant memories and strengthen important ones during idle time',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Reputation Scoring',
    tier: 'creator',
    module: 'DEFENSE',
    outcome_summary: 'Score request sources by behavioral reputation to prioritize trusted traffic',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Webhook Intelligence',
    tier: 'creator',
    module: 'RELAY',
    outcome_summary: 'Auto-retry, deduplicate, and validate webhooks with intelligent failure recovery',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Test Oracle Generation',
    tier: 'creator',
    module: 'ENCODE',
    outcome_summary: 'Generate expected test outcomes from specification analysis without manual test writing',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Latency Prediction',
    tier: 'creator',
    module: 'NEXUS',
    outcome_summary: 'Predict provider response times and pre-route requests to the fastest option',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Usage Forecasting',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Forecast usage patterns and recommend capacity adjustments before spikes hit',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Capability Recommendation',
    tier: 'creator',
    module: 'ATLAS',
    outcome_summary: 'Suggest the best capabilities for your use case based on project analysis',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Predictive Self-Healing',
    tier: 'creator',
    module: 'MEDIC',
    outcome_summary: 'Detect degradation patterns and apply fixes before systems actually break',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // ARCHITECT TIER ($79/mo) — 14 existing + 43 crown jewels = 57
  // ══════════════════════════════════════════════════════
  {
    name: 'Zero-Day Detection',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Detect unknown attack patterns beyond known vulnerability signatures',
    category: 'security',
    public_safe: true,
  },
  {
    name: 'Attack Correlation',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Link distributed attack campaigns across IPs, sessions, and time',
    category: 'security',
    public_safe: true,
  },
  {
    name: 'Behavioral Fingerprinting',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Create behavioral signatures that persist beyond device fingerprints',
    category: 'security',
    public_safe: true,
  },
  {
    name: 'Identity Graph',
    tier: 'architect',
    module: 'IDENTITY',
    outcome_summary: 'Build cross-session identity graphs for unified user understanding',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Behavioral Biometrics',
    tier: 'architect',
    module: 'IDENTITY',
    outcome_summary: 'Continuously authenticate users through interaction patterns',
    category: 'security',
    public_safe: true,
  },
  {
    name: 'Incident Prediction',
    tier: 'architect',
    module: 'SYSTEM',
    outcome_summary: 'Predict incidents from health telemetry before they become outages',
    category: 'observability',
    public_safe: true,
  },
  {
    name: 'Capacity Forecasting',
    tier: 'architect',
    module: 'SYSTEM',
    outcome_summary: 'Predict capacity limits and recommend scaling actions proactively',
    category: 'optimization',
    public_safe: true,
  },
  {
    name: 'Forensic Timeline',
    tier: 'architect',
    module: 'AUDIT',
    outcome_summary: 'Automatically reconstruct forensic timelines for compliance investigations',
    category: 'compliance',
    public_safe: true,
  },
  {
    name: 'Regulatory Autopilot',
    tier: 'architect',
    module: 'AUDIT',
    outcome_summary: 'Auto-generate SOC2, GDPR, and HIPAA compliance reports on demand',
    category: 'compliance',
    public_safe: true,
  },
  {
    name: 'Temporal Reasoning',
    tier: 'architect',
    module: 'MEMORY',
    outcome_summary: 'Analyze causal chains across memories to understand temporal relationships',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Semantic Refactoring',
    tier: 'architect',
    module: 'ENCODE',
    outcome_summary: 'Behavior-preserving code refactoring with formal verification guarantees',
    category: 'intelligence',
    public_safe: true,
  },
  {
    name: 'Dependency Impact Analysis',
    tier: 'architect',
    module: 'CORTEX',
    outcome_summary: 'Map blast radius across dependency graphs before making changes',
    category: 'observability',
    public_safe: true,
  },
  {
    name: 'Model Quality Scoring',
    tier: 'architect',
    module: 'NEXUS',
    outcome_summary: 'Score AI model output quality in real-time and detect hallucinations',
    category: 'intelligence',
    public_safe: true,
  },
  // ── NEW Architect Crown Jewels ──
  {
    name: 'Adaptive Personality Engine',
    tier: 'architect',
    module: 'DECODE',
    outcome_summary: 'Dynamically adjust AI personality and tone based on user sentiment and context in real-time',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Dream-State Synthesis',
    tier: 'architect',
    module: 'DREAM',
    outcome_summary: 'Generate novel solutions by combining patterns discovered during autonomous off-peak analysis',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cascade Failure Prevention',
    tier: 'architect',
    module: 'RIPPLE',
    outcome_summary: 'Detect and halt cascading failures across modules before they propagate system-wide',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Predictive Connector Health',
    tier: 'architect',
    module: 'INTEGRATION',
    outcome_summary: 'Forecast integration breakdowns days in advance using historical health patterns',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Intelligent Cost Arbitrage',
    tier: 'architect',
    module: 'NEXUS',
    outcome_summary: 'Automatically route requests to the cheapest provider that meets quality thresholds',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cross-Module Orchestration',
    tier: 'architect',
    module: 'CORTEX',
    outcome_summary: 'Compose multi-module workflows that discover emergent capabilities beyond individual modules',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Architecture Modernization Planner',
    tier: 'architect',
    module: 'EVOLUTION',
    outcome_summary: 'Generate risk-scored migration roadmaps with incremental execution plans for legacy systems',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ── Wave 2 Architect Crown Jewels ──
  {
    name: 'Provider Trust Scoring',
    tier: 'architect',
    module: 'NEXUS',
    outcome_summary: 'Score AI providers on reliability, cost, and quality to automate routing decisions',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Anomaly Precognition',
    tier: 'architect',
    module: 'VISION',
    outcome_summary: 'Detect anomalies before they manifest using predictive behavioral modeling',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Selective Memory Pruning',
    tier: 'architect',
    module: 'MEMORY',
    outcome_summary: 'Intelligently prune low-value memories while preserving critical context chains',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Adaptive Delivery Optimization',
    tier: 'architect',
    module: 'RELAY',
    outcome_summary: 'Adapt delivery strategy per-recipient based on engagement history and preferences',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Causal Attribution Engine',
    tier: 'architect',
    module: 'AUDIT',
    outcome_summary: 'Trace any system event back to its root cause across the full module graph',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Zero-Day Pattern Synthesis',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Synthesize novel attack signatures from partial indicators before exploitation',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Trust Decay Modeling',
    tier: 'architect',
    module: 'IDENTITY',
    outcome_summary: 'Model identity trust as a decaying function that requires continuous behavioral verification',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Multi-Objective Optimization',
    tier: 'architect',
    module: 'CORTEX',
    outcome_summary: 'Balance competing objectives (cost vs speed vs quality) with Pareto-optimal solutions',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Knowledge Distillation',
    tier: 'architect',
    module: 'BRAIN',
    outcome_summary: 'Compress large knowledge bases into compact, high-fidelity representations for fast retrieval',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Lucid Dream Intervention',
    tier: 'architect',
    module: 'DREAM',
    outcome_summary: 'Steer autonomous analysis sessions in real-time to explore specific hypothesis branches',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Semantic Debt Detection',
    tier: 'architect',
    module: 'ENCODE',
    outcome_summary: 'Detect semantic debt — code that works but no longer reflects its original intent',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Empathic Calibration',
    tier: 'architect',
    module: 'DECODE',
    outcome_summary: 'Dynamically calibrate AI empathy levels based on detected user emotional state',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Dynamic Pricing Intelligence',
    tier: 'architect',
    module: 'ECONOMY',
    outcome_summary: 'Optimize internal resource pricing in real-time based on demand and availability',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Chaos Orchestration',
    tier: 'architect',
    module: 'SANDBOX',
    outcome_summary: 'Run controlled chaos experiments to discover failure modes before production',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cognitive Horizon Scanning',
    tier: 'architect',
    module: 'VISION',
    outcome_summary: 'Scan emerging patterns at the edge of detection to surface early warnings',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Entitlement Reasoning',
    tier: 'architect',
    module: 'ACCESS',
    outcome_summary: 'Reason about complex entitlement graphs to prevent unauthorized capability access',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Adaptive Circuit Topology',
    tier: 'architect',
    module: 'NERVE',
    outcome_summary: 'Dynamically reshape module communication circuits based on real-time load patterns',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cognitive Accessibility',
    tier: 'architect',
    module: 'INCLUSIVE',
    outcome_summary: 'Adapt interfaces for cognitive accessibility beyond WCAG — dyslexia, ADHD, and autism support',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // ENTERPRISE (Custom) — 3 existing + 21 crown jewels = 24
  // ══════════════════════════════════════════════════════
  {
    name: 'Source Code Access',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Full source access for self-hosted deployment and custom governance',
    category: 'compliance',
    public_safe: true,
  },
  {
    name: 'Air-Gapped Deployment',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Run the full substrate in air-gapped environments with zero external calls',
    category: 'security',
    public_safe: true,
  },
  {
    name: 'Custom Governance Rules',
    tier: 'enterprise',
    module: 'CORTEX',
    outcome_summary: 'Define custom governance policies tailored to your regulatory requirements',
    category: 'compliance',
    public_safe: true,
  },
  // ── NEW Enterprise Crown Jewels ──
  {
    name: 'Multi-Tenant Intelligence Isolation',
    tier: 'enterprise',
    module: 'BRAIN',
    outcome_summary: 'Complete memory and intelligence isolation across tenants with zero data leakage guarantees',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Sovereign Identity Federation',
    tier: 'enterprise',
    module: 'IDENTITY',
    outcome_summary: 'Federate identity across organizations with cryptographic provenance and trust portability',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Enterprise Threat Intelligence Network',
    tier: 'enterprise',
    module: 'DEFENSE',
    outcome_summary: 'Share anonymized threat intelligence across deployments for collective defense',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Guaranteed Delivery SLA',
    tier: 'enterprise',
    module: 'RELAY',
    outcome_summary: 'Cryptographically-verified delivery guarantees with contractual SLA enforcement',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Autonomous Cost Governance',
    tier: 'enterprise',
    module: 'ECONOMY',
    outcome_summary: 'Organization-wide budget enforcement with automated chargeback and departmental allocation',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cross-Deployment Observability',
    tier: 'enterprise',
    module: 'VISION',
    outcome_summary: 'Unified monitoring across all substrate deployments with centralized dashboards and alerting',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Evolution Sandbox Clusters',
    tier: 'enterprise',
    module: 'SANDBOX',
    outcome_summary: 'Run parallel evolution experiments across sandbox clusters with automated winner selection',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  // ── Wave 2 Enterprise Crown Jewels ──
  {
    name: 'Recursive Planning Intelligence',
    tier: 'enterprise',
    module: 'CORTEX',
    outcome_summary: 'Decompose strategic goals into executable multi-quarter plans with dependency tracking',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Topology Mutation Engine',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Autonomously restructure system topology to optimize for changing workload patterns',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Predictive State Modeling',
    tier: 'enterprise',
    module: 'VISION',
    outcome_summary: 'Model future system states across multiple timelines to enable preemptive action',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Adversarial Simulation',
    tier: 'enterprise',
    module: 'DEFENSE',
    outcome_summary: 'Continuously simulate adversarial attacks against your own infrastructure to find weaknesses',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Episodic Replay Engine',
    tier: 'enterprise',
    module: 'BRAIN',
    outcome_summary: 'Replay past decision sequences to extract patterns and improve future judgment',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Intent Compilation',
    tier: 'enterprise',
    module: 'ENCODE',
    outcome_summary: 'Compile natural language intent directly into optimized executable workflows',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Homeostatic Regulation',
    tier: 'enterprise',
    module: 'CORE',
    outcome_summary: 'Maintain system equilibrium by automatically counteracting destabilizing changes',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Shadow Evolution Tracking',
    tier: 'enterprise',
    module: 'MODERNIZER',
    outcome_summary: 'Track and govern shadow evolution paths to prevent uncontrolled system drift',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Counterfactual Analysis',
    tier: 'enterprise',
    module: 'DREAM',
    outcome_summary: 'Explore "what if" scenarios by simulating alternate decision paths and their outcomes',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Attention Allocation',
    tier: 'enterprise',
    module: 'CORTEX',
    outcome_summary: 'Dynamically allocate cognitive attention across competing priorities based on impact potential',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Entropy Reversal',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Detect and reverse system entropy — automatically restore order from accumulated technical chaos',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Generative Hypothesis Engine',
    tier: 'enterprise',
    module: 'DREAM',
    outcome_summary: 'Generate novel hypotheses from cross-domain pattern synthesis for breakthrough discovery',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Goal Decomposition',
    tier: 'enterprise',
    module: 'CORTEX',
    outcome_summary: 'Break complex objectives into measurable sub-goals with automated progress tracking',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Temporal Reasoning Engine',
    tier: 'enterprise',
    module: 'BRAIN',
    outcome_summary: 'Reason about time-dependent relationships and predict temporal cascading effects',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // WAVE 3 — CREATOR ($9/mo) — 10 new crown jewels
  // ══════════════════════════════════════════════════════
  {
    name: 'Drift Correction Engine',
    tier: 'creator',
    module: 'ENCODE',
    outcome_summary: 'Detect when implementations drift from specs and auto-generate corrective PRs',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Sentiment-Aware Routing',
    tier: 'creator',
    module: 'DECODE',
    outcome_summary: 'Route conversations to the best-fit handler based on detected user sentiment',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Proactive Cache Warming',
    tier: 'creator',
    module: 'BRAIN',
    outcome_summary: 'Pre-warm memory caches by predicting which knowledge will be needed next',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Intelligent Retry Orchestration',
    tier: 'creator',
    module: 'NEXUS',
    outcome_summary: 'Orchestrate retries across providers with exponential backoff and quality thresholds',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Schema Evolution Guard',
    tier: 'creator',
    module: 'ENCODE',
    outcome_summary: 'Validate schema changes against downstream consumers before they deploy',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Anomaly Fingerprinting',
    tier: 'creator',
    module: 'DEFENSE',
    outcome_summary: 'Create unique fingerprints for anomaly patterns to accelerate future detection',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cost-Per-Outcome Tracking',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Track actual cost per business outcome rather than per API call',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Delivery Confirmation Intelligence',
    tier: 'creator',
    module: 'RELAY',
    outcome_summary: 'Verify message delivery and automatically escalate through backup channels',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Dependency Health Radar',
    tier: 'creator',
    module: 'INTEGRATION',
    outcome_summary: 'Continuously scan dependency health and alert on upcoming breaking changes',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Context Window Optimization',
    tier: 'creator',
    module: 'BRAIN',
    outcome_summary: 'Automatically compress and prioritize context to maximize AI response quality',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // WAVE 3 — ARCHITECT ($19/mo) — 18 new crown jewels
  // ══════════════════════════════════════════════════════
  {
    name: 'Cognitive Fatigue Detection',
    tier: 'architect',
    module: 'DECODE',
    outcome_summary: 'Detect user cognitive fatigue and simplify interactions before errors occur',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Phantom Load Detection',
    tier: 'architect',
    module: 'SYSTEM',
    outcome_summary: 'Identify hidden resource consumption from orphaned processes and zombie connections',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cross-Tenant Pattern Sharing',
    tier: 'architect',
    module: 'DREAM',
    outcome_summary: 'Share anonymized improvement patterns across tenants for collective intelligence',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Blast Radius Containment',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Automatically contain security incidents by isolating affected modules in real-time',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Intent Disambiguation Engine',
    tier: 'architect',
    module: 'DECODE',
    outcome_summary: 'Resolve ambiguous user intent using contextual signals and historical patterns',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Regulatory Change Radar',
    tier: 'architect',
    module: 'AUDIT',
    outcome_summary: 'Monitor regulatory changes and auto-flag affected policies before deadlines',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Memory Provenance Tracking',
    tier: 'architect',
    module: 'MEMORY',
    outcome_summary: 'Track the origin and transformation history of every memory for auditability',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Provider Arbitrage Engine',
    tier: 'architect',
    module: 'NEXUS',
    outcome_summary: 'Exploit price differentials across providers while maintaining quality guarantees',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Behavioral Drift Detection',
    tier: 'architect',
    module: 'VISION',
    outcome_summary: 'Detect gradual behavioral changes that individually pass thresholds but collectively signal problems',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Pipeline Fusion Optimizer',
    tier: 'architect',
    module: 'CORTEX',
    outcome_summary: 'Automatically merge redundant pipeline stages to reduce latency and cost',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Privilege Escalation Detection',
    tier: 'architect',
    module: 'ACCESS',
    outcome_summary: 'Detect and block privilege escalation attempts across the entitlement graph',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cognitive Load Shedding',
    tier: 'architect',
    module: 'NERVE',
    outcome_summary: 'Gracefully shed non-critical cognitive load during peak demand to maintain core performance',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Inclusive Language Guard',
    tier: 'architect',
    module: 'INCLUSIVE',
    outcome_summary: 'Scan and suggest inclusive language alternatives across all generated content',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Sandbox Escape Detection',
    tier: 'architect',
    module: 'SANDBOX',
    outcome_summary: 'Detect and prevent sandbox escape attempts with multi-layer containment verification',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Knowledge Graph Healing',
    tier: 'architect',
    module: 'BRAIN',
    outcome_summary: 'Detect and repair broken links and inconsistencies in knowledge graphs automatically',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Revenue Impact Forecasting',
    tier: 'architect',
    module: 'ECONOMY',
    outcome_summary: 'Forecast revenue impact of capability changes before deployment',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Dream Replay Analysis',
    tier: 'architect',
    module: 'DREAM',
    outcome_summary: 'Replay and analyze autonomous dream cycles to extract actionable improvement patterns',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Mutation Impact Scoring',
    tier: 'architect',
    module: 'ENCODE',
    outcome_summary: 'Score the potential impact of code mutations before they enter the test pipeline',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // WAVE 3 — ENTERPRISE (Custom) — 14 new crown jewels
  // ══════════════════════════════════════════════════════
  {
    name: 'Multi-Region Intelligence Sync',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Synchronize intelligence and learning across geographically distributed deployments',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Autonomous Incident Commander',
    tier: 'enterprise',
    module: 'SYSTEM',
    outcome_summary: 'Automatically triage, coordinate, and resolve incidents with minimal human intervention',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cryptographic Audit Chain',
    tier: 'enterprise',
    module: 'AUDIT',
    outcome_summary: 'Immutable cryptographic chain of custody for every decision and data mutation',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Zero-Knowledge Verification',
    tier: 'enterprise',
    module: 'IDENTITY',
    outcome_summary: 'Verify credentials and entitlements without exposing underlying identity data',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Federated Learning Orchestrator',
    tier: 'enterprise',
    module: 'DREAM',
    outcome_summary: 'Coordinate learning across deployments without sharing raw data — privacy-preserving intelligence',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Supply Chain Security Scanner',
    tier: 'enterprise',
    module: 'DEFENSE',
    outcome_summary: 'Continuously scan the full software supply chain for compromised dependencies',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Autonomous Capacity Orchestration',
    tier: 'enterprise',
    module: 'CORTEX',
    outcome_summary: 'Orchestrate capacity across all modules with predictive scaling and cost optimization',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Data Sovereignty Engine',
    tier: 'enterprise',
    module: 'IDENTITY',
    outcome_summary: 'Enforce data residency and sovereignty requirements across jurisdictions automatically',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Executive Intelligence Dashboard',
    tier: 'enterprise',
    module: 'VISION',
    outcome_summary: 'Generate executive-ready intelligence reports with ROI analysis and strategic recommendations',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Compliance Drift Detector',
    tier: 'enterprise',
    module: 'AUDIT',
    outcome_summary: 'Continuously monitor for compliance drift and auto-remediate before violations',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Knowledge Sovereignty Vault',
    tier: 'enterprise',
    module: 'BRAIN',
    outcome_summary: 'Air-gapped knowledge vault with cryptographic access controls and tamper-proof storage',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Multi-Model Consensus Engine',
    tier: 'enterprise',
    module: 'NEXUS',
    outcome_summary: 'Route critical decisions through multiple AI models and require consensus before acting',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Organizational Learning Memory',
    tier: 'enterprise',
    module: 'MEMORY',
    outcome_summary: 'Persist and share organizational learning across teams, projects, and deployments',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Autonomous Migration Planner',
    tier: 'enterprise',
    module: 'MODERNIZER',
    outcome_summary: 'Generate and execute multi-phase migration plans with automated rollback and validation',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // WAVE 4 — CREATOR ($9/mo) — 10 new crown jewels
  // ══════════════════════════════════════════════════════
  {
    name: 'Event Correlation Engine',
    tier: 'creator',
    module: 'RIPPLE',
    outcome_summary: 'Correlate related events across modules to surface hidden cause-and-effect chains',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Tone Calibration Engine',
    tier: 'creator',
    module: 'DECODE',
    outcome_summary: 'Auto-calibrate AI communication tone to match brand voice and audience expectations',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Memory Deduplication',
    tier: 'creator',
    module: 'BRAIN',
    outcome_summary: 'Automatically merge duplicate and near-duplicate memories to keep knowledge clean',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Quality Prediction',
    tier: 'creator',
    module: 'NEXUS',
    outcome_summary: 'Predict AI output quality before generation to pre-select the best model for each task',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Regression Prevention Guard',
    tier: 'creator',
    module: 'ENCODE',
    outcome_summary: 'Detect potential regressions before deployment by analyzing code change impact patterns',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Behavioral Baseline Engine',
    tier: 'creator',
    module: 'DEFENSE',
    outcome_summary: 'Establish behavioral baselines per user to detect deviation and potential compromise',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Waste Detection Engine',
    tier: 'creator',
    module: 'ECONOMY',
    outcome_summary: 'Identify wasted compute, idle resources, and redundant operations to cut costs',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Smart Batching Engine',
    tier: 'creator',
    module: 'RELAY',
    outcome_summary: 'Intelligently batch related notifications and deliveries to reduce noise and improve engagement',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Integration Health Forecasting',
    tier: 'creator',
    module: 'INTEGRATION',
    outcome_summary: 'Forecast integration health trends and predict which connectors will degrade next',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Workflow Suggestion Engine',
    tier: 'creator',
    module: 'ATLAS',
    outcome_summary: 'Suggest optimal workflows based on project patterns and capability usage history',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },

  // ══════════════════════════════════════════════════════
  // WAVE 4 — ARCHITECT ($19/mo) — 18 new crown jewels
  // ══════════════════════════════════════════════════════
  {
    name: 'Threat Prediction Engine',
    tier: 'architect',
    module: 'DEFENSE',
    outcome_summary: 'Predict attack vectors and pre-deploy countermeasures before threats materialize',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cognitive Load Heatmap',
    tier: 'architect',
    module: 'VISION',
    outcome_summary: 'Visualize cognitive load distribution across modules to identify processing bottlenecks',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Semantic Memory Versioning',
    tier: 'architect',
    module: 'MEMORY',
    outcome_summary: 'Version control for memories — track changes, diff states, and rollback knowledge mutations',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Channel Failover Intelligence',
    tier: 'architect',
    module: 'RELAY',
    outcome_summary: 'Automatically failover to backup channels when primary delivery paths degrade',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Compliance Simulation Engine',
    tier: 'architect',
    module: 'AUDIT',
    outcome_summary: 'Simulate compliance audits against draft policies before enforcement to prevent false positives',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Session Forensics Engine',
    tier: 'architect',
    module: 'IDENTITY',
    outcome_summary: 'Reconstruct complete session histories for security investigations with full event replay',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Workflow Compression',
    tier: 'architect',
    module: 'CORTEX',
    outcome_summary: 'Compress multi-step workflows into fewer optimized stages without losing functionality',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Knowledge Aging Engine',
    tier: 'architect',
    module: 'BRAIN',
    outcome_summary: 'Age knowledge entries based on relevance decay and auto-archive stale information',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Innovation Scoring',
    tier: 'architect',
    module: 'DREAM',
    outcome_summary: 'Score dream-cycle outputs by novelty and practical applicability to prioritize implementations',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Behavioral Testing Engine',
    tier: 'architect',
    module: 'ENCODE',
    outcome_summary: 'Generate behavior-driven tests from natural language specifications automatically',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Margin Optimization',
    tier: 'architect',
    module: 'ECONOMY',
    outcome_summary: 'Optimize cost margins across capabilities by rebalancing provider allocation and caching',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Sandbox Resource Prediction',
    tier: 'architect',
    module: 'SANDBOX',
    outcome_summary: 'Predict sandbox resource requirements before execution to prevent OOM and timeout failures',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Neurodiversity Adaptation',
    tier: 'architect',
    module: 'INCLUSIVE',
    outcome_summary: 'Adapt interfaces for neurodivergent users with ADHD, dyslexia, and autism-specific optimizations',
    category: 'compliance',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Signal Prioritization Engine',
    tier: 'architect',
    module: 'NERVE',
    outcome_summary: 'Prioritize inter-module signals by urgency and impact to reduce communication overhead',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Anomalous Usage Detection',
    tier: 'architect',
    module: 'ACCESS',
    outcome_summary: 'Detect anomalous API usage patterns that may indicate credential compromise or abuse',
    category: 'security',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Trend Extrapolation Engine',
    tier: 'architect',
    module: 'VISION',
    outcome_summary: 'Extrapolate system and behavioral trends to forecast future states weeks in advance',
    category: 'observability',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Cultural Adaptation Engine',
    tier: 'architect',
    module: 'DECODE',
    outcome_summary: 'Adapt AI outputs for cultural context including idioms, formality, and regional expectations',
    category: 'intelligence',
    public_safe: true,
    is_crown_jewel: true,
  },
  {
    name: 'Capacity Simulation',
    tier: 'architect',
    module: 'SYSTEM',
    outcome_summary: 'Simulate capacity scenarios to validate scaling decisions before committing resources',
    category: 'optimization',
    public_safe: true,
    is_crown_jewel: true,
  },
];

/** Get capabilities for a specific tier */
export function getCapabilitiesByTier(tier: PublicCapability['tier']): PublicCapability[] {
  return PUBLIC_CAPABILITY_MANIFEST.filter(c => c.tier === tier);
}

/** Get crown jewels for a tier */
export function getCrownJewelsByTier(tier: PublicCapability['tier']): PublicCapability[] {
  return PUBLIC_CAPABILITY_MANIFEST.filter(c => c.tier === tier && c.is_crown_jewel);
}

/** Get capabilities grouped by category */
export function getCapabilitiesByCategory(tier: PublicCapability['tier']): Record<string, PublicCapability[]> {
  const caps = getCapabilitiesByTier(tier);
  return caps.reduce((acc, cap) => {
    if (!acc[cap.category]) acc[cap.category] = [];
    acc[cap.category].push(cap);
    return acc;
  }, {} as Record<string, PublicCapability[]>);
}

/** Outcome-oriented category labels for public display */
export const CATEGORY_LABELS: Record<string, { label: string; icon: string }> = {
  security: { label: 'Threat Protection', icon: '🛡️' },
  intelligence: { label: 'Deep Intelligence', icon: '🧠' },
  optimization: { label: 'Autonomous Optimization', icon: '⚡' },
  compliance: { label: 'Compliance & Governance', icon: '📋' },
  observability: { label: 'Predictive Observability', icon: '👁️' },
};
