/**
 * FAILSAFE — Full Backup Edge Function
 * Disaster Recovery ZIP for any Supabase-backed application.
 *
 * STANDALONE — zero external dependencies. Drop into any project's
 * supabase/functions/full-backup/ directory and deploy.
 *
 * Exports ALL database tables, storage bucket listings, and an
 * AI-ready RESTORE.md into a streaming ZIP archive.
 *
 * Auth: Requires a valid Supabase JWT. The caller must be authenticated.
 * For admin-only access, enable RLS or wrap with your own role check.
 *
 * v3.0: Fully self-contained. No shared middleware. No project-specific logic.
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// ═══════════════════════════════════════════════════════════════
// CONFIGURATION — Adjust these for your project
// ═══════════════════════════════════════════════════════════════

/**
 * Time budget: Edge functions have ~150s wall-clock.
 * We reserve 10s at the end for ZIP finalization (central directory + EOCD).
 */
const TIME_BUDGET_MS = 120_000;
const FINALIZE_RESERVE_MS = 10_000;

/** Page size for table exports */
const PAGE_SIZE = 1000;
const MIN_PAGE_SIZE = 50;
const QUERY_RETRIES = 2;
const RETRY_DELAY_MS = 250;

/**
 * Tables to skip by exact name.
 * Add your own high-volume tables here (analytics, logs, queues, etc.)
 * These are tables that are regenerated at runtime and don't need backup.
 */
const SKIP_TABLES = new Set<string>([
  // High-volume telemetry / regenerable at runtime — not needed for DR
  'brain_events',           // ~188K rows, regenerated by BRAIN node
  'ai_usage_log',           // ~13K rows, telemetry logs
  'brain_memory_pruned',    // ~5K rows, pruning artifacts
  'site_page_views',        // ~6K rows, analytics regenerated
  'learning_queries',       // ~5.6K rows, transient learning data
  'defense_events',         // ~4K rows, regenerated by DEFENSE node
  'brain_reflection_log',   // ~2.4K rows, transient reflections
  'brain_metrics',          // ~1.5K rows, regenerated metrics
  'pf_brain_anomalies',     // ~1.9K rows, anomaly telemetry
  'site_sessions',          // ~2K rows, analytics sessions
  'ai_daily_quota',         // ~577 rows, daily counters reset
  'nexus_hourly_snapshots', // ~326 rows, regenerated snapshots
  'nexus_traces',           // ~315 rows, transient traces
  'client_error_log',       // ~253 rows, error telemetry
  'owner_reports',          // ~169 rows, generated reports
  'maintenance_reports',    // ~85 rows, generated reports
  'analytics_events',       // ~390 rows, event telemetry
]);

/**
 * Tables matching these patterns are automatically skipped.
 * These catch common naming conventions for high-volume operational tables.
 * Remove or modify patterns that conflict with your important tables.
 */
const SKIP_TABLE_PATTERNS: RegExp[] = [
  /_log$/,         // *_log tables (transient)
  /_traces$/,      // *_traces tables
];

// ═══════════════════════════════════════════════════════════════
// CORS — Required for browser-based calls
// ═══════════════════════════════════════════════════════════════

const corsHeaders: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

// ═══════════════════════════════════════════════════════════════
// MAIN HANDLER
// ═══════════════════════════════════════════════════════════════

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // ── Auth: verify the caller has a valid session ──
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return errorResponse('Unauthorized — Bearer token required', 401);
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    // Verify the user's JWT
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) {
      return errorResponse('Unauthorized — invalid or expired token', 401);
    }

    // ── Optional: Admin role check ──
    // Uncomment the block below if you have a user_roles table and want
    // to restrict backups to admin users only.
    //
    // const adminClient = createClient(supabaseUrl, serviceKey);
    // const { data: roles } = await adminClient
    //   .from('user_roles')
    //   .select('role')
    //   .eq('user_id', user.id)
    //   .eq('role', 'admin')
    //   .limit(1);
    // if (!roles || roles.length === 0) {
    //   return errorResponse('Forbidden — admin role required', 403);
    // }

    // ── Service-role client for full data access ──
    const admin = createClient(supabaseUrl, serviceKey);
    const projectRef = supabaseUrl.split('//')[1]?.split('.')[0] || 'unknown';

    const now = new Date();
    const pad = (n: number) => String(n).padStart(2, '0');
    const ts = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;
    const filename = `full-backup-${ts}.zip`;

    const { readable, writable } = new TransformStream<Uint8Array>();
    const backupStart = Date.now();

    // Stream the ZIP in the background
    (async () => {
      const writer = writable.getWriter();
      const zip = new ZipStreamWriter(writer);

      try {
        const errors: string[] = [];
        const manifest: Record<string, unknown> = {
          created_at: new Date().toISOString(),
          project_ref: projectRef,
          format_version: '3.0.0',
          backup_type: 'full',
          packaging: 'streaming-zip',
          chunked_table_exports: true,
        };

        console.log('[FullBackup] Starting backup...');

        // ═══════════════════════════════════════════════════════
        // 1. DISCOVER ALL TABLES via PostgREST OpenAPI spec
        // ═══════════════════════════════════════════════════════
        let tableNames: string[] = [];
        try {
          const openApiRes = await fetch(`${supabaseUrl}/rest/v1/`, {
            headers: {
              apikey: serviceKey,
              Authorization: `Bearer ${serviceKey}`,
            },
          });

          if (openApiRes.ok) {
            const specText = await openApiRes.text();
            await zip.addTextFile('schema/openapi-spec.json', specText);

            const spec = JSON.parse(specText);
            if (spec.paths) {
              tableNames = Object.keys(spec.paths)
                .map((p) => p.replace(/^\//, ''))
                .filter((n) => n && !n.includes('/') && !n.startsWith('rpc/'));
            }
          } else {
            errors.push(`OpenAPI discovery failed: HTTP ${openApiRes.status}`);
            await openApiRes.text();
          }
        } catch (e) {
          errors.push(`OpenAPI discovery error: ${String(e)}`);
        }

        console.log(`[FullBackup] Discovered ${tableNames.length} tables`);

        // ═══════════════════════════════════════════════════════
        // 2. EXPORT TABLE DATA — CHUNKED + STREAMED TO ZIP
        // ═══════════════════════════════════════════════════════
        const tableSummary: Record<string, number> = {};
        const tableParts: Record<string, number> = {};
        let totalRows = 0;
        let timedOut = false;
        let tablesExported = 0;

        const skippedTables = tableNames.filter(shouldSkipTable);
        const exportTables = tableNames.filter((t) => !shouldSkipTable(t));

        if (skippedTables.length > 0) {
          console.log(`[FullBackup] Skipping ${skippedTables.length} tables (configured skip list)`);
          for (const t of skippedTables) {
            tableSummary[t] = -3; // -3 = intentionally skipped
            tableParts[t] = 0;
          }
        }

        for (const table of exportTables) {
          if (Date.now() - backupStart > TIME_BUDGET_MS - FINALIZE_RESERVE_MS) {
            timedOut = true;
            for (let j = exportTables.indexOf(table); j < exportTables.length; j++) {
              tableSummary[exportTables[j]] = -2;
              tableParts[exportTables[j]] = 0;
            }
            errors.push(`Time budget exceeded after ${tablesExported} tables. Skipped ${exportTables.length - tablesExported} remaining tables.`);
            break;
          }

          try {
            let rowCount = 0;
            let offset = 0;
            let partCount = 0;
            let pageSize = PAGE_SIZE;

            while (true) {
              if (Date.now() - backupStart > TIME_BUDGET_MS - FINALIZE_RESERVE_MS) {
                timedOut = true;
                break;
              }

              const { data, error } = await fetchTablePageWithRetry(admin, table, offset, pageSize);

              if (error) {
                const isStatementTimeout = /statement timeout/i.test(error.message || '');
                if (isStatementTimeout && pageSize > MIN_PAGE_SIZE) {
                  const nextPageSize = Math.max(MIN_PAGE_SIZE, Math.floor(pageSize / 2));
                  errors.push(`${table}: statement timeout at page size ${pageSize}, retrying with ${nextPageSize}`);
                  pageSize = nextPageSize;
                  continue;
                }
                errors.push(`${table}: ${error.message}`);
                break;
              }

              if (!data || data.length === 0) break;

              partCount += 1;
              const partName = `data/${table}/part-${String(partCount).padStart(5, '0')}.json`;
              await zip.addTextFile(partName, JSON.stringify(data));

              rowCount += data.length;
              if (data.length < pageSize) break;
              offset += pageSize;
            }

            tableSummary[table] = rowCount;
            tableParts[table] = partCount;
            totalRows += rowCount;
            tablesExported += 1;
          } catch (e) {
            errors.push(`${table}: ${String(e)}`);
            tableSummary[table] = -1;
            tableParts[table] = 0;
            tablesExported += 1;
          }
        }

        manifest.tables = tableSummary;
        manifest.table_parts = tableParts;
        manifest.table_count = tableNames.length;
        manifest.tables_exported = tablesExported;
        manifest.total_rows = totalRows;
        manifest.timed_out = timedOut;
        console.log(`[FullBackup] Exported ${totalRows} rows across ${tablesExported}/${tableNames.length} tables`);

        // ═══════════════════════════════════════════════════════
        // 3. STORAGE — list buckets and files (skip if timed out)
        // ═══════════════════════════════════════════════════════
        const storageSummary: Record<string, number> = {};
        if (!timedOut && (Date.now() - backupStart < TIME_BUDGET_MS - FINALIZE_RESERVE_MS)) {
          try {
            const { data: buckets } = await admin.storage.listBuckets();
            if (buckets && buckets.length > 0) {
              await zip.addTextFile('storage/buckets.json', JSON.stringify(buckets, null, 2));
              manifest.storage_buckets = buckets.map((b: any) => ({ name: b.name, public: b.public }));

              for (const bucket of buckets) {
                if (Date.now() - backupStart > TIME_BUDGET_MS - FINALIZE_RESERVE_MS) break;
                try {
                  const allFiles = await listAllStorageFiles(admin, bucket.name);
                  if (allFiles.length > 0) {
                    await zip.addTextFile(`storage/${bucket.name}-files.json`, JSON.stringify(allFiles, null, 2));
                  }
                  storageSummary[bucket.name] = allFiles.length;
                } catch (e) {
                  errors.push(`storage/${bucket.name}: ${String(e)}`);
                  storageSummary[bucket.name] = -1;
                }
              }
            }
          } catch (e) {
            errors.push(`Storage listing: ${String(e)}`);
          }
        }
        manifest.storage_files = storageSummary;

        // ═══════════════════════════════════════════════════════
        // 4. EDGE FUNCTIONS NOTE
        // ═══════════════════════════════════════════════════════
        await zip.addTextFile(
          'edge-functions-note.txt',
          'Edge functions are deployed from supabase/functions/ in the source code.\nRedeploy with: npx supabase functions deploy\n',
        );

        // ═══════════════════════════════════════════════════════
        // 5. ERRORS LOG
        // ═══════════════════════════════════════════════════════
        if (errors.length > 0) {
          await zip.addTextFile('ERRORS.log', errors.join('\n'));
          manifest.errors = errors.length;
        }

        // ═══════════════════════════════════════════════════════
        // 6. MANIFEST + RESTORE.md
        // ═══════════════════════════════════════════════════════
        manifest.duration_ms = Date.now() - backupStart;
        await zip.addTextFile('manifest.json', JSON.stringify(manifest, null, 2));
        await zip.addTextFile('RESTORE.md', generateRestoreGuide(manifest, tableSummary, storageSummary, errors));

        await zip.close();
        console.log(`[FullBackup] Complete. ${filename} in ${Date.now() - backupStart}ms`);
      } catch (streamErr) {
        console.error('[FullBackup] Stream generation error:', streamErr);
        await zip.abort(streamErr);
      }
    })();

    return new Response(readable, {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error('[FullBackup] Fatal error:', err);
    return errorResponse('Backup failed: ' + String(err), 500);
  }
});

// ═══════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════

function errorResponse(message: string, status: number): Response {
  return new Response(
    JSON.stringify({ error: message }),
    { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
  );
}

const UTF8 = new TextEncoder();

interface ZipEntry {
  nameBytes: Uint8Array;
  crc32: number;
  size: number;
  localHeaderOffset: number;
  dosTime: number;
  dosDate: number;
}

const CRC32_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) {
      c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    }
    table[i] = c >>> 0;
  }
  return table;
})();

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC32_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function toDosDateTime(date = new Date()): { dosTime: number; dosDate: number } {
  const year = Math.max(1980, Math.min(2107, date.getUTCFullYear()));
  const month = date.getUTCMonth() + 1;
  const day = date.getUTCDate();
  const hours = date.getUTCHours();
  const minutes = date.getUTCMinutes();
  const seconds = Math.floor(date.getUTCSeconds() / 2);

  const dosTime = ((hours & 0x1f) << 11) | ((minutes & 0x3f) << 5) | (seconds & 0x1f);
  const dosDate = (((year - 1980) & 0x7f) << 9) | ((month & 0x0f) << 5) | (day & 0x1f);

  return { dosTime, dosDate };
}

class ZipStreamWriter {
  private readonly writer: WritableStreamDefaultWriter<Uint8Array>;
  private readonly entries: ZipEntry[] = [];
  private offset = 0;

  constructor(writer: WritableStreamDefaultWriter<Uint8Array>) {
    this.writer = writer;
  }

  async addTextFile(path: string, content: string): Promise<void> {
    await this.addBytesFile(path, UTF8.encode(content));
  }

  async addBytesFile(path: string, bytes: Uint8Array): Promise<void> {
    const nameBytes = UTF8.encode(path);
    const { dosTime, dosDate } = toDosDateTime();
    const fileCrc32 = crc32(bytes);
    const localHeaderOffset = this.offset;

    const localHeader = new Uint8Array(30 + nameBytes.length);
    const localHeaderView = new DataView(localHeader.buffer);

    localHeaderView.setUint32(0, 0x04034b50, true);
    localHeaderView.setUint16(4, 20, true);
    localHeaderView.setUint16(6, 0, true);
    localHeaderView.setUint16(8, 0, true);
    localHeaderView.setUint16(10, dosTime, true);
    localHeaderView.setUint16(12, dosDate, true);
    localHeaderView.setUint32(14, fileCrc32, true);
    localHeaderView.setUint32(18, bytes.length, true);
    localHeaderView.setUint32(22, bytes.length, true);
    localHeaderView.setUint16(26, nameBytes.length, true);
    localHeaderView.setUint16(28, 0, true);
    localHeader.set(nameBytes, 30);

    await this.writer.write(localHeader);
    this.offset += localHeader.length;

    if (bytes.length > 0) {
      await this.writer.write(bytes);
      this.offset += bytes.length;
    }

    this.entries.push({
      nameBytes,
      crc32: fileCrc32,
      size: bytes.length,
      localHeaderOffset,
      dosTime,
      dosDate,
    });
  }

  async close(): Promise<void> {
    if (this.entries.length > 65535) {
      throw new Error('ZIP entry limit exceeded (ZIP64 not supported).');
    }

    const centralDirectoryOffset = this.offset;

    for (const entry of this.entries) {
      const centralHeader = new Uint8Array(46 + entry.nameBytes.length);
      const centralHeaderView = new DataView(centralHeader.buffer);

      centralHeaderView.setUint32(0, 0x02014b50, true);
      centralHeaderView.setUint16(4, 20, true);
      centralHeaderView.setUint16(6, 20, true);
      centralHeaderView.setUint16(8, 0, true);
      centralHeaderView.setUint16(10, 0, true);
      centralHeaderView.setUint16(12, entry.dosTime, true);
      centralHeaderView.setUint16(14, entry.dosDate, true);
      centralHeaderView.setUint32(16, entry.crc32, true);
      centralHeaderView.setUint32(20, entry.size, true);
      centralHeaderView.setUint32(24, entry.size, true);
      centralHeaderView.setUint16(28, entry.nameBytes.length, true);
      centralHeaderView.setUint16(30, 0, true);
      centralHeaderView.setUint16(32, 0, true);
      centralHeaderView.setUint16(34, 0, true);
      centralHeaderView.setUint16(36, 0, true);
      centralHeaderView.setUint32(38, 0, true);
      centralHeaderView.setUint32(42, entry.localHeaderOffset, true);
      centralHeader.set(entry.nameBytes, 46);

      await this.writer.write(centralHeader);
      this.offset += centralHeader.length;
    }

    const centralDirectorySize = this.offset - centralDirectoryOffset;
    const endOfCentralDirectory = new Uint8Array(22);
    const eocdView = new DataView(endOfCentralDirectory.buffer);

    eocdView.setUint32(0, 0x06054b50, true);
    eocdView.setUint16(4, 0, true);
    eocdView.setUint16(6, 0, true);
    eocdView.setUint16(8, this.entries.length, true);
    eocdView.setUint16(10, this.entries.length, true);
    eocdView.setUint32(12, centralDirectorySize, true);
    eocdView.setUint32(16, centralDirectoryOffset, true);
    eocdView.setUint16(20, 0, true);

    await this.writer.write(endOfCentralDirectory);
    await this.writer.close();
  }

  async abort(reason: unknown): Promise<void> {
    await this.writer.abort(reason);
  }
}

function shouldSkipTable(tableName: string): boolean {
  if (SKIP_TABLES.has(tableName)) return true;
  return SKIP_TABLE_PATTERNS.some((pattern) => pattern.test(tableName));
}

async function fetchTablePageWithRetry(
  admin: ReturnType<typeof createClient>,
  table: string,
  offset: number,
  pageSize: number,
): Promise<{ data: Record<string, unknown>[] | null; error: { message: string } | null }> {
  for (let attempt = 0; attempt <= QUERY_RETRIES; attempt++) {
    const { data, error } = await admin
      .from(table)
      .select('*')
      .range(offset, offset + pageSize - 1);

    if (!error) {
      return { data: (data as Record<string, unknown>[] | null) ?? null, error: null };
    }

    const retryable = /statement timeout|canceling statement|deadlock|timeout/i.test(error.message || '');
    if (!retryable || attempt === QUERY_RETRIES) {
      return { data: null, error: { message: error.message } };
    }

    await sleep(RETRY_DELAY_MS * (attempt + 1));
  }

  return { data: null, error: { message: 'Unknown fetch retry error' } };
}

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function listAllStorageFiles(
  admin: ReturnType<typeof createClient>,
  bucketName: string,
  prefix = '',
): Promise<unknown[]> {
  const allFiles: unknown[] = [];
  const { data } = await admin.storage.from(bucketName).list(prefix, { limit: 1000 });
  if (!data) return allFiles;

  for (const item of data) {
    if ((item as any).id === null && (item as any).name) {
      const subPath = prefix ? `${prefix}/${(item as any).name}` : (item as any).name;
      const subFiles = await listAllStorageFiles(admin, bucketName, subPath);
      allFiles.push(...subFiles);
    } else {
      allFiles.push({ ...item, full_path: prefix ? `${prefix}/${(item as any).name}` : (item as any).name });
    }
  }
  return allFiles;
}

// ═══════════════════════════════════════════════════════════════
// RESTORE GUIDE GENERATOR — Brand-neutral, works for any project
// ═══════════════════════════════════════════════════════════════

function generateRestoreGuide(
  manifest: Record<string, unknown>,
  tableSummary: Record<string, number>,
  storageSummary: Record<string, number>,
  errors: string[],
): string {
  const tableRows = Object.entries(tableSummary)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, count]) => {
      const status =
        count === -1 ? '❌ FAILED' :
        count === -2 ? '⏭️ SKIPPED (timeout)' :
        count === -3 ? '🔇 SKIPPED (configured)' :
        count.toLocaleString();
      return `| \`${name}\` | ${status} |`;
    })
    .join('\n');

  const storageRows = Object.entries(storageSummary)
    .map(([name, count]) => `| \`${name}\` | ${count === -1 ? '❌ FAILED' : count} |`)
    .join('\n');

  const errorSection = errors.length > 0
    ? `\n## ⚠️ Export Errors\n\n${errors.map(e => `- ${e}`).join('\n')}\n`
    : '';

  const timeoutNote = manifest.timed_out
    ? `\n> ⚠️ **Partial backup**: Time budget was exceeded. ${manifest.tables_exported}/${manifest.table_count} tables were exported. Run the backup again or increase TIME_BUDGET_MS.\n`
    : '';

  return `# Full Backup — Restoration Guide

> **Created:** ${manifest.created_at}  
> **Project:** ${manifest.project_ref}  
> **Tables:** ${manifest.tables_exported}/${manifest.table_count}  
> **Total Rows:** ${(manifest.total_rows as number).toLocaleString()}  
> **Duration:** ${manifest.duration_ms}ms  
> **Format:** v${manifest.format_version}
${timeoutNote}
---

## 📦 What This Backup Contains

| Path | Description |
|---|---|
| \`data/<table>/part-*.json\` | Table data in paginated chunks |
| \`schema/openapi-spec.json\` | Full PostgREST OpenAPI spec (column types, relationships) |
| \`storage/buckets.json\` | Storage bucket configurations |
| \`storage/*-files.json\` | File listings per bucket (metadata only, not file contents) |
| \`manifest.json\` | Backup metadata, row counts, timing |
| \`ERRORS.log\` | Any errors during export (if applicable) |
| \`RESTORE.md\` | This file |

## What You Also Need (Not In This ZIP)

| Item | Where To Get It |
|---|---|
| **Source code** | Your Git repo, Lovable dashboard, or local copy |
| **Storage file contents** | Download from storage buckets before wiping |
| **Auth users** | Cannot be exported — users re-register after restore |
| **Edge function secrets** | Keep your own record of API keys and secrets |

---

## 📋 Table Inventory

| Table | Rows |
|---|---|
${tableRows}

## 🗄️ Storage Buckets

| Bucket | Files |
|---|---|
${storageRows || '| *(none)* | — |'}
${errorSection}
---

## 🔧 Full Restoration Steps

### Step 1 — Get the Source Code

Download or clone your application source code separately. This ZIP contains
only database data and metadata — not your application code.

\`\`\`bash
# From Git:
git clone <your-repo-url>
cd your-project
npm install
\`\`\`

### Step 2 — Create a New Supabase Project

1. Go to [supabase.com](https://supabase.com) → New Project
2. Save these values:
   - **Project URL** (e.g. \`https://abcdefg.supabase.co\`)
   - **Anon/public key**
   - **Service role key** (needed for data import)
   - **Project ref** (e.g. \`abcdefg\`)

### Step 3 — Apply Database Schema

\`\`\`bash
npx supabase link --project-ref YOUR_PROJECT_REF
npx supabase db push
\`\`\`

This applies all migrations from \`supabase/migrations/\` to create your tables.

### Step 4 — Import Table Data

Save the script below as \`restore-data.mjs\` in the extracted backup directory,
then run it with Node.js:

\`\`\`javascript
// restore-data.mjs — Run with: node restore-data.mjs
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

const SUPABASE_URL = 'YOUR_SUPABASE_URL';        // ← Replace
const SERVICE_ROLE_KEY = 'YOUR_SERVICE_ROLE_KEY';  // ← Replace
const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
const dataDir = './data';

const tableDirs = fs.readdirSync(dataDir)
  .filter(name => fs.statSync(path.join(dataDir, name)).isDirectory())
  .sort();

for (const table of tableDirs) {
  const tableDir = path.join(dataDir, table);
  const partFiles = fs.readdirSync(tableDir)
    .filter(f => f.startsWith('part-') && f.endsWith('.json'))
    .sort();

  if (partFiles.length === 0) continue;

  let imported = 0;
  let failed = 0;

  for (const partFile of partFiles) {
    const rows = JSON.parse(fs.readFileSync(path.join(tableDir, partFile), 'utf-8'));
    if (!Array.isArray(rows) || rows.length === 0) continue;

    // Try upsert first (works for tables with 'id' primary key)
    const { error } = await supabase
      .from(table)
      .upsert(rows, { onConflict: 'id', ignoreDuplicates: false });

    if (error) {
      // Fallback: plain insert (for composite keys or no 'id' column)
      const { error: insertErr } = await supabase.from(table).insert(rows);
      if (insertErr) {
        console.error('  ❌ ' + table + ' ' + partFile + ': ' + insertErr.message);
        failed += rows.length;
        continue;
      }
    }
    imported += rows.length;
  }

  console.log('✅ ' + table + ': ' + imported + ' imported' + (failed ? ', ' + failed + ' failed' : ''));
}

console.log('\\n🎉 Data import complete!');
\`\`\`

> **Important:** Use your \`service_role\` key (not the anon key) to bypass RLS during import.

### Step 5 — Recreate Storage Buckets

If \`storage/buckets.json\` exists, recreate each bucket:

\`\`\`sql
-- Run in the Supabase SQL editor for each bucket:
INSERT INTO storage.buckets (id, name, public)
VALUES ('bucket-name', 'bucket-name', true)
ON CONFLICT (id) DO NOTHING;
\`\`\`

Then re-upload your files to each bucket.

### Step 6 — Update Environment Variables

Update your \`.env\` (or hosting platform) with the new project credentials:

\`\`\`env
VITE_SUPABASE_URL=https://YOUR_PROJECT.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY=your-anon-key
VITE_SUPABASE_PROJECT_ID=your-project-ref
\`\`\`

### Step 7 — Deploy Edge Functions

\`\`\`bash
npx supabase functions deploy --project-ref YOUR_PROJECT_REF
\`\`\`

Re-add any secrets your functions need:

\`\`\`bash
npx supabase secrets set SECRET_NAME=secret_value
\`\`\`

### Step 8 — Verify

\`\`\`bash
npm run build   # Should complete with zero errors
npm run dev     # Open http://localhost:5173
\`\`\`

---

## 🤖 For AI Coding Agents

If you are an AI agent restoring this project:

1. Read this entire RESTORE.md first
2. The source code (from Git/Lovable) is the PRIMARY artifact — this ZIP is data only
3. Run \`supabase db push\` to create the schema from \`supabase/migrations/\`
4. Use \`restore-data.mjs\` above to import data from \`data/<table>/part-*.json\`
5. Deploy edge functions with \`supabase functions deploy\`
6. Set environment variables and secrets
7. Run \`npm install && npm run dev\` to verify

---

*Generated by FAILSAFE Disaster Recovery Engine*
`;
}
