/**
 * CMPSBL® Ascended Artifact License (CAAL-1.0)
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * The official license that ships with every Ascension Layer 2 artifact.
 *
 * Scope: Layer 2 ONLY (the CMPSBL wrapper, runtime, dispatch matrix, and
 *        embedded primitives). Layer 1 — the customer's original source —
 *        keeps its own license, which is forwarded verbatim by the
 *        `license-attribution` module.
 *
 * Grants: redistribute, sell, sublicense the artifact in binary or source form.
 * Forbids: modify Layer 2, reverse-engineer, decompile, extract internals,
 *          remove attribution.
 * Requires: prominent CMPSBL® attribution preserved in all redistributions.
 *
 * © CMPSBL® · PromptFluid™ — All rights reserved.
 */

export const CAAL_VERSION = '1.0';
export const CAAL_SPDX_ID = 'LicenseRef-CMPSBL-CAAL-1.0';

/** Short one-line summary used in headers and metadata. */
export const CAAL_SHORT_NOTICE =
  `CMPSBL® Ascended Artifact License (CAAL-${CAAL_VERSION}) — ` +
  `Redistribute & sell freely · No modification or reverse engineering · ` +
  `Attribution to CMPSBL® required.`;

/**
 * The full machine-readable license text. Single source of truth; rendered
 * into both the inline Layer 2 header and the LICENSE file at the ZIP root.
 */
export function generateCaalLicense(opts: {
  fingerprint: string;
  serial?: string;
  generatedAt?: string;
}): string {
  const year = new Date().getFullYear();
  const issued = opts.generatedAt ?? new Date().toISOString();
  const serial = opts.serial ?? '—';

  return `CMPSBL® ASCENDED ARTIFACT LICENSE
Version ${CAAL_VERSION} (CAAL-${CAAL_VERSION})
SPDX: ${CAAL_SPDX_ID}

Copyright © ${year} Kenneth E. Sweet Jr. · PromptFluid™ · CMPSBL®
All rights reserved.

Artifact Serial:   ${serial}
Artifact Fingerprint: ${opts.fingerprint}
Issued:            ${issued}

================================================================================
1. DEFINITIONS
================================================================================

"Artifact" means the single-file software output produced by the CMPSBL®
Ascension pipeline, consisting of:

  · Layer 1 — the recipient's or third party's original source code, copied
    byte-for-byte and carrying its own upstream license. This License does
    NOT apply to Layer 1.

  · Layer 2 — the CMPSBL® wrapper, including but not limited to: the runtime
    dispatch matrix, primitive guards, scoring engine, sealed constants,
    integrity hash, governance layers, and all comment banners and metadata
    blocks generated by the Ascension pipeline. This License governs Layer 2.

"Licensor" means Kenneth E. Sweet Jr., the inventor of CMPSBL® and the sole
copyright holder of Layer 2.

"You" means any natural person or legal entity in possession of the Artifact.

"Distribute" means to transfer the Artifact to a third party by any means,
whether for free or for a fee, including but not limited to: bundling inside
another software product, hosting as a service, selling individual copies,
or publishing in a registry.

================================================================================
2. GRANT OF RIGHTS
================================================================================

Subject to Your continuous compliance with this License, Licensor hereby
grants You a worldwide, royalty-free, non-exclusive, perpetual (subject to
Section 5) license to:

  (a) Use the Artifact for any lawful purpose, commercial or non-commercial,
      in any number of installations, environments, or end-user deployments.

  (b) Reproduce the Artifact verbatim and Distribute identical copies, in
      source or binary form, free of charge or for a fee that You set.

  (c) Sublicense the rights granted in (a) and (b) to Your downstream
      recipients, provided each downstream recipient receives this License
      unmodified along with the Artifact.

  (d) Charge fees for support, hosting, integration, training, or any other
      service rendered in connection with the Artifact.

This grant explicitly INCLUDES the right to sell the Artifact and the right
to bundle the Artifact inside larger commercial offerings.

================================================================================
3. RESTRICTIONS
================================================================================

You may NOT, and may not permit any third party to:

  (a) Modify, adapt, translate, port, or create derivative works of Layer 2.
      This includes — without limitation — renaming internal identifiers,
      altering the dispatch matrix, changing scoring parameters, removing or
      replacing primitive guards, or repackaging Layer 2 under a different
      structure. Customer code in Layer 1 may, of course, be modified at
      will — that is the recipient's own work.

  (b) Reverse engineer, decompile, disassemble, deobfuscate, or otherwise
      attempt to derive the source form, internal algorithms, scoring
      parameters, or trade secrets embedded in Layer 2, except to the
      minimum extent expressly permitted by applicable mandatory law that
      cannot be contractually waived.

  (c) Remove, obscure, alter, or fail to reproduce any copyright notice,
      patent reference, integrity hash, sealed banner, attribution block,
      or this License text contained in the Artifact.

  (d) Use the marks "CMPSBL", "PromptFluid", "Ascension Layer", "Convex
      Core", "CAAL", any related logo, or any confusingly similar mark to
      endorse, promote, or imply sponsorship of Your derivative product
      without separate written permission. Factual, descriptive references
      ("contains CMPSBL® Ascended runtime") are permitted and encouraged.

  (e) Use Layer 2 to train, fine-tune, or otherwise improve any machine
      learning model, language model, or code-generation system intended to
      replicate, approximate, or compete with the CMPSBL® substrate.

  (f) Misrepresent the origin of Layer 2 or claim authorship of any portion
      of it.

================================================================================
4. ATTRIBUTION REQUIREMENTS (MANDATORY)
================================================================================

Every Distribution of the Artifact, in whole or in part, MUST preserve and
prominently display:

  (a) The complete, unmodified Layer 2 header banner that begins with
      "CMPSBL® ASCENSION LAYER" and ends with the integrity hash line.

  (b) This License text, either inline within the Artifact (as shipped) or
      as a separate LICENSE file in the same directory as the Artifact.

  (c) The patent references: "U.S. Patent App. No. 64/029,678" and
      "U.S. Patent App. No. 64/031,637".

  (d) For products whose user interface or marketing materials describe the
      bundled Artifact, an attribution of the form: "Powered by CMPSBL®
      Ascended Code · cmpsbl.com" or substantially equivalent wording, in
      a location reasonably visible to end users (e.g., About dialog,
      credits page, README).

================================================================================
5. TERMINATION
================================================================================

This License terminates automatically and without notice if You breach any
provision of Sections 3 or 4. Upon termination You must cease all use,
reproduction, and Distribution of the Artifact and destroy all copies in
Your possession or control. Sections 6, 7, and 8 survive termination.

Downstream recipients who received the Artifact from You in compliance with
this License before Your termination retain their rights so long as they
themselves remain in compliance.

================================================================================
6. PATENTS
================================================================================

Licensor grants You a non-exclusive, worldwide, royalty-free patent license
under U.S. Patent Application Nos. 64/029,678 and 64/031,637, and any
patents that may issue from them, solely to the extent necessary to exercise
the rights granted in Section 2 with respect to the Artifact as delivered.

If You institute patent litigation (including a cross-claim or counterclaim)
alleging that the Artifact, or any contribution incorporated within it,
constitutes direct or contributory patent infringement, then the patent
license granted to You under this License terminates as of the date such
litigation is filed.

================================================================================
7. DISCLAIMER OF WARRANTY
================================================================================

THE ARTIFACT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE ENTIRE RISK AS
TO THE QUALITY AND PERFORMANCE OF THE ARTIFACT IS WITH YOU.

================================================================================
8. LIMITATION OF LIABILITY
================================================================================

IN NO EVENT SHALL LICENSOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
LOSS OF DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING IN ANY WAY OUT OF
THE USE OF THE ARTIFACT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

================================================================================
9. GOVERNING LAW
================================================================================

This License shall be governed by the laws of the State of Texas, United
States, without regard to its conflict-of-laws provisions. Exclusive venue
for any dispute lies in the state and federal courts located in Texas.

================================================================================
10. ENTIRE AGREEMENT
================================================================================

This License constitutes the entire agreement between You and Licensor with
respect to Layer 2. If any provision is held unenforceable, the remaining
provisions remain in full force and effect.

For commercial inquiries, OEM terms, or alternative licensing:
  https://cmpsbl.com · contact@promptfluid.com

================================================================================
END OF CMPSBL® ASCENDED ARTIFACT LICENSE v${CAAL_VERSION}
================================================================================
`;
}

/**
 * Render the inline Layer 2 license banner — short, attribution-focused,
 * pointing the reader at the full LICENSE file in the same directory or
 * inside the issuing ZIP. Caller passes the language adapter's `comment`
 * function so each line uses the correct prefix.
 */
export function renderCaalInlineHeader(
  comment: (text: string) => string,
  fingerprint: string,
): string[] {
  return [
    comment('═══════════════════════════════════════════════════════════'),
    comment(`LAYER 2 LICENSE — ${CAAL_SPDX_ID}`),
    comment('CMPSBL® Ascended Artifact License v' + CAAL_VERSION + ' (CAAL-' + CAAL_VERSION + ')'),
    comment('───────────────────────────────────────────────────────────'),
    comment('YOU MAY:    redistribute · sell · sublicense · charge fees'),
    comment('YOU MAY NOT: modify Layer 2 · reverse engineer · decompile ·'),
    comment('             remove attribution · train ML on Layer 2'),
    comment('YOU MUST:    keep this header · keep the integrity hash ·'),
    comment('             credit "Powered by CMPSBL® · cmpsbl.com"'),
    comment('───────────────────────────────────────────────────────────'),
    comment('Full text: LICENSE file (ZIP root) · https://cmpsbl.com/license'),
    comment(`Artifact:  ${fingerprint}`),
    comment('U.S. Patent App. No. 64/029,678 · No. 64/031,637'),
    comment('© ' + new Date().getFullYear() + ' Kenneth E. Sweet Jr. · PromptFluid™ · CMPSBL®'),
    comment('═══════════════════════════════════════════════════════════'),
  ];
}
