/**
 * AI Template Generator — Premium Marketplace Feature
 * Generate unique random templates with AI
 * Pack-aware: generates degraded baseline-safe templates when required packs are inactive
 */

import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  Sparkles, Dices, Crown, Lock, Download, Zap, Star, Gift,
  Brain, Shield, Moon, Eye, MessageSquare, Settings, Cpu, Globe,
  ArrowRight, Check, Loader2, Copy, AlertTriangle, Package
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { openCheckoutRedirect } from "@/lib/checkout/checkoutRedirect";
import { evaluateTemplatePolicy, generateRequirementsBlock, buildAuditEntry, type TemplatePolicy } from "@/lib/quarry/template-policy";
import { useArtifactSlots } from "@/hooks/useArtifactSlots";
import {
  GENERATOR_CONFIG,
  RARITY_TIERS,
  formatValueRange,
  formatExpectedValue,
  getGeneratorValueMultiplier
} from "@/config/marketplace-rarity";

// Stripe product/price for the generator - $87 (Rare floor)
const GENERATOR_PRICE_ID = 'price_1Stkx6Q7FtTiAL4aHfmaRUyc';
const GENERATOR_PRODUCT_ID = 'prod_TrTuiFPK6wjaNt';
const GENERATOR_PRICE = 8700; // $87 - Rare tier floor price

// Template generation constants for display
const CATEGORIES = ['Brain', 'Decode', 'Defense', 'Nexus', 'Vision', 'Dream', 'System', 'Integration', 'Cortex'];
const DIFFICULTIES = ['Beginner', 'Intermediate', 'Advanced', 'Premium', 'Elite', 'Pro'];

// Use rarity tiers from config
const RARITIES = RARITY_TIERS.map(r => ({
  name: r.label,
  color: r.color,
  chance: `${Math.round(r.dropChance * 100)}%`,
  priceRange: `$${(r.priceRange.min / 100).toFixed(0)}-$${(r.priceRange.max / 100).toFixed(0)}`,
}));

// Calculate total combinations
const TOTAL_COMBINATIONS = GENERATOR_CONFIG.totalCombinations;
const FORMATTED_COMBINATIONS = TOTAL_COMBINATIONS.toLocaleString();

interface GeneratedTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  difficulty: string;
  rarity: string;
  features: string[];
  code: string;
  estimatedTime: string;
  useCase: string;
  estimatedValue: string;
}

interface AITemplateGeneratorProps {
  featured?: boolean;
}

export function AITemplateGenerator({ featured = false }: AITemplateGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCheckingOut, setIsCheckingOut] = useState(false);
  const [generatedTemplate, setGeneratedTemplate] = useState<GeneratedTemplate | null>(null);
  const [showResult, setShowResult] = useState(false);
  const { activePacks } = useArtifactSlots();
  const activePackIds = useMemo(() => new Set(activePacks.map(p => p.pack_id)), [activePacks]);

  const handleCheckout = () => {
    setIsCheckingOut(true);

    try {
      openCheckoutRedirect({
        fn: 'marketplace-checkout',
        body: {
          product_type: 'template',
          price_id: GENERATOR_PRICE_ID,
          product_id: GENERATOR_PRODUCT_ID,
          template_name: 'AI Template Generator - Random Unique Template',
          item_name: 'AI Template Generator',
          unit_amount_usd: Math.round(GENERATOR_PRICE / 100),
        },
      });

      toast.success('Opening secure checkout…');
    } catch (error) {
      console.error('Checkout error:', error);
      toast.error('Checkout failed. Please try again.');
    } finally {
      setIsCheckingOut(false);
    }
  };

  const handleGenerate = async (sessionId: string) => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('marketplace-generate-template', {
        body: { session_id: sessionId },
      });

      if (error) throw error;
      if (!data?.success) throw new Error(data?.error || 'Generation failed');
      
      setGeneratedTemplate(data.template);
      setShowResult(true);
      toast.success(`Generated: ${data.template.name}!`);
      
    } catch (error) {
      console.error('Generation error:', error);
      toast.error('Failed to generate template. Please contact support.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!generatedTemplate) return;

    // Evaluate pack policy for this template's category
    const policy = evaluateTemplatePolicy(generatedTemplate.category, activePackIds);
    const requirementsBlock = generateRequirementsBlock(policy);

    // Log audit entry
    const audit = buildAuditEntry(generatedTemplate.category, policy, generatedTemplate.id);
    console.info('[TemplateGenerator] Audit:', audit);
    
    const content = `/**
 * ${generatedTemplate.name}
 * Generated by CMPSBL AI Template Generator
 * 
 * Category: ${generatedTemplate.category}
 * Difficulty: ${generatedTemplate.difficulty}
 * Rarity: ${generatedTemplate.rarity}
 * Estimated Value: ${generatedTemplate.estimatedValue}
 * Generation Mode: ${policy.mode === 'full' ? 'Full (all packs active)' : 'Degraded (missing packs)'}
 * 
 * Features:
${generatedTemplate.features.map(f => ` * - ${f}`).join('\n')}
 * 
 * Use Case: ${generatedTemplate.useCase}
 */

${requirementsBlock}${generatedTemplate.code}
`;
    
    const blob = new Blob([content], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedTemplate.id}.ts`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success(policy.mode === 'full' ? 'Full template downloaded!' : 'Baseline template downloaded — activate packs for full version');
  };

  const handleCopyCode = () => {
    if (!generatedTemplate) return;
    navigator.clipboard.writeText(generatedTemplate.code);
    toast.success('Code copied to clipboard!');
  };

  return (
    <section id="ai-generator" className={`relative overflow-hidden ${featured ? 'py-12 sm:py-16' : 'py-8'}`}>
      {/* Background Effects - hidden on mobile for performance */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-neon-purple/5" />
        <motion.div 
          animate={{ rotate: 360 }}
          transition={{ duration: 120, repeat: Infinity, ease: "linear" }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] opacity-20 hidden sm:block"
        >
          <div className="absolute inset-0 bg-gradient-conic from-primary via-neon-purple via-neon-cyan to-primary rounded-full blur-3xl" />
        </motion.div>
      </div>

      <div className="container mx-auto px-4">
        <Card className={`border-2 border-primary/30 bg-gradient-to-br from-card via-card to-primary/5 ${featured ? 'max-w-5xl mx-auto' : ''}`}>
          <CardHeader className="text-center pb-4 px-4 sm:px-6">
            {/* Badge */}
            <div className="flex justify-center mb-3 sm:mb-4">
              <Badge className="gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 text-xs sm:text-sm bg-gradient-to-r from-neon-amber/20 to-neon-magenta/20 text-neon-amber border-neon-amber/30">
                <Dices className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                <span className="hidden xs:inline">AI-Powered •</span> {FORMATTED_COMBINATIONS}+ Combos
              </Badge>
            </div>

            <CardTitle className="text-2xl sm:text-3xl md:text-4xl font-black">
              <span className="bg-gradient-to-r from-neon-magenta via-neon-amber to-neon-green bg-clip-text text-transparent animate-gradient bg-[length:200%_200%]">
                AI Template Generator
              </span>
            </CardTitle>
            <p className="text-sm sm:text-base md:text-lg text-muted-foreground max-w-2xl mx-auto mt-2">
              Get a <span className="text-foreground font-semibold">unique, AI-generated template</span> with random difficulty and rarity.
              <span className="hidden sm:inline"> Your template may never appear in the public marketplace.</span>
            </p>
          </CardHeader>

          <CardContent className="space-y-6 sm:space-y-8 px-4 sm:px-6">
            {/* Value Proposition Grid */}
            <div className="grid sm:grid-cols-3 gap-3 sm:gap-4">
              <div className="p-3 sm:p-4 rounded-xl bg-gradient-to-br from-neon-purple/10 to-neon-purple/5 border border-neon-purple/20">
                <Sparkles className="w-6 h-6 sm:w-8 sm:h-8 text-neon-purple mb-2" />
                <h3 className="font-bold text-sm sm:text-base mb-1">Truly Unique</h3>
                <p className="text-xs sm:text-sm text-muted-foreground">
                  {FORMATTED_COMBINATIONS}+ combinations. One-of-a-kind.
                </p>
              </div>
              <div className="p-3 sm:p-4 rounded-xl bg-gradient-to-br from-neon-amber/10 to-neon-amber/5 border border-neon-amber/20">
                <Crown className="w-6 h-6 sm:w-8 sm:h-8 text-neon-amber mb-2" />
                <h3 className="font-bold text-sm sm:text-base mb-1">Variable Value</h3>
                <p className="text-xs sm:text-sm text-muted-foreground">
                  Worth {formatValueRange()}. Avg: {formatExpectedValue()}.
                </p>
              </div>
              <div className="p-3 sm:p-4 rounded-xl bg-gradient-to-br from-neon-green/10 to-neon-green/5 border border-neon-green/20">
                <Lock className="w-6 h-6 sm:w-8 sm:h-8 text-neon-green mb-2" />
                <h3 className="font-bold text-sm sm:text-base mb-1">{getGeneratorValueMultiplier()} Value</h3>
                <p className="text-xs sm:text-sm text-muted-foreground">
                  Download & keep forever.
                </p>
              </div>
            </div>

            {/* Rarity Display */}
            <div className="p-3 sm:p-4 rounded-xl bg-muted/50 border border-border/50">
              <div className="flex items-center gap-2 mb-2 sm:mb-3">
                <Gift className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
                <span className="font-semibold text-sm sm:text-base">Rarity Chances</span>
              </div>
              <div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5 sm:gap-2">
                {RARITIES.map((rarity) => (
                  <div key={rarity.name} className="text-center p-1.5 sm:p-2 rounded-lg bg-background/50">
                    <p className={`font-bold text-xs sm:text-sm ${rarity.color}`}>{rarity.name}</p>
                    <p className="text-[10px] sm:text-xs text-muted-foreground">{rarity.chance}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Category Icons - hidden on very small screens */}
            <div className="hidden xs:flex flex-wrap justify-center gap-2 sm:gap-3">
              {[Brain, MessageSquare, Shield, Zap, Eye, Moon, Settings, Globe, Cpu].map((Icon, i) => (
                <div 
                  key={i}
                  className="w-8 h-8 sm:w-10 sm:h-10 rounded-lg bg-muted/50 border border-border/50 flex items-center justify-center"
                >
                  <Icon className="w-4 h-4 sm:w-5 sm:h-5 text-muted-foreground" />
                </div>
              ))}
            </div>

            {/* Price & CTA */}
            <div className="text-center space-y-3 sm:space-y-4">
              <div className="flex items-center justify-center gap-3 sm:gap-4">
                <div className="text-3xl sm:text-4xl font-black text-foreground">${GENERATOR_PRICE / 100}</div>
                <div className="text-left">
                  <p className="text-xs sm:text-sm text-muted-foreground line-through">{formatExpectedValue()} avg value</p>
                  <Badge variant="outline" className="text-[10px] sm:text-xs text-neon-green border-neon-green/30">
                    {getGeneratorValueMultiplier()} Avg Return
                  </Badge>
                </div>
              </div>

              <Button
                size="lg"
                onClick={handleCheckout}
                disabled={isCheckingOut}
                className="gap-2 px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg font-bold bg-gradient-to-r from-neon-magenta via-neon-amber to-neon-green hover:opacity-90 text-white w-full sm:w-auto"
              >
                {isCheckingOut ? (
                  <>
                    <Loader2 className="w-4 h-4 sm:w-5 sm:h-5 animate-spin" />
                    Opening...
                  </>
                ) : (
                  <>
                    <Dices className="w-4 h-4 sm:w-5 sm:h-5" />
                    <span className="hidden sm:inline">Generate Random Template — ${GENERATOR_PRICE / 100}</span>
                    <span className="sm:hidden">Generate Template — ${GENERATOR_PRICE / 100}</span>
                    <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5" />
                  </>
                )}
              </Button>

              <p className="text-[10px] sm:text-xs text-muted-foreground">
                Instant delivery • Never underprices Rare+ templates • Yours forever
              </p>
            </div>

            {/* What You Get - More compact on mobile */}
            <div className="grid sm:grid-cols-2 gap-3 sm:gap-4 pt-3 sm:pt-4 border-t border-border/50">
              <div className="space-y-1.5 sm:space-y-2">
                <h4 className="font-semibold text-sm sm:text-base flex items-center gap-2">
                  <Check className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-neon-green" />
                  What's Included
                </h4>
                <ul className="text-xs sm:text-sm text-muted-foreground space-y-0.5 sm:space-y-1">
                  <li>• Production-ready TypeScript</li>
                  <li>• 3-7 unique features</li>
                  <li>• SDK integration ready</li>
                  <li>• Docs & use case guide</li>
                </ul>
              </div>
              <div className="space-y-1.5 sm:space-y-2">
                <h4 className="font-semibold text-sm sm:text-base flex items-center gap-2">
                  <Star className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-neon-amber" />
                  Categories
                </h4>
                <ul className="text-xs sm:text-sm text-muted-foreground space-y-0.5 sm:space-y-1">
                  <li>• Brain (Memory)</li>
                  <li>• Defense (Security)</li>
                  <li>• Dream (Evolution)</li>
                  <li>• + 6 more modules</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Generated Template Result Modal */}
      <AnimatePresence>
        {showResult && generatedTemplate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm p-4"
            onClick={() => setShowResult(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-card border border-border rounded-2xl p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="text-center mb-6">
                <Badge className={`mb-2 ${
                  generatedTemplate.rarity === 'mythic' ? 'bg-neon-magenta/20 text-neon-magenta' :
                  generatedTemplate.rarity === 'legendary' ? 'bg-neon-amber/20 text-neon-amber' :
                  generatedTemplate.rarity === 'epic' ? 'bg-neon-purple/20 text-neon-purple' :
                  generatedTemplate.rarity === 'rare' ? 'bg-neon-blue/20 text-neon-blue' :
                  generatedTemplate.rarity === 'uncommon' ? 'bg-neon-green/20 text-neon-green' :
                  'bg-slate-500/20 text-slate-400'
                }`}>
                  {generatedTemplate.rarity.toUpperCase()} • {generatedTemplate.difficulty}
                </Badge>
                <h2 className="text-2xl font-bold">{generatedTemplate.name}</h2>
                <p className="text-muted-foreground">{generatedTemplate.description}</p>
              </div>

              <div className="space-y-4">
                {/* Pack-awareness indicator */}
                {(() => {
                  const policy = evaluateTemplatePolicy(generatedTemplate.category, activePackIds);
                  if (policy.mode === 'degraded') {
                    return (
                      <div className="flex items-start gap-2 p-3 rounded-lg bg-muted/50 border border-border/50 text-xs">
                        <AlertTriangle className="w-4 h-4 text-neon-amber shrink-0 mt-0.5" />
                        <div>
                          <span className="font-medium text-foreground">Baseline mode</span>
                          <span className="text-muted-foreground"> — Activate </span>
                          <span className="font-medium text-foreground">{policy.missingPackNames.slice(0, 2).join(', ')}</span>
                          {policy.missingPackNames.length > 2 && <span className="text-muted-foreground"> +{policy.missingPackNames.length - 2} more</span>}
                          <span className="text-muted-foreground"> for full output. </span>
                          <a href="/packs" className="text-primary hover:underline">Manage packs →</a>
                        </div>
                      </div>
                    );
                  }
                  return (
                    <div className="flex items-center gap-2 p-2 rounded-lg bg-primary/5 text-xs">
                      <Package className="w-3.5 h-3.5 text-primary" />
                      <span className="text-muted-foreground">Full template — all required packs active</span>
                    </div>
                  );
                })()}

                <div className="flex flex-wrap gap-2">
                  {generatedTemplate.features.map((feature, i) => (
                    <Badge key={i} variant="outline">{feature}</Badge>
                  ))}
                </div>

                <div className="p-4 rounded-lg bg-muted/50 font-mono text-sm overflow-x-auto">
                  <pre className="whitespace-pre-wrap">{generatedTemplate.code.slice(0, 500)}...</pre>
                </div>

                <div className="flex gap-2">
                  <Button onClick={handleDownload} className="flex-1 gap-2">
                    <Download className="w-4 h-4" />
                    Download Template
                  </Button>
                  <Button onClick={handleCopyCode} variant="outline" className="gap-2">
                    <Copy className="w-4 h-4" />
                    Copy Code
                  </Button>
                </div>

                <p className="text-center text-sm text-muted-foreground">
                  Estimated Value: <span className="font-bold text-primary">{generatedTemplate.estimatedValue}</span>
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
