/**
 * CMPSBL Quantum™ — Vertical Crown Jewel Registry
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * 144 Architectural Crown Jewels: 9 per each of the 16 quantum primitives.
 * Classification: Architecture (permanently black-boxed).
 * All CJPI ≥ 92 — governor-curated, S-Tier.
 *
 * © CMPSBL® — All rights reserved.
 */

import type { STierEntry } from './types';

/* ─── Helper ─── */
function cj(
  rank: number, id: string, name: string, cjpi: number,
  module: string, description: string, sig: string,
): STierEntry {
  return {
    rank, id, name, cjpi, module,
    type: 'Architecture',
    description,
    dependencyFootprint: [],
    exportMode: 'PureStandalone',
    signatureHash: sig,
    version: '1.0.0',
    approved: true,
    generatedAt: '2026-04-05T00:00:00.000Z',
    hasCode: true,
  };
}

// ── HADRON ──
const HADRON_JEWELS: STierEntry[] = [
  cj(700, 'S-HDR01', 'Monte Carlo Event Generator', 98, 'HADRON',
    'High-energy particle collision simulation using importance sampling and phase space integration for accurate cross-section computation across energy regimes.',
    'db5d9a25'),
  cj(701, 'S-HDR02', 'Parton Distribution Function Evaluator', 97, 'HADRON',
    'Evaluates quark and gluon momentum distributions within hadrons using DGLAP evolution equations with NLO/NNLO corrections.',
    '3003ac6e'),
  cj(702, 'S-HDR03', 'Jet Clustering Algorithm Suite', 96, 'HADRON',
    'Anti-kT, Cambridge-Aachen, and SISCone jet clustering implementations with infrared and collinear safety guarantees for collider physics analysis.',
    'f530244a'),
  cj(703, 'S-HDR04', 'Decay Chain Simulator', 95, 'HADRON',
    'Simulates multi-body particle decay chains with spin correlation preservation, phase space sampling, and branching ratio computation.',
    'adec6ac3'),
  cj(704, 'S-HDR05', 'Feynman Diagram Evaluator', 94, 'HADRON',
    'Automated evaluation of Feynman diagrams including loop integrals, UV renormalization, and IR regularization for perturbative QFT calculations.',
    '999f0192'),
  cj(705, 'S-HDR06', 'Detector Response Modeler', 93, 'HADRON',
    'Parameterized detector response simulation including resolution smearing, acceptance effects, and pile-up modeling for realistic experimental comparison.',
    '7b21c10e'),
  cj(706, 'S-HDR07', 'Background Estimation Engine', 96, 'HADRON',
    'Data-driven background estimation using sideband methods, ABCD techniques, and template fitting for signal extraction in particle searches.',
    'bf245eb8'),
  cj(707, 'S-HDR08', 'Statistical Hypothesis Tester', 95, 'HADRON',
    'CLs method implementation with profile likelihood ratios, Asimov datasets, and expected limit computation for new physics searches.',
    '8d3aed5a'),
  cj(708, 'S-HDR09', 'Event Display Renderer', 92, 'HADRON',
    'Three-dimensional event visualization with track reconstruction, calorimeter deposit display, and interactive detector geometry exploration.',
    'a60bbe50'),
];

// ── QUBIT ──
const QUBIT_JEWELS: STierEntry[] = [
  cj(709, 'S-QBT01', 'Quantum Circuit Transpiler', 98, 'QUBIT',
    'Optimizes quantum circuits for specific hardware topologies through gate decomposition, routing, and scheduling with minimal CNOT overhead.',
    '0576fd97'),
  cj(710, 'S-QBT02', 'Error Syndrome Decoder', 97, 'QUBIT',
    'Real-time quantum error syndrome decoding using minimum-weight perfect matching for surface code and related topological codes.',
    '22775e51'),
  cj(711, 'S-QBT03', 'Variational Ansatz Optimizer', 96, 'QUBIT',
    'Optimizes parameterized quantum circuit ansatze for VQE and QAOA using gradient-free and gradient-based classical optimization loops.',
    '9d990cf8'),
  cj(712, 'S-QBT04', 'Qubit Allocation Manager', 95, 'QUBIT',
    'Assigns logical qubits to physical qubits considering connectivity constraints, crosstalk minimization, and decoherence time maximization.',
    '2400fb2b'),
  cj(713, 'S-QBT05', 'Gate Fidelity Benchmarker', 94, 'QUBIT',
    'Characterizes single and two-qubit gate fidelities using randomized benchmarking, interleaved benchmarking, and cycle benchmarking protocols.',
    'ed5767ad'),
  cj(714, 'S-QBT06', 'Quantum Volume Calculator', 93, 'QUBIT',
    'Measures quantum volume through heavy output generation with statistical validation and confidence interval estimation.',
    '5eebf2fa'),
  cj(715, 'S-QBT07', 'Noise Model Characterizer', 96, 'QUBIT',
    'Extracts device noise models from calibration data including T1, T2, gate errors, and crosstalk for accurate simulation.',
    '7736d46f'),
  cj(716, 'S-QBT08', 'Circuit Depth Optimizer', 95, 'QUBIT',
    'Minimizes circuit depth through gate cancellation, commutation analysis, and template matching while preserving quantum program semantics.',
    '339b1fbc'),
  cj(717, 'S-QBT09', 'Pulse-Level Control Compiler', 92, 'QUBIT',
    'Compiles gate-level circuits into optimized microwave pulse sequences with cross-resonance calibration and drag pulse shaping.',
    '7c2558c4'),
];

// ── PHOTON ──
const PHOTON_JEWELS: STierEntry[] = [
  cj(718, 'S-PHT01', 'Optical Mode Solver', 98, 'PHOTON',
    'Computes electromagnetic modes in photonic structures using finite element and plane wave expansion methods with material dispersion.',
    '4b6fc366'),
  cj(719, 'S-PHT02', 'Beam Propagation Simulator', 97, 'PHOTON',
    'Simulates Gaussian beam propagation through complex optical systems including lenses, crystals, and fiber with diffraction and nonlinear effects.',
    '33580dd4'),
  cj(720, 'S-PHT03', 'Quantum Key Distribution Engine', 96, 'PHOTON',
    'Implements BB84, E91, and continuous-variable QKD protocols with security parameter estimation and key distillation.',
    'a99e7759'),
  cj(721, 'S-PHT04', 'Single Photon Source Characterizer', 95, 'PHOTON',
    'Analyzes single photon source quality through g2 correlation measurement, indistinguishability analysis, and brightness optimization.',
    '7ffa90ea'),
  cj(722, 'S-PHT05', 'Interferometric Measurement Engine', 94, 'PHOTON',
    'Processes interferometric measurement data with fringe analysis, phase extraction, and noise-limited sensitivity estimation.',
    'd5ffaf6b'),
  cj(723, 'S-PHT06', 'Waveguide Design Optimizer', 93, 'PHOTON',
    'Optimizes integrated photonic waveguide geometries for target mode profiles, coupling efficiency, and fabrication tolerance.',
    '4dabb323'),
  cj(724, 'S-PHT07', 'Nonlinear Optical Process Simulator', 96, 'PHOTON',
    'Simulates second and third harmonic generation, parametric down-conversion, and four-wave mixing with phase matching optimization.',
    'babebad9'),
  cj(725, 'S-PHT08', 'Fiber Optic Network Analyzer', 95, 'PHOTON',
    'Analyzes fiber optic network performance including dispersion, attenuation, PMD, and nonlinear impairments for capacity planning.',
    'f8c8550d'),
  cj(726, 'S-PHT09', 'Polarization State Controller', 92, 'PHOTON',
    'Manages polarization states through Stokes parameter tracking and Mueller matrix computation with automatic compensation of birefringence drift.',
    '073c23a9'),
];

// ── FERMION ──
const FERMION_JEWELS: STierEntry[] = [
  cj(727, 'S-FRM01', 'Many-Body Wavefunction Solver', 98, 'FERMION',
    'Solves the many-electron Schrodinger equation using configuration interaction, coupled cluster, and DMRG methods with systematic accuracy control.',
    'e3a671eb'),
  cj(728, 'S-FRM02', 'Density Functional Theory Engine', 97, 'FERMION',
    'Self-consistent DFT calculations with multiple exchange-correlation functionals, pseudopotentials, and basis set convergence testing.',
    'c8d0bd5a'),
  cj(729, 'S-FRM03', 'Quantum Monte Carlo Integrator', 96, 'FERMION',
    'Variational and diffusion Monte Carlo methods for correlated electron systems with trial wavefunction optimization and fixed-node approximation.',
    'f8e05740'),
  cj(730, 'S-FRM04', 'Band Structure Calculator', 95, 'FERMION',
    'Electronic band structure computation along high-symmetry paths with spin-orbit coupling, van Hove singularity detection, and Fermi surface mapping.',
    'e7c1a775'),
  cj(731, 'S-FRM05', 'Electron Correlation Analyzer', 94, 'FERMION',
    'Quantifies electron correlation effects using natural orbital analysis, pair density functions, and correlation energy decomposition.',
    '6055331a'),
  cj(732, 'S-FRM06', 'Superconductivity Gap Solver', 93, 'FERMION',
    'Solves BCS and Eliashberg gap equations for superconducting order parameters with Coulomb pseudopotential estimation and critical temperature prediction.',
    '51d799f8'),
  cj(733, 'S-FRM07', 'Hubbard Model Solver', 96, 'FERMION',
    'Exact diagonalization and DMFT solutions for Hubbard-type models with Mott transition detection and magnetic phase diagram computation.',
    'fbd2ae5a'),
  cj(734, 'S-FRM08', 'Topological Invariant Calculator', 95, 'FERMION',
    'Computes Chern numbers, Z2 invariants, and Berry phases for topological material classification using Wilson loop methods.',
    '4dbeefd4'),
  cj(735, 'S-FRM09', 'Spin-Orbit Coupling Engine', 92, 'FERMION',
    'Incorporates relativistic spin-orbit interactions into electronic structure calculations using scalar and full two-component approaches.',
    'a268e338'),
];

// ── ENTANGLE ──
const ENTANGLE_JEWELS: STierEntry[] = [
  cj(736, 'S-ENT01', 'Bell State Preparation Protocol', 98, 'ENTANGLE',
    'Optimal Bell state preparation sequences for different hardware platforms with fidelity maximization and verification measurement protocols.',
    '63635e16'),
  cj(737, 'S-ENT02', 'Entanglement Distillation Engine', 97, 'ENTANGLE',
    'Purifies noisy entangled pairs through recurrence and hashing distillation protocols with yield optimization and fidelity tracking.',
    '6cbe04c8'),
  cj(738, 'S-ENT03', 'Quantum Teleportation Manager', 96, 'ENTANGLE',
    'Orchestrates quantum state teleportation protocols including Bell measurement, classical communication, and local correction with fidelity verification.',
    '3f7681b4'),
  cj(739, 'S-ENT04', 'Entanglement Witness Constructor', 95, 'ENTANGLE',
    'Constructs optimal entanglement witnesses from partial tomographic data with detection efficiency analysis and noise robustness evaluation.',
    '3e9cf8b7'),
  cj(740, 'S-ENT05', 'Multipartite Entanglement Classifier', 94, 'ENTANGLE',
    'Classifies multipartite entanglement types including GHZ, W, and cluster states using SLOCC equivalence classes and entanglement monotones.',
    'ccc486c8'),
  cj(741, 'S-ENT06', 'Quantum Network Router', 93, 'ENTANGLE',
    'Routes entanglement distribution through quantum network topologies with repeater scheduling, memory management, and path optimization.',
    '153bc524'),
  cj(742, 'S-ENT07', 'Decoherence Rate Estimator', 96, 'ENTANGLE',
    'Estimates decoherence rates from experimental data using process tomography fitting with model selection between Markovian and non-Markovian dynamics.',
    'c40cea77'),
  cj(743, 'S-ENT08', 'EPR Source Optimizer', 95, 'ENTANGLE',
    'Optimizes entangled photon pair source parameters including pump power, crystal temperature, and collection efficiency for maximum entanglement rate.',
    '13227015'),
  cj(744, 'S-ENT09', 'Entanglement Swapping Coordinator', 92, 'ENTANGLE',
    'Coordinates entanglement swapping across quantum repeater nodes with synchronization, measurement scheduling, and success probability optimization.',
    '30fa1400'),
];

// ── LATTICE ──
const LATTICE_JEWELS: STierEntry[] = [
  cj(745, 'S-LAT01', 'Crystal Structure Predictor', 98, 'LATTICE',
    'Predicts stable crystal structures from chemical composition using evolutionary algorithms, random structure searching, and energy landscape exploration.',
    '9b0db76f'),
  cj(746, 'S-LAT02', 'Phonon Dispersion Calculator', 97, 'LATTICE',
    'Computes phonon dispersion relations using density functional perturbation theory with thermal conductivity estimation and Raman spectra prediction.',
    '12e5ae9b'),
  cj(747, 'S-LAT03', 'Molecular Dynamics Integrator', 96, 'LATTICE',
    'High-performance molecular dynamics with multiple time-step integration, constraint algorithms, and enhanced sampling methods for rare event simulation.',
    '50bc6865'),
  cj(748, 'S-LAT04', 'Defect Formation Energy Calculator', 95, 'LATTICE',
    'Calculates point defect formation energies with charged defect corrections, chemical potential referencing, and defect concentration estimation.',
    '5b1203ce'),
  cj(749, 'S-LAT05', 'Surface Energy Analyzer', 94, 'LATTICE',
    'Computes surface energies and Wulff shapes for crystal facets with adsorbate interaction modeling and catalytic activity prediction.',
    '5e0b5369'),
  cj(750, 'S-LAT06', 'Phase Diagram Constructor', 93, 'LATTICE',
    'Constructs temperature-composition phase diagrams using cluster expansion, Monte Carlo sampling, and thermodynamic integration methods.',
    '8e548d29'),
  cj(751, 'S-LAT07', 'Elastic Constant Calculator', 96, 'LATTICE',
    'Determines elastic constants from strain-stress relationships with Voigt-Reuss-Hill averaging and mechanical stability criterion checking.',
    '82d709d4'),
  cj(752, 'S-LAT08', 'Magnetic Ordering Solver', 95, 'LATTICE',
    'Determines magnetic ground states and transition temperatures using Heisenberg model fitting, mean-field analysis, and Monte Carlo simulation.',
    '687dcc94'),
  cj(753, 'S-LAT09', 'Diffusion Pathway Finder', 92, 'LATTICE',
    'Identifies minimum energy diffusion pathways using nudged elastic band method with climbing image extension for accurate barrier determination.',
    '3bda0ee1'),
];

// ── PLASMA ──
const PLASMA_JEWELS: STierEntry[] = [
  cj(754, 'S-PLS01', 'Magnetohydrodynamics Solver', 98, 'PLASMA',
    'Solves ideal and resistive MHD equations using Godunov-type schemes with divergence-free magnetic field maintenance and adaptive mesh refinement.',
    'db2f3635'),
  cj(755, 'S-PLS02', 'Particle-In-Cell Simulator', 97, 'PLASMA',
    'Kinetic plasma simulation using PIC methods with charge-conserving current deposition, field interpolation, and collision operators.',
    'c4e8cff2'),
  cj(756, 'S-PLS03', 'Tokamak Equilibrium Solver', 96, 'PLASMA',
    'Computes Grad-Shafranov equilibria for tokamak configurations with free-boundary solutions and beta limit stability analysis.',
    '16bfc615'),
  cj(757, 'S-PLS04', 'Plasma Instability Analyzer', 95, 'PLASMA',
    'Linear stability analysis of plasma configurations including kink, ballooning, tearing, and interchange instabilities with growth rate computation.',
    '752791d8'),
  cj(758, 'S-PLS05', 'Fusion Reaction Rate Calculator', 94, 'PLASMA',
    'Computes thermonuclear fusion reaction rates using cross-section databases with Maxwellian and non-Maxwellian velocity distribution averaging.',
    'e445a1d4'),
  cj(759, 'S-PLS06', 'Plasma Diagnostic Interpreter', 93, 'PLASMA',
    'Interprets plasma diagnostic measurements including Thomson scattering, interferometry, and spectroscopy for temperature and density profile reconstruction.',
    '7e240ab7'),
  cj(760, 'S-PLS07', 'Magnetic Confinement Optimizer', 96, 'PLASMA',
    'Optimizes magnetic field configurations for plasma confinement using stellarator coil optimization and neoclassical transport minimization.',
    '7e3b74ad'),
  cj(761, 'S-PLS08', 'Laser-Plasma Interaction Modeler', 95, 'PLASMA',
    'Simulates laser-plasma interactions including parametric instabilities, hot electron generation, and ablation pressure for inertial confinement fusion.',
    '2ab97428'),
  cj(762, 'S-PLS09', 'Plasma Turbulence Analyzer', 92, 'PLASMA',
    'Analyzes gyrokinetic turbulence spectra with transport coefficient extraction and turbulent transport prediction for confinement optimization.',
    '582b3d15'),
];

// ── CRYOGEN ──
const CRYOGEN_JEWELS: STierEntry[] = [
  cj(763, 'S-CRY01', 'Dilution Refrigerator Controller', 98, 'CRYOGEN',
    'Optimizes dilution refrigerator operation with mixing chamber temperature regulation, circulation rate control, and heat load management.',
    '7434e401'),
  cj(764, 'S-CRY02', 'Thermal Noise Calculator', 97, 'CRYOGEN',
    'Computes Johnson-Nyquist, shot, and 1/f noise contributions in cryogenic electronics with noise temperature estimation and amplifier chain optimization.',
    'fd36af64'),
  cj(765, 'S-CRY03', 'Cryogenic Wiring Optimizer', 96, 'CRYOGEN',
    'Designs optimal cryogenic wiring harnesses balancing thermal conductivity, electrical resistance, and signal integrity across temperature stages.',
    'ffd3a880'),
  cj(766, 'S-CRY04', 'Helium Recovery Manager', 95, 'CRYOGEN',
    'Monitors and optimizes helium recovery systems including gas purity analysis, compressor efficiency, and liquefier performance tracking.',
    '0451a557'),
  cj(767, 'S-CRY05', 'Superconducting Transition Monitor', 94, 'CRYOGEN',
    'Monitors superconducting critical temperature transitions with resistance measurement, magnetic susceptibility tracking, and quench detection.',
    '5fd04805'),
  cj(768, 'S-CRY06', 'Cryostat Vacuum Manager', 93, 'CRYOGEN',
    'Manages cryostat vacuum levels with leak detection, outgassing estimation, and cryopump regeneration scheduling.',
    'cfc8b3d1'),
  cj(769, 'S-CRY07', 'Thermal Radiation Shield Optimizer', 96, 'CRYOGEN',
    'Optimizes multi-layer insulation and radiation shield configurations to minimize radiative heat loads at each temperature stage.',
    '7e3399b6'),
  cj(770, 'S-CRY08', 'Pulse Tube Cooler Controller', 95, 'CRYOGEN',
    'Optimizes pulse tube cryocooler operation including phase angle control, regenerator performance monitoring, and cool-down trajectory planning.',
    'c2055123'),
  cj(771, 'S-CRY09', 'Cryogenic Safety Interlock System', 92, 'CRYOGEN',
    'Monitors cryogenic safety parameters including pressure relief, oxygen depletion, and thermal runaway with automatic interlock activation.',
    '86fe6a2e'),
];

// ── MUON ──
const MUON_JEWELS: STierEntry[] = [
  cj(772, 'S-MUN01', 'Muon Lifetime Precision Measurer', 98, 'MUON',
    'High-precision muon lifetime measurement with pile-up correction, detector efficiency mapping, and systematic uncertainty quantification.',
    'f8b23a5c'),
  cj(773, 'S-MUN02', 'Muon Spin Rotation Analyzer', 97, 'MUON',
    'Analyzes muon spin rotation and relaxation data for material characterization including magnetic field distribution and spin dynamics.',
    '3e657de2'),
  cj(774, 'S-MUN03', 'Cosmic Ray Muon Tomographer', 96, 'MUON',
    'Reconstructs 3D density maps from cosmic ray muon absorption and scattering measurements for non-destructive structure inspection.',
    '79d38614'),
  cj(775, 'S-MUN04', 'Muon Beam Optics Designer', 95, 'MUON',
    'Designs muon beam transport lines with solenoid and quadrupole focusing, momentum selection, and beam cooling channel optimization.',
    '30e70d1b'),
  cj(776, 'S-MUN05', 'Neutrino Factory Optimizer', 94, 'MUON',
    'Optimizes muon storage ring parameters for neutrino factory applications including muon capture, cooling, and acceleration efficiency.',
    '692ebdea'),
  cj(777, 'S-MUN06', 'Muon Anomalous Magnetic Moment Calculator', 93, 'MUON',
    'Computes contributions to muon g-2 from QED, hadronic, and electroweak sectors with uncertainty propagation.',
    'd6afb020'),
  cj(778, 'S-MUN07', 'Muon Collider Luminosity Estimator', 96, 'MUON',
    'Estimates achievable luminosity for muon collider configurations considering beam-beam effects, bunch compression, and emittance preservation.',
    '4816c28d'),
  cj(779, 'S-MUN08', 'Charged Lepton Flavor Violation Searcher', 95, 'MUON',
    'Optimizes experimental sensitivity for mu-to-e conversion, mu-to-e-gamma, and mu-to-3e searches with background estimation.',
    '93c11b48'),
  cj(780, 'S-MUN09', 'Muonic Atom Spectroscopy Engine', 92, 'MUON',
    'Computes muonic atom energy levels with nuclear structure effects, vacuum polarization, and finite nuclear size corrections.',
    '3886405b'),
];

// ── BOSON ──
const BOSON_JEWELS: STierEntry[] = [
  cj(781, 'S-BSN01', 'Higgs Boson Signal Extractor', 98, 'BOSON',
    'Extracts Higgs boson signals from complex backgrounds using multivariate analysis with systematic uncertainty profiling and signal strength measurement.',
    '780f0260'),
  cj(782, 'S-BSN02', 'Gauge Boson Polarization Analyzer', 97, 'BOSON',
    'Measures W and Z boson polarization fractions from angular distributions with template fitting and anomalous coupling sensitivity.',
    'a589a6a3'),
  cj(783, 'S-BSN03', 'Electroweak Precision Observable Calculator', 96, 'BOSON',
    'Computes electroweak precision observables including oblique corrections, Z-pole parameters, and W mass predictions with higher-order corrections.',
    'fbe2db7b'),
  cj(784, 'S-BSN04', 'Di-Boson Production Cross-Section Calculator', 95, 'BOSON',
    'Calculates WW, WZ, ZZ, and W-gamma production cross-sections at NLO/NNLO with anomalous triple gauge coupling sensitivity.',
    '5863f80a'),
  cj(785, 'S-BSN05', 'Bose-Einstein Condensation Simulator', 94, 'BOSON',
    'Simulates BEC dynamics using Gross-Pitaevskii equation with vortex nucleation, collective mode excitation, and atom number tracking.',
    '3d143ad5'),
  cj(786, 'S-BSN06', 'Photon-Photon Scattering Calculator', 93, 'BOSON',
    'Computes light-by-light scattering cross-sections using QED box diagrams with hadronic contributions from dispersion relations.',
    'b5b07675'),
  cj(787, 'S-BSN07', 'Spontaneous Symmetry Breaking Analyzer', 96, 'BOSON',
    'Analyzes symmetry breaking patterns in scalar potentials with vacuum stability, metastability, and tunneling rate calculations.',
    '0d612df4'),
  cj(788, 'S-BSN08', 'Weak Boson Fusion Identifier', 95, 'BOSON',
    'Identifies vector boson fusion events using forward jet tagging, central jet vetoing, and rapidity gap requirements.',
    'f4949483'),
  cj(789, 'S-BSN09', 'Goldstone Boson Mode Counter', 92, 'BOSON',
    'Counts Nambu-Goldstone modes from symmetry breaking patterns and identifies pseudo-Goldstone masses from explicit symmetry breaking.',
    'd7c288c9'),
];

// ── NEUTRINO ──
const NEUTRINO_JEWELS: STierEntry[] = [
  cj(790, 'S-NTR01', 'Oscillation Probability Calculator', 98, 'NEUTRINO',
    'Computes three-flavor neutrino oscillation probabilities including matter effects using exact diagonalization and expansion approximations.',
    '774db773'),
  cj(791, 'S-NTR02', 'Mass Hierarchy Discriminator', 97, 'NEUTRINO',
    'Optimizes experimental configurations for neutrino mass hierarchy determination using atmospheric, reactor, and accelerator neutrino data.',
    '74b1b1e7'),
  cj(792, 'S-NTR03', 'CP Violation Phase Estimator', 96, 'NEUTRINO',
    'Estimates the Dirac CP violation phase from combined neutrino oscillation data with systematic uncertainty propagation and degeneracy resolution.',
    '675c781e'),
  cj(793, 'S-NTR04', 'Neutrino Cross-Section Calculator', 95, 'NEUTRINO',
    'Computes neutrino-nucleus cross-sections including quasi-elastic, resonance, and deep inelastic scattering channels with nuclear model uncertainties.',
    '192ed9cc'),
  cj(794, 'S-NTR05', 'Supernova Neutrino Signal Predictor', 94, 'NEUTRINO',
    'Predicts neutrino signals from core-collapse supernovae with MSW flavor conversion, collective oscillation effects, and detector response.',
    '7d63bd4d'),
  cj(795, 'S-NTR06', 'Sterile Neutrino Search Optimizer', 93, 'NEUTRINO',
    'Optimizes experimental parameters for sterile neutrino searches in short-baseline reactor and accelerator experiments.',
    '8b41141f'),
  cj(796, 'S-NTR07', 'Coherent Elastic Scattering Analyzer', 96, 'NEUTRINO',
    'Analyzes coherent elastic neutrino-nucleus scattering signals with quenching factor correction and nuclear form factor computation.',
    '705cb1dd'),
  cj(797, 'S-NTR08', 'Neutrino Flux Predictor', 95, 'NEUTRINO',
    'Predicts neutrino fluxes from reactor, solar, atmospheric, and accelerator sources with systematic uncertainty budgets.',
    'af7a8ecd'),
  cj(798, 'S-NTR09', 'Double Beta Decay Rate Calculator', 92, 'NEUTRINO',
    'Computes neutrinoless and two-neutrino double beta decay rates with nuclear matrix element evaluation and phase space integration.',
    'd1afa6df'),
];

// ── GLUON ──
const GLUON_JEWELS: STierEntry[] = [
  cj(799, 'S-GLU01', 'QCD Running Coupling Evaluator', 98, 'GLUON',
    'Evaluates the strong coupling constant at arbitrary energy scales using perturbative running with matching conditions across quark thresholds.',
    'c2a264ca'),
  cj(800, 'S-GLU02', 'Parton Shower Generator', 97, 'GLUON',
    'Generates QCD parton showers using DGLAP splitting functions with coherent branching, dead-cone effects, and hadronization interface.',
    '12cff0b6'),
  cj(801, 'S-GLU03', 'Color Flow Tracker', 96, 'GLUON',
    'Tracks color flow through Feynman diagrams and parton shower histories for color reconnection modeling and string fragmentation.',
    '7467b169'),
  cj(802, 'S-GLU04', 'Jet Substructure Analyzer', 95, 'GLUON',
    'Analyzes jet substructure using N-subjettiness, energy correlation functions, and grooming algorithms for boosted object identification.',
    '548904e5'),
  cj(803, 'S-GLU05', 'Heavy Quark Fragmentation Modeler', 94, 'GLUON',
    'Models heavy quark fragmentation using Peterson and Bowler parameterizations with charm and bottom quark mass effects.',
    '31365297'),
  cj(804, 'S-GLU06', 'Lattice QCD Observable Extractor', 93, 'GLUON',
    'Extracts hadronic observables from lattice QCD gauge field configurations using correlator analysis and spectral decomposition.',
    '98b73821'),
  cj(805, 'S-GLU07', 'Gluon Fusion Process Calculator', 96, 'GLUON',
    'Calculates gluon fusion production cross-sections for Higgs and beyond-Standard-Model particles with heavy quark loop contributions.',
    'e2a5f1f6'),
  cj(806, 'S-GLU08', 'Color Confinement Modeler', 95, 'GLUON',
    'Models color confinement using string tension parametrization and Regge trajectory analysis for hadron spectroscopy predictions.',
    '832171ae'),
  cj(807, 'S-GLU09', 'QCD Sum Rule Evaluator', 92, 'GLUON',
    'Evaluates QCD sum rules for hadron properties using operator product expansion with perturbative and non-perturbative contributions.',
    '364cef9f'),
];

// ── GRAVITON ──
const GRAVITON_JEWELS: STierEntry[] = [
  cj(808, 'S-GRV01', 'Gravitational Wave Template Bank', 98, 'GRAVITON',
    'Generates template banks for gravitational wave matched filtering covering binary inspiral, merger, and ringdown with spin precession.',
    '0de52eae'),
  cj(809, 'S-GRV02', 'Black Hole Merger Simulator', 97, 'GRAVITON',
    'Simulates binary black hole mergers using numerical relativity-calibrated waveform models with spin and eccentricity parametrization.',
    '1c384df0'),
  cj(810, 'S-GRV03', 'LIGO Signal Processor', 96, 'GRAVITON',
    'Processes LIGO strain data with glitch subtraction, noise power spectral density estimation, and matched filter signal-to-noise computation.',
    '9e3b195a'),
  cj(811, 'S-GRV04', 'Neutron Star Equation of State Constrainer', 95, 'GRAVITON',
    'Constrains neutron star equation of state from gravitational wave tidal deformability measurements with nuclear physics prior integration.',
    'a5f0f55d'),
  cj(812, 'S-GRV05', 'Cosmological Perturbation Calculator', 94, 'GRAVITON',
    'Computes cosmological perturbation evolution through matter and radiation dominated eras with tensor mode gravitational wave spectrum prediction.',
    '10e3bdfa'),
  cj(813, 'S-GRV06', 'Geodesic Ray Tracer', 93, 'GRAVITON',
    'Traces null and timelike geodesics in curved spacetimes for gravitational lensing simulation and black hole shadow computation.',
    '442d5ebf'),
  cj(814, 'S-GRV07', 'Post-Newtonian Expansion Engine', 96, 'GRAVITON',
    'Computes post-Newtonian corrections to binary orbital dynamics including spin-spin, spin-orbit, and tidal interactions at high PN order.',
    '3a506a24'),
  cj(815, 'S-GRV08', 'Stochastic Background Analyzer', 95, 'GRAVITON',
    'Searches for stochastic gravitational wave backgrounds using cross-correlation techniques with overlap reduction function computation.',
    '3798b44e'),
  cj(816, 'S-GRV09', 'Modified Gravity Theory Tester', 92, 'GRAVITON',
    'Tests modified gravity theories against gravitational wave observations including propagation speed, dispersion, and polarization mode measurements.',
    '982c6973'),
];

// ── TACHYON ──
const TACHYON_JEWELS: STierEntry[] = [
  cj(817, 'S-TCH01', 'Superluminal Signal Modeler', 98, 'TACHYON',
    'Models hypothetical superluminal signal propagation with causality constraint analysis and Lorentz invariance violation parametrization.',
    '595051fd'),
  cj(818, 'S-TCH02', 'Tachyonic Field Theory Solver', 97, 'TACHYON',
    'Solves tachyonic field equations including spontaneous Lorentz symmetry breaking and vacuum decay rate computation.',
    '326c64ed'),
  cj(819, 'S-TCH03', 'Closed Timelike Curve Analyzer', 96, 'TACHYON',
    'Analyzes spacetime geometries for closed timelike curves with Novikov self-consistency condition checking and chronology protection evaluation.',
    '5eb0cc95'),
  cj(820, 'S-TCH04', 'Casimir Effect Calculator', 95, 'TACHYON',
    'Computes Casimir forces for various geometries including parallel plates, spheres, and cylinders with finite temperature and material corrections.',
    'f032f0c0'),
  cj(821, 'S-TCH05', 'Quantum Tunneling Rate Estimator', 94, 'TACHYON',
    'Estimates quantum tunneling rates through potential barriers using WKB approximation and instanton methods with multi-dimensional generalization.',
    '7b0d4a0c'),
  cj(822, 'S-TCH06', 'Vacuum Stability Analyzer', 93, 'TACHYON',
    'Analyzes electroweak vacuum stability using effective potential computation with higher-order corrections and gravitational effects.',
    '1bb6e0a5'),
  cj(823, 'S-TCH07', 'Unruh Effect Simulator', 96, 'TACHYON',
    'Simulates the Unruh effect for accelerated observers including thermal spectrum computation and detector response analysis.',
    '4639ac90'),
  cj(824, 'S-TCH08', 'Hawking Radiation Calculator', 95, 'TACHYON',
    'Calculates Hawking radiation spectra for various black hole types including greybody factors and back-reaction effects.',
    '3d8eb477'),
  cj(825, 'S-TCH09', 'Schwinger Pair Production Calculator', 92, 'TACHYON',
    'Computes electron-positron pair production rates in strong electromagnetic fields using Schwinger formula with finite-size and temporal effects.',
    '807dbc12'),
];

// ── MESON ──
const MESON_JEWELS: STierEntry[] = [
  cj(826, 'S-MSN01', 'Meson Spectroscopy Calculator', 98, 'MESON',
    'Computes meson mass spectra using quark model, lattice QCD, and QCD sum rule methods with relativistic and spin corrections.',
    'ce504e69'),
  cj(827, 'S-MSN02', 'CP Violation in B Meson Analyzer', 97, 'MESON',
    'Analyzes CP violation observables in B meson decays using CKM matrix parametrization with penguin and tree amplitude interference.',
    'cb7433c7'),
  cj(828, 'S-MSN03', 'Charm Meson Mixing Analyzer', 96, 'MESON',
    'Analyzes D meson mixing parameters using time-dependent decay rate measurements with CPV asymmetry extraction.',
    'f4b23869'),
  cj(829, 'S-MSN04', 'Exotic Meson Candidate Classifier', 95, 'MESON',
    'Classifies exotic meson candidates including tetraquarks, molecules, and hybrids using decay pattern analysis and mass spectrum fitting.',
    '4d7e2f98'),
  cj(830, 'S-MSN05', 'Form Factor Calculator', 94, 'MESON',
    'Computes meson form factors for semileptonic decays using lattice QCD and light-cone sum rule methods with uncertainty quantification.',
    'b0975b2b'),
  cj(831, 'S-MSN06', 'Kaon CP Violation Parameter Extractor', 93, 'MESON',
    'Extracts epsilon and epsilon-prime parameters from kaon decay data with isospin decomposition and electroweak penguin contributions.',
    '883dc509'),
  cj(832, 'S-MSN07', 'Pion Distribution Amplitude Fitter', 96, 'MESON',
    'Fits pion distribution amplitudes from experimental data using conformal expansion and evolution equation solutions.',
    '7308792a'),
  cj(833, 'S-MSN08', 'Heavy Quarkonium Decay Calculator', 95, 'MESON',
    'Calculates heavy quarkonium decay rates including radiative, hadronic, and leptonic channels with relativistic corrections.',
    'd7091080'),
  cj(834, 'S-MSN09', 'Hadronization Model Tuner', 92, 'MESON',
    'Tunes hadronization model parameters using LEP, HERA, and LHC data with multivariate optimization and uncertainty propagation.',
    '48c808dc'),
];

// ── PRISM ──
const PRISM_JEWELS: STierEntry[] = [
  cj(835, 'S-PRM01', 'Atomic Emission Line Identifier', 98, 'PRISM',
    'Identifies atomic emission lines from spectroscopic data using comprehensive wavelength databases with self-absorption and Stark broadening corrections.',
    'a35f5faa'),
  cj(836, 'S-PRM02', 'Absorption Spectrum Deconvolver', 97, 'PRISM',
    'Deconvolves overlapping absorption features using Voigt profile fitting with instrumental resolution correction and baseline subtraction.',
    '8ae0057e'),
  cj(837, 'S-PRM03', 'Raman Spectrum Analyzer', 96, 'PRISM',
    'Analyzes Raman spectra with peak identification, crystal orientation determination, and stress-strain mapping from frequency shifts.',
    '93d8e3ad'),
  cj(838, 'S-PRM04', 'X-Ray Fluorescence Quantifier', 95, 'PRISM',
    'Quantifies elemental composition from XRF spectra using fundamental parameters method with matrix correction and detection limit estimation.',
    'b0e1c8d9'),
  cj(839, 'S-PRM05', 'Mass Spectrometry Peak Finder', 94, 'PRISM',
    'Identifies molecular species from mass spectra using isotope pattern matching, fragmentation prediction, and database searching.',
    '65919afc'),
  cj(840, 'S-PRM06', 'NMR Chemical Shift Predictor', 93, 'PRISM',
    'Predicts NMR chemical shifts from molecular structure using gauge-invariant atomic orbital methods with solvent effect correction.',
    'd2783086'),
  cj(841, 'S-PRM07', 'Infrared Spectrum Simulator', 96, 'PRISM',
    'Simulates infrared absorption spectra from molecular geometry using harmonic and anharmonic frequency calculations with intensity prediction.',
    'd825a5a0'),
  cj(842, 'S-PRM08', 'Photoelectron Spectrum Analyzer', 95, 'PRISM',
    'Analyzes XPS and UPS spectra with peak fitting, chemical state identification, and depth profiling for surface composition analysis.',
    '0043546e'),
  cj(843, 'S-PRM09', 'Circular Dichroism Interpreter', 92, 'PRISM',
    'Interprets circular dichroism spectra for protein secondary structure determination using reference spectrum databases and deconvolution algorithms.',
    '71a8b3bb'),
];

/* ═══════════════════════════════════════════════
   REGISTRY EXPORT
   ═══════════════════════════════════════════════ */

export const QUANTUM_CROWN_JEWELS: STierEntry[] = [
  ...HADRON_JEWELS,
  ...QUBIT_JEWELS,
  ...PHOTON_JEWELS,
  ...FERMION_JEWELS,
  ...ENTANGLE_JEWELS,
  ...LATTICE_JEWELS,
  ...PLASMA_JEWELS,
  ...CRYOGEN_JEWELS,
  ...MUON_JEWELS,
  ...BOSON_JEWELS,
  ...NEUTRINO_JEWELS,
  ...GLUON_JEWELS,
  ...GRAVITON_JEWELS,
  ...TACHYON_JEWELS,
  ...MESON_JEWELS,
  ...PRISM_JEWELS,
];

export const QUANTUM_CJ_COUNT = QUANTUM_CROWN_JEWELS.length;

export function getQuantumJewelsByPrimitive(primitiveId: string): STierEntry[] {
  return QUANTUM_CROWN_JEWELS.filter(j => j.module === primitiveId);
}

export function getQuantumJewelSummary(): Array<{
  primitive: string; count: number; avgCjpi: number; topJewel: string;
}> {
  const primitives = [...new Set(QUANTUM_CROWN_JEWELS.map(j => j.module))];
  return primitives.map(p => {
    const jewels = QUANTUM_CROWN_JEWELS.filter(j => j.module === p);
    const top = jewels.reduce((a, b) => a.cjpi > b.cjpi ? a : b);
    return {
      primitive: p,
      count: jewels.length,
      avgCjpi: Math.round(jewels.reduce((s, j) => s + j.cjpi, 0) / jewels.length * 10) / 10,
      topJewel: top.name,
    };
  });
}
