/**
 * PromptFluid Brain Nightly Meta-Learning Reflection
 * Analyzes past reports and adjusts heuristic parameters
 * Uses FREE-TIER AI routing (NO Lovable AI)
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { callFreeTierAI } from '../_shared/free-tier-router.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const sb = createClient(supabaseUrl, supabaseKey);

    console.log('🌙 Starting nightly meta-learning reflection...');

    // Fetch last 4 reports (24 hours worth)
    const { data: recentReports } = await sb
      .from('brain_reports')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(4);

    // Fetch recent metrics
    const { data: recentMetrics } = await sb
      .from('brain_metrics')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(10);

    if (!recentMetrics || recentMetrics.length === 0) {
      console.log('⚠️ No metrics available for reflection');
      return new Response(
        JSON.stringify({ ok: true, message: 'No metrics to reflect on' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Compute trends
    const avgFreedomScore = recentMetrics.reduce((sum, m) => sum + m.freedom_score, 0) / recentMetrics.length;
    const avgRepetition = recentMetrics.reduce((sum, m) => sum + m.repetition_rate, 0) / recentMetrics.length;
    const avgHallucination = recentMetrics.reduce((sum, m) => sum + m.hallucination_rate, 0) / recentMetrics.length;
    const avgCreativeDrift = recentMetrics.reduce((sum, m) => sum + m.creative_drift, 0) / recentMetrics.length;

    // Generate insights using free-tier AI
    const reflectionPrompt = `Analyze these Brain system metrics from the past 24 hours:
- Average Freedom Score: ${avgFreedomScore.toFixed(2)}
- Average Repetition Rate: ${avgRepetition.toFixed(2)}
- Average Hallucination Rate: ${avgHallucination.toFixed(2)}
- Average Creative Drift: ${avgCreativeDrift.toFixed(2)}

Provide 2-3 actionable insights and adjustments for system optimization. Be concise.`;

    const aiResult = await callFreeTierAI(reflectionPrompt, {
      temperature: 0.3,
      maxTokens: 400,
      systemPrompt: 'You are a metacognitive AI system analyzer. Provide technical, actionable insights.'
    });
    
    const insights = [
      {
        finding: 'AI-generated analysis',
        action: aiResult.content.substring(0, 200),
        adjustment: `Generated by ${aiResult.provider}/${aiResult.model}`
      }
    ];

    // Log reflection to brain_reflections table
    await sb.from('brain_reflections').insert({
      reflection_date: new Date().toISOString().split('T')[0],
      summary: `Reflection generated using ${aiResult.provider}: ${aiResult.content.substring(0, 100)}...`,
      lessons: {
        insights,
        metrics: {
          avg_freedom_score: avgFreedomScore.toFixed(2),
          avg_repetition: (avgRepetition * 100).toFixed(1) + '%',
          avg_hallucination: (avgHallucination * 100).toFixed(1) + '%',
          avg_creative_drift: (avgCreativeDrift * 100).toFixed(1) + '%'
        }
      }
    });

    console.log('✅ Nightly reflection complete:', insights);

    return new Response(
      JSON.stringify({
        ok: true,
        insights,
        metrics: {
          avg_freedom_score: avgFreedomScore.toFixed(2),
          avg_repetition: (avgRepetition * 100).toFixed(1) + '%',
          avg_hallucination: (avgHallucination * 100).toFixed(1) + '%',
          avg_creative_drift: (avgCreativeDrift * 100).toFixed(1) + '%'
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('❌ Reflection error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
