import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Require authentication
    const authHeader = req.headers.get('Authorization') || '';
    const token = authHeader.replace('Bearer ', '');
    const { data: { user } } = await supabase.auth.getUser(token);
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    const { action, ...params } = await req.json();

    console.log(`[pf-access] Action: ${action}`);

    switch (action) {
      case 'scan': {
        const { url } = params;
        const issues = [
          { type: 'missing_alt', severity: 'high', element: 'img#hero' },
          { type: 'low_contrast', severity: 'medium', element: '.cta-button' }
        ];
        await supabase.from('access_scans').insert({
          url,
          issues_found: issues.length,
          scan_data: { issues }
        });
        return new Response(JSON.stringify({ success: true, issues }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      case 'fix': {
        const { issue_id, fix_type } = params;
        return new Response(JSON.stringify({
          success: true,
          fix: { code: '<img alt="Descriptive text" />', applied: true }
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }

      case 'report': {
        const { data: scans } = await supabase.from('access_scans')
          .select('*')
          .order('created_at', { ascending: false })
          .limit(params.limit || 10);
        return new Response(JSON.stringify({ success: true, scans }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      case 'tts': {
        return new Response(JSON.stringify({
          success: true,
          audio_url: 'https://example.com/audio.mp3'
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }

      case 'alt_text': {
        const { image_url } = params;
        return new Response(JSON.stringify({
          success: true,
          alt_text: 'A descriptive alt text generated by AI'
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }

      case 'recommendations': {
        return new Response(JSON.stringify({
          success: true,
          recommendations: [
            'Add ARIA labels to navigation',
            'Improve color contrast on buttons'
          ]
        }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }

      default:
        throw new Error(`Unknown action: ${action}`);
    }

  } catch (error: any) {
    console.error('[pf-access] Error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
