/**
 * GOVERNANCE Ultimate — System 5: Drift Detection & Correction
 * 
 * Continuous policy baseline monitoring, Jaccard distance calculation,
 * drift velocity tracking, and auto-generated correction proposals.
 * 
 * @module governance/ultimate/driftCorrectionEngine
 */

// ── Types ────────────────────────────────────────────────────────

export interface PolicyBaseline {
  id: string;
  name: string;
  declaredPolicies: string[];      // Policy IDs that SHOULD be active
  declaredModes: string[];         // Governance modes that SHOULD be allowed
  declaredConstraints: string[];   // Constraint keys
  capturedAt: number;
}

export interface DriftMeasurement {
  id: string;
  baselineId: string;
  jaccardDistance: number;         // 0 = identical, 1 = completely different
  missingPolicies: string[];
  extraPolicies: string[];
  modeMismatches: string[];
  constraintDrift: string[];
  velocity: number;               // Rate of divergence change per measurement
  severity: 'none' | 'low' | 'medium' | 'high' | 'critical';
  measuredAt: number;
}

export interface CorrectionProposal {
  id: string;
  measurementId: string;
  actions: CorrectionAction[];
  autoGenerated: boolean;
  status: 'proposed' | 'approved' | 'applied' | 'rejected';
  createdAt: number;
}

export interface CorrectionAction {
  type: 'add_policy' | 'remove_policy' | 'restore_mode' | 'restore_constraint';
  target: string;
  description: string;
}

export interface DriftCorrectionStats {
  totalBaselines: number;
  totalMeasurements: number;
  currentDriftScore: number;
  driftVelocity: number;
  proposalsPending: number;
  proposalsApplied: number;
  avgDriftSeverity: string;
}

// ── State ────────────────────────────────────────────────────────

const baselines: Map<string, PolicyBaseline> = new Map();
const measurements: DriftMeasurement[] = [];
const proposals: CorrectionProposal[] = [];
const MAX_MEASUREMENTS = 500;
const MAX_PROPOSALS = 200;

const DRIFT_THRESHOLDS = { low: 0.1, medium: 0.25, high: 0.5, critical: 0.75 };

function genId(prefix: string): string { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`; }

// ── Core API ────────────────────────────────────────────────────

/** Capture a policy baseline */
export function captureBaseline(
  name: string, policies: string[], modes: string[], constraints: string[],
): PolicyBaseline {
  const baseline: PolicyBaseline = {
    id: genId('bl'), name,
    declaredPolicies: [...policies],
    declaredModes: [...modes],
    declaredConstraints: [...constraints],
    capturedAt: Date.now(),
  };
  baselines.set(baseline.id, baseline);
  return baseline;
}

/** Measure drift against a baseline */
export function measureDrift(
  baselineId: string,
  currentPolicies: string[],
  currentModes: string[],
  currentConstraints: string[],
): DriftMeasurement | null {
  const baseline = baselines.get(baselineId);
  if (!baseline) return null;

  // Jaccard distance for policies
  const policyUnion = new Set([...baseline.declaredPolicies, ...currentPolicies]);
  const policyIntersection = baseline.declaredPolicies.filter(p => currentPolicies.includes(p));
  const jaccardDistance = policyUnion.size > 0
    ? 1 - policyIntersection.length / policyUnion.size
    : 0;

  const missing = baseline.declaredPolicies.filter(p => !currentPolicies.includes(p));
  const extra = currentPolicies.filter(p => !baseline.declaredPolicies.includes(p));
  const modeMismatch = baseline.declaredModes.filter(m => !currentModes.includes(m));
  const constraintDrift = baseline.declaredConstraints.filter(c => !currentConstraints.includes(c));

  // Calculate velocity (rate of change)
  const prevMeasurements = measurements.filter(m => m.baselineId === baselineId);
  const velocity = prevMeasurements.length > 0
    ? jaccardDistance - prevMeasurements[prevMeasurements.length - 1].jaccardDistance
    : 0;

  // Severity from Jaccard distance
  let severity: DriftMeasurement['severity'] = 'none';
  if (jaccardDistance >= DRIFT_THRESHOLDS.critical) severity = 'critical';
  else if (jaccardDistance >= DRIFT_THRESHOLDS.high) severity = 'high';
  else if (jaccardDistance >= DRIFT_THRESHOLDS.medium) severity = 'medium';
  else if (jaccardDistance >= DRIFT_THRESHOLDS.low) severity = 'low';

  const measurement: DriftMeasurement = {
    id: genId('dm'), baselineId, jaccardDistance,
    missingPolicies: missing, extraPolicies: extra,
    modeMismatches: modeMismatch, constraintDrift,
    velocity: Math.round(velocity * 1000) / 1000,
    severity, measuredAt: Date.now(),
  };

  measurements.push(measurement);
  if (measurements.length > MAX_MEASUREMENTS) measurements.splice(0, measurements.length - MAX_MEASUREMENTS);

  // Auto-generate correction proposal if drift is significant
  if (severity !== 'none' && severity !== 'low') {
    generateCorrectionProposal(measurement);
  }

  return measurement;
}

/** Auto-generate a correction proposal */
function generateCorrectionProposal(measurement: DriftMeasurement): CorrectionProposal {
  const actions: CorrectionAction[] = [];

  for (const policy of measurement.missingPolicies) {
    actions.push({ type: 'add_policy', target: policy, description: `Restore missing policy: ${policy}` });
  }
  for (const policy of measurement.extraPolicies) {
    actions.push({ type: 'remove_policy', target: policy, description: `Remove undeclared policy: ${policy}` });
  }
  for (const mode of measurement.modeMismatches) {
    actions.push({ type: 'restore_mode', target: mode, description: `Restore missing mode: ${mode}` });
  }
  for (const constraint of measurement.constraintDrift) {
    actions.push({ type: 'restore_constraint', target: constraint, description: `Restore constraint: ${constraint}` });
  }

  const proposal: CorrectionProposal = {
    id: genId('cp'), measurementId: measurement.id,
    actions, autoGenerated: true,
    status: 'proposed', createdAt: Date.now(),
  };

  proposals.push(proposal);
  if (proposals.length > MAX_PROPOSALS) proposals.splice(0, proposals.length - MAX_PROPOSALS);

  return proposal;
}

/** Approve/reject a correction proposal */
export function resolveProposal(proposalId: string, approved: boolean): boolean {
  const proposal = proposals.find(p => p.id === proposalId);
  if (!proposal || proposal.status !== 'proposed') return false;
  proposal.status = approved ? 'approved' : 'rejected';
  return true;
}

/** Mark a proposal as applied */
export function applyProposal(proposalId: string): boolean {
  const proposal = proposals.find(p => p.id === proposalId);
  if (!proposal || proposal.status !== 'approved') return false;
  proposal.status = 'applied';
  return true;
}

// ── Query ────────────────────────────────────────────────────────

export function getBaseline(id: string): PolicyBaseline | undefined { return baselines.get(id); }
export function getAllBaselines(): PolicyBaseline[] { return [...baselines.values()]; }
export function getMeasurements(baselineId?: string, count?: number): DriftMeasurement[] {
  let filtered = baselineId ? measurements.filter(m => m.baselineId === baselineId) : measurements;
  if (count) filtered = filtered.slice(-count);
  return filtered;
}
export function getProposals(status?: CorrectionProposal['status']): CorrectionProposal[] {
  return status ? proposals.filter(p => p.status === status) : [...proposals];
}

export function getDriftCorrectionStats(): DriftCorrectionStats {
  const latest = measurements[measurements.length - 1];

  // O(n) frequency count instead of O(n³) sort-with-filter
  let mostCommon: DriftMeasurement['severity'] = 'none';
  if (measurements.length > 0) {
    const freq: Record<string, number> = {};
    let maxCount = 0;
    for (const m of measurements) {
      const c = (freq[m.severity] = (freq[m.severity] || 0) + 1);
      if (c > maxCount) { maxCount = c; mostCommon = m.severity; }
    }
  }

  // Single-pass proposal counting
  let pending = 0, applied = 0;
  for (const p of proposals) {
    if (p.status === 'proposed') pending++;
    else if (p.status === 'applied') applied++;
  }

  return {
    totalBaselines: baselines.size,
    totalMeasurements: measurements.length,
    currentDriftScore: latest?.jaccardDistance ?? 0,
    driftVelocity: latest?.velocity ?? 0,
    proposalsPending: pending,
    proposalsApplied: applied,
    avgDriftSeverity: mostCommon,
  };
}

export function resetDriftCorrection(): void {
  baselines.clear();
  measurements.length = 0;
  proposals.length = 0;
}
