/**
 * Automated Health Monitoring with Alerting
 * Real-time module health tracking with configurable alerts
 */

import { supabase } from '@/integrations/supabase/client';
import { substrate } from '@/lib/substrate';

export type AlertSeverity = 'info' | 'warning' | 'critical';
export type AlertStatus = 'active' | 'acknowledged' | 'resolved';

export interface HealthAlert {
  id: string;
  module: string;
  severity: AlertSeverity;
  status: AlertStatus;
  message: string;
  healthScore: number;
  threshold: number;
  triggeredAt: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  metadata?: Record<string, unknown>;
}

export interface AlertConfig {
  module: string;
  criticalThreshold: number;
  warningThreshold: number;
  enabled: boolean;
  cooldownMinutes: number;
}

export interface MonitoringState {
  isRunning: boolean;
  lastCheck: string | null;
  activeAlerts: HealthAlert[];
  moduleHealth: Map<string, number>;
}

const DEFAULT_ALERT_CONFIGS: AlertConfig[] = [
  // Kernel Layer
  { module: 'core', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 5 },
  { module: 'defense', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 10 },
  { module: 'vision', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 20 },
  { module: 'access', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 10 },
  { module: 'ripple', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 15 },
  // Cognitive Layer
  { module: 'brain', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  { module: 'decode', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  { module: 'nexus', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 15 },
  { module: 'dream', criticalThreshold: 40, warningThreshold: 60, enabled: true, cooldownMinutes: 30 },
  // Operational Layer
  { module: 'integration', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  // Administrative Layer
  { module: 'system', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 5 },
  { module: 'inclusive', criticalThreshold: 40, warningThreshold: 60, enabled: true, cooldownMinutes: 20 },
  { module: 'evolution', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  // Orchestrator Layer
  { module: 'cortex', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  { module: 'encode', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  // Infrastructure Layer
  { module: 'memory', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 10 },
  { module: 'relay', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 10 },
  { module: 'audit', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 10 },
  { module: 'identity', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 10 },
  { module: 'economy', criticalThreshold: 30, warningThreshold: 50, enabled: true, cooldownMinutes: 15 },
  { module: 'sandbox', criticalThreshold: 35, warningThreshold: 55, enabled: true, cooldownMinutes: 20 },
  // Mesh Overlays
  { module: 'immunity', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 10 },
  { module: 'evolution', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 15 },
  { module: 'intent', criticalThreshold: 25, warningThreshold: 45, enabled: true, cooldownMinutes: 15 },
  { module: 'governance', criticalThreshold: 20, warningThreshold: 40, enabled: true, cooldownMinutes: 10 },
];

const MAX_ACTIVE_ALERTS = 200;

// In-memory alert state
const alertState: MonitoringState = {
  isRunning: false,
  lastCheck: null,
  activeAlerts: [],
  moduleHealth: new Map(),
};

// Cooldown tracking
const lastAlertTime = new Map<string, number>();

/**
 * Check if module is in cooldown
 */
function isInCooldown(module: string, cooldownMinutes: number): boolean {
  const lastTime = lastAlertTime.get(module);
  if (!lastTime) return false;
  return Date.now() - lastTime < cooldownMinutes * 60 * 1000;
}

/**
 * Create a new alert
 */
function createAlert(
  module: string,
  severity: AlertSeverity,
  healthScore: number,
  threshold: number
): HealthAlert {
  return {
    id: crypto.randomUUID(),
    module,
    severity,
    status: 'active',
    message: `${module.toUpperCase()} health dropped to ${healthScore}% (threshold: ${threshold}%)`,
    healthScore,
    threshold,
    triggeredAt: new Date().toISOString(),
    metadata: { autoGenerated: true },
  };
}

/**
 * Check module health and generate alerts
 */
async function checkModuleHealth(config: AlertConfig): Promise<HealthAlert | null> {
  if (!config.enabled) return null;
  
  try {
    const response = await substrate.invoke({ module: config.module as any, action: 'status' });
    
    if (!response.success) {
      // Module not responding - critical
      if (!isInCooldown(config.module, config.cooldownMinutes)) {
        lastAlertTime.set(config.module, Date.now());
        return createAlert(config.module, 'critical', 0, config.criticalThreshold);
      }
      return null;
    }
    
    const data = response.data as { health?: number; health_score?: number };
    const health = data?.health ?? data?.health_score ?? 100;
    
    alertState.moduleHealth.set(config.module, health);
    
    // Check thresholds
    if (health <= config.criticalThreshold) {
      if (!isInCooldown(config.module, config.cooldownMinutes)) {
        lastAlertTime.set(config.module, Date.now());
        return createAlert(config.module, 'critical', health, config.criticalThreshold);
      }
    } else if (health <= config.warningThreshold) {
      if (!isInCooldown(config.module, config.cooldownMinutes)) {
        lastAlertTime.set(config.module, Date.now());
        return createAlert(config.module, 'warning', health, config.warningThreshold);
      }
    } else {
      // Health recovered - resolve active alerts
      const activeAlert = alertState.activeAlerts.find(
        a => a.module === config.module && a.status === 'active'
      );
      if (activeAlert) {
        activeAlert.status = 'resolved';
        activeAlert.resolvedAt = new Date().toISOString();
      }
    }
    
    return null;
  } catch {
    return null;
  }
}

/**
 * Run a single health check cycle
 */
export async function runHealthCheck(
  configs: AlertConfig[] = DEFAULT_ALERT_CONFIGS
): Promise<{
  timestamp: string;
  newAlerts: HealthAlert[];
  moduleHealth: Record<string, number>;
}> {
  const newAlerts: HealthAlert[] = [];
  
  // Check all modules in parallel
  const results = await Promise.all(
    configs.map(config => checkModuleHealth(config))
  );
  
  results.forEach(alert => {
    if (alert) {
      newAlerts.push(alert);
      alertState.activeAlerts.push(alert);
    }
  });
  
  alertState.lastCheck = new Date().toISOString();
  
  // Persist alerts to database (fire-and-forget — don't block the check cycle)
  if (newAlerts.length > 0) {
    persistAlerts(newAlerts).catch(() => {});
  }
  
  // Clean up old resolved alerts and enforce cap
  alertState.activeAlerts = alertState.activeAlerts.filter(
    a => a.status === 'active' || 
    (a.resolvedAt && Date.now() - new Date(a.resolvedAt).getTime() < 3600000)
  );
  if (alertState.activeAlerts.length > MAX_ACTIVE_ALERTS) {
    alertState.activeAlerts = alertState.activeAlerts.slice(-MAX_ACTIVE_ALERTS);
  }
  
  return {
    timestamp: alertState.lastCheck,
    newAlerts,
    moduleHealth: Object.fromEntries(alertState.moduleHealth),
  };
}

/**
 * Persist alerts to database
 */
async function persistAlerts(alerts: HealthAlert[]): Promise<void> {
  try {
    await supabase.from('brain_events').insert(
      alerts.map(alert => ({
        module: 'system',
        event_type: 'health_alert',
        data: alert as any,
        outcome: alert.severity,
      }))
    );
  } catch (err) {
    console.error('Failed to persist alerts:', err);
  }
}

/**
 * Acknowledge an alert
 */
export function acknowledgeAlert(alertId: string): boolean {
  const alert = alertState.activeAlerts.find(a => a.id === alertId);
  if (alert && alert.status === 'active') {
    alert.status = 'acknowledged';
    alert.acknowledgedAt = new Date().toISOString();
    return true;
  }
  return false;
}

/**
 * Resolve an alert manually
 */
export function resolveAlert(alertId: string): boolean {
  const alert = alertState.activeAlerts.find(a => a.id === alertId);
  if (alert && alert.status !== 'resolved') {
    alert.status = 'resolved';
    alert.resolvedAt = new Date().toISOString();
    return true;
  }
  return false;
}

/**
 * Get current monitoring state
 */
export function getMonitoringState(): MonitoringState {
  return { ...alertState };
}

/**
 * Get active alerts only
 */
export function getActiveAlerts(): HealthAlert[] {
  return alertState.activeAlerts.filter(a => a.status === 'active');
}

/**
 * Get alert history from database
 */
export async function getAlertHistory(
  limit: number = 50
): Promise<HealthAlert[]> {
  try {
    const { data } = await supabase
      .from('brain_events')
      .select('data, created_at')
      .eq('event_type', 'health_alert')
      .order('created_at', { ascending: false })
      .limit(limit);
    
    return (data || []).map(row => ({
      ...(row.data as unknown as HealthAlert),
      triggeredAt: row.created_at,
    }));
  } catch {
    return [];
  }
}

/**
 * Start continuous monitoring (call from app initialization)
 */
let monitoringInterval: ReturnType<typeof setInterval> | null = null;

export function startMonitoring(intervalMs: number = 60000): void {
  if (alertState.isRunning) return;
  
  alertState.isRunning = true;
  
  // Initial check
  runHealthCheck();
  
  // Periodic checks
  monitoringInterval = setInterval(() => {
    runHealthCheck();
  }, intervalMs);
}

export function stopMonitoring(): void {
  if (monitoringInterval) {
    clearInterval(monitoringInterval);
    monitoringInterval = null;
  }
  alertState.isRunning = false;
}

/**
 * Get health summary for dashboard
 */
export async function getHealthSummary(): Promise<{
  overallHealth: number;
  criticalCount: number;
  warningCount: number;
  healthyCount: number;
  modules: Array<{ module: string; health: number; status: string }>;
}> {
  const health = Object.fromEntries(alertState.moduleHealth);
  const modules = Object.entries(health).map(([module, score]) => ({
    module,
    health: score,
    status: score <= 30 ? 'critical' : score <= 50 ? 'warning' : 'healthy',
  }));
  
  const criticalCount = modules.filter(m => m.status === 'critical').length;
  const warningCount = modules.filter(m => m.status === 'warning').length;
  const healthyCount = modules.filter(m => m.status === 'healthy').length;
  
  const overallHealth = modules.length > 0
    ? Math.round(modules.reduce((sum, m) => sum + m.health, 0) / modules.length)
    : 100;
  
  return { overallHealth, criticalCount, warningCount, healthyCount, modules };
}
