/**
 * REPORTER Engine — Multi-channel notification dispatch
 * Dispatches maintenance results via DB, email, ATLAS, and webhooks
 */

import { supabase } from '@/integrations/supabase/client';
import type {
  MaintenanceRunResult,
  MaintenanceFinding,
  NotificationConfig,
  OrchestratorRunResult,
  TriggerSource,
} from './types';

// ── Config Loader ──────────────────────────────────────────────────────────

async function loadNotificationConfig(): Promise<NotificationConfig | null> {
  try {
    const { data, error } = await supabase
      .from('maintenance_notification_config' as any)
      .select('*')
      .eq('enabled', true)
      .limit(1)
      .single();

    if (error || !data) return null;

    const row = data as any;
    return {
      emailRecipients: row.email_recipients ?? [],
      webhookUrl: row.webhook_url ?? undefined,
      webhookSecret: row.webhook_secret ?? undefined,
      notifyOnFailure: row.notify_on_failure ?? true,
      notifyOnSuccess: row.notify_on_success ?? false,
      notifyOnPartial: row.notify_on_partial ?? true,
      atlasNotifications: row.atlas_notifications ?? true,
      enabled: row.enabled ?? true,
    };
  } catch {
    return null;
  }
}

// ── DB Persistence ─────────────────────────────────────────────────────────

async function persistToDb(result: MaintenanceRunResult): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from('maintenance_reports' as any)
      .insert({
        engine: result.engine,
        status: result.status,
        trigger_source: result.triggerSource,
        duration_ms: result.durationMs,
        findings: result.findings as any,
        summary: result.summary as any,
        pass_results: result.passResults as any,
        completed_at: new Date().toISOString(),
        metadata: result.metadata ?? {},
      } as any)
      .select('id')
      .single();

    if (error) {
      console.error('[REPORTER] DB persist failed:', error.message);
      return null;
    }
    return (data as any)?.id ?? null;
  } catch (err: any) {
    console.error('[REPORTER] DB persist error:', err?.message);
    return null;
  }
}

// ── Email Dispatch ─────────────────────────────────────────────────────────

function buildEmailBody(orchestratorResult: OrchestratorRunResult): string {
  const statusEmoji = orchestratorResult.overallStatus === 'passed' ? '✅' :
    orchestratorResult.overallStatus === 'failed' ? '❌' : '⚠️';

  const sections = orchestratorResult.engines.map(engine => {
    const icon = engine.status === 'passed' ? '✅' : engine.status === 'failed' ? '❌' : '⚠️';
    const criticalFindings = engine.findings
      .filter(f => f.severity === 'critical' || f.severity === 'error')
      .slice(0, 5);

    return `
<h3>${icon} ${engine.engine.toUpperCase()} Engine</h3>
<p>Status: <strong>${engine.status.toUpperCase()}</strong> | Duration: ${engine.durationMs}ms</p>
<p>Findings: ${engine.summary.critical} critical, ${engine.summary.errors} errors, ${engine.summary.warnings} warnings</p>
${criticalFindings.length > 0 ? `
<ul>
${criticalFindings.map(f => `<li><strong>${f.title}</strong>: ${f.detail}</li>`).join('\n')}
</ul>` : '<p style="color:#888">No critical findings.</p>'}`;
  }).join('\n<hr/>\n');

  return `
<html>
<body style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
<h1>${statusEmoji} Maintenance Report</h1>
<p><strong>Overall Status:</strong> ${orchestratorResult.overallStatus.toUpperCase()}</p>
<p><strong>Duration:</strong> ${orchestratorResult.totalDurationMs}ms</p>
<p><strong>Triggered By:</strong> ${orchestratorResult.triggeredBy}</p>
<p><strong>Completed:</strong> ${orchestratorResult.completedAt}</p>
<hr/>
${sections}
<hr/>
<p style="color:#888; font-size:12px">Generated by CMPSBL Maintenance System</p>
</body>
</html>`;
}

async function sendEmail(
  config: NotificationConfig,
  orchestratorResult: OrchestratorRunResult,
): Promise<boolean> {
  if (config.emailRecipients.length === 0) return false;

  try {
    const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
    const anonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    const response = await fetch(
      `https://${projectId}.supabase.co/functions/v1/maintenance-reporter`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${anonKey}`,
        },
        body: JSON.stringify({
          action: 'send_email',
          recipients: config.emailRecipients,
          subject: `[CMPSBL] Maintenance ${orchestratorResult.overallStatus.toUpperCase()} — ${new Date().toLocaleDateString()}`,
          html: buildEmailBody(orchestratorResult),
        }),
      },
    );

    return response.ok;
  } catch {
    console.error('[REPORTER] Email dispatch failed');
    return false;
  }
}

// ── Webhook Dispatch ───────────────────────────────────────────────────────

async function sendWebhook(
  config: NotificationConfig,
  orchestratorResult: OrchestratorRunResult,
): Promise<boolean> {
  if (!config.webhookUrl) return false;

  try {
    const payload = {
      event: 'maintenance.completed',
      timestamp: orchestratorResult.completedAt,
      status: orchestratorResult.overallStatus,
      duration_ms: orchestratorResult.totalDurationMs,
      triggered_by: orchestratorResult.triggeredBy,
      engines: orchestratorResult.engines.map(e => ({
        engine: e.engine,
        status: e.status,
        duration_ms: e.durationMs,
        summary: e.summary,
      })),
    };

    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (config.webhookSecret) {
      headers['X-Webhook-Secret'] = config.webhookSecret;
    }

    const response = await fetch(config.webhookUrl, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    });

    return response.ok;
  } catch {
    console.error('[REPORTER] Webhook dispatch failed');
    return false;
  }
}

// ── ATLAS Notification ─────────────────────────────────────────────────────

function sendAtlasNotification(orchestratorResult: OrchestratorRunResult): boolean {
  try {
    // Dispatch through the substrate event system
    const { emit } = require('@/lib/substrate/events/emit');

    emit('maintenance:completed', {
      status: orchestratorResult.overallStatus,
      duration_ms: orchestratorResult.totalDurationMs,
      triggered_by: orchestratorResult.triggeredBy,
      engine_summaries: orchestratorResult.engines.map(e => ({
        engine: e.engine,
        status: e.status,
        critical: e.summary.critical,
        errors: e.summary.errors,
      })),
    });

    return true;
  } catch {
    return false;
  }
}

// ── Should Notify Check ────────────────────────────────────────────────────

function shouldNotify(config: NotificationConfig, status: string): boolean {
  if (!config.enabled) return false;
  if (status === 'failed' && config.notifyOnFailure) return true;
  if (status === 'passed' && config.notifyOnSuccess) return true;
  if (status === 'partial' && config.notifyOnPartial) return true;
  return false;
}

// ── Main Runner ────────────────────────────────────────────────────────────

export async function runReporterEngine(
  orchestratorResult: OrchestratorRunResult,
  triggerSource: TriggerSource = 'manual',
): Promise<MaintenanceRunResult> {
  const start = performance.now();
  const findings: MaintenanceFinding[] = [];

  // 1. Always persist to DB
  let dbSuccess = true;
  for (const engineResult of orchestratorResult.engines) {
    const id = await persistToDb(engineResult);
    if (!id) dbSuccess = false;
  }

  findings.push({
    id: 'report_db',
    severity: dbSuccess ? 'info' : 'warn',
    category: 'reporting',
    title: dbSuccess ? 'Results persisted to database' : 'Some DB writes failed',
    detail: `${orchestratorResult.engines.length} engine results ${dbSuccess ? 'saved' : 'partially saved'}.`,
  });

  // 2. Load notification config
  const config = await loadNotificationConfig();
  let emailSent = false;
  let webhookSent = false;
  let atlasNotified = false;

  if (config && shouldNotify(config, orchestratorResult.overallStatus)) {
    // 3. Email
    if (config.emailRecipients.length > 0) {
      emailSent = await sendEmail(config, orchestratorResult);
      findings.push({
        id: 'report_email',
        severity: emailSent ? 'info' : 'warn',
        category: 'reporting',
        title: emailSent ? `Email sent to ${config.emailRecipients.length} recipient(s)` : 'Email dispatch failed',
        detail: emailSent ? `Recipients: ${config.emailRecipients.join(', ')}` : 'Check edge function logs.',
      });
    }

    // 4. Webhook
    if (config.webhookUrl) {
      webhookSent = await sendWebhook(config, orchestratorResult);
      findings.push({
        id: 'report_webhook',
        severity: webhookSent ? 'info' : 'warn',
        category: 'reporting',
        title: webhookSent ? 'Webhook delivered' : 'Webhook delivery failed',
        detail: webhookSent ? `URL: ${config.webhookUrl}` : 'Check webhook URL and connectivity.',
      });
    }

    // 5. ATLAS
    if (config.atlasNotifications) {
      atlasNotified = sendAtlasNotification(orchestratorResult);
      findings.push({
        id: 'report_atlas',
        severity: 'info',
        category: 'reporting',
        title: atlasNotified ? 'ATLAS notification dispatched' : 'ATLAS notification skipped',
        detail: 'Maintenance results routed through substrate event system.',
      });
    }
  } else {
    findings.push({
      id: 'report_config',
      severity: 'info',
      category: 'reporting',
      title: config ? 'Notification suppressed by config' : 'No notification config found',
      detail: config ? `Status "${orchestratorResult.overallStatus}" does not trigger notifications per current settings.` : 'Add notification preferences in maintenance_notification_config.',
    });
  }

  // Update orchestrator result
  orchestratorResult.notificationsSent = {
    email: emailSent,
    webhook: webhookSent,
    atlas: atlasNotified,
    db: dbSuccess,
  };

  const durationMs = Math.round(performance.now() - start);

  return {
    engine: 'reporter',
    status: dbSuccess ? 'passed' : 'partial',
    triggerSource,
    durationMs,
    findings,
    summary: {
      total: findings.length,
      critical: 0,
      errors: findings.filter(f => f.severity === 'error').length,
      warnings: findings.filter(f => f.severity === 'warn').length,
      info: findings.filter(f => f.severity === 'info').length,
      autoFixed: 0,
      passed: dbSuccess,
    },
  };
}
