/**
 * SIGNAL FORGE — Free Template Synthesis Engine
 * 
 * Generates production-ready templates from the substrate's combinatorial
 * module × category × capability space. Auth-gated with daily rate limits.
 * Lives on the CodeLab page as the primary hero feature.
 */

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Sparkles, Dices, Download, Zap, Brain, Shield, Moon, Eye, 
  MessageSquare, Settings, Cpu, Globe, ArrowRight, Check, 
  Loader2, Copy, Lock, Network, Flame, RefreshCw, LogIn
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { forgeSignalBatch, SIGNAL_FORGE_PRIMITIVE } from "@/lib/substrate/forge/signal-forge";
import type { GeneratedTemplate } from "@/lib/discovery/template-generator";
import { Link } from "react-router-dom";

// Rate limit: 5 downloads per day per user
const DAILY_LIMIT = 5;
const STORAGE_KEY = 'signal-forge-downloads';

interface DownloadRecord {
  date: string;
  count: number;
}

function getTodayDownloads(): DownloadRecord {
  const today = new Date().toISOString().slice(0, 10);
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const record: DownloadRecord = JSON.parse(raw);
      if (record.date === today) return record;
    }
  } catch {}
  return { date: today, count: 0 };
}

function incrementDownloads(): DownloadRecord {
  const record = getTodayDownloads();
  record.count++;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(record));
  return record;
}

const CATEGORY_ICONS: Record<string, React.ElementType> = {
  cognitive: Brain,
  evolution: Flame,
  security: Shield,
  routing: Network,
  learning: Brain,
  orchestration: Cpu,
  integration: Globe,
  observability: Eye,
  governance: Shield,
  compliance: Lock,
  prediction: Sparkles,
  ethics: Shield,
  privacy: Lock,
  synthesis: Zap,
  localization: Globe,
  geospatial: Globe,
  simulation: Cpu,
  contracts: Settings,
  acquisition: Download,
  edge: Zap,
};

export function SignalForge() {
  const [user, setUser] = useState<any>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [isForging, setIsForging] = useState(false);
  const [forgedTemplates, setForgedTemplates] = useState<GeneratedTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<GeneratedTemplate | null>(null);
  const [downloadsToday, setDownloadsToday] = useState(0);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_, session) => {
      setUser(session?.user ?? null);
      setAuthLoading(false);
    });
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
      setAuthLoading(false);
    });
    setDownloadsToday(getTodayDownloads().count);
    return () => subscription.unsubscribe();
  }, []);

  const handleForge = useCallback(() => {
    setIsForging(true);
    requestAnimationFrame(() => {
      setTimeout(() => {
        const result = forgeSignalBatch({
          batchSize: 12,
          minModules: 2,
          maxModules: 5,
          minCjpiTarget: 80,
          biasHighValue: true,
        });
        setForgedTemplates(result.templates);
        setSelectedTemplate(null);
        setIsForging(false);
        toast.success(`Forged ${result.templates.length} templates in ${result.executionMs}ms [${result.batchId}]`);
      }, 600);
    });
  }, []);

  const handleDownload = (template: GeneratedTemplate) => {
    if (!user) {
      toast.error('Sign in to download templates');
      return;
    }
    const record = getTodayDownloads();
    if (record.count >= DAILY_LIMIT) {
      toast.error(`Daily limit reached (${DAILY_LIMIT}/day). Come back tomorrow!`);
      return;
    }

    const content = `/**
 * ${template.namePattern}
 * Generated by CMPSBL SIGNAL FORGE
 * 
 * Category: ${template.category}
 * Module Chain: ${template.modulePattern.join(' → ')}
 * Error Strategy: ${template.errorStrategy}
 * Max Execution: ${template.maxExecutionMs}ms
 * 
 * Description:
 * ${template.descriptionPattern}
 * 
 * Rationale:
 * ${template.rationale}
 * 
 * CJPI Scores:
 *   Strategic Leverage: ${template.baseBreakdown.strategicLeverage}/100
 *   Recursion Potential: ${template.baseBreakdown.recursionPotential}/100
 *   Cross-Node Impact: ${template.baseBreakdown.crossNodeImpact}/100
 *   Composability: ${template.baseBreakdown.composability}/100
 *   Governance Influence: ${template.baseBreakdown.governanceInfluence}/100
 *   Moat Sensitivity: ${template.baseBreakdown.moatSensitivity}/100
 */

import { substrate } from '@cmpsbl/sdk';

// Entry: ${template.entryPattern}
// Exit: ${template.exitPattern}

const pipeline = substrate.pipeline({
  name: '${template.namePattern}',
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
  errorStrategy: '${template.errorStrategy}',
  maxExecutionMs: ${template.maxExecutionMs},
});

// Initialize module chain
${template.modulePattern.map((m, i) => `const ${m.toLowerCase()}Node = pipeline.node('${m}', { order: ${i + 1} });`).join('\n')}

// Wire entry → chain → exit
pipeline.entry('${template.entryPattern}', ${template.modulePattern[0].toLowerCase()}Node);
${template.modulePattern.slice(0, -1).map((m, i) => `${m.toLowerCase()}Node.pipe(${template.modulePattern[i + 1].toLowerCase()}Node);`).join('\n')}
${template.modulePattern[template.modulePattern.length - 1].toLowerCase()}Node.exit('${template.exitPattern}');

// Execute
export async function run(input: Record<string, unknown>) {
  return pipeline.execute(input);
}

export default pipeline;
`;

    const blob = new Blob([content], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const kebab = template.namePattern.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    a.download = `${kebab}.ts`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    const updated = incrementDownloads();
    setDownloadsToday(updated.count);
    toast.success(`Downloaded: ${template.namePattern} (${updated.count}/${DAILY_LIMIT} today)`);
  };

  const handleCopy = (template: GeneratedTemplate) => {
    const snippet = `// ${template.namePattern} — ${template.category}
// Modules: ${template.modulePattern.join(' → ')}
import { substrate } from '@cmpsbl/sdk';
const pipeline = substrate.pipeline({
  name: '${template.namePattern}',
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
});`;
    navigator.clipboard.writeText(snippet);
    setCopiedId(template.namePattern);
    setTimeout(() => setCopiedId(null), 2000);
    toast.success('Copied to clipboard');
  };

  const remaining = DAILY_LIMIT - downloadsToday;

  const avgCjpi = (t: GeneratedTemplate) => {
    const b = t.baseBreakdown;
    return Math.round(
      b.strategicLeverage * 0.30 + b.recursionPotential * 0.20 +
      b.crossNodeImpact * 0.15 + b.composability * 0.15 +
      b.governanceInfluence * 0.10 + b.moatSensitivity * 0.10
    );
  };

  return (
    <section className="relative overflow-hidden">
      {/* Hero — Cinematic Mobile-First */}
      <div className="relative border-b border-border/50 overflow-hidden">
        {/* Layered background */}
        <div className="absolute inset-0 bg-gradient-to-b from-background via-background to-muted/30" />
        <div className="absolute inset-0 opacity-[0.04]" style={{
          backgroundImage: `
            linear-gradient(hsl(var(--primary) / 0.6) 1px, transparent 1px),
            linear-gradient(90deg, hsl(var(--primary) / 0.6) 1px, transparent 1px)
          `,
          backgroundSize: '48px 48px',
        }} />
        {/* Glow orbs */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] rounded-full bg-primary/8 blur-[120px]" />
        <div className="absolute bottom-0 right-0 w-[300px] h-[200px] rounded-full bg-neon-cyan/6 blur-[80px]" />

        <div className="container mx-auto px-5 pt-10 pb-12 md:pt-20 md:pb-16 relative">
          <div className="max-w-3xl mx-auto text-center">
            {/* Top badge */}
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex justify-center mb-5"
            >
              <Badge variant="outline" className="gap-2 px-3.5 py-1.5 text-xs font-mono border-primary/30 bg-primary/5 text-primary">
                <Dices className="w-3.5 h-3.5" />
                FREE · UNLIMITED FORGING · {DAILY_LIMIT} DOWNLOADS/DAY
              </Badge>
            </motion.div>

            {/* Title */}
            <motion.h1
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.05 }}
              className="text-[2.5rem] leading-[1.05] sm:text-5xl md:text-6xl font-black tracking-tight mb-5"
            >
              <span className="bg-gradient-to-r from-primary via-neon-cyan to-neon-purple bg-clip-text text-transparent">
                SIGNAL FORGE
              </span>
            </motion.h1>

            {/* Subtitle */}
            <motion.p
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-base sm:text-lg text-muted-foreground leading-relaxed mb-8 max-w-xl mx-auto"
            >
              Synthesize production-ready pipeline templates from 
              <span className="font-semibold text-foreground"> 31 modules × 20 categories</span>. 
              Every template is unique, CJPI-validated, and free to forge.
            </motion.p>

            {/* Cinematic Pipeline Diagram — Vertical on mobile, horizontal on desktop */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.15 }}
              className="mb-10 mx-auto max-w-md md:max-w-2xl"
            >
              <div className="rounded-2xl border border-border/60 bg-card/60 backdrop-blur-sm p-5 md:p-6">
                <p className="text-[11px] font-mono uppercase tracking-widest text-muted-foreground mb-4">Pipeline Synthesis Flow</p>
                
                {/* Mobile: vertical timeline / Desktop: horizontal */}
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 md:gap-0">
                  {[
                    { icon: Dices, label: 'Randomize', color: 'bg-primary/10 text-primary border-primary/20' },
                    { icon: Brain, label: 'Synthesize', color: 'bg-neon-cyan/10 text-neon-cyan border-neon-cyan/20' },
                    { icon: Zap, label: 'Score', color: 'bg-neon-amber/10 text-neon-amber border-neon-amber/20' },
                    { icon: Eye, label: 'Preview', color: 'bg-neon-green/10 text-neon-green border-neon-green/20' },
                    { icon: Download, label: 'Download', color: 'bg-neon-purple/10 text-neon-purple border-neon-purple/20' },
                  ].map((step, i, arr) => (
                    <div key={i} className="flex md:flex-col items-center gap-3 md:gap-2 relative">
                      {/* Step circle */}
                      <div className={`w-11 h-11 md:w-12 md:h-12 rounded-xl border ${step.color} flex items-center justify-center shrink-0 transition-transform hover:scale-110`}>
                        <step.icon className="w-5 h-5" />
                      </div>
                      <span className="text-sm font-semibold text-foreground md:text-xs">{step.label}</span>
                      
                      {/* Connector line — vertical on mobile, horizontal on desktop */}
                      {i < arr.length - 1 && (
                        <>
                          {/* Mobile vertical connector */}
                          <div className="absolute left-[21px] top-[44px] w-px h-3 bg-border/60 md:hidden" />
                          {/* Desktop horizontal connector */}
                          <div className="hidden md:block absolute -right-[calc(50%-24px)] top-[23px] w-[calc(100%-48px)] h-px bg-border/60" style={{ left: 'calc(50% + 24px)' }} />
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>

            {/* Forge Button */}
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="space-y-3"
            >
              <Button
                size="lg"
                onClick={handleForge}
                disabled={isForging}
                className="gap-3 px-8 h-14 text-base font-bold shadow-xl shadow-primary/25 hover:shadow-primary/35 hover:scale-[1.02] active:scale-[0.98] transition-all"
              >
                {isForging ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Forging…
                  </>
                ) : (
                  <>
                    <Dices className="w-5 h-5" />
                    Forge Templates
                    <Sparkles className="w-4 h-4" />
                  </>
                )}
              </Button>

              {forgedTemplates.length > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleForge}
                  disabled={isForging}
                  className="gap-2 text-muted-foreground"
                >
                  <RefreshCw className="w-4 h-4" />
                  Re-Forge New Batch
                </Button>
              )}

              <p className="text-xs text-muted-foreground">
                {user ? (
                  <>
                    <span className="text-neon-green font-medium font-mono">{remaining} downloads remaining</span>
                    {' '}· Forge unlimited
                  </>
                ) : (
                  <>
                    Forge freely · <Link to="/auth" className="text-primary hover:underline font-medium">Sign in</Link> to download ({DAILY_LIMIT}/day free)
                  </>
                )}
              </p>
            </motion.div>
          </div>
        </div>
      </div>
      {/* Forged Results */}
      <AnimatePresence>
        {forgedTemplates.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="container mx-auto px-4 py-8 md:py-12"
          >
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="text-2xl font-bold">Forged Templates</h2>
                <p className="text-sm text-muted-foreground">
                  {forgedTemplates.length} unique pipeline templates synthesized from the substrate
                </p>
              </div>
              <Badge variant="outline" className="text-xs">
                CJPI Validated
              </Badge>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {forgedTemplates.map((template, index) => {
                const Icon = CATEGORY_ICONS[template.category] || Zap;
                const cjpi = avgCjpi(template);
                const isSelected = selectedTemplate?.namePattern === template.namePattern;

                return (
                  <motion.div
                    key={template.namePattern + index}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <Card
                      className={`p-4 cursor-pointer transition-all hover:border-primary/50 ${
                        isSelected ? 'border-primary ring-1 ring-primary/20' : ''
                      }`}
                      onClick={() => setSelectedTemplate(isSelected ? null : template)}
                    >
                      <div className="flex items-start gap-3 mb-3">
                        <div className="w-10 h-10 rounded-lg bg-muted flex items-center justify-center shrink-0">
                          <Icon className="w-5 h-5 text-primary" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-semibold text-sm truncate">{template.namePattern}</h3>
                          <p className="text-xs text-muted-foreground capitalize">{template.category}</p>
                        </div>
                        <Badge 
                          variant="outline" 
                          className={`shrink-0 text-xs ${
                            cjpi >= 90 ? 'text-emerald-500 border-emerald-500/30' :
                            cjpi >= 80 ? 'text-cyan-500 border-cyan-500/30' :
                            'text-amber-500 border-amber-500/30'
                          }`}
                        >
                          CJPI {cjpi}
                        </Badge>
                      </div>

                      {/* Module chain */}
                      <div className="flex flex-wrap gap-1 mb-3">
                        {template.modulePattern.map((mod, i) => (
                          <Badge key={i} variant="secondary" className="text-[10px] font-mono">
                            {mod}
                          </Badge>
                        ))}
                      </div>

                      <p className="text-xs text-muted-foreground line-clamp-2 mb-3">
                        {template.descriptionPattern}
                      </p>

                      {/* Expanded detail */}
                      <AnimatePresence>
                        {isSelected && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="pt-3 border-t border-border/50 space-y-3">
                              {/* Scores */}
                              <div className="grid grid-cols-3 gap-2 text-xs">
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.strategicLeverage}</p>
                                  <p className="text-muted-foreground text-[10px]">Strategy</p>
                                </div>
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.composability}</p>
                                  <p className="text-muted-foreground text-[10px]">Compose</p>
                                </div>
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.crossNodeImpact}</p>
                                  <p className="text-muted-foreground text-[10px]">Impact</p>
                                </div>
                              </div>

                              {/* Rationale */}
                              <p className="text-xs text-muted-foreground italic">
                                "{template.rationale}"
                              </p>

                              {/* Pipeline preview */}
                              <pre className="bg-muted/50 p-3 rounded text-[11px] font-mono overflow-auto max-h-32">
{`// ${template.namePattern}
import { substrate } from '@cmpsbl/sdk';

const pipeline = substrate.pipeline({
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
  errorStrategy: '${template.errorStrategy}',
});`}
                              </pre>

                              {/* Actions */}
                              <div className="flex gap-2">
                                {user ? (
                                  <Button
                                    size="sm"
                                    className="flex-1 gap-1.5"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleDownload(template);
                                    }}
                                    disabled={remaining <= 0}
                                  >
                                    <Download className="w-3.5 h-3.5" />
                                    {remaining > 0 ? 'Download .ts' : 'Limit Reached'}
                                  </Button>
                                ) : (
                                  <Button
                                    asChild
                                    size="sm"
                                    className="flex-1 gap-1.5"
                                  >
                                    <Link to="/auth">
                                      <LogIn className="w-3.5 h-3.5" />
                                      Sign In to Download
                                    </Link>
                                  </Button>
                                )}
                                <Button
                                  variant="outline"
                                  size="sm"
                                  className="gap-1.5"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleCopy(template);
                                  }}
                                >
                                  {copiedId === template.namePattern ? (
                                    <Check className="w-3.5 h-3.5" />
                                  ) : (
                                    <Copy className="w-3.5 h-3.5" />
                                  )}
                                </Button>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </Card>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
