/**
 * SIGNAL FORGE — Free Template Synthesis Engine
 * 
 * Generates production-ready templates from the substrate's combinatorial
 * module × category × capability space. Auth-gated with daily rate limits.
 * Lives on the CodeLab page as the primary hero feature.
 */

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Sparkles, Dices, Download, Zap, Brain, Shield, Moon, Eye, 
  MessageSquare, Settings, Cpu, Globe, ArrowRight, Check, 
  Loader2, Copy, Lock, Network, Flame, RefreshCw, LogIn
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { generateTemplateBatch, type GeneratedTemplate } from "@/lib/discovery/template-generator";
import { Link } from "react-router-dom";

// Rate limit: 5 downloads per day per user
const DAILY_LIMIT = 5;
const STORAGE_KEY = 'signal-forge-downloads';

interface DownloadRecord {
  date: string;
  count: number;
}

function getTodayDownloads(): DownloadRecord {
  const today = new Date().toISOString().slice(0, 10);
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const record: DownloadRecord = JSON.parse(raw);
      if (record.date === today) return record;
    }
  } catch {}
  return { date: today, count: 0 };
}

function incrementDownloads(): DownloadRecord {
  const record = getTodayDownloads();
  record.count++;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(record));
  return record;
}

const CATEGORY_ICONS: Record<string, React.ElementType> = {
  cognitive: Brain,
  evolution: Flame,
  security: Shield,
  routing: Network,
  learning: Brain,
  orchestration: Cpu,
  integration: Globe,
  observability: Eye,
  governance: Shield,
  compliance: Lock,
  prediction: Sparkles,
  ethics: Shield,
  privacy: Lock,
  synthesis: Zap,
  localization: Globe,
  geospatial: Globe,
  simulation: Cpu,
  contracts: Settings,
  acquisition: Download,
  edge: Zap,
};

export function SignalForge() {
  const [user, setUser] = useState<any>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [isForging, setIsForging] = useState(false);
  const [forgedTemplates, setForgedTemplates] = useState<GeneratedTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<GeneratedTemplate | null>(null);
  const [downloadsToday, setDownloadsToday] = useState(0);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_, session) => {
      setUser(session?.user ?? null);
      setAuthLoading(false);
    });
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
      setAuthLoading(false);
    });
    setDownloadsToday(getTodayDownloads().count);
    return () => subscription.unsubscribe();
  }, []);

  const handleForge = useCallback(() => {
    setIsForging(true);
    // Use requestAnimationFrame to allow UI to update before heavy computation
    requestAnimationFrame(() => {
      setTimeout(() => {
        const batch = generateTemplateBatch({
          batchSize: 12,
          minModules: 2,
          maxModules: 5,
          minCjpiTarget: 80,
          biasHighValue: true,
        });
        setForgedTemplates(batch);
        setSelectedTemplate(null);
        setIsForging(false);
        toast.success(`Forged ${batch.length} templates from the substrate`);
      }, 600); // Brief delay for dramatic effect
    });
  }, []);

  const handleDownload = (template: GeneratedTemplate) => {
    if (!user) {
      toast.error('Sign in to download templates');
      return;
    }
    const record = getTodayDownloads();
    if (record.count >= DAILY_LIMIT) {
      toast.error(`Daily limit reached (${DAILY_LIMIT}/day). Come back tomorrow!`);
      return;
    }

    const content = `/**
 * ${template.namePattern}
 * Generated by CMPSBL SIGNAL FORGE
 * 
 * Category: ${template.category}
 * Module Chain: ${template.modulePattern.join(' → ')}
 * Error Strategy: ${template.errorStrategy}
 * Max Execution: ${template.maxExecutionMs}ms
 * 
 * Description:
 * ${template.descriptionPattern}
 * 
 * Rationale:
 * ${template.rationale}
 * 
 * CJPI Scores:
 *   Strategic Leverage: ${template.baseBreakdown.strategicLeverage}/100
 *   Recursion Potential: ${template.baseBreakdown.recursionPotential}/100
 *   Cross-Node Impact: ${template.baseBreakdown.crossNodeImpact}/100
 *   Composability: ${template.baseBreakdown.composability}/100
 *   Governance Influence: ${template.baseBreakdown.governanceInfluence}/100
 *   Moat Sensitivity: ${template.baseBreakdown.moatSensitivity}/100
 */

import { substrate } from '@cmpsbl/sdk';

// Entry: ${template.entryPattern}
// Exit: ${template.exitPattern}

const pipeline = substrate.pipeline({
  name: '${template.namePattern}',
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
  errorStrategy: '${template.errorStrategy}',
  maxExecutionMs: ${template.maxExecutionMs},
});

// Initialize module chain
${template.modulePattern.map((m, i) => `const ${m.toLowerCase()}Node = pipeline.node('${m}', { order: ${i + 1} });`).join('\n')}

// Wire entry → chain → exit
pipeline.entry('${template.entryPattern}', ${template.modulePattern[0].toLowerCase()}Node);
${template.modulePattern.slice(0, -1).map((m, i) => `${m.toLowerCase()}Node.pipe(${template.modulePattern[i + 1].toLowerCase()}Node);`).join('\n')}
${template.modulePattern[template.modulePattern.length - 1].toLowerCase()}Node.exit('${template.exitPattern}');

// Execute
export async function run(input: Record<string, unknown>) {
  return pipeline.execute(input);
}

export default pipeline;
`;

    const blob = new Blob([content], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const kebab = template.namePattern.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    a.download = `${kebab}.ts`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    const updated = incrementDownloads();
    setDownloadsToday(updated.count);
    toast.success(`Downloaded: ${template.namePattern} (${updated.count}/${DAILY_LIMIT} today)`);
  };

  const handleCopy = (template: GeneratedTemplate) => {
    const snippet = `// ${template.namePattern} — ${template.category}
// Modules: ${template.modulePattern.join(' → ')}
import { substrate } from '@cmpsbl/sdk';
const pipeline = substrate.pipeline({
  name: '${template.namePattern}',
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
});`;
    navigator.clipboard.writeText(snippet);
    setCopiedId(template.namePattern);
    setTimeout(() => setCopiedId(null), 2000);
    toast.success('Copied to clipboard');
  };

  const remaining = DAILY_LIMIT - downloadsToday;

  const avgCjpi = (t: GeneratedTemplate) => {
    const b = t.baseBreakdown;
    return Math.round(
      b.strategicLeverage * 0.30 + b.recursionPotential * 0.20 +
      b.crossNodeImpact * 0.15 + b.composability * 0.15 +
      b.governanceInfluence * 0.10 + b.moatSensitivity * 0.10
    );
  };

  return (
    <section className="relative overflow-hidden">
      {/* Hero */}
      <div className="relative border-b border-border/50">
        <div className="absolute inset-0 bg-gradient-to-br from-violet-500/5 via-transparent to-cyan-500/5" />
        <div className="absolute inset-0 opacity-[0.03]" style={{
          backgroundImage: `radial-gradient(circle at 1px 1px, hsl(var(--foreground)) 1px, transparent 0)`,
          backgroundSize: '32px 32px',
        }} />

        <div className="container mx-auto px-4 py-12 md:py-20 relative">
          <div className="max-w-5xl mx-auto">
            {/* Badge */}
            <div className="flex justify-center mb-6">
              <Badge className="gap-2 px-4 py-2 text-sm bg-gradient-to-r from-violet-500/20 to-cyan-500/20 text-violet-400 border-violet-500/30">
                <Dices className="w-4 h-4" />
                Free · Unlimited Forging · {DAILY_LIMIT} Downloads/Day
              </Badge>
            </div>

            <h1 className="text-4xl md:text-5xl lg:text-6xl font-black text-center mb-4">
              <span className="bg-gradient-to-r from-violet-400 via-cyan-400 to-emerald-400 bg-clip-text text-transparent">
                SIGNAL FORGE
              </span>
            </h1>

            <p className="text-xl md:text-2xl text-muted-foreground text-center mb-4 max-w-3xl mx-auto">
              The substrate's combinatorial engine synthesizes production-ready pipeline templates 
              from {31} modules × {20} categories × infinite configurations.
            </p>

            <p className="text-muted-foreground text-center max-w-2xl mx-auto mb-8">
              Every template is unique — generated from the same autonomous discovery engine 
              that powers the substrate's internal evolution. Forge, preview, download. No cost. No limits on generation.
            </p>

            {/* How It Works — Inline Diagram */}
            <div className="max-w-4xl mx-auto mb-10">
              <div className="grid grid-cols-1 md:grid-cols-5 gap-2 md:gap-0 items-center">
                {[
                  { icon: Dices, label: 'Randomize', desc: 'Module × Category', color: 'text-violet-500', bg: 'from-violet-500/10 to-violet-500/5' },
                  { icon: Brain, label: 'Synthesize', desc: 'Pipeline Topology', color: 'text-cyan-500', bg: 'from-cyan-500/10 to-cyan-500/5' },
                  { icon: Zap, label: 'Score', desc: 'CJPI Validation', color: 'text-amber-500', bg: 'from-amber-500/10 to-amber-500/5' },
                  { icon: Eye, label: 'Preview', desc: 'Code & Modules', color: 'text-emerald-500', bg: 'from-emerald-500/10 to-emerald-500/5' },
                  { icon: Download, label: 'Download', desc: 'Production-Ready', color: 'text-rose-500', bg: 'from-rose-500/10 to-rose-500/5' },
                ].map((step, i) => (
                  <div key={i} className="flex md:flex-col items-center gap-2 md:gap-1 relative">
                    <div className={`w-12 h-12 md:w-14 md:h-14 rounded-xl bg-gradient-to-br ${step.bg} border border-border/50 flex items-center justify-center`}>
                      <step.icon className={`w-5 h-5 md:w-6 md:h-6 ${step.color}`} />
                    </div>
                    <div className="md:text-center">
                      <p className="font-semibold text-sm">{step.label}</p>
                      <p className="text-xs text-muted-foreground">{step.desc}</p>
                    </div>
                    {i < 4 && (
                      <ArrowRight className="hidden md:block absolute -right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground/40 z-10" style={{ top: '28px' }} />
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Forge Button */}
            <div className="text-center space-y-3">
              <Button
                size="lg"
                onClick={handleForge}
                disabled={isForging}
                className="gap-3 px-8 py-6 text-lg font-bold bg-gradient-to-r from-violet-600 via-cyan-600 to-emerald-600 hover:opacity-90 text-white shadow-lg shadow-violet-500/20 hover:shadow-xl hover:shadow-violet-500/30 hover:scale-[1.02] active:scale-[0.98] transition-all"
              >
                {isForging ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Forging Templates…
                  </>
                ) : (
                  <>
                    <Dices className="w-5 h-5" />
                    Forge Templates
                    <Sparkles className="w-4 h-4" />
                  </>
                )}
              </Button>

              {forgedTemplates.length > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleForge}
                  disabled={isForging}
                  className="gap-2 text-muted-foreground"
                >
                  <RefreshCw className="w-4 h-4" />
                  Re-Forge New Batch
                </Button>
              )}

              <p className="text-xs text-muted-foreground">
                {user ? (
                  <>
                    <span className="text-emerald-500 font-medium">{remaining} downloads remaining today</span>
                    {' '}· Forge unlimited · Sign out to browse only
                  </>
                ) : (
                  <>
                    Forge freely · <Link to="/auth" className="text-primary hover:underline">Sign in</Link> to download ({DAILY_LIMIT}/day free)
                  </>
                )}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Forged Results */}
      <AnimatePresence>
        {forgedTemplates.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="container mx-auto px-4 py-8 md:py-12"
          >
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="text-2xl font-bold">Forged Templates</h2>
                <p className="text-sm text-muted-foreground">
                  {forgedTemplates.length} unique pipeline templates synthesized from the substrate
                </p>
              </div>
              <Badge variant="outline" className="text-xs">
                CJPI Validated
              </Badge>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {forgedTemplates.map((template, index) => {
                const Icon = CATEGORY_ICONS[template.category] || Zap;
                const cjpi = avgCjpi(template);
                const isSelected = selectedTemplate?.namePattern === template.namePattern;

                return (
                  <motion.div
                    key={template.namePattern + index}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <Card
                      className={`p-4 cursor-pointer transition-all hover:border-primary/50 ${
                        isSelected ? 'border-primary ring-1 ring-primary/20' : ''
                      }`}
                      onClick={() => setSelectedTemplate(isSelected ? null : template)}
                    >
                      <div className="flex items-start gap-3 mb-3">
                        <div className="w-10 h-10 rounded-lg bg-muted flex items-center justify-center shrink-0">
                          <Icon className="w-5 h-5 text-primary" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-semibold text-sm truncate">{template.namePattern}</h3>
                          <p className="text-xs text-muted-foreground capitalize">{template.category}</p>
                        </div>
                        <Badge 
                          variant="outline" 
                          className={`shrink-0 text-xs ${
                            cjpi >= 90 ? 'text-emerald-500 border-emerald-500/30' :
                            cjpi >= 80 ? 'text-cyan-500 border-cyan-500/30' :
                            'text-amber-500 border-amber-500/30'
                          }`}
                        >
                          CJPI {cjpi}
                        </Badge>
                      </div>

                      {/* Module chain */}
                      <div className="flex flex-wrap gap-1 mb-3">
                        {template.modulePattern.map((mod, i) => (
                          <Badge key={i} variant="secondary" className="text-[10px] font-mono">
                            {mod}
                          </Badge>
                        ))}
                      </div>

                      <p className="text-xs text-muted-foreground line-clamp-2 mb-3">
                        {template.descriptionPattern}
                      </p>

                      {/* Expanded detail */}
                      <AnimatePresence>
                        {isSelected && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="pt-3 border-t border-border/50 space-y-3">
                              {/* Scores */}
                              <div className="grid grid-cols-3 gap-2 text-xs">
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.strategicLeverage}</p>
                                  <p className="text-muted-foreground text-[10px]">Strategy</p>
                                </div>
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.composability}</p>
                                  <p className="text-muted-foreground text-[10px]">Compose</p>
                                </div>
                                <div className="text-center p-1.5 rounded bg-muted/50">
                                  <p className="font-mono font-bold text-foreground">{template.baseBreakdown.crossNodeImpact}</p>
                                  <p className="text-muted-foreground text-[10px]">Impact</p>
                                </div>
                              </div>

                              {/* Rationale */}
                              <p className="text-xs text-muted-foreground italic">
                                "{template.rationale}"
                              </p>

                              {/* Pipeline preview */}
                              <pre className="bg-muted/50 p-3 rounded text-[11px] font-mono overflow-auto max-h-32">
{`// ${template.namePattern}
import { substrate } from '@cmpsbl/sdk';

const pipeline = substrate.pipeline({
  modules: [${template.modulePattern.map(m => `'${m}'`).join(', ')}],
  category: '${template.category}',
  errorStrategy: '${template.errorStrategy}',
});`}
                              </pre>

                              {/* Actions */}
                              <div className="flex gap-2">
                                {user ? (
                                  <Button
                                    size="sm"
                                    className="flex-1 gap-1.5"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleDownload(template);
                                    }}
                                    disabled={remaining <= 0}
                                  >
                                    <Download className="w-3.5 h-3.5" />
                                    {remaining > 0 ? 'Download .ts' : 'Limit Reached'}
                                  </Button>
                                ) : (
                                  <Button
                                    asChild
                                    size="sm"
                                    className="flex-1 gap-1.5"
                                  >
                                    <Link to="/auth">
                                      <LogIn className="w-3.5 h-3.5" />
                                      Sign In to Download
                                    </Link>
                                  </Button>
                                )}
                                <Button
                                  variant="outline"
                                  size="sm"
                                  className="gap-1.5"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleCopy(template);
                                  }}
                                >
                                  {copiedId === template.namePattern ? (
                                    <Check className="w-3.5 h-3.5" />
                                  ) : (
                                    <Copy className="w-3.5 h-3.5" />
                                  )}
                                </Button>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </Card>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
