/**
 * Evolution Proposal Report — AI-Consumable JSON Export
 * 
 * Deterministic, machine-readable, self-contained report schema
 * for external AI execution of evolution proposals.
 * 
 * No logs. No side effects. No mutations. Strict JSON only.
 */

import { engineerNode } from '@/lib/control-plane/engineer/maintenance';
import { intelAggregator } from '@/lib/control-plane/intel/aggregator';
import { emitEvolveEvent } from './telemetry';

// ═══════════════════════════════════════════════════════════════
// SCHEMA
// ═══════════════════════════════════════════════════════════════

export interface EvolutionProposalReport {
  schema_version: '1.0';
  generated_at: string;
  system_id: 'cmpsbl-substrate';
  proposal: {
    id: string;
    title: string;
    description: string;
    risk_level: 'low' | 'medium' | 'high';
    scope: string;
    rationale: string;
    affected_areas: string[];
    suggested_files?: string[];
    suggested_actions: string[];
    rollback_plan: string;
    test_requirements: string[];
  };
  context: {
    originating_findings: string[];
    related_signals: string[];
    mastery_state?: Record<string, unknown>;
  };
  guardrails: {
    destructive: boolean;
    requires_backup: boolean;
    requires_manual_review: true;
  };
}

// ═══════════════════════════════════════════════════════════════
// SNAPSHOT DISCIPLINE
// ═══════════════════════════════════════════════════════════════

interface SnapshotCheck {
  exists: boolean;
  snapshot_id?: string;
  timestamp?: string;
}

function checkSystemSnapshot(): SnapshotCheck {
  // Check for recent system snapshot in INTEL aggregator
  const summary = intelAggregator.getSummary();
  const hasSignals = summary.total_signals > 0;
  
  // A snapshot "exists" if we have any INTEL signals (system has been observed)
  if (hasSignals) {
    return {
      exists: true,
      snapshot_id: `snapshot-${Date.now()}`,
      timestamp: new Date().toISOString(),
    };
  }
  
  return { exists: false };
}

// ═══════════════════════════════════════════════════════════════
// REPORT GENERATOR
// ═══════════════════════════════════════════════════════════════

export interface GenerateReportResult {
  success: boolean;
  report?: EvolutionProposalReport;
  error?: string;
}

/**
 * Generate a strict JSON EvolutionProposalReport for a given proposal ID.
 * 
 * - Loads the EngineerProposal
 * - Compiles structured report
 * - Marks proposal status as "exported"
 * - Does NOT mutate any system component
 * 
 * Returns strict JSON only.
 */
export function generateEvolutionReport(proposalId: string): GenerateReportResult {
  // 1. Load proposal
  const allProposals = engineerNode.getProposals();
  const proposal = allProposals.find(p => p.id === proposalId);

  if (!proposal) {
    return {
      success: false,
      error: `Proposal not found: ${proposalId}`,
    };
  }

  // 2. Snapshot discipline guard
  const snapshotCheck = checkSystemSnapshot();
  if (!snapshotCheck.exists) {
    return {
      success: false,
      error: 'System snapshot required before export. Run ENGINEER maintenance battery first to capture system state.',
    };
  }

  // 3. Gather related findings
  const allFindings = engineerNode.getFindings(true);
  const originatingFinding = allFindings.find(f => f.id === proposal.finding_id);

  // 4. Gather related INTEL signals
  const recentCards = intelAggregator.getCards({ limit: 10 });
  const relatedSignals = recentCards
    .filter(c => c.source.includes('ENGINEER'))
    .map(c => c.id);

  // 5. Determine destructiveness
  const isDestructive = proposal.risk_level === 'high';

  // 6. Compile report
  const report: EvolutionProposalReport = {
    schema_version: '1.0',
    generated_at: new Date().toISOString(),
    system_id: 'cmpsbl-substrate',
    proposal: {
      id: proposal.id,
      title: proposal.title,
      description: proposal.description,
      risk_level: proposal.risk_level,
      scope: proposal.scope,
      rationale: originatingFinding
        ? `Finding: ${originatingFinding.title} — ${originatingFinding.description}`
        : 'Generated by ENGINEER maintenance battery.',
      affected_areas: [proposal.scope],
      suggested_actions: [
        `Review: ${proposal.description}`,
        `Scope: ${proposal.scope}`,
        `Rollback: ${proposal.rollback_plan}`,
      ],
      rollback_plan: proposal.rollback_plan,
      test_requirements: [
        'Verify no regression in affected scope',
        'Confirm rollback path is functional',
        'Run substrate health check post-apply',
      ],
    },
    context: {
      originating_findings: originatingFinding ? [originatingFinding.id] : [],
      related_signals: relatedSignals,
    },
    guardrails: {
      destructive: isDestructive,
      requires_backup: !snapshotCheck.exists || isDestructive,
      requires_manual_review: true,
    },
  };

  // 7. Mark proposal as exported (status transition)
  engineerNode.updateProposalStatus(proposalId, 'exported' as any);

  // 8. Emit telemetry (non-mutating observation)
  emitEvolveEvent('evolution_report_exported' as any, {
    proposal_id: proposalId,
    report_schema_version: '1.0',
  });

  return {
    success: true,
    report,
  };
}

/**
 * Generate reports for all exportable proposals.
 */
export function generateAllExportableReports(): {
  reports: EvolutionProposalReport[];
  errors: string[];
} {
  const exportable = engineerNode.getProposals().filter(
    p => p.status === 'draft' || p.status === 'reviewed'
  );
  
  const reports: EvolutionProposalReport[] = [];
  const errors: string[] = [];

  for (const proposal of exportable) {
    const result = generateEvolutionReport(proposal.id);
    if (result.success && result.report) {
      reports.push(result.report);
    } else if (result.error) {
      errors.push(`${proposal.id}: ${result.error}`);
    }
  }

  return { reports, errors };
}
