/**
 * Privacy Policy — Legal page with TOC sidebar and active section tracking
 */

import { useState, useEffect, useRef } from "react";
import { PublicNav } from "@/components/PublicNav";
import { EnhancedFooter } from "@/components/EnhancedFooter";
import { RelatedCapabilities } from "@/components/RelatedCapabilities";
import { PageSEOBlock } from "@/components/seo/PageSEOBlock";
import { SEO } from "@/components/SEO";
import { Badge } from "@/components/ui/badge";
import { Shield, ChevronRight } from "lucide-react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import { Link } from "react-router-dom";

const sections = [
  {
    id: "introduction",
    title: "1. Introduction",
    content: `CMPSBL® ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website, use our platform (including the 40-primitive substrate, Memory Stream, npm packages, and API services), or interact with our cognitive infrastructure.`,
  },
  {
    id: "information",
    title: "2. Information We Collect",
    content: null,
    subsections: [
      {
        title: "Personal Information",
        content: "We may collect personal information that you voluntarily provide to us, including:",
        list: ["Name and email address", "Account credentials", "Payment information (processed by Stripe — we never store card details)", "Contact and communication preferences", "API keys you configure through BYOK (Bring Your Own Keys)"],
      },
      {
        title: "Platform & Usage Data",
        content: "When you use our services, we automatically collect:",
        list: [
          "Device information, IP address, browser type, and operating system",
          "Usage patterns across the substrate dashboard and Memory Stream",
          "Telemetry from primitive interactions (NEXUS routing, DEFENSE threat events, VISION observability)",
          "Memory Stream crystallization and discovery activity",
          "npm package download and integration telemetry (anonymous)",
        ],
      },
    ],
  },
  {
    id: "usage",
    title: "3. How We Use Your Information",
    content: "We use the information we collect to:",
    list: [
      "Provide, maintain, and improve the CMPSBL platform and its 40 primitives",
      "Process transactions for capability packs, Composable Cognitives, and subscriptions",
      "Power the Memory Stream discovery engine and crystallization scoring",
      "Route AI requests through the NEXUS Organ's 14-provider network",
      "Send promotional communications (with your consent)",
      "Respond to your comments, questions, and support requests",
      "Monitor system health via the VISION Agent and MEDIC Organ",
      "Detect, investigate, and prevent security incidents via the DEFENSE Layer and IMMUNITY Layer",
    ],
  },
  {
    id: "byok",
    title: "4. BYOK & Data Sovereignty",
    content: "CMPSBL operates on a Bring Your Own Keys (BYOK) model. Your AI provider API keys are encrypted with AES-GCM and stored in our secrets vault, scoped per primitive. We never access your data or use it for training. The SOVEREIGN Organ enforces jurisdictional data residency — all data stays within your chosen region. Row-Level Security (RLS) ensures complete tenant isolation.",
  },
  {
    id: "memory-stream",
    title: "5. Memory Stream & Discovery Data",
    content: "The Memory Stream generates crystallized discoveries from your system activity. You own all discoveries, artifacts, and pipeline outputs generated by your substrate instance. Crystallized artifacts exported as npm-compatible packages remain your intellectual property. DREAM Engine synthesis data is processed in memory-isolated environments and is never shared across tenants.",
  },
  {
    id: "security",
    title: "6. Data Security",
    content: "We implement enterprise-grade security measures including AES-256 encryption at rest, TLS 1.3 in transit, adaptive rate limiting via the DEFENSE Layer, behavioral threat detection via the IMMUNITY Layer, and tamper-evident audit logging via the AUDIT Agent. Every mutating action passes GOVERNANCE Layer enforcement checks. However, no method of transmission over the Internet is 100% secure.",
  },
  {
    id: "retention",
    title: "7. Data Retention",
    content: "We retain your personal information for as long as necessary to fulfill the purposes for which it was collected and to comply with our legal obligations. Memory Stream data follows the 4-tier lifecycle (hot → warm → cold → glacier) with configurable retention per tier. You may request full data export or deletion at any time.",
  },
  {
    id: "rights",
    title: "8. Your Rights",
    content: "Depending on your location, you may have the right to:",
    list: ["Access your personal information and platform data", "Correct inaccurate data", "Request deletion of your data and Memory Stream history", "Object to processing of your data", "Export your data (data portability)", "Withdraw consent at any time"],
  },
  {
    id: "npm",
    title: "9. npm Packages & Open Source",
    content: "The @cmpsbl npm ecosystem (11 packages) is distributed under Apache-2.0. Package download telemetry collected by npm is governed by npm's own privacy policy. Our SDK, runtime, and tooling packages do not collect personal data. Anonymous usage metrics may be collected for package stability and compatibility improvements.",
  },
  {
    id: "third-party",
    title: "10. Third-Party Services",
    content: "Our platform integrates with third-party AI providers (via NEXUS Organ routing), payment processors (Stripe), and analytics services. Each provider's data handling is governed by their own privacy policy. We minimize data shared with third parties to what is strictly required for service delivery.",
  },
  {
    id: "children",
    title: "11. Children's Privacy",
    content: "Our services are not intended for children under 13. We do not knowingly collect personal information from children under 13.",
  },
  {
    id: "changes",
    title: "12. Changes to This Policy",
    content: 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. Material changes will be communicated via email or platform notification.',
  },
  {
    id: "contact",
    title: "13. Contact Us",
    content: "If you have questions about this Privacy Policy or your data rights, please contact us at:",
    contact: true,
  },
];

export default function Privacy() {
  const [activeSection, setActiveSection] = useState(sections[0].id);
  const sectionRefs = useRef<Record<string, HTMLElement | null>>({});

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        }
      },
      { rootMargin: "-20% 0px -60% 0px" }
    );

    sections.forEach((s) => {
      const el = sectionRefs.current[s.id];
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="Privacy Policy — Your Data Rights | CMPSBL®"
        description="How CMPSBL collects, stores, and safeguards your data. Covers Memory Stream crystallization ownership, GDPR compliance, cookie usage, third-party sharing, and your right to deletion."
        keywords={['CMPSBL privacy policy', 'AI data privacy', 'GDPR compliant AI', 'memory stream data rights']}
      />
      <PublicNav />

      <main className="container mx-auto px-4 pt-24 pb-16 max-w-6xl relative">
        <div className="fixed inset-0 pointer-events-none z-0">
          <div className="absolute top-40 right-1/4 w-[300px] h-[300px] rounded-full animate-hero-orb-2" style={{ background: "radial-gradient(circle, hsl(var(--primary) / 0.04) 0%, transparent 60%)" }} />
        </div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative z-10">
          <nav className="mb-8">
            <Link to="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary transition-colors min-h-[44px] py-2">
              <ChevronRight className="w-3 h-3 rotate-180 mr-1" /> Back to Home
            </Link>
          </nav>

          <div className="mb-10">
            <Badge variant="outline" className="mb-4 gap-1.5 border-primary/30 px-4 py-1.5">
              <Shield className="w-3 h-3 text-primary" />
              <span className="text-xs font-semibold">Legal</span>
            </Badge>
            <h1 className="text-3xl sm:text-4xl font-black tracking-tight mb-2">Privacy Policy</h1>
            <p className="text-muted-foreground text-sm">Last updated: March 27, 2026</p>
          </div>

          <div className="flex gap-8">
            {/* Sticky TOC — desktop only */}
            <aside className="hidden lg:block w-56 shrink-0">
              <div className="sticky top-28">
                <p className="text-[10px] uppercase tracking-widest text-muted-foreground/60 font-mono mb-3">On this page</p>
                <nav className="space-y-0.5">
                  {sections.map((s) => (
                    <a
                      key={s.id}
                      href={`#${s.id}`}
                      className={cn(
                        "block text-xs py-1.5 pl-3 border-l-2 transition-all duration-200",
                        activeSection === s.id
                          ? "border-primary text-primary font-medium"
                          : "border-transparent text-muted-foreground/60 hover:text-muted-foreground hover:border-border"
                      )}
                    >
                      {s.title.replace(/^\d+\.\s*/, "")}
                    </a>
                  ))}
                </nav>
              </div>
            </aside>

            {/* Content */}
            <div className="flex-1 min-w-0 space-y-5">
              {sections.map((section, i) => (
                <motion.section
                  key={section.id}
                  id={section.id}
                  ref={(el) => { sectionRefs.current[section.id] = el; }}
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.02 }}
                  className="p-5 sm:p-6 rounded-2xl border border-border/30 bg-card/40 backdrop-blur-sm glass-edge scroll-mt-28"
                >
                  <h2 className="text-lg sm:text-xl font-bold mb-3 text-foreground">{section.title}</h2>
                  {section.content && (
                    <p className="text-sm text-muted-foreground leading-relaxed mb-3">{section.content}</p>
                  )}
                  {section.subsections?.map((sub) => (
                    <div key={sub.title} className="mt-4">
                      <h3 className="text-base font-semibold mb-2">{sub.title}</h3>
                      {sub.content && <p className="text-sm text-muted-foreground leading-relaxed mb-2">{sub.content}</p>}
                      {sub.list && (
                        <ul className="space-y-1.5 ml-1">
                          {sub.list.map((item) => (
                            <li key={item} className="flex items-start gap-2 text-sm text-muted-foreground">
                              <span className="w-1 h-1 rounded-full bg-primary/60 mt-2 shrink-0" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                  {section.list && (
                    <ul className="space-y-1.5 ml-1">
                      {section.list.map((item) => (
                        <li key={item} className="flex items-start gap-2 text-sm text-muted-foreground">
                          <span className="w-1 h-1 rounded-full bg-primary/60 mt-2 shrink-0" />
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                  {section.contact && (
                    <div className="mt-3 p-4 rounded-xl bg-muted/30 border border-border/30">
                      <p className="text-sm text-muted-foreground">
                        <strong className="text-foreground">Email:</strong> Dev@CMPSBL.com<br />
                        <strong className="text-foreground">Phone:</strong> (760) 358-4324
                      </p>
                    </div>
                  )}
                </motion.section>
              ))}
            </div>
          </div>
        </motion.div>
      </main>

      <RelatedCapabilities />
      <PageSEOBlock path="/privacy" title="Privacy Policy" />
      <EnhancedFooter />
    </div>
  );
}
