/**
 * Ascension Capability Registry
 * All 5 capabilities from the api_gateway-20260328 export pack.
 * Pack fingerprint: FEDAC39F87A1
 */

import type { CapabilityMeta } from './capabilityEngine';

export const ASCENSION_CAPABILITIES: CapabilityMeta[] = [
  // ── Original 5 (api_gateway pack) ──────────────────────────────
  {
    id: 'ctp-004',
    name: 'Cognitive_Threat_Profiler_Plus_ENCODE_SOVEREIGN_EVOLUTION_IMMUNITY_FORGE',
    displayName: 'Cognitive Threat Profiler',
    cjpi: 97,
    tier: 'apex',
    chain: ['API_GATEWAY', 'ENCODE', 'SOVEREIGN', 'EVOLUTION', 'DEFENSE', 'BRAIN', 'IMMUNITY', 'FORGE'],
    fingerprint: '69162EC40ECB',
    moatSignature: 'bd0f75bd-1ddc-430a-a580-2a42918c8274',
    description: 'Profiles data through an 8-Primitive security chain. Detects XSS, prototype pollution, SQL injection, path traversal, and template injection patterns. Adds sovereign governance hashing, evolution fitness scoring, and immunity shielding.',
    protects: 'DEFENSE · IMMUNITY · ENCODE',
  },
  {
    id: 'gme-001',
    name: 'Generative_Mutation_Engine_Plus_SOVEREIGN_GOVERNANCE_INTENT_RELAY',
    displayName: 'Generative Mutation Engine',
    cjpi: 87,
    tier: 'mythic',
    chain: ['API_GATEWAY', 'SOVEREIGN', 'GOVERNANCE', 'INTENT', 'RELAY', 'EVOLUTION', 'DREAM'],
    fingerprint: 'FEDAC39F87A1',
    moatSignature: '29695ad9-e590-4c2c-ac57-eaed9592efe0',
    description: 'Governs mutation pipelines through sovereign policy checks, intent routing, and relay forwarding. Integrates evolution fitness tracking with dream-space exploration for generative discovery.',
    protects: 'EVOLUTION · GOVERNANCE · DREAM',
  },
  {
    id: 'ara-002',
    name: 'Accessibility_Reasoning_Advisor_Plus_SHADOW_SOVEREIGN_SYSTEM_ENGINEER',
    displayName: 'Accessibility Reasoning Advisor',
    cjpi: 92,
    tier: 'apex',
    chain: ['API_GATEWAY', 'SHADOW', 'SOVEREIGN', 'SYSTEM', 'INCLUSIVE', 'BRAIN', 'ENGINEER'],
    fingerprint: '851A629A8DAF',
    moatSignature: 'dc6f8ccf-d3fa-4684-94e8-25e4bb1ff79f',
    description: 'Scans data for accessibility compliance — alt text, ARIA labels, semantic HTML. Runs shadow verification, sovereign governance, system stability checks, and engineering quality gates.',
    protects: 'INCLUSIVE · SHADOW · SYSTEM',
  },
  {
    id: 'cen-003',
    name: 'Consensus_Event_Network_Plus_VISION_GOVERNANCE_ECHO_INTENT_CONSCIENCE',
    displayName: 'Consensus Event Network',
    cjpi: 87,
    tier: 'mythic',
    chain: ['API_GATEWAY', 'VISION', 'GOVERNANCE', 'ECHO', 'NERVE', 'RIPPLE', 'INTENT', 'CONSCIENCE'],
    fingerprint: 'B102B26FD2BE',
    moatSignature: 'a7c3e8f1-9d2b-4a76-b5e4-3f8c1d2a9b70',
    description: 'Builds consensus across the event mesh. Vision analysis feeds governance policy, echo replay captures state, nerve routes signals, ripple propagates cascading responses, and conscience applies ethical clearance.',
    protects: 'GOVERNANCE · NERVE · CONSCIENCE',
  },
  {
    id: 'zkr-005',
    name: 'Zero_Knowledge_Reasoner_Plus_IMMUNITY_TREATY_ENGINEER_ECHO_NEXUS',
    displayName: 'Zero Knowledge Reasoner',
    cjpi: 96,
    tier: 'apex',
    chain: ['API_GATEWAY', 'IMMUNITY', 'TREATY', 'PHANTOM', 'BRAIN', 'ENGINEER', 'ECHO', 'NEXUS'],
    fingerprint: 'AC97C7AD0669',
    moatSignature: 'f4a2c7e9-8b31-4d5a-a1c6-2e9f0d3b8a54',
    description: 'Privacy-preserving reasoning pipeline. Immunity shields errors, treaty enforces compliance, phantom anonymizes data through 3-hop proxy, brain analyzes complexity, and NEXUS routes to internal substrate providers only.',
    protects: 'IMMUNITY · TREATY · PHANTOM',
  },
  // ── Consensus Engine Pack (consensusengine-20260328) ─────────
  {
    id: 'cpm-006',
    name: 'Capability_Performance_Map_Plus_SHADOW_ENCODE_DREAM_SYSTEM_REFLEX',
    displayName: 'Capability Performance Map',
    cjpi: 90,
    tier: 'mythic',
    chain: ['CONSENSUSENGINE', 'SHADOW', 'ENCODE', 'DREAM', 'ENGINEER', 'ATLAS', 'SYSTEM', 'REFLEX'],
    fingerprint: 'FF09AAD04F67',
    moatSignature: '21b6438a-dc5b-4ef9-9a57-6a76cec5d521',
    description: 'Maps performance characteristics of consensus across shadow verification, encoding, dream-space exploration, and reflex-driven system calibration.',
    protects: 'SYSTEM · SHADOW · ENGINEER',
  },
  {
    id: 'gme-007',
    name: 'Generative_Mutation_Engine_Plus_DECODE_CONSCIENCE_SOVEREIGN_CORTEX_SANDBOX',
    displayName: 'Generative Mutation Engine (Consensus)',
    cjpi: 89,
    tier: 'mythic',
    chain: ['CONSENSUSENGINE', 'DECODE', 'CONSCIENCE', 'DREAM', 'EVOLUTION', 'SOVEREIGN', 'CORTEX', 'SANDBOX'],
    fingerprint: 'FD48DE1A8C24',
    moatSignature: 'bfad1e5f-c17d-41b6-8df4-81f06c696021',
    description: 'Applies generative mutation to consensus state through ethical conscience checks, sovereign governance, and sandboxed execution.',
    protects: 'EVOLUTION · CONSCIENCE · SOVEREIGN',
  },
  {
    id: 'zkr-008',
    name: 'Zero_Knowledge_Reasoner_Plus_SANDBOX_HARVEST_DEFENSE_TREATY',
    displayName: 'Zero Knowledge Reasoner (Consensus)',
    cjpi: 89,
    tier: 'mythic',
    chain: ['CONSENSUSENGINE', 'SANDBOX', 'HARVEST', 'DEFENSE', 'TREATY', 'BRAIN', 'PHANTOM'],
    fingerprint: '3DA35AF32EA6',
    moatSignature: 'c8502fe9-2326-4b58-aa93-154d25a36f1d',
    description: 'Privacy-preserving consensus reasoning through sandboxed harvest, defense validation, treaty compliance, and phantom anonymization.',
    protects: 'DEFENSE · TREATY · PHANTOM',
  },
  {
    id: 'sdr-009',
    name: 'Sovereign_Data_Reasoner_Plus_IDENTITY_INTEGRATION_GOVERNANCE_LINGUA_NERVE',
    displayName: 'Sovereign Data Reasoner',
    cjpi: 89,
    tier: 'mythic',
    chain: ['CONSENSUSENGINE', 'IDENTITY', 'INTEGRATION', 'SOVEREIGN', 'BRAIN', 'GOVERNANCE', 'LINGUA', 'NERVE'],
    fingerprint: '9D5C22C50D04',
    moatSignature: '85cdfffa-5660-4594-a6b7-76d6386bba48',
    description: 'Sovereign data reasoning across identity verification, integration protocols, governance policy enforcement, and nerve signal routing.',
    protects: 'IDENTITY · GOVERNANCE · NERVE',
  },
  {
    id: 'cao-010',
    name: 'Context_Aware_Orchestrator_Plus_TREATY_LINGUA_NERVE_INTEGRATION_DECODE',
    displayName: 'Context-Aware Orchestrator',
    cjpi: 91,
    tier: 'mythic',
    chain: ['CONSENSUSENGINE', 'CORTEX', 'MEMORY', 'TREATY', 'LINGUA', 'NERVE', 'INTEGRATION', 'DECODE'],
    fingerprint: 'A4AF587BE9F5',
    moatSignature: '871a2d60-92a6-41e4-a105-78c2630deb02',
    description: 'Context-aware orchestration of consensus through cortex coordination, memory state, treaty compliance, and multi-integration decode.',
    protects: 'CORTEX · MEMORY · INTEGRATION',
  },
];

export const PACK_META = {
  name: 'cmpsbl-capability-pack-unified-20260328',
  totalCapabilities: 10,
  averageCjpi: 91,
  averageTier: 'apex' as const,
  fingerprint: 'FEDAC39F87A1',
  exported: '2026-03-28',
  source: 'proprietary-evolution-lifecycle',
  originalLanguage: 'PHP',
  translatedTo: 'TypeScript',
};
