/**
 * pf-agency-export v1.0.0
 * 
 * Generate exportable deliverables from completed tasks:
 * - Markdown reports
 * - HTML formatted reports
 * - JSON data exports
 * - CSV for data-focused tasks
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.79.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function generateMarkdown(task: any): string {
  const output = task.output_data || {};
  const result = output.result || '';
  const insights = output.insights || [];
  const sources = output.sources || [];

  return `# ${task.title}

**Task Type:** ${task.task_type}
**Status:** ${task.status}
**Completed:** ${task.completed_at ? new Date(task.completed_at).toLocaleString() : 'N/A'}
**Provider:** ${output.provider || 'N/A'}
**Execution Time:** ${output.executionTimeMs ? `${Math.round(output.executionTimeMs / 1000)}s` : 'N/A'}

---

## Summary

${result}

---

## Key Insights

${insights.map((i: string, idx: number) => `${idx + 1}. ${i}`).join('\n')}

---

## Sources

${sources.length > 0 ? sources.map((s: string) => `- ${s}`).join('\n') : 'No external sources used.'}

---

*Generated by Agency AI on ${new Date().toLocaleString()}*
`;
}

function generateHTML(task: any): string {
  const output = task.output_data || {};
  const result = output.result || '';
  const insights = output.insights || [];
  const sources = output.sources || [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${task.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f8f9fa; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); overflow: hidden; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; }
    .header h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
    .meta { display: flex; gap: 1.5rem; flex-wrap: wrap; font-size: 0.875rem; opacity: 0.9; }
    .content { padding: 2rem; }
    .section { margin-bottom: 2rem; }
    .section h2 { color: #667eea; font-size: 1.25rem; margin-bottom: 1rem; border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }
    .result { white-space: pre-wrap; background: #f8f9fa; padding: 1.5rem; border-radius: 8px; font-size: 0.9375rem; }
    .insights { list-style: none; }
    .insights li { padding: 0.75rem 1rem; background: #f0f4ff; margin-bottom: 0.5rem; border-radius: 8px; border-left: 4px solid #667eea; }
    .sources { list-style: none; }
    .sources li { padding: 0.5rem 0; border-bottom: 1px solid #eee; }
    .sources a { color: #667eea; text-decoration: none; }
    .sources a:hover { text-decoration: underline; }
    .footer { text-align: center; padding: 1.5rem; background: #f8f9fa; color: #666; font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${task.title}</h1>
      <div class="meta">
        <span><strong>Type:</strong> ${task.task_type}</span>
        <span><strong>Status:</strong> ${task.status}</span>
        <span><strong>Time:</strong> ${output.executionTimeMs ? `${Math.round(output.executionTimeMs / 1000)}s` : 'N/A'}</span>
      </div>
    </div>
    <div class="content">
      <div class="section">
        <h2>Report</h2>
        <div class="result">${result.replace(/\n/g, '<br>')}</div>
      </div>
      ${insights.length > 0 ? `
      <div class="section">
        <h2>Key Insights</h2>
        <ul class="insights">
          ${insights.map((i: string) => `<li>${i}</li>`).join('')}
        </ul>
      </div>
      ` : ''}
      ${sources.length > 0 ? `
      <div class="section">
        <h2>Sources</h2>
        <ul class="sources">
          ${sources.map((s: string) => `<li><a href="${s}" target="_blank">${s}</a></li>`).join('')}
        </ul>
      </div>
      ` : ''}
    </div>
    <div class="footer">
      Generated by Agency AI • ${new Date().toLocaleString()}
    </div>
  </div>
</body>
</html>`;
}

function generateJSON(task: any): string {
  return JSON.stringify({
    id: task.id,
    title: task.title,
    task_type: task.task_type,
    status: task.status,
    created_at: task.created_at,
    completed_at: task.completed_at,
    input: task.input_data,
    output: task.output_data,
    metadata: task.metadata,
  }, null, 2);
}

function generateCSV(task: any): string {
  const output = task.output_data || {};
  const insights = output.insights || [];
  const sources = output.sources || [];

  const rows = [
    ['Field', 'Value'],
    ['Task ID', task.id],
    ['Title', task.title],
    ['Type', task.task_type],
    ['Status', task.status],
    ['Created', task.created_at],
    ['Completed', task.completed_at || ''],
    ['Provider', output.provider || ''],
    ['Execution Time (ms)', output.executionTimeMs || ''],
    ...insights.map((i: string, idx: number) => [`Insight ${idx + 1}`, i]),
    ...sources.map((s: string, idx: number) => [`Source ${idx + 1}`, s]),
  ];

  return rows.map((row: string[]) => row.map((cell: string) => `"${String(cell).replace(/"/g, '""')}"`).join(',')).join('\n');
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { taskId, format = 'markdown', sendEmail, recipientEmail } = await req.json();

    if (!taskId) {
      return new Response(JSON.stringify({ error: 'taskId is required' }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch the task
    const { data: task, error: taskError } = await supabase
      .from('agency_tasks')
      .select('*')
      .eq('id', taskId)
      .single();

    if (taskError || !task) {
      return new Response(JSON.stringify({ error: 'Task not found' }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Generate content based on format
    let content = '';
    let contentType = 'text/plain';
    let filename = `report-${task.id.slice(0, 8)}`;

    switch (format) {
      case 'html':
        content = generateHTML(task);
        contentType = 'text/html';
        filename += '.html';
        break;
      case 'json':
        content = generateJSON(task);
        contentType = 'application/json';
        filename += '.json';
        break;
      case 'csv':
        content = generateCSV(task);
        contentType = 'text/csv';
        filename += '.csv';
        break;
      case 'markdown':
      default:
        content = generateMarkdown(task);
        contentType = 'text/markdown';
        filename += '.md';
    }

    // Store the deliverable
    const { data: deliverable, error: deliverableError } = await supabase
      .from('agency_task_deliverables')
      .insert({
        task_id: taskId,
        agency_id: task.agency_id,
        deliverable_type: format,
        title: `${task.title} - ${format.toUpperCase()} Export`,
        content,
        file_size_bytes: new TextEncoder().encode(content).length,
        emailed_to: sendEmail && recipientEmail ? [recipientEmail] : [],
        expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days
      })
      .select()
      .single();

    if (deliverableError) {
      console.error('Failed to store deliverable:', deliverableError);
    }

    // Queue email if requested
    if (sendEmail && recipientEmail) {
      await supabase.from('agency_email_queue').insert({
        agency_id: task.agency_id,
        task_id: taskId,
        deliverable_id: deliverable?.id,
        recipient_email: recipientEmail,
        email_type: 'deliverable',
        subject: `Your Report: ${task.title}`,
        body_html: format === 'html' ? content : `<pre style="white-space: pre-wrap; font-family: monospace;">${content}</pre>`,
        body_text: format === 'markdown' ? content : `View the attached ${format.toUpperCase()} report.`,
        status: 'pending',
      });

      // Trigger email sending
      await supabase.functions.invoke('pf-agency-send-email', {}).catch(() => {});
    }

    // If returning raw content for download
    if (req.headers.get('Accept')?.includes(contentType)) {
      return new Response(content, {
        headers: {
          ...corsHeaders,
          'Content-Type': contentType,
          'Content-Disposition': `attachment; filename="${filename}"`,
        },
      });
    }

    return new Response(JSON.stringify({
      success: true,
      deliverableId: deliverable?.id,
      format,
      filename,
      contentLength: content.length,
      content,
      emailQueued: sendEmail && recipientEmail,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error("❌ Export error:", error);
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
