/**
 * Intent Mesh — Capability Manifest
 * Each module's advertised resolvers
 * 
 * This is the "phone book" of the mesh. Modules declare what they can do,
 * and the router matches intents to capable resolvers dynamically.
 * 
 * IMPORTANT: All resolvers default to 'read' risk. No mutations without governance.
 */

import type { MeshResolver } from './types';

export const MESH_MANIFEST: MeshResolver[] = [
  // ── DEFENSE ──
  {
    id: 'defense.threat_score',
    module: 'DEFENSE',
    description: 'Calculate threat score for an IP, actor, or session',
    domains: ['security', 'threat', 'ip'],
    accepts: ['ip', 'actor_id', 'session_id'],
    produces: ['threat_score', 'risk_level', 'blocked'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.ip_reputation',
    module: 'DEFENSE',
    description: 'Lookup IP reputation and history',
    domains: ['security', 'ip', 'reputation'],
    accepts: ['ip'],
    produces: ['reputation_score', 'total_requests', 'blocked_count', 'last_seen'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.anomaly_detect',
    module: 'DEFENSE',
    description: 'Detect behavioral anomalies for an actor',
    domains: ['security', 'anomaly', 'behavior'],
    accepts: ['actor_id', 'session_id', 'action_history'],
    produces: ['anomaly_score', 'anomaly_type', 'confidence'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.geo_analysis',
    module: 'DEFENSE',
    description: 'Geo-location analysis and impossible travel detection',
    domains: ['geo', 'security', 'ip'],
    accepts: ['ip', 'actor_id'],
    produces: ['geo_location', 'country', 'impossible_travel', 'vpn_detected'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.rate_limit_status',
    module: 'DEFENSE',
    description: 'Check current rate limit state for an actor or IP',
    domains: ['rate_limiting', 'security'],
    accepts: ['ip', 'actor_id', 'endpoint'],
    produces: ['rate_limit_status', 'remaining_requests', 'reset_at', 'throttled'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.threat_timeline',
    module: 'DEFENSE',
    description: 'Historical threat activity timeline for forensic analysis',
    domains: ['threat', 'security', 'history'],
    accepts: ['ip', 'actor_id', 'time_range'],
    produces: ['threat_timeline', 'attack_vector', 'escalation_pattern'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.fingerprint_analysis',
    module: 'DEFENSE',
    description: 'Device fingerprint analysis and consistency checking',
    domains: ['fingerprint', 'security', 'identity'],
    accepts: ['session_id', 'actor_id'],
    produces: ['device_type', 'fingerprint_hash', 'fingerprint_consistency', 'spoofing_risk'],
    risk: 'read',
    enabled: true,
  },

  // ── RELAY ──
  {
    id: 'relay.email_by_actor',
    module: 'RELAY',
    description: 'Resolve email address for an actor ID',
    domains: ['identity', 'email', 'contact'],
    accepts: ['actor_id', 'user_id'],
    produces: ['email', 'email_verified', 'last_contacted'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'relay.delivery_history',
    module: 'RELAY',
    description: 'Get webhook/notification delivery history for a target',
    domains: ['delivery', 'webhook', 'notification'],
    accepts: ['target_url', 'actor_id'],
    produces: ['delivery_count', 'success_rate', 'last_delivery'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'relay.engagement_score',
    module: 'RELAY',
    description: 'Calculate communication engagement score for an actor',
    domains: ['communication', 'email', 'behavior'],
    accepts: ['actor_id'],
    produces: ['engagement_score', 'open_rate', 'bounce_rate', 'preferred_channel', 'opt_out_status'],
    risk: 'read',
    enabled: true,
  },

  // ── VISION ──
  {
    id: 'vision.last_login',
    module: 'VISION',
    description: 'Get last login details for a user/actor',
    domains: ['session', 'login', 'identity'],
    accepts: ['actor_id', 'user_id', 'ip'],
    produces: ['last_login_at', 'login_ip', 'device_fingerprint', 'geo_location'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'vision.session_timeline',
    module: 'VISION',
    description: 'Get session activity timeline for anomaly correlation',
    domains: ['session', 'timeline', 'behavior'],
    accepts: ['session_id', 'actor_id'],
    produces: ['events', 'page_views', 'duration_ms', 'actions'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'vision.anomaly_score',
    module: 'VISION',
    description: 'Calculate behavioral anomaly score from session patterns',
    domains: ['anomaly', 'behavior', 'session'],
    accepts: ['actor_id', 'session_id'],
    produces: ['anomaly_score', 'deviation_type', 'baseline_comparison'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'vision.usage_analytics',
    module: 'VISION',
    description: 'Aggregate usage analytics and feature adoption metrics',
    domains: ['analytics', 'usage', 'monitoring', 'performance'],
    accepts: ['module', 'period', 'metric'],
    produces: ['conversion_rate', 'retention_score', 'churn_risk', 'usage_pattern', 'peak_hours', 'feature_adoption'],
    risk: 'read',
    enabled: true,
  },

  // ── IDENTITY ──
  {
    id: 'identity.resolve_actor',
    module: 'IDENTITY',
    description: 'Resolve full actor profile from any identifier',
    domains: ['identity', 'actor', 'profile'],
    accepts: ['actor_id', 'user_id', 'email', 'ip'],
    produces: ['actor_id', 'display_name', 'role', 'trust_level', 'created_at'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'identity.trust_score',
    module: 'IDENTITY',
    description: 'Calculate trust score for an actor based on history',
    domains: ['identity', 'trust', 'security'],
    accepts: ['actor_id'],
    produces: ['trust_score', 'trust_factors', 'risk_flags'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'identity.auth_strength',
    module: 'IDENTITY',
    description: 'Assess authentication strength and credential health',
    domains: ['authentication', 'identity', 'security'],
    accepts: ['actor_id', 'user_id'],
    produces: ['auth_method', 'credential_age', 'identity_strength', 'mfa_enabled', 'passkey_registered'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'identity.access_history',
    module: 'IDENTITY',
    description: 'Get access and authorization history for an actor',
    domains: ['authorization', 'identity', 'audit'],
    accepts: ['actor_id'],
    produces: ['access_history', 'privilege_level', 'role_changes', 'permission_anomalies'],
    risk: 'read',
    enabled: true,
  },

  // ── ECONOMY ──
  {
    id: 'economy.actor_value',
    module: 'ECONOMY',
    description: 'Get lifetime value and cost attribution for an actor',
    domains: ['economy', 'value', 'cost'],
    accepts: ['actor_id', 'user_id'],
    produces: ['lifetime_value_cents', 'total_cost_cents', 'roi', 'tier'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'economy.budget_check',
    module: 'ECONOMY',
    description: 'Check if an operation is within budget constraints',
    domains: ['economy', 'budget', 'cost'],
    accepts: ['operation', 'estimated_cost_cents'],
    produces: ['within_budget', 'remaining_budget_cents', 'daily_spend_cents'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'economy.cost_forecast',
    module: 'ECONOMY',
    description: 'Forecast costs and identify savings opportunities',
    domains: ['cost', 'budget', 'pricing'],
    accepts: ['module', 'period'],
    produces: ['projected_spend', 'cost_trend', 'savings_opportunity', 'cost_per_operation'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'economy.quota_status',
    module: 'ECONOMY',
    description: 'Check quota usage and remaining allocation',
    domains: ['quota', 'economy', 'usage'],
    accepts: ['actor_id', 'module'],
    produces: ['quota_remaining', 'quota_used_pct', 'reset_date', 'overage_risk'],
    risk: 'read',
    enabled: true,
  },

  // ── MEMORY ──
  {
    id: 'memory.recall_context',
    module: 'MEMORY',
    description: 'Recall relevant memories for a topic or entity',
    domains: ['memory', 'context', 'knowledge'],
    accepts: ['query', 'topic', 'entity_id'],
    produces: ['memories', 'relevance_scores', 'source_modules'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'memory.pattern_match',
    module: 'MEMORY',
    description: 'Find historical patterns matching current context',
    domains: ['memory', 'pattern', 'history'],
    accepts: ['pattern_signature', 'domain'],
    produces: ['matches', 'confidence', 'historical_outcomes'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'memory.semantic_search',
    module: 'MEMORY',
    description: 'Semantic similarity search across the knowledge base',
    domains: ['semantic', 'knowledge', 'recall'],
    accepts: ['query', 'domain', 'limit'],
    produces: ['semantic_similarity', 'knowledge_density', 'cross_references', 'memory_freshness'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'memory.learning_context',
    module: 'MEMORY',
    description: 'Provide learning context and historical insights for a module',
    domains: ['learning', 'context', 'history'],
    accepts: ['module', 'topic'],
    produces: ['learning_history', 'improvement_trajectory', 'key_discoveries', 'related_memories'],
    risk: 'read',
    enabled: true,
  },

  // ── AUDIT ──
  {
    id: 'audit.actor_history',
    module: 'AUDIT',
    description: 'Get immutable audit trail for an actor or entity',
    domains: ['audit', 'history', 'compliance'],
    accepts: ['actor_id', 'entity_id', 'entity_type'],
    produces: ['audit_entries', 'total_actions', 'risk_actions'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'audit.compliance_score',
    module: 'AUDIT',
    description: 'Calculate compliance posture score across governance domains',
    domains: ['compliance', 'governance', 'audit'],
    accepts: ['module', 'standard'],
    produces: ['compliance_score', 'policy_violations', 'regulatory_status', 'remediation_needed'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'audit.change_velocity',
    module: 'AUDIT',
    description: 'Measure rate of changes and detect anomalous modification patterns',
    domains: ['audit', 'behavior', 'accountability'],
    accepts: ['actor_id', 'entity_type', 'time_range'],
    produces: ['change_velocity', 'action_frequency', 'actor_risk_profile', 'unusual_patterns'],
    risk: 'read',
    enabled: true,
  },

  // ── BRAIN ──
  {
    id: 'brain.reasoning_context',
    module: 'BRAIN',
    description: 'Get cognitive reasoning context for a decision',
    domains: ['reasoning', 'cognition', 'decision'],
    accepts: ['decision_type', 'context'],
    produces: ['reasoning_chain', 'confidence', 'alternatives'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'brain.prediction',
    module: 'BRAIN',
    description: 'Generate predictive analysis based on historical patterns and learning',
    domains: ['prediction', 'intelligence', 'analysis'],
    accepts: ['context', 'prediction_type', 'module'],
    produces: ['prediction', 'confidence', 'supporting_evidence', 'risk_factors'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'brain.cross_module_insight',
    module: 'BRAIN',
    description: 'Synthesize cross-module insights and correlations',
    domains: ['intelligence', 'learning', 'cognition'],
    accepts: ['topic', 'modules'],
    produces: ['cross_module_correlation', 'insight_novelty', 'cognitive_load', 'decision_quality'],
    risk: 'read',
    enabled: true,
  },

  // ── SANDBOX ──
  {
    id: 'sandbox.safe_eval',
    module: 'SANDBOX',
    description: 'Safely evaluate code or expressions in isolation',
    domains: ['execution', 'validation', 'code'],
    accepts: ['code', 'language', 'timeout_ms'],
    produces: ['result', 'stdout', 'exit_code', 'execution_ms'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'sandbox.safety_assessment',
    module: 'SANDBOX',
    description: 'Assess safety and determinism of a proposed operation',
    domains: ['safety', 'validation', 'testing'],
    accepts: ['operation', 'context'],
    produces: ['safety_score', 'side_effects_detected', 'determinism_score', 'resource_usage'],
    risk: 'read',
    enabled: true,
  },

  // ── INCLUSIVE ──
  {
    id: 'inclusive.accessibility_score',
    module: 'INCLUSIVE',
    description: 'Get accessibility compliance score for a resource',
    domains: ['accessibility', 'compliance', 'wcag'],
    accepts: ['url', 'resource_id'],
    produces: ['score', 'violations', 'wcag_level', 'auto_fixable'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'inclusive.usability_assessment',
    module: 'INCLUSIVE',
    description: 'Assess overall usability and inclusivity metrics',
    domains: ['usability', 'inclusivity', 'accessibility'],
    accepts: ['resource_id', 'context'],
    produces: ['usability_score', 'improvement_delta', 'priority_violations', 'remediation_history'],
    risk: 'read',
    enabled: true,
  },

  // ── CORTEX ──
  {
    id: 'cortex.orchestration_status',
    module: 'CORTEX',
    description: 'Get current orchestration pipeline status and capacity',
    domains: ['orchestration', 'pipeline', 'capacity'],
    accepts: ['pipeline_id'],
    produces: ['status', 'active_pipelines', 'queue_depth', 'capacity_pct'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'cortex.bottleneck_analysis',
    module: 'CORTEX',
    description: 'Identify bottlenecks and optimal routing in pipeline execution',
    domains: ['orchestration', 'performance', 'scheduling'],
    accepts: ['pipeline_id', 'module'],
    produces: ['bottleneck_module', 'optimal_routing', 'throughput_rate', 'pipeline_health'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'cortex.workflow_coordination',
    module: 'CORTEX',
    description: 'Coordinate multi-step workflows across modules',
    domains: ['workflow', 'coordination', 'orchestration'],
    accepts: ['workflow_id', 'step', 'modules'],
    produces: ['workflow_status', 'next_step', 'dependency_graph', 'estimated_completion'],
    risk: 'read',
    enabled: true,
  },

  // ── DECODE ──
  {
    id: 'decode.intent_analysis',
    module: 'DECODE',
    description: 'Analyze and enrich raw intents with context and entity recognition',
    domains: ['intent', 'parsing', 'entity_recognition'],
    accepts: ['raw_input', 'context'],
    produces: ['parsed_intent', 'entities', 'confidence', 'ambiguity_score'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'decode.context_enrichment',
    module: 'DECODE',
    description: 'Enrich a request with contextual signals from parse history',
    domains: ['language', 'interpretation', 'context'],
    accepts: ['query', 'session_id'],
    produces: ['context_enrichment', 'command_suggestion', 'related_intents'],
    risk: 'read',
    enabled: true,
  },

  // ── NEXUS ──
  {
    id: 'nexus.provider_health',
    module: 'NEXUS',
    description: 'Get health and reliability metrics for AI providers',
    domains: ['provider', 'routing', 'ai'],
    accepts: ['model', 'task_type'],
    produces: ['provider_status', 'provider_reliability', 'latency_estimate', 'cost_estimate'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'nexus.optimal_routing',
    module: 'NEXUS',
    description: 'Determine optimal model/provider for a given task',
    domains: ['routing', 'ai', 'load_balancing'],
    accepts: ['task_type', 'priority', 'budget_cents'],
    produces: ['best_model', 'fallback_chain', 'estimated_latency', 'estimated_cost'],
    risk: 'read',
    enabled: true,
  },

  // ── DREAM ──
  {
    id: 'dream.synthesis_context',
    module: 'DREAM',
    description: 'Provide dream synthesis context and creative exploration results',
    domains: ['dream', 'synthesis', 'creativity'],
    accepts: ['topic', 'seed', 'mode'],
    produces: ['dream_content', 'synthesis_quality', 'novelty_score', 'cross_pollination'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'dream.exploration_insights',
    module: 'DREAM',
    description: 'Extract actionable insights from dream exploration cycles',
    domains: ['exploration', 'imagination', 'intelligence'],
    accepts: ['domain', 'depth'],
    produces: ['insight_applicability', 'exploration_depth', 'serendipity_score', 'applied_discoveries'],
    risk: 'read',
    enabled: true,
  },

  // ── ENCODE ──
  {
    id: 'encode.code_analysis',
    module: 'ENCODE',
    description: 'Analyze code patterns, architecture, and technical debt',
    domains: ['code', 'architecture', 'patterns'],
    accepts: ['context', 'pattern', 'module'],
    produces: ['code_quality_score', 'pattern_matches', 'tech_debt_estimate', 'refactoring_suggestions'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'encode.generation_context',
    module: 'ENCODE',
    description: 'Provide code generation context and pattern recommendations',
    domains: ['generation', 'typescript', 'react'],
    accepts: ['context', 'component_type'],
    produces: ['recommended_pattern', 'dependency_graph', 'architecture_fit', 'code_template'],
    risk: 'read',
    enabled: true,
  },

  // ── EVOLUTION ──
  {
    id: 'evolution.evolution_status',
    module: 'EVOLUTION',
    description: 'Get status and risk assessment of evolution runs',
    domains: ['evolution', 'upgrade', 'migration'],
    accepts: ['plan_id', 'module', 'operation'],
    produces: ['evolution_phase', 'risk_score', 'rollback_available', 'shadow_accuracy'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'evolution.upgrade_readiness',
    module: 'EVOLUTION',
    description: 'Assess module readiness for upgrade or migration',
    domains: ['upgrade', 'deployment', 'regression'],
    accepts: ['module', 'target_version'],
    produces: ['readiness_score', 'blocking_issues', 'migration_complexity', 'estimated_duration'],
    risk: 'read',
    enabled: true,
  },

  // ── SYSTEM ──
  {
    id: 'system.health_check',
    module: 'SYSTEM',
    description: 'Get system health status and resource utilization',
    domains: ['health', 'monitoring', 'resource'],
    accepts: ['module', 'metric', 'check_type'],
    produces: ['health_status', 'uptime_pct', 'resource_usage', 'error_rate'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'system.incident_analysis',
    module: 'SYSTEM',
    description: 'Analyze incidents and self-heal outcomes',
    domains: ['incident', 'reliability', 'self_heal'],
    accepts: ['incident_id', 'module', 'time_range'],
    produces: ['root_cause', 'impact_scope', 'mttr_ms', 'self_heal_success', 'prevention_recommendation'],
    risk: 'read',
    enabled: true,
  },

  // ── ACCESS ──
  {
    id: 'access.developer_profile',
    module: 'ACCESS',
    description: 'Get developer profile, subscription, and API key status',
    domains: ['auth', 'developer', 'subscription'],
    accepts: ['actor_id', 'api_key_id', 'developer_id'],
    produces: ['developer_tier', 'subscription_status', 'api_key_count', 'quota_remaining'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'access.permission_audit',
    module: 'ACCESS',
    description: 'Audit permissions, API key usage, and quota consumption',
    domains: ['permission', 'api_key', 'quota'],
    accepts: ['actor_id', 'module'],
    produces: ['permission_level', 'api_usage_pct', 'anomalous_access', 'billing_status'],
    risk: 'read',
    enabled: true,
  },

  // ── RIPPLE ──
  {
    id: 'ripple.webhook_health',
    module: 'RIPPLE',
    description: 'Get webhook and integration health metrics',
    domains: ['webhook', 'integration', 'sync'],
    accepts: ['webhook_id', 'event_type', 'target_url'],
    produces: ['delivery_success_rate', 'avg_latency_ms', 'failure_pattern', 'retry_count'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'ripple.event_propagation',
    module: 'RIPPLE',
    description: 'Track event propagation and realtime sync status',
    domains: ['event', 'realtime', 'propagation'],
    accepts: ['event_type', 'source_module'],
    produces: ['propagation_status', 'subscriber_count', 'delivery_lag_ms', 'dedup_rate'],
    risk: 'read',
    enabled: true,
  },

  // ── INTEGRATION ──
  {
    id: 'integration.connector_status',
    module: 'INTEGRATION',
    description: 'Get connector health and enterprise integration status',
    domains: ['connector', 'enterprise', 'api'],
    accepts: ['connector_id', 'adapter'],
    produces: ['connector_health', 'sync_status', 'last_sync_at', 'error_count'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'integration.schema_mapping',
    module: 'INTEGRATION',
    description: 'Analyze schema mappings and data transform quality',
    domains: ['adapter', 'transform', 'mapping'],
    accepts: ['connector_id', 'schema'],
    produces: ['mapping_quality', 'field_coverage', 'transform_accuracy', 'compatibility_score'],
    risk: 'read',
    enabled: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // SIGNATURE FEATURES — Governance-locked
  // ═══════════════════════════════════════════════════════════════

  // 🔴 CMPSBL-ONLY — Recursive Cognition & Meta-Intelligence
  {
    id: 'brain.meta_reasoning',
    module: 'BRAIN',
    description: 'Recursive cognition — the brain reasons about its own reasoning chains to improve decision quality',
    domains: ['reasoning', 'cognition', 'meta', 'intelligence'],
    accepts: ['reasoning_chain', 'decision_type', 'context'],
    produces: ['meta_confidence', 'reasoning_quality_score', 'blind_spots', 'recursive_depth', 'self_correction'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'brain.hypothesis_generation',
    module: 'BRAIN',
    description: 'Autonomous hypothesis creation from cross-module data patterns and correlations',
    domains: ['intelligence', 'prediction', 'synthesis', 'cognition'],
    accepts: ['context', 'data_signals', 'modules'],
    produces: ['hypotheses', 'evidence_strength', 'test_suggestions', 'novelty_score', 'cross_module_support'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'memory.insight_synthesis',
    module: 'MEMORY',
    description: 'Cross-domain insight synthesis — merges knowledge across memory tiers to produce novel discoveries',
    domains: ['knowledge', 'synthesis', 'semantic', 'learning'],
    accepts: ['domains', 'topic', 'depth'],
    produces: ['synthesized_insights', 'knowledge_novelty', 'cross_domain_links', 'synthesis_confidence', 'actionability_score'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'dream.lucidity_control',
    module: 'DREAM',
    description: 'Dream depth and lucidity management — controls creative exploration intensity and focus',
    domains: ['dream', 'creativity', 'exploration', 'synthesis'],
    accepts: ['topic', 'lucidity_level', 'constraints'],
    produces: ['dream_depth', 'lucidity_score', 'creative_yield', 'boundary_integrity', 'serendipity_potential'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'cortex.cascade_failure_prevention',
    module: 'CORTEX',
    description: 'Predictive cascade failure prevention — detects dependency chain risks before they propagate',
    domains: ['orchestration', 'reliability', 'prediction', 'safety'],
    accepts: ['pipeline_id', 'module', 'dependency_graph'],
    produces: ['cascade_risk_score', 'failure_chain', 'isolation_recommendation', 'blast_radius', 'prevention_action'],
    risk: 'read',
    enabled: true,
  },

  // 🟡 ENTERPRISE — Advanced Security & Operations Intelligence
  {
    id: 'defense.zero_day_detection',
    module: 'DEFENSE',
    description: 'Novel attack pattern detection — identifies attack vectors not matching known signatures',
    domains: ['security', 'threat', 'anomaly', 'zero_day'],
    accepts: ['ip', 'actor_id', 'request_pattern'],
    produces: ['zero_day_confidence', 'attack_novelty', 'signature_distance', 'containment_urgency', 'similar_known_vectors'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.attack_correlation',
    module: 'DEFENSE',
    description: 'Cross-IP/session attack correlation — links distributed attack patterns into unified campaigns',
    domains: ['security', 'threat', 'forensics', 'correlation'],
    accepts: ['ip', 'actor_id', 'time_range', 'attack_type'],
    produces: ['campaign_id', 'correlated_actors', 'attack_timeline', 'coordination_score', 'origin_analysis'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'identity.identity_graph',
    module: 'IDENTITY',
    description: 'Cross-session identity graph construction — links actors across sessions, devices, and credentials',
    domains: ['identity', 'actor', 'graph', 'forensics'],
    accepts: ['actor_id', 'email', 'ip', 'fingerprint'],
    produces: ['identity_cluster', 'linked_actors', 'device_graph', 'session_chain', 'confidence_score'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'system.incident_prediction',
    module: 'SYSTEM',
    description: 'Predictive incident detection — forecasts system failures before they occur using health telemetry',
    domains: ['monitoring', 'prediction', 'reliability', 'incident'],
    accepts: ['module', 'metric', 'time_horizon'],
    produces: ['incident_probability', 'predicted_type', 'time_to_incident', 'leading_indicators', 'prevention_steps'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'audit.forensic_timeline',
    module: 'AUDIT',
    description: 'Automated forensic timeline construction — reconstructs complete event chains for compliance investigations',
    domains: ['audit', 'forensics', 'compliance', 'history'],
    accepts: ['actor_id', 'entity_id', 'time_range', 'incident_id'],
    produces: ['forensic_timeline', 'causal_chain', 'evidence_quality', 'tampering_indicators', 'regulatory_completeness'],
    risk: 'read',
    enabled: true,
  },

  // 🟢 CREATOR — Operational Intelligence & Optimization
  {
    id: 'memory.knowledge_gap_detection',
    module: 'MEMORY',
    description: 'Detects when system knowledge is stale, incomplete, or contradictory across domains',
    domains: ['memory', 'knowledge', 'quality', 'learning'],
    accepts: ['domain', 'topic', 'freshness_threshold'],
    produces: ['gap_areas', 'staleness_score', 'contradiction_count', 'coverage_pct', 'refresh_priority'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'economy.cost_anomaly_detection',
    module: 'ECONOMY',
    description: 'Detects cost anomalies and spending spikes before they impact budgets',
    domains: ['cost', 'anomaly', 'budget', 'monitoring'],
    accepts: ['module', 'period', 'threshold'],
    produces: ['anomaly_detected', 'anomaly_magnitude', 'cost_trend', 'root_cause_module', 'projected_overage'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'vision.user_journey_mapping',
    module: 'VISION',
    description: 'Reconstructs complete user journeys across sessions for behavioral analysis',
    domains: ['analytics', 'behavior', 'session', 'journey'],
    accepts: ['actor_id', 'time_range'],
    produces: ['journey_map', 'touchpoints', 'drop_off_points', 'conversion_path', 'engagement_arc'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'nexus.provider_failure_prediction',
    module: 'NEXUS',
    description: 'Predicts provider outages and degradation before they impact routing',
    domains: ['provider', 'prediction', 'reliability', 'routing'],
    accepts: ['model', 'provider', 'time_horizon'],
    produces: ['failure_probability', 'degradation_trend', 'recommended_fallback', 'confidence_interval', 'historical_pattern'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'encode.architecture_drift_detection',
    module: 'ENCODE',
    description: 'Detects when codebase architecture drifts from intended design patterns and module boundaries',
    domains: ['code', 'architecture', 'quality', 'patterns'],
    accepts: ['module', 'pattern', 'baseline'],
    produces: ['drift_score', 'violated_boundaries', 'coupling_increase', 'suggested_refactors', 'debt_trajectory'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'dream.pattern_consolidation',
    module: 'DREAM',
    description: 'Consolidates repeated behavioral patterns into reusable templates during dream cycles',
    domains: ['dream', 'pattern', 'learning', 'optimization'],
    accepts: ['domain', 'pattern_threshold', 'consolidation_depth'],
    produces: ['consolidated_templates', 'pattern_frequency', 'reuse_potential', 'template_quality', 'efficiency_gain'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'relay.channel_optimization',
    module: 'RELAY',
    description: 'Determines optimal delivery channel per recipient based on engagement history and preferences',
    domains: ['communication', 'delivery', 'optimization'],
    accepts: ['actor_id', 'message_type', 'urgency'],
    produces: ['optimal_channel', 'delivery_confidence', 'engagement_prediction', 'fallback_channel', 'timing_recommendation'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'vision.cohort_analysis',
    module: 'VISION',
    description: 'Groups users into behavioral cohorts for targeted optimization and retention analysis',
    domains: ['analytics', 'behavior', 'cohort', 'retention'],
    accepts: ['time_range', 'segmentation_criteria'],
    produces: ['cohort_segments', 'retention_curves', 'churn_predictors', 'behavioral_clusters', 'optimization_targets'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'decode.intent_evolution_tracking',
    module: 'DECODE',
    description: 'Tracks how user intents evolve over time to predict future needs and command patterns',
    domains: ['intent', 'prediction', 'behavior', 'language'],
    accepts: ['actor_id', 'session_history', 'time_range'],
    produces: ['intent_trajectory', 'predicted_next_intent', 'skill_progression', 'command_maturity', 'feature_discovery_rate'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'economy.value_attribution',
    module: 'ECONOMY',
    description: 'Attributes revenue and value generation to specific capabilities and modules',
    domains: ['economy', 'attribution', 'value', 'analytics'],
    accepts: ['module', 'capability', 'period'],
    produces: ['attributed_value_cents', 'value_per_invocation', 'roi_by_capability', 'value_trend', 'underutilized_capabilities'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'ripple.event_dedup_intelligence',
    module: 'RIPPLE',
    description: 'Semantic event deduplication — understands equivalent events beyond exact matches',
    domains: ['event', 'deduplication', 'intelligence', 'optimization'],
    accepts: ['event_type', 'payload', 'similarity_threshold'],
    produces: ['is_duplicate', 'semantic_similarity', 'canonical_event', 'dedup_savings', 'merge_recommendation'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'integration.health_prediction',
    module: 'INTEGRATION',
    description: 'Predicts connector failures and API degradation before they impact data flow',
    domains: ['connector', 'prediction', 'reliability', 'integration'],
    accepts: ['connector_id', 'time_horizon'],
    produces: ['failure_probability', 'degradation_indicators', 'recommended_action', 'historical_reliability', 'alternative_connectors'],
    risk: 'read',
    enabled: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // CROWN JEWELS — Wave 2 Discovery v10.5.3 (Governance-locked)
  // ═══════════════════════════════════════════════════════════════

  // 🔴 CMPSBL-ONLY — Autonomous Cognition & Self-Governance
  {
    id: 'brain.cognitive_load_balancing',
    module: 'BRAIN',
    description: 'Distributes cognitive tasks across engines based on real-time load, preventing bottlenecks in reasoning pipelines',
    domains: ['cognition', 'load_balancing', 'orchestration', 'performance'],
    accepts: ['task_type', 'cognitive_engines', 'current_load'],
    produces: ['optimal_engine', 'load_distribution', 'bottleneck_risk', 'rebalance_action', 'cognitive_throughput'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'brain.autonomous_goal_decomposition',
    module: 'BRAIN',
    description: 'Breaks complex goals into sub-goals and assigns to optimal modules — recursive planning without human input',
    domains: ['planning', 'goal', 'decomposition', 'autonomy'],
    accepts: ['goal', 'constraints', 'available_modules'],
    produces: ['sub_goals', 'module_assignments', 'execution_order', 'dependency_map', 'estimated_completion'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'dream.cross_pollination_synthesis',
    module: 'DREAM',
    description: 'Cross-instance dream pooling — merges insights from multiple substrate deployments into shared discoveries',
    domains: ['dream', 'federation', 'synthesis', 'collective'],
    accepts: ['instance_id', 'domain', 'privacy_level'],
    produces: ['cross_instance_insights', 'collective_novelty', 'privacy_compliance', 'synthesis_depth', 'federated_confidence'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'cortex.self_healing_orchestration',
    module: 'CORTEX',
    description: 'Autonomous pipeline repair — detects broken pipeline steps and reroutes execution around failures in real-time',
    domains: ['orchestration', 'self_heal', 'reliability', 'autonomy'],
    accepts: ['pipeline_id', 'failed_step', 'context'],
    produces: ['repair_action', 'alternative_route', 'heal_confidence', 'downtime_avoided_ms', 'learning_applied'],
    risk: 'read',
    enabled: true,
  },

  // 🟡 ARCHITECT — Advanced Intelligence & Governance
  {
    id: 'memory.temporal_reasoning',
    module: 'MEMORY',
    description: 'Temporal logic across memories — answers "what happened before X that caused Y" with causal chain analysis',
    domains: ['memory', 'temporal', 'causality', 'reasoning'],
    accepts: ['event', 'time_range', 'causal_depth'],
    produces: ['causal_chain', 'temporal_sequence', 'contributing_factors', 'confidence', 'counterfactual_analysis'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'defense.behavioral_fingerprinting',
    module: 'DEFENSE',
    description: 'Creates unique behavioral signatures for actors beyond device fingerprints — typing cadence, navigation patterns, API call rhythm',
    domains: ['security', 'identity', 'behavior', 'fingerprint'],
    accepts: ['actor_id', 'interaction_data', 'session_id'],
    produces: ['behavioral_signature', 'consistency_score', 'impersonation_risk', 'signature_drift', 'confidence_level'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'encode.semantic_refactoring',
    module: 'ENCODE',
    description: 'Understands code semantics to suggest behavior-preserving refactoring with formal verification of equivalence',
    domains: ['code', 'refactoring', 'semantics', 'verification'],
    accepts: ['code_context', 'module', 'refactoring_goal'],
    produces: ['refactoring_plan', 'semantic_equivalence_proof', 'risk_assessment', 'complexity_reduction', 'test_coverage_impact'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'system.capacity_forecasting',
    module: 'SYSTEM',
    description: 'Predicts when system will hit capacity limits and recommends proactive scaling actions',
    domains: ['capacity', 'prediction', 'scaling', 'infrastructure'],
    accepts: ['module', 'metric', 'forecast_horizon'],
    produces: ['capacity_timeline', 'saturation_date', 'scaling_recommendation', 'cost_of_scaling', 'risk_of_inaction'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'cortex.dependency_impact_analysis',
    module: 'CORTEX',
    description: 'Maps blast radius of any module change across the full dependency graph with ripple effect scoring',
    domains: ['dependency', 'impact', 'change_management', 'orchestration'],
    accepts: ['module', 'change_type', 'change_scope'],
    produces: ['blast_radius', 'affected_modules', 'ripple_score', 'breaking_risk', 'safe_deployment_order'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'nexus.model_quality_scoring',
    module: 'NEXUS',
    description: 'Real-time model output quality scoring — detects model degradation and hallucination drift across providers',
    domains: ['quality', 'ai', 'monitoring', 'routing'],
    accepts: ['model', 'output', 'expected_quality'],
    produces: ['quality_score', 'hallucination_risk', 'degradation_trend', 'provider_comparison', 'reroute_recommendation'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'identity.behavioral_biometrics',
    module: 'IDENTITY',
    description: 'Continuous authentication via interaction patterns — typing cadence, mouse dynamics, API rhythm as identity signals',
    domains: ['identity', 'authentication', 'biometrics', 'continuous'],
    accepts: ['actor_id', 'interaction_stream', 'session_id'],
    produces: ['biometric_match', 'identity_confidence', 'anomaly_detected', 'session_hijack_risk', 're_auth_recommended'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'audit.regulatory_autopilot',
    module: 'AUDIT',
    description: 'Auto-generates compliance reports for SOC2/GDPR/HIPAA from audit data — continuous compliance without manual work',
    domains: ['compliance', 'audit', 'regulatory', 'automation'],
    accepts: ['standard', 'time_range', 'scope'],
    produces: ['compliance_report', 'gap_analysis', 'evidence_completeness', 'remediation_priority', 'audit_readiness_score'],
    risk: 'read',
    enabled: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // FULL MATRIX COVERAGE — Remaining 20 Nodes
  // ═══════════════════════════════════════════════════════════════

  // ── CORE (Kernel / SPINE) ──
  {
    id: 'core.system_pulse',
    module: 'CORE',
    description: 'Get substrate heartbeat, boot stage, and kernel health',
    domains: ['health', 'monitoring', 'kernel'],
    accepts: ['check_type'],
    produces: ['pulse_status', 'boot_stage', 'kernel_health', 'uptime_ms'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'core.topology_snapshot',
    module: 'CORE',
    description: 'Snapshot of the 40-node matrix topology and sector assignments',
    domains: ['topology', 'architecture', 'kernel'],
    accepts: ['sector', 'depth'],
    produces: ['node_count', 'sector_map', 'weight_distribution', 'activation_order'],
    risk: 'read',
    enabled: true,
  },

  // ── NERVE (CCR) ──
  {
    id: 'nerve.signal_status',
    module: 'NERVE',
    description: 'Get signal emission state and gate health across the 4-gate pathway',
    domains: ['signal', 'communication', 'health'],
    accepts: ['signal_type', 'module'],
    produces: ['gate_status', 'signal_queue_depth', 'emission_rate', 'blocked_signals'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'nerve.cross_module_signal',
    module: 'NERVE',
    description: 'Analyze cross-module signal patterns and routing efficiency',
    domains: ['signal', 'routing', 'performance'],
    accepts: ['source_module', 'target_module', 'time_range'],
    produces: ['signal_latency_ms', 'delivery_rate', 'routing_efficiency', 'bottleneck_path'],
    risk: 'read',
    enabled: true,
  },

  // ── CONSCIENCE (OCG) ──
  {
    id: 'conscience.bias_scan',
    module: 'CONSCIENCE',
    description: 'Run 5-type bias detection scan on a decision or output',
    domains: ['ethics', 'bias', 'fairness', 'governance'],
    accepts: ['decision', 'context', 'output'],
    produces: ['bias_score', 'bias_types_detected', 'fairness_index', 'remediation_suggestions'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'conscience.ethical_assessment',
    module: 'CONSCIENCE',
    description: 'Ethical risk assessment for proposed actions or system changes',
    domains: ['ethics', 'governance', 'safety', 'compliance'],
    accepts: ['action', 'context', 'affected_parties'],
    produces: ['ethical_risk_score', 'principle_violations', 'stakeholder_impact', 'approval_recommendation'],
    risk: 'read',
    enabled: true,
  },

  // ── ORACLE (Execution) ──
  {
    id: 'oracle.bayesian_forecast',
    module: 'ORACLE',
    description: 'Bayesian network forecasting with Monte Carlo simulation',
    domains: ['prediction', 'forecast', 'intelligence', 'analytics'],
    accepts: ['variables', 'evidence', 'iterations'],
    produces: ['forecast_distribution', 'confidence_interval', 'most_likely_outcome', 'sensitivity_analysis'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'oracle.capability_forecast',
    module: 'ORACLE',
    description: 'Forecast capability evolution and emerging system needs',
    domains: ['capability', 'prediction', 'planning'],
    accepts: ['module', 'time_horizon', 'growth_signals'],
    produces: ['capability_trajectory', 'demand_forecast', 'investment_priority', 'emergence_probability'],
    risk: 'read',
    enabled: true,
  },

  // ── PHANTOM (Security) ──
  {
    id: 'phantom.anonymization_status',
    module: 'PHANTOM',
    description: 'Check anonymization layer health and 3-hop proxy integrity',
    domains: ['privacy', 'anonymization', 'security'],
    accepts: ['actor_id', 'session_id'],
    produces: ['anonymization_depth', 'proxy_chain_intact', 'deanonymization_risk', 'privacy_score'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'phantom.privacy_audit',
    module: 'PHANTOM',
    description: 'Audit data exposure and PII leak risk across modules',
    domains: ['privacy', 'compliance', 'audit', 'security'],
    accepts: ['module', 'data_type'],
    produces: ['exposure_risk', 'pii_detected', 'anonymization_coverage', 'gdpr_compliance_score'],
    risk: 'read',
    enabled: true,
  },

  // ── HARVEST (Data) ──
  {
    id: 'harvest.ingestion_status',
    module: 'HARVEST',
    description: 'Get data ingestion pipeline status and deduplication metrics',
    domains: ['data', 'ingestion', 'pipeline'],
    accepts: ['source', 'pipeline_id'],
    produces: ['ingestion_rate', 'dedup_rate', 'bloom_filter_fill', 'queue_depth', 'error_rate'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'harvest.data_quality',
    module: 'HARVEST',
    description: 'Assess data quality, freshness, and completeness across sources',
    domains: ['data', 'quality', 'validation'],
    accepts: ['source', 'domain', 'freshness_threshold'],
    produces: ['quality_score', 'completeness_pct', 'freshness_age_ms', 'anomaly_count', 'schema_drift'],
    risk: 'read',
    enabled: true,
  },

  // ── GOVERNANCE (Plane) ──
  {
    id: 'governance.policy_check',
    module: 'GOVERNANCE',
    description: 'Evaluate an action against active governance policies and tier gates',
    domains: ['governance', 'policy', 'authorization'],
    accepts: ['action', 'actor_id', 'module', 'tier'],
    produces: ['policy_verdict', 'blocking_policies', 'tier_clearance', 'escalation_required'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'governance.proposal_status',
    module: 'GOVERNANCE',
    description: 'Get status of governance proposals and approval pipeline',
    domains: ['governance', 'approval', 'evolution'],
    accepts: ['proposal_id', 'module'],
    produces: ['proposal_phase', 'approval_status', 'gate_progress', 'risk_assessment', 'estimated_promotion'],
    risk: 'read',
    enabled: true,
  },

  // ── ATLAS (Expansion) ──
  {
    id: 'atlas.capability_registry',
    module: 'ATLAS',
    description: 'Query the 80-capability registry for availability and gating status',
    domains: ['capability', 'registry', 'discovery'],
    accepts: ['capability_id', 'tier', 'category'],
    produces: ['capability_status', 'gate_requirements', 'usage_count', 'tier_mapping', 'dependencies'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'atlas.entitlement_check',
    module: 'ATLAS',
    description: 'Resolve entitlements and capability access for a given actor or tier',
    domains: ['entitlement', 'access', 'capability'],
    accepts: ['actor_id', 'tier', 'capability_id'],
    produces: ['entitled', 'entitlement_source', 'cascade_path', 'expiry', 'upgrade_path'],
    risk: 'read',
    enabled: true,
  },

  // ── IMMUNITY (Fields) ──
  {
    id: 'immunity.anomaly_baseline',
    module: 'IMMUNITY',
    description: 'Get adaptive 3-sigma anomaly baselines and drift detection status',
    domains: ['anomaly', 'immunity', 'monitoring', 'health'],
    accepts: ['module', 'metric'],
    produces: ['baseline_value', 'sigma_threshold', 'drift_score', 'anomaly_detected', 'cascade_risk'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'immunity.system_immunity_score',
    module: 'IMMUNITY',
    description: 'Overall system immunity posture — resistance to failures and attacks',
    domains: ['immunity', 'resilience', 'health', 'security'],
    accepts: ['sector', 'depth'],
    produces: ['immunity_score', 'vulnerability_count', 'self_heal_capacity', 'attack_surface', 'resilience_trend'],
    risk: 'read',
    enabled: true,
  },

  // ── INTENT (Self — Fields) ──
  {
    id: 'intent.mesh_status',
    module: 'INTENT',
    description: 'Get INTENT mesh health, resolver count, and routing statistics',
    domains: ['intent', 'mesh', 'monitoring'],
    accepts: ['time_range'],
    produces: ['total_resolvers', 'active_resolvers', 'resolution_rate', 'avg_latency_ms', 'gap_count'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'intent.goal_tracking',
    module: 'INTENT',
    description: 'Track goal decomposition, milestone completion, and action plan status',
    domains: ['goal', 'planning', 'orchestration'],
    accepts: ['goal_id', 'actor_id'],
    produces: ['goal_status', 'milestones_completed', 'action_plan_progress', 'blocking_dependencies'],
    risk: 'read',
    enabled: true,
  },

  // ── SHADOW (Expansion) ──
  {
    id: 'shadow.comparison_result',
    module: 'SHADOW',
    description: 'Get shadow execution comparison results and TSAC verification status',
    domains: ['shadow', 'testing', 'verification'],
    accepts: ['execution_id', 'module'],
    produces: ['shadow_match', 'divergence_score', 'tsac_verified', 'promotion_safe', 'diff_summary'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'shadow.evolution_readiness',
    module: 'SHADOW',
    description: 'Assess shadow-validated readiness for production promotion',
    domains: ['shadow', 'deployment', 'validation'],
    accepts: ['module', 'change_id'],
    produces: ['readiness_score', 'shadow_pass_rate', 'regression_risk', 'confidence_level'],
    risk: 'read',
    enabled: true,
  },

  // ── FORGE (ESZ) ──
  {
    id: 'forge.skill_registry',
    module: 'FORGE',
    description: 'Query the 71-skill registry across 19 categories with proficiency levels',
    domains: ['skill', 'capability', 'generation'],
    accepts: ['category', 'skill_id'],
    produces: ['skill_status', 'proficiency_level', 'hash_seal_valid', 'generation_budget', 'usage_count'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'forge.hardening_status',
    module: 'FORGE',
    description: 'Get Forge v2.0.0 hardening suite status — FNV-1a seals, narrative blockers, VOLVER handicap',
    domains: ['hardening', 'security', 'generation'],
    accepts: ['module'],
    produces: ['seal_integrity', 'narrative_blocker_active', 'volver_handicap', 'generation_remaining'],
    risk: 'read',
    enabled: true,
  },

  // ── LINGUA (EPZ) ──
  {
    id: 'lingua.translation_quality',
    module: 'LINGUA',
    description: 'Assess translation quality and linguistic accuracy across locales',
    domains: ['language', 'translation', 'localization'],
    accepts: ['text', 'source_locale', 'target_locale'],
    produces: ['quality_score', 'fluency_rating', 'semantic_preservation', 'cultural_adaptation'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'lingua.locale_coverage',
    module: 'LINGUA',
    description: 'Get localization coverage and missing translation analysis',
    domains: ['localization', 'coverage', 'language'],
    accepts: ['locale', 'module'],
    produces: ['coverage_pct', 'missing_keys', 'stale_translations', 'priority_gaps'],
    risk: 'read',
    enabled: true,
  },

  // ── ECHO (EMZ) ──
  {
    id: 'echo.feedback_analysis',
    module: 'ECHO',
    description: 'Analyze user feedback patterns and sentiment across interactions',
    domains: ['feedback', 'sentiment', 'user_experience'],
    accepts: ['actor_id', 'time_range', 'channel'],
    produces: ['sentiment_score', 'feedback_themes', 'satisfaction_trend', 'churn_signal'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'echo.resonance_score',
    module: 'ECHO',
    description: 'Measure feature and content resonance with target audience segments',
    domains: ['engagement', 'analytics', 'feedback'],
    accepts: ['feature_id', 'content_id', 'segment'],
    produces: ['resonance_score', 'engagement_depth', 'viral_coefficient', 'retention_impact'],
    risk: 'read',
    enabled: true,
  },

  // ── SOVEREIGN (Shell) ──
  {
    id: 'sovereign.voice_consistency',
    module: 'SOVEREIGN',
    description: 'Check voice profile consistency and SOVEREIGN personality adherence',
    domains: ['voice', 'personality', 'communication'],
    accepts: ['output', 'mode', 'context'],
    produces: ['consistency_score', 'voice_drift', 'tone_alignment', 'boundary_violations'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'sovereign.guard_status',
    module: 'SOVEREIGN',
    description: 'Get internal guard policy status — architecture detail protection level',
    domains: ['security', 'governance', 'communication'],
    accepts: ['query', 'actor_tier'],
    produces: ['guard_active', 'classification_level', 'disclosure_risk', 'redaction_applied'],
    risk: 'read',
    enabled: true,
  },

  // ── REFLEX (Shell) ──
  {
    id: 'reflex.reaction_latency',
    module: 'REFLEX',
    description: 'Measure system reaction times and reflex pathway performance',
    domains: ['performance', 'latency', 'reflex'],
    accepts: ['pathway', 'trigger_type'],
    produces: ['reaction_ms', 'p95_latency', 'pathway_health', 'optimization_potential'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'reflex.auto_response_audit',
    module: 'REFLEX',
    description: 'Audit automated response accuracy and false-positive rates',
    domains: ['automation', 'accuracy', 'audit'],
    accepts: ['trigger_type', 'time_range'],
    produces: ['accuracy_rate', 'false_positive_pct', 'response_appropriateness', 'override_count'],
    risk: 'read',
    enabled: true,
  },

  // ── TREATY (Governance) ──
  {
    id: 'treaty.agreement_status',
    module: 'TREATY',
    description: 'Get inter-module treaty and SLA agreement status',
    domains: ['governance', 'sla', 'agreement'],
    accepts: ['treaty_id', 'module_a', 'module_b'],
    produces: ['treaty_status', 'sla_compliance', 'violation_count', 'renegotiation_needed'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'treaty.cross_boundary_policy',
    module: 'TREATY',
    description: 'Evaluate cross-sector collaboration policies and boundary enforcement',
    domains: ['policy', 'boundary', 'governance'],
    accepts: ['source_sector', 'target_sector', 'operation'],
    produces: ['policy_verdict', 'boundary_intact', 'escalation_path', 'collaboration_history'],
    risk: 'read',
    enabled: true,
  },

  // ── ENGINEER (Expansion — Node 39) ──
  {
    id: 'engineer.tech_debt_assessment',
    module: 'ENGINEER',
    description: 'Assess technical debt levels and P95 latency tracking across modules',
    domains: ['engineering', 'debt', 'performance'],
    accepts: ['module', 'metric'],
    produces: ['debt_score', 'p95_latency_ms', 'refactoring_priority', 'estimated_effort'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'engineer.infrastructure_health',
    module: 'ENGINEER',
    description: 'Infrastructure reliability metrics and scaling recommendations',
    domains: ['infrastructure', 'reliability', 'scaling'],
    accepts: ['service', 'time_range'],
    produces: ['reliability_score', 'scaling_headroom', 'hotspot_services', 'degradation_trend'],
    risk: 'read',
    enabled: true,
  },

  // ── COMPASS (Navigation) ──
  {
    id: 'compass.navigation_resolution',
    module: 'COMPASS',
    description: 'Resolve semantic navigation intents to node IDs and implementation paths',
    domains: ['navigation', 'routing', 'discovery'],
    accepts: ['query', 'context'],
    produces: ['resolved_node', 'confidence', 'alternative_nodes', 'implementation_path'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'compass.substrate_map',
    module: 'COMPASS',
    description: 'Get substrate navigation map with sector and node relationships',
    domains: ['topology', 'navigation', 'architecture'],
    accepts: ['sector', 'depth'],
    produces: ['node_map', 'sector_boundaries', 'connection_graph', 'navigation_shortcuts'],
    risk: 'read',
    enabled: true,
  },

  // ── OBSERVER (Monitoring) ──
  {
    id: 'observer.telemetry_summary',
    module: 'OBSERVER',
    description: 'Aggregate telemetry summary across modules and sectors',
    domains: ['monitoring', 'telemetry', 'observability'],
    accepts: ['module', 'metric', 'time_range'],
    produces: ['telemetry_snapshot', 'metric_trends', 'alert_count', 'anomaly_flags'],
    risk: 'read',
    enabled: true,
  },
  {
    id: 'observer.watchdog_status',
    module: 'OBSERVER',
    description: 'Get watchdog monitoring status and active alert conditions',
    domains: ['monitoring', 'alerting', 'health'],
    accepts: ['module', 'severity'],
    produces: ['active_alerts', 'watchdog_health', 'escalation_queue', 'silence_status'],
    risk: 'read',
    enabled: true,
  },
];

/** Get all resolvers for a specific module */
export function getModuleResolvers(module: string): MeshResolver[] {
  return MESH_MANIFEST.filter(r => r.module === module.toUpperCase());
}

/** Get all resolvers that can handle a specific domain */
export function getResolversByDomain(domain: string): MeshResolver[] {
  return MESH_MANIFEST.filter(r => r.enabled && r.domains.includes(domain));
}

/** Get all resolvers that produce a specific output key */
export function getResolversByOutput(outputKey: string): MeshResolver[] {
  return MESH_MANIFEST.filter(r => r.enabled && r.produces.includes(outputKey));
}

/** Get all unique modules in the manifest */
export function getMeshModules(): string[] {
  return [...new Set(MESH_MANIFEST.map(r => r.module))];
}
