/**
 * Scan Report Export — PDF/CSV generation
 * Item #12: Download scan reports as branded PDFs or CSV
 */

interface ScanFinding {
  id: string;
  title: string;
  category: string;
  severity: string;
  description: string;
  recommendation?: string;
}

interface ScanReportData {
  domain: string;
  scanMode: string;
  score: number;
  findings: ScanFinding[];
  scannedAt: string;
}

/**
 * Export scan findings as CSV.
 */
export function exportScanCSV(report: ScanReportData): void {
  const headers = ['ID', 'Title', 'Category', 'Severity', 'Description', 'Recommendation'];
  const rows = report.findings.map(f => [
    f.id,
    `"${f.title.replace(/"/g, '""')}"`,
    f.category,
    f.severity,
    `"${f.description.replace(/"/g, '""')}"`,
    `"${(f.recommendation || '').replace(/"/g, '""')}"`,
  ]);

  const csv = [
    `# Scan Report: ${report.domain}`,
    `# Score: ${report.score}/100`,
    `# Mode: ${report.scanMode}`,
    `# Date: ${report.scannedAt}`,
    '',
    headers.join(','),
    ...rows.map(r => r.join(',')),
  ].join('\n');

  downloadBlob(csv, `scan-${report.domain}-${Date.now()}.csv`, 'text/csv');
}

/**
 * Export scan report as branded HTML (printable as PDF via browser).
 */
export function exportScanPDF(report: ScanReportData): void {
  const severityColors: Record<string, string> = {
    critical: '#dc2626',
    high: '#ea580c',
    medium: '#d97706',
    low: '#2563eb',
    info: '#6b7280',
  };

  const findingsHtml = report.findings.map(f => `
    <tr>
      <td style="padding:8px;border:1px solid #ddd;"><span style="color:${severityColors[f.severity] || '#333'};font-weight:600;">${f.severity.toUpperCase()}</span></td>
      <td style="padding:8px;border:1px solid #ddd;">${f.title}</td>
      <td style="padding:8px;border:1px solid #ddd;">${f.category}</td>
      <td style="padding:8px;border:1px solid #ddd;font-size:0.85em;">${f.description}</td>
    </tr>
  `).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Scan Report — ${report.domain}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2em; color: #1a1a1a; }
  h1 { font-size: 1.5em; color: #7A5FFF; }
  .score { font-size: 3em; font-weight: 700; color: ${report.score >= 80 ? '#16a34a' : report.score >= 50 ? '#d97706' : '#dc2626'}; }
  .meta { color: #666; font-size: 0.9em; margin-bottom: 2em; }
  table { width: 100%; border-collapse: collapse; margin: 1em 0; }
  th { background: #f4f4f4; padding: 10px 8px; border: 1px solid #ddd; text-align: left; font-size: 0.85em; }
  .footer { margin-top: 3em; border-top: 1px solid #ddd; padding-top: 1em; font-size: 0.8em; color: #999; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>CMPSBL Scan Report</h1>
  <div class="meta">${report.domain} · ${report.scanMode} scan · ${report.scannedAt}</div>
  <div class="score">${report.score}<span style="font-size:0.3em;color:#666">/100</span></div>
  <p>${report.findings.length} findings detected</p>
  <table>
    <thead><tr><th>Severity</th><th>Finding</th><th>Category</th><th>Description</th></tr></thead>
    <tbody>${findingsHtml}</tbody>
  </table>
  <div class="footer">Generated by CMPSBL · cmpsbl.com · ${new Date().toISOString()}</div>
</body>
</html>`;

  // Open in new tab for print-to-PDF
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
