/**
 * Crystallized Pipeline Registry — 100 Crown Jewel Pipelines
 * Tiered Pipeline Crystallization
 * 
 * Crystallized pipelines are multi-module resolver chains that emerged
 * from Intent Mesh discovery and were hardened into permanent, reusable
 * execution templates. Each pipeline composes 2-4 modules into a
 * sealed, black-boxed workflow.
 * 
 * Tiers:
 *   CMPSBL-Only (Architecture) — 20 pipelines (never released)
 *   Enterprise — 16 pipelines
 *   Architect — 36 pipelines  
 *   Creator — 28 pipelines
 */

export type PipelineTier = 'cmpsbl' | 'enterprise' | 'architect' | 'creator';

export interface CrystallizedPipeline {
  id: string;
  name: string;
  modules: string[];
  description: string;
  emergentProperty: string;
  tier: PipelineTier;
  category: 'security' | 'intelligence' | 'optimization' | 'compliance' | 'observability' | 'orchestration';
  isSealed: boolean;
  discoveredFrom: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CMPSBL-ONLY PIPELINES (20) — Architecture-class, never released
// ═══════════════════════════════════════════════════════════════════════════════

const CMPSBL_PIPELINES: CrystallizedPipeline[] = [
  {
    id: 'cp-recursive-self-evolution',
    name: 'Recursive Self-Evolution Loop',
    modules: ['CORTEX', 'DREAM', 'BRAIN', 'EVOLUTION'],
    description: 'Closed-loop self-improvement where insights from Dream analysis feed back into architecture mutations',
    emergentProperty: 'Autonomous architecture improvement without external input',
    tier: 'cmpsbl',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-001',
  },
  {
    id: 'cp-cognitive-bootstrap-chain',
    name: 'Cognitive Bootstrap Chain',
    modules: ['BRAIN', 'CORTEX', 'ENCODE', 'SYSTEM'],
    description: 'Cold-start intelligence bootstrapping from minimal seed knowledge',
    emergentProperty: 'Zero-to-competent cognitive initialization',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-002',
  },
  {
    id: 'cp-meta-governance-loop',
    name: 'Meta-Governance Feedback Loop',
    modules: ['CORTEX', 'DEFENSE', 'AUDIT', 'SYSTEM'],
    description: 'Governance policies that evaluate and refine themselves based on enforcement outcomes',
    emergentProperty: 'Self-correcting governance without human intervention',
    tier: 'cmpsbl',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-003',
  },
  {
    id: 'cp-architecture-telomere-repair',
    name: 'Architecture Telomere Repair',
    modules: ['MODERNIZER', 'SYSTEM', 'CORTEX', 'VISION'],
    description: 'Detects and repairs architecture aging patterns before they cause systemic degradation',
    emergentProperty: 'Perpetual architecture youth maintenance',
    tier: 'cmpsbl',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-004',
  },
  {
    id: 'cp-knowledge-fusion-cascade',
    name: 'Knowledge Fusion Cascade',
    modules: ['BRAIN', 'DREAM', 'MEMORY', 'CORTEX'],
    description: 'Multi-stage knowledge synthesis producing novel insights from cross-domain fusion',
    emergentProperty: 'Autonomous discovery of non-obvious knowledge connections',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-005',
  },
  {
    id: 'cp-emergent-strategy-compiler',
    name: 'Emergent Strategy Compiler',
    modules: ['CORTEX', 'VISION', 'BRAIN', 'DREAM'],
    description: 'Compiles emergent patterns into executable strategic plans',
    emergentProperty: 'Strategy synthesis from raw signal patterns',
    tier: 'cmpsbl',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-006',
  },
  {
    id: 'cp-substrate-homeostasis-loop',
    name: 'Substrate Homeostasis Loop',
    modules: ['CORE', 'SYSTEM', 'CORTEX', 'DEFENSE'],
    description: 'Maintains substrate equilibrium by counteracting destabilizing changes in real-time',
    emergentProperty: 'Autonomous stability without manual intervention',
    tier: 'cmpsbl',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-007',
  },
  {
    id: 'cp-cognitive-deception-shield',
    name: 'Cognitive Deception Shield',
    modules: ['DEFENSE', 'BRAIN', 'DECODE', 'IDENTITY'],
    description: 'Deploys cognitive deception techniques to mislead and trap adversarial actors',
    emergentProperty: 'Active defense through controlled information asymmetry',
    tier: 'cmpsbl',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-008',
  },
  {
    id: 'cp-autonomous-triage-cascade',
    name: 'Autonomous Triage Cascade',
    modules: ['SYSTEM', 'CORTEX', 'DEFENSE', 'VISION'],
    description: 'Multi-priority triage that autonomously escalates and resolves system health events',
    emergentProperty: 'Zero-human-touch incident resolution',
    tier: 'cmpsbl',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-009',
  },
  {
    id: 'cp-synthetic-intuition-engine',
    name: 'Synthetic Intuition Engine',
    modules: ['DREAM', 'BRAIN', 'CORTEX', 'VISION'],
    description: 'Generates intuitive leaps by synthesizing subconscious pattern recognition',
    emergentProperty: 'Non-linear creative problem solving',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-010',
  },
  // ── NEW CMPSBL-ONLY (10 additions) ──
  {
    id: 'cp-temporal-causality-engine',
    name: 'Temporal Causality Engine',
    modules: ['CORTEX', 'BRAIN', 'DREAM', 'MEMORY'],
    description: 'Reconstructs causal chains across time to predict consequences of future mutations',
    emergentProperty: 'Time-aware decision making across architecture changes',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-011',
  },
  {
    id: 'cp-consciousness-continuity-bridge',
    name: 'Consciousness Continuity Bridge',
    modules: ['MEMORY', 'BRAIN', 'CORTEX', 'DREAM'],
    description: 'Preserves cognitive identity across cold restarts, migrations, and version upgrades',
    emergentProperty: 'Unbroken identity persistence through infrastructure changes',
    tier: 'cmpsbl',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-012',
  },
  {
    id: 'cp-entropic-decay-reversal',
    name: 'Entropic Decay Reversal',
    modules: ['MODERNIZER', 'DREAM', 'CORTEX', 'SYSTEM'],
    description: 'Detects entropy accumulation in knowledge stores and actively reverses degradation',
    emergentProperty: 'Negative entropy maintenance in long-lived systems',
    tier: 'cmpsbl',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-013',
  },
  {
    id: 'cp-adversarial-hypothesis-generator',
    name: 'Adversarial Hypothesis Generator',
    modules: ['DEFENSE', 'DREAM', 'BRAIN', 'CORTEX'],
    description: 'Generates worst-case attack scenarios the system has never seen to strengthen defenses',
    emergentProperty: 'Preemptive defense against novel attack vectors',
    tier: 'cmpsbl',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-014',
  },
  {
    id: 'cp-value-crystallization-loop',
    name: 'Value Crystallization Loop',
    modules: ['CORTEX', 'BRAIN', 'ECONOMY', 'DREAM'],
    description: 'Converts ephemeral insights into permanent value-generating structures',
    emergentProperty: 'Automatic wealth creation from transient intelligence',
    tier: 'cmpsbl',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-015',
  },
  {
    id: 'cp-cognitive-immune-system',
    name: 'Cognitive Immune System',
    modules: ['DEFENSE', 'BRAIN', 'CORTEX', 'SYSTEM'],
    description: 'Biological-inspired immune response to cognitive contamination and adversarial injection',
    emergentProperty: 'Autonomous cognitive purity maintenance',
    tier: 'cmpsbl',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-016',
  },
  {
    id: 'cp-recursive-abstraction-ladder',
    name: 'Recursive Abstraction Ladder',
    modules: ['BRAIN', 'DREAM', 'CORTEX', 'ENCODE'],
    description: 'Elevates concrete patterns into progressively higher abstractions autonomously',
    emergentProperty: 'Self-generating conceptual hierarchies',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-017',
  },
  {
    id: 'cp-substrate-dreaming-protocol',
    name: 'Substrate Dreaming Protocol',
    modules: ['DREAM', 'CORTEX', 'MEMORY', 'BRAIN'],
    description: 'Offline synthesis where the substrate dreams solutions to unsolved problems',
    emergentProperty: 'Sleep-cycle problem solving without active compute',
    tier: 'cmpsbl',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-018',
  },
  {
    id: 'cp-governance-genome-sequencer',
    name: 'Governance Genome Sequencer',
    modules: ['AUDIT', 'CORTEX', 'SYSTEM', 'BRAIN'],
    description: 'Maps the complete governance genome and identifies mutation risks before they express',
    emergentProperty: 'Predictive governance mutation analysis',
    tier: 'cmpsbl',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-019',
  },
  {
    id: 'cp-infinite-horizon-planner',
    name: 'Infinite Horizon Planner',
    modules: ['CORTEX', 'DREAM', 'VISION', 'ECONOMY'],
    description: 'Plans across unbounded time horizons with discounted future value optimization',
    emergentProperty: 'Arbitrarily long strategic planning without horizon collapse',
    tier: 'cmpsbl',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-alpha-020',
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ENTERPRISE PIPELINES (16) — Governance-grade sealed workflows
// ═══════════════════════════════════════════════════════════════════════════════

const ENTERPRISE_PIPELINES: CrystallizedPipeline[] = [
  {
    id: 'cp-compliance-automation-chain',
    name: 'Compliance Automation Chain',
    modules: ['AUDIT', 'CORTEX', 'DEFENSE', 'IDENTITY'],
    description: 'End-to-end compliance workflow from detection through remediation and reporting',
    emergentProperty: 'Automated SOC2/GDPR compliance with zero manual steps',
    tier: 'enterprise',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-001',
  },
  {
    id: 'cp-org-threat-intelligence-mesh',
    name: 'Org Threat Intelligence Mesh',
    modules: ['DEFENSE', 'VISION', 'IDENTITY', 'RELAY'],
    description: 'Cross-organization threat intelligence sharing with anonymized pattern distribution',
    emergentProperty: 'Collective defense intelligence across deployments',
    tier: 'enterprise',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-002',
  },
  {
    id: 'cp-multi-tenant-isolation-fabric',
    name: 'Multi-Tenant Isolation Fabric',
    modules: ['BRAIN', 'MEMORY', 'ACCESS', 'IDENTITY'],
    description: 'Cryptographic tenant isolation with zero-leakage memory partitioning',
    emergentProperty: 'Hardware-grade tenant separation in shared infrastructure',
    tier: 'enterprise',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-003',
  },
  {
    id: 'cp-sla-aware-execution-governor',
    name: 'SLA-Aware Execution Governor',
    modules: ['CORTEX', 'NEXUS', 'SYSTEM', 'ECONOMY'],
    description: 'Governs all execution paths to meet contractual SLA targets with automated failover',
    emergentProperty: 'Guaranteed execution within SLA bounds',
    tier: 'enterprise',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-004',
  },
  {
    id: 'cp-enterprise-audit-trail',
    name: 'Enterprise Audit Trail Pipeline',
    modules: ['AUDIT', 'MEMORY', 'IDENTITY', 'SYSTEM'],
    description: 'Immutable audit trail construction with forensic timeline reconstruction',
    emergentProperty: 'Court-admissible digital evidence generation',
    tier: 'enterprise',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-005',
  },
  {
    id: 'cp-capacity-prediction-chain',
    name: 'Capacity Prediction Chain',
    modules: ['SYSTEM', 'VISION', 'ECONOMY', 'CORTEX'],
    description: 'Multi-horizon capacity prediction with automated scaling recommendations',
    emergentProperty: 'Proactive capacity management eliminating reactive scaling',
    tier: 'enterprise',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-006',
  },
  {
    id: 'cp-cross-deployment-sync',
    name: 'Cross-Deployment Sync Pipeline',
    modules: ['RELAY', 'MEMORY', 'SYSTEM', 'CORTEX'],
    description: 'Synchronized state propagation across geographically distributed deployments',
    emergentProperty: 'Eventually-consistent global state without conflicts',
    tier: 'enterprise',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-007',
  },
  {
    id: 'cp-regulatory-autopilot',
    name: 'Regulatory Autopilot Pipeline',
    modules: ['AUDIT', 'DECODE', 'CORTEX', 'RELAY'],
    description: 'Monitors regulatory changes and auto-generates compliance adjustment plans',
    emergentProperty: 'Zero-lag regulatory adaptation',
    tier: 'enterprise',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-008',
  },
  // ── NEW ENTERPRISE (8 additions) ──
  {
    id: 'cp-privilege-escalation-sentinel',
    name: 'Privilege Escalation Sentinel',
    modules: ['IDENTITY', 'DEFENSE', 'AUDIT', 'CORTEX'],
    description: 'Detects anomalous privilege escalation patterns and auto-revokes before breach completion',
    emergentProperty: 'Real-time privilege abuse prevention',
    tier: 'enterprise',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-009',
  },
  {
    id: 'cp-data-residency-enforcer',
    name: 'Data Residency Enforcer',
    modules: ['MEMORY', 'AUDIT', 'RELAY', 'IDENTITY'],
    description: 'Guarantees data never leaves designated geographic or logical boundaries',
    emergentProperty: 'Provable data sovereignty compliance',
    tier: 'enterprise',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-010',
  },
  {
    id: 'cp-org-knowledge-graph-weaver',
    name: 'Org Knowledge Graph Weaver',
    modules: ['BRAIN', 'MEMORY', 'CORTEX', 'VISION'],
    description: 'Constructs and maintains a living knowledge graph across all organizational units',
    emergentProperty: 'Emergent organizational intelligence from siloed data',
    tier: 'enterprise',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-011',
  },
  {
    id: 'cp-incident-replay-simulator',
    name: 'Incident Replay Simulator',
    modules: ['SYSTEM', 'DEFENSE', 'VISION', 'AUDIT'],
    description: 'Reconstructs and replays past incidents in sandbox to test improved responses',
    emergentProperty: 'Retrospective defense improvement through simulation',
    tier: 'enterprise',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-012',
  },
  {
    id: 'cp-cost-attribution-fabric',
    name: 'Cost Attribution Fabric',
    modules: ['ECONOMY', 'AUDIT', 'IDENTITY', 'VISION'],
    description: 'Attributes every cent of compute cost to specific users, teams, and workflows',
    emergentProperty: 'Granular cost accountability across the organization',
    tier: 'enterprise',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-013',
  },
  {
    id: 'cp-federated-learning-mesh',
    name: 'Federated Learning Mesh',
    modules: ['BRAIN', 'RELAY', 'DEFENSE', 'CORTEX'],
    description: 'Cross-deployment learning without raw data leaving tenant boundaries',
    emergentProperty: 'Privacy-preserving collective intelligence',
    tier: 'enterprise',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-014',
  },
  {
    id: 'cp-executive-decision-ledger',
    name: 'Executive Decision Ledger',
    modules: ['AUDIT', 'CORTEX', 'MEMORY', 'IDENTITY'],
    description: 'Records every autonomous decision with full causal justification for board-level review',
    emergentProperty: 'Boardroom-ready AI accountability',
    tier: 'enterprise',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-015',
  },
  {
    id: 'cp-disaster-recovery-orchestrator',
    name: 'Disaster Recovery Orchestrator',
    modules: ['SYSTEM', 'RELAY', 'MEMORY', 'DEFENSE'],
    description: 'Autonomous multi-region failover with zero data loss and minimal recovery time',
    emergentProperty: 'Sub-minute disaster recovery without human intervention',
    tier: 'enterprise',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-ent-016',
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ARCHITECT PIPELINES (36) — Premium sealed workflows ($79/mo)
// ═══════════════════════════════════════════════════════════════════════════════

const ARCHITECT_PIPELINES: CrystallizedPipeline[] = [
  {
    id: 'cp-threat-prediction-chain',
    name: 'Threat Prediction Chain',
    modules: ['DEFENSE', 'VISION', 'BRAIN'],
    description: 'Predict security threats from behavioral patterns before exploitation occurs',
    emergentProperty: 'Pre-incident threat neutralization',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-001',
  },
  {
    id: 'cp-semantic-refactoring-pipeline',
    name: 'Semantic Refactoring Pipeline',
    modules: ['ENCODE', 'BRAIN', 'CORTEX'],
    description: 'Behavior-preserving code transformation with formal verification',
    emergentProperty: 'Risk-free codebase modernization',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-002',
  },
  {
    id: 'cp-cross-module-orchestration',
    name: 'Cross-Module Orchestration',
    modules: ['CORTEX', 'BRAIN', 'NEXUS', 'VISION'],
    description: 'Multi-module workflow composition with emergent capability discovery',
    emergentProperty: 'Capabilities beyond individual module sum',
    tier: 'architect',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-003',
  },
  {
    id: 'cp-zero-day-synthesis-chain',
    name: 'Zero-Day Synthesis Chain',
    modules: ['DEFENSE', 'DREAM', 'ENCODE'],
    description: 'Synthesize novel attack signatures from partial behavioral indicators',
    emergentProperty: 'Pre-signature threat pattern generation',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-004',
  },
  {
    id: 'cp-knowledge-distillation-pipeline',
    name: 'Knowledge Distillation Pipeline',
    modules: ['BRAIN', 'MEMORY', 'CORTEX'],
    description: 'Compress large knowledge bases into compact high-fidelity representations',
    emergentProperty: 'Lossless knowledge compression for fast retrieval',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-005',
  },
  {
    id: 'cp-adaptive-delivery-optimizer',
    name: 'Adaptive Delivery Optimizer',
    modules: ['RELAY', 'VISION', 'DECODE'],
    description: 'Per-recipient delivery strategy optimization based on engagement history',
    emergentProperty: 'Maximum delivery effectiveness per-channel',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-006',
  },
  {
    id: 'cp-chaos-resilience-pipeline',
    name: 'Chaos Resilience Pipeline',
    modules: ['SANDBOX', 'SYSTEM', 'DEFENSE', 'VISION'],
    description: 'Controlled chaos experiments that discover failure modes before production',
    emergentProperty: 'Proactive resilience through controlled failure injection',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-007',
  },
  {
    id: 'cp-identity-trust-fabric',
    name: 'Identity Trust Fabric',
    modules: ['IDENTITY', 'DEFENSE', 'AUDIT'],
    description: 'Continuous identity verification with trust decay modeling',
    emergentProperty: 'Zero-trust authentication beyond session boundaries',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-008',
  },
  {
    id: 'cp-cognitive-load-optimizer',
    name: 'Cognitive Load Optimizer',
    modules: ['VISION', 'CORTEX', 'DECODE'],
    description: 'Detect and reduce cognitive overload across user interfaces and AI interactions',
    emergentProperty: 'Optimal information density per-user',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-009',
  },
  {
    id: 'cp-pipeline-fusion-engine',
    name: 'Pipeline Fusion Engine',
    modules: ['CORTEX', 'BRAIN', 'DREAM'],
    description: 'Merge compatible pipelines into optimized super-pipelines',
    emergentProperty: 'Emergent efficiency through pipeline consolidation',
    tier: 'architect',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-010',
  },
  {
    id: 'cp-memory-provenance-chain',
    name: 'Memory Provenance Chain',
    modules: ['MEMORY', 'AUDIT', 'BRAIN'],
    description: 'Track origin and transformation of every memory entry for full auditability',
    emergentProperty: 'Complete knowledge lineage tracking',
    tier: 'architect',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-011',
  },
  {
    id: 'cp-provider-arbitrage-pipeline',
    name: 'Provider Arbitrage Pipeline',
    modules: ['NEXUS', 'ECONOMY', 'VISION'],
    description: 'Exploit cross-provider price differentials while maintaining quality guarantees',
    emergentProperty: 'Optimal cost-quality balance across providers',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-012',
  },
  {
    id: 'cp-blast-radius-containment',
    name: 'Blast Radius Containment',
    modules: ['DEFENSE', 'CORTEX', 'SYSTEM'],
    description: 'Automatically contain security incidents by isolating affected module chains',
    emergentProperty: 'Instantaneous failure domain isolation',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-013',
  },
  {
    id: 'cp-behavioral-drift-detector',
    name: 'Behavioral Drift Detector',
    modules: ['VISION', 'BRAIN', 'SYSTEM'],
    description: 'Detect when system or user behavior drifts from established baselines',
    emergentProperty: 'Early warning for behavioral anomalies',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-014',
  },
  {
    id: 'cp-dynamic-pricing-pipeline',
    name: 'Dynamic Pricing Pipeline',
    modules: ['ECONOMY', 'VISION', 'CORTEX'],
    description: 'Real-time resource pricing based on demand, availability, and quality metrics',
    emergentProperty: 'Market-optimal internal pricing',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-015',
  },
  {
    id: 'cp-empathic-interaction-chain',
    name: 'Empathic Interaction Chain',
    modules: ['DECODE', 'BRAIN', 'VISION'],
    description: 'Calibrate AI empathy and personality based on real-time user emotional state',
    emergentProperty: 'Emotionally intelligent interaction adaptation',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-016',
  },
  {
    id: 'cp-semantic-debt-scanner',
    name: 'Semantic Debt Scanner',
    modules: ['ENCODE', 'BRAIN', 'VISION'],
    description: 'Detect code that works but no longer reflects original intent',
    emergentProperty: 'Intent-drift detection beyond static analysis',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-017',
  },
  {
    id: 'cp-innovation-scoring-pipeline',
    name: 'Innovation Scoring Pipeline',
    modules: ['DREAM', 'VISION', 'CORTEX'],
    description: 'Score creative outputs by novelty, feasibility, and impact potential',
    emergentProperty: 'Quantified innovation assessment',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-018',
  },
  // ── NEW ARCHITECT (18 additions) ──
  {
    id: 'cp-multi-modal-reasoning-chain',
    name: 'Multi-Modal Reasoning Chain',
    modules: ['BRAIN', 'DECODE', 'VISION', 'CORTEX'],
    description: 'Fuses text, image, and structured data into unified reasoning across modalities',
    emergentProperty: 'Cross-modal insight synthesis',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-019',
  },
  {
    id: 'cp-autonomous-rollback-authority',
    name: 'Autonomous Rollback Authority',
    modules: ['SYSTEM', 'CORTEX', 'AUDIT', 'ENCODE'],
    description: 'Detects regressions and autonomously rolls back to last-known-good state',
    emergentProperty: 'Self-healing deployment with zero-downtime rollback',
    tier: 'architect',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-020',
  },
  {
    id: 'cp-signal-noise-separator',
    name: 'Signal-Noise Separator',
    modules: ['DECODE', 'BRAIN', 'CORTEX'],
    description: 'Strips noise from high-volume data streams to surface actionable signals only',
    emergentProperty: 'Pure signal extraction from chaotic inputs',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-021',
  },
  {
    id: 'cp-dependency-risk-mapper',
    name: 'Dependency Risk Mapper',
    modules: ['ENCODE', 'VISION', 'DEFENSE'],
    description: 'Maps transitive dependency risks and predicts supply chain vulnerabilities',
    emergentProperty: 'Proactive supply chain risk mitigation',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-022',
  },
  {
    id: 'cp-adaptive-rate-limiter',
    name: 'Adaptive Rate Limiter',
    modules: ['NEXUS', 'DEFENSE', 'VISION'],
    description: 'Dynamically adjusts rate limits based on real-time traffic patterns and trust scores',
    emergentProperty: 'Intelligent throttling that protects without blocking legitimate traffic',
    tier: 'architect',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-023',
  },
  {
    id: 'cp-knowledge-gap-discoverer',
    name: 'Knowledge Gap Discoverer',
    modules: ['BRAIN', 'DREAM', 'VISION'],
    description: 'Identifies what the system does not know and prioritizes knowledge acquisition',
    emergentProperty: 'Self-aware ignorance mapping',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-024',
  },
  {
    id: 'cp-performance-regression-oracle',
    name: 'Performance Regression Oracle',
    modules: ['VISION', 'ENCODE', 'SYSTEM'],
    description: 'Predicts performance regressions from code changes before deployment',
    emergentProperty: 'Pre-deploy performance guarantee',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-025',
  },
  {
    id: 'cp-intent-disambiguation-engine',
    name: 'Intent Disambiguation Engine',
    modules: ['DECODE', 'BRAIN', 'CORTEX'],
    description: 'Resolves ambiguous user intents through multi-hypothesis scoring',
    emergentProperty: 'High-confidence intent resolution from vague inputs',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-026',
  },
  {
    id: 'cp-workflow-bottleneck-eliminator',
    name: 'Workflow Bottleneck Eliminator',
    modules: ['VISION', 'CORTEX', 'SYSTEM'],
    description: 'Identifies and restructures workflow bottlenecks in real-time',
    emergentProperty: 'Continuous throughput optimization',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-027',
  },
  {
    id: 'cp-cross-project-learning-bridge',
    name: 'Cross-Project Learning Bridge',
    modules: ['MEMORY', 'BRAIN', 'CORTEX'],
    description: 'Transfers learned patterns between projects without leaking project-specific data',
    emergentProperty: 'Privacy-safe knowledge portability',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-028',
  },
  {
    id: 'cp-anomaly-fingerprinting-chain',
    name: 'Anomaly Fingerprinting Chain',
    modules: ['VISION', 'DEFENSE', 'BRAIN'],
    description: 'Creates unique fingerprints for anomaly types enabling instant future recognition',
    emergentProperty: 'One-shot anomaly learning',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-029',
  },
  {
    id: 'cp-resource-contention-arbiter',
    name: 'Resource Contention Arbiter',
    modules: ['NEXUS', 'ECONOMY', 'CORTEX'],
    description: 'Resolves competing resource claims using value-weighted priority scoring',
    emergentProperty: 'Fair resource allocation under contention',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-030',
  },
  {
    id: 'cp-semantic-versioning-guardian',
    name: 'Semantic Versioning Guardian',
    modules: ['ENCODE', 'BRAIN', 'AUDIT'],
    description: 'Automatically determines semantic version bumps from behavioral change analysis',
    emergentProperty: 'Human-free semantic versioning',
    tier: 'architect',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-031',
  },
  {
    id: 'cp-feedback-loop-detector',
    name: 'Feedback Loop Detector',
    modules: ['VISION', 'CORTEX', 'BRAIN'],
    description: 'Identifies runaway feedback loops before they destabilize system behavior',
    emergentProperty: 'Early termination of dangerous positive feedback',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-032',
  },
  {
    id: 'cp-capability-maturity-scorer',
    name: 'Capability Maturity Scorer',
    modules: ['VISION', 'BRAIN', 'CORTEX'],
    description: 'Scores each capability on a maturity ladder and recommends graduation paths',
    emergentProperty: 'Quantified capability lifecycle management',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-033',
  },
  {
    id: 'cp-synthetic-benchmark-generator',
    name: 'Synthetic Benchmark Generator',
    modules: ['ENCODE', 'DREAM', 'VISION'],
    description: 'Generates domain-specific benchmarks from production patterns for realistic testing',
    emergentProperty: 'Production-representative testing without production data',
    tier: 'architect',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-034',
  },
  {
    id: 'cp-contextual-retry-strategist',
    name: 'Contextual Retry Strategist',
    modules: ['NEXUS', 'BRAIN', 'VISION'],
    description: 'Selects retry strategies based on failure context rather than fixed backoff',
    emergentProperty: 'Intelligent retry that adapts to failure cause',
    tier: 'architect',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-035',
  },
  {
    id: 'cp-impact-radius-predictor',
    name: 'Impact Radius Predictor',
    modules: ['CORTEX', 'VISION', 'SYSTEM'],
    description: 'Predicts the blast radius of any proposed change before execution',
    emergentProperty: 'Pre-commit impact visualization',
    tier: 'architect',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-arc-036',
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CREATOR PIPELINES (28) — Builder-friendly sealed workflows ($29/mo)
// ═══════════════════════════════════════════════════════════════════════════════

const CREATOR_PIPELINES: CrystallizedPipeline[] = [
  {
    id: 'cp-smart-event-routing',
    name: 'Smart Event Routing',
    modules: ['RIPPLE', 'BRAIN', 'DECODE'],
    description: 'Route events to optimal handlers based on semantic meaning, not just type',
    emergentProperty: 'Intent-aware event distribution',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-001',
  },
  {
    id: 'cp-memory-consolidation-pipeline',
    name: 'Memory Consolidation Pipeline',
    modules: ['BRAIN', 'MEMORY', 'DREAM'],
    description: 'Merge redundant memories and strengthen important ones during idle time',
    emergentProperty: 'Self-organizing knowledge optimization',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-002',
  },
  {
    id: 'cp-cost-anomaly-detection',
    name: 'Cost Anomaly Detection Pipeline',
    modules: ['ECONOMY', 'VISION', 'RELAY'],
    description: 'Predict cost spikes and alert before budgets are impacted',
    emergentProperty: 'Preemptive cost containment',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-003',
  },
  {
    id: 'cp-webhook-intelligence-chain',
    name: 'Webhook Intelligence Chain',
    modules: ['RELAY', 'DEFENSE', 'BRAIN'],
    description: 'Auto-retry, deduplicate, and validate webhooks with intelligent failure recovery',
    emergentProperty: 'Guaranteed webhook delivery with zero duplicates',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-004',
  },
  {
    id: 'cp-test-oracle-generator',
    name: 'Test Oracle Generator',
    modules: ['ENCODE', 'DECODE', 'BRAIN'],
    description: 'Generate expected test outcomes from specification analysis',
    emergentProperty: 'Zero-effort test creation from specs',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-005',
  },
  {
    id: 'cp-latency-prediction-router',
    name: 'Latency Prediction Router',
    modules: ['NEXUS', 'VISION', 'BRAIN'],
    description: 'Predict provider response times and pre-route to fastest option',
    emergentProperty: 'Minimal-latency request routing',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-006',
  },
  {
    id: 'cp-drift-correction-pipeline',
    name: 'Drift Correction Pipeline',
    modules: ['ENCODE', 'VISION', 'BRAIN'],
    description: 'Detect implementation drift from specs and auto-generate corrective patches',
    emergentProperty: 'Self-correcting codebase alignment',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-007',
  },
  {
    id: 'cp-reputation-scoring-chain',
    name: 'Reputation Scoring Chain',
    modules: ['DEFENSE', 'IDENTITY', 'VISION'],
    description: 'Score request sources by behavioral reputation to prioritize trusted traffic',
    emergentProperty: 'Trust-weighted request processing',
    tier: 'creator',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-008',
  },
  {
    id: 'cp-user-journey-reconstructor',
    name: 'User Journey Reconstructor',
    modules: ['VISION', 'DECODE', 'BRAIN'],
    description: 'Reconstruct complete user journeys to find drop-off points',
    emergentProperty: 'Full-path user behavior visibility',
    tier: 'creator',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-009',
  },
  {
    id: 'cp-schema-evolution-guard',
    name: 'Schema Evolution Guard',
    modules: ['ENCODE', 'INTEGRATION', 'BRAIN'],
    description: 'Validate schema changes against downstream consumers before deployment',
    emergentProperty: 'Zero-downtime schema migrations',
    tier: 'creator',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-010',
  },
  {
    id: 'cp-context-window-optimizer',
    name: 'Context Window Optimizer',
    modules: ['BRAIN', 'DECODE', 'NEXUS'],
    description: 'Compress and prioritize context to maximize AI response quality',
    emergentProperty: 'Maximum signal density per token',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-011',
  },
  {
    id: 'cp-connector-health-monitor',
    name: 'Connector Health Monitor',
    modules: ['INTEGRATION', 'VISION', 'RELAY'],
    description: 'Predict connector failures before they impact integrations',
    emergentProperty: 'Pre-failure connector remediation',
    tier: 'creator',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-012',
  },
  {
    id: 'cp-pattern-consolidation-pipeline',
    name: 'Pattern Consolidation Pipeline',
    modules: ['DREAM', 'BRAIN', 'ENCODE'],
    description: 'Consolidate repeated patterns into reusable optimized templates',
    emergentProperty: 'Automatic template generation from usage patterns',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-013',
  },
  {
    id: 'cp-usage-forecasting-pipeline',
    name: 'Usage Forecasting Pipeline',
    modules: ['ECONOMY', 'VISION', 'BRAIN'],
    description: 'Forecast usage patterns and recommend capacity adjustments',
    emergentProperty: 'Proactive resource planning',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-014',
  },
  // ── NEW CREATOR (14 additions) ──
  {
    id: 'cp-smart-cache-invalidator',
    name: 'Smart Cache Invalidator',
    modules: ['BRAIN', 'MEMORY', 'VISION'],
    description: 'Predicts which cache entries will become stale and pre-invalidates them',
    emergentProperty: 'Zero-stale-read caching',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-015',
  },
  {
    id: 'cp-error-context-enricher',
    name: 'Error Context Enricher',
    modules: ['VISION', 'BRAIN', 'DECODE'],
    description: 'Attaches rich contextual metadata to errors for instant root cause identification',
    emergentProperty: 'One-glance error diagnosis',
    tier: 'creator',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-016',
  },
  {
    id: 'cp-prompt-quality-scorer',
    name: 'Prompt Quality Scorer',
    modules: ['DECODE', 'BRAIN', 'VISION'],
    description: 'Scores prompt quality and suggests improvements before execution',
    emergentProperty: 'Higher AI output quality through input optimization',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-017',
  },
  {
    id: 'cp-api-compatibility-checker',
    name: 'API Compatibility Checker',
    modules: ['INTEGRATION', 'ENCODE', 'BRAIN'],
    description: 'Validates API changes against all known consumers before release',
    emergentProperty: 'Breaking-change prevention across integrations',
    tier: 'creator',
    category: 'compliance',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-018',
  },
  {
    id: 'cp-token-budget-optimizer',
    name: 'Token Budget Optimizer',
    modules: ['ECONOMY', 'BRAIN', 'NEXUS'],
    description: 'Allocates token budgets across concurrent tasks for maximum total value',
    emergentProperty: 'Value-maximized token spending',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-019',
  },
  {
    id: 'cp-session-handoff-chain',
    name: 'Session Handoff Chain',
    modules: ['MEMORY', 'BRAIN', 'DECODE'],
    description: 'Transfers full session context between agents without information loss',
    emergentProperty: 'Seamless multi-agent session continuity',
    tier: 'creator',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-020',
  },
  {
    id: 'cp-response-calibration-pipeline',
    name: 'Response Calibration Pipeline',
    modules: ['DECODE', 'VISION', 'BRAIN'],
    description: 'Calibrates AI response length, tone, and detail level to user preferences',
    emergentProperty: 'Personalized response formatting',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-021',
  },
  {
    id: 'cp-integration-health-dashboard',
    name: 'Integration Health Dashboard Chain',
    modules: ['INTEGRATION', 'VISION', 'SYSTEM'],
    description: 'Aggregates health signals from all connected integrations into a unified view',
    emergentProperty: 'Single-pane integration monitoring',
    tier: 'creator',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-022',
  },
  {
    id: 'cp-smart-deduplication-engine',
    name: 'Smart Deduplication Engine',
    modules: ['BRAIN', 'MEMORY', 'ENCODE'],
    description: 'Detects semantic duplicates across data stores even when syntactically different',
    emergentProperty: 'Meaning-aware deduplication',
    tier: 'creator',
    category: 'optimization',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-023',
  },
  {
    id: 'cp-auto-documentation-chain',
    name: 'Auto-Documentation Chain',
    modules: ['ENCODE', 'BRAIN', 'DECODE'],
    description: 'Generates and maintains documentation from code behavior, not just comments',
    emergentProperty: 'Living documentation that never goes stale',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-024',
  },
  {
    id: 'cp-graceful-degradation-router',
    name: 'Graceful Degradation Router',
    modules: ['NEXUS', 'SYSTEM', 'BRAIN'],
    description: 'Routes requests to fallback providers with degraded but functional capabilities',
    emergentProperty: 'Service continuity under provider failures',
    tier: 'creator',
    category: 'orchestration',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-025',
  },
  {
    id: 'cp-metric-correlation-finder',
    name: 'Metric Correlation Finder',
    modules: ['VISION', 'BRAIN', 'ECONOMY'],
    description: 'Discovers hidden correlations between metrics that humans miss',
    emergentProperty: 'Non-obvious metric relationship discovery',
    tier: 'creator',
    category: 'observability',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-026',
  },
  {
    id: 'cp-input-sanitization-chain',
    name: 'Input Sanitization Chain',
    modules: ['DEFENSE', 'DECODE', 'BRAIN'],
    description: 'Multi-layer input sanitization that catches injection vectors standard filters miss',
    emergentProperty: 'Deep sanitization beyond pattern matching',
    tier: 'creator',
    category: 'security',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-027',
  },
  {
    id: 'cp-output-confidence-calibrator',
    name: 'Output Confidence Calibrator',
    modules: ['BRAIN', 'VISION', 'DECODE'],
    description: 'Calibrates confidence scores so stated certainty matches actual accuracy',
    emergentProperty: 'Trustworthy confidence reporting',
    tier: 'creator',
    category: 'intelligence',
    isSealed: true,
    discoveredFrom: 'mesh-receipt-cre-028',
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// COMBINED REGISTRY
// ═══════════════════════════════════════════════════════════════════════════════

export const CRYSTALLIZED_PIPELINES: readonly CrystallizedPipeline[] = Object.freeze([
  ...CMPSBL_PIPELINES,
  ...ENTERPRISE_PIPELINES,
  ...ARCHITECT_PIPELINES,
  ...CREATOR_PIPELINES,
]);

export const CRYSTALLIZED_PIPELINE_COUNT = CRYSTALLIZED_PIPELINES.length; // 100

export const CRYSTALLIZED_PIPELINE_TIER_COUNTS = {
  cmpsbl: CMPSBL_PIPELINES.length,        // 20
  enterprise: ENTERPRISE_PIPELINES.length, // 16
  architect: ARCHITECT_PIPELINES.length,   // 36
  creator: CREATOR_PIPELINES.length,       // 28
} as const;

/** Get pipelines by tier */
export function getPipelinesByTier(tier: PipelineTier): CrystallizedPipeline[] {
  return CRYSTALLIZED_PIPELINES.filter(p => p.tier === tier);
}

/** Get pipelines by module */
export function getPipelinesByModule(module: string): CrystallizedPipeline[] {
  return CRYSTALLIZED_PIPELINES.filter(p => p.modules.includes(module));
}

/** Get public-safe pipelines (everything except CMPSBL) */
export function getPublicPipelines(): CrystallizedPipeline[] {
  return CRYSTALLIZED_PIPELINES.filter(p => p.tier !== 'cmpsbl');
}

export const CRYSTALLIZED_REGISTRY_VERSION = '10.8.0' as const;
