/**
 * Bot Exporter — ZIP Bundle Generator
 * Creates exportable cognitive packages for marketplace delivery
 */

import JSZip from 'jszip';
import { BotClass, getClassById, MEMORY_MODES, LEARNING_MODES } from './botClasses';
import { generateLicenseHTML, generateReadmeHTML } from '@/lib/export/elegant-html-docs';
import { generateProductDetailsHTML } from '@/lib/export/product-details-page';
import { generateIntegrationGuide } from '@/lib/export/integration-guide-generator';

export interface ExportConfig {
  id: string;
  name: string;
  class: string;
  version: string;
  memoryMode: string;
  learningModes: string[];
  capabilities: string[];
  providers: string[];
  dreamEnabled: boolean;
  graphEnabled: boolean;
}

export interface ExportBundle {
  blob: Blob;
  filename: string;
  files: string[];
}

function generateBotYaml(config: ExportConfig): string {
  return `# Cognitive Bot Configuration
# Generated by CMPSBL® Forge D-Mode
# Version: ${config.version}

name: "${config.name}"
class: ${config.class}
version: "${config.version}"

memory:
  mode: ${config.memoryMode}
  ${config.memoryMode === 'Persistent' ? 'tables:\n    - brain_memory_hot\n    - brain_memory_cold' : ''}
  ${config.memoryMode === 'CognitiveGraph' ? 'graph_enabled: true' : ''}
  ${config.memoryMode === 'DreamRetention' ? 'dream_retention: true' : ''}

learning:
  modes:
${config.learningModes.map(m => `    - ${m}`).join('\n')}
  dream_enabled: ${config.dreamEnabled}
  graph_enabled: ${config.graphEnabled}

providers:
${config.providers.map(p => `  - ${p.toLowerCase()}`).join('\n')}

capabilities:
${config.capabilities.map(c => `  - "${c}"`).join('\n')}

nexus:
  fallback_enabled: true
  max_retries: 3
  timeout_ms: 30000

runtime:
  api_endpoint: /api/c/${config.id}/run
  learn_endpoint: /api/c/${config.id}/learn
  status_endpoint: /api/c/${config.id}/status
`;
}

function generateBotCode(config: ExportConfig): string {
  const botClass = getClassById(config.class);
  const selectedCaps = botClass?.capabilities.filter(c => config.capabilities.includes(c.id)) || [];

  const capabilityMethods = selectedCaps.map(cap => `
  async ${cap.methodName}(input: unknown): Promise<unknown> {
    // ${cap.description}
    return await this.nexus.text(\`${cap.name}: \${JSON.stringify(input)}\`);
  }`).join('\n');

  return `/**
 * ${config.name} — ${config.class} Cognitive Bot
 * Generated by CMPSBL® Forge D-Mode
 * Version: ${config.version}
 */

import { substrate, brain, nexus, dream } from '@cmpsbl/sdk';

interface CognitiveMemory {
  store: (key: string, value: unknown) => Promise<void>;
  retrieve: (key: string) => Promise<unknown>;
  clear: () => Promise<void>;
}

class ${config.name.replace(/[^a-zA-Z0-9]/g, '')}Cognitive {
  private nexus = nexus;
  private brain = brain;
  private dream = dream;
  private memory: CognitiveMemory;
  private learningModes: string[] = ${JSON.stringify(config.learningModes)};
  
  constructor() {
    this.memory = this.initMemory('${config.memoryMode}');
    ${config.dreamEnabled ? 'this.initDreamCycle();' : ''}
    ${config.graphEnabled ? 'this.initGraph();' : ''}
  }
  
  private initMemory(mode: string): CognitiveMemory {
    const store: Record<string, unknown> = {};
    
    switch (mode) {
      case 'Stateless':
        return {
          store: async () => {},
          retrieve: async () => null,
          clear: async () => {},
        };
      case 'Episodic':
        return {
          store: async (k, v) => { store[k] = v; },
          retrieve: async (k) => store[k],
          clear: async () => { Object.keys(store).forEach(k => delete store[k]); },
        };
      case 'Persistent':
      case 'CognitiveGraph':
      case 'DreamRetention':
        return {
          store: async (k, v) => { 
            await brain.remember(JSON.stringify({ key: k, value: v }), 'bot_memory');
          },
          retrieve: async (k) => {
            const result = await brain.recall(k, 1);
            return result.data;
          },
          clear: async () => {},
        };
      default:
        return {
          store: async () => {},
          retrieve: async () => null,
          clear: async () => {},
        };
    }
  }
  
  ${config.dreamEnabled ? `
  private async initDreamCycle() {
    // Initialize dream-based learning
    console.log('[${config.name}] Dream cycle initialized');
  }` : ''}
  
  ${config.graphEnabled ? `
  private async initGraph() {
    // Initialize knowledge graph
    await brain.graphBuild();
    console.log('[${config.name}] Knowledge graph initialized');
  }` : ''}
  ${capabilityMethods}
  
  async run(task: string): Promise<string> {
    console.log(\`[\${this.constructor.name}] Running: \${task}\`);
    
    const result = await this.nexus.text(task);
    
    if (this.learningModes.includes('task')) {
      await this.learn(task, result);
    }
    
    if (result.success && result.data) {
      return String(result.data);
    }
    
    return 'Task processing failed';
  }
  
  async learn(context: string, result: unknown): Promise<void> {
    await brain.learn(JSON.stringify({ context, result }), 'cognitive_task');
  }
  
  async status(): Promise<object> {
    return {
      name: '${config.name}',
      class: '${config.class}',
      version: '${config.version}',
      memoryMode: '${config.memoryMode}',
      learningModes: this.learningModes,
      dreamEnabled: ${config.dreamEnabled},
      graphEnabled: ${config.graphEnabled},
      ready: true,
    };
  }
}

export const cognitive = new ${config.name.replace(/[^a-zA-Z0-9]/g, '')}Cognitive();
export default cognitive;
`;
}

function generateReadme(config: ExportConfig): string {
  return `# ${config.name}

A **${config.class}** cognitive generated by CMPSBL® Forge D-Mode.

## Version

\`${config.version}\`

## Configuration

- **Class**: ${config.class}
- **Memory Mode**: ${config.memoryMode}
- **Learning Modes**: ${config.learningModes.join(', ')}
- **Dream Enabled**: ${config.dreamEnabled ? 'Yes' : 'No'}
- **Graph Enabled**: ${config.graphEnabled ? 'Yes' : 'No'}
- **Providers**: ${config.providers.join(', ')}

## Quick Start

\`\`\`typescript
import cognitive from './src/index';

// Run a task
const result = await cognitive.run('Your task here');
console.log(result);

// Check status
const status = await cognitive.status();
console.log(status);
\`\`\`

## API Endpoints

When deployed as a hosted runtime:

- \`POST /api/c/${config.id}/run\` - Execute tasks
- \`POST /api/c/${config.id}/learn\` - Submit learning data
- \`GET /api/c/${config.id}/status\` - Get cognitive status

## Capabilities

${config.capabilities.map(c => `- ${c}`).join('\n')}

## Memory

This cognitive uses **${config.memoryMode}** memory mode.

## Providers

Configured AI providers through Nexus:
${config.providers.map(p => `- ${p}`).join('\n')}

---
Generated by CMPSBL® Cognitive Forge D-Mode
`;
}

function generateUsageMd(config: ExportConfig): string {
  return `# Usage Guide — ${config.name}

## Installation

\`\`\`bash
npm install
npm start
\`\`\`

## Environment Setup

Create a \`.env\` file:

\`\`\`env
SUBSTRATE_URL=https://your-substrate-url
SUBSTRATE_KEY=your-anon-key
\`\`\`

## Basic Usage

\`\`\`typescript
import cognitive from './src/index';

// Run a task
const result = await cognitive.run('Analyze the market trends for Q1 2026');

// Access specific capabilities
${config.capabilities.slice(0, 2).map(c => `// await cognitive.${c.split('.').pop()}(...);`).join('\n')}
\`\`\`

## Memory Modes

Current mode: **${config.memoryMode}**

${MEMORY_MODES.map(m => `- **${m.name}**: ${m.description}`).join('\n')}

## Learning Modes

Active modes: ${config.learningModes.join(', ')}

${LEARNING_MODES.map(m => `- **${m.name}**: ${m.description}`).join('\n')}

## Upgrade Path

To upgrade this cognitive:
1. Export a new version from Forge
2. Merge configuration changes
3. Run migration scripts if needed
4. Deploy to runtime
`;
}

function generateApiMd(config: ExportConfig): string {
  return `# API Reference — ${config.name}

## Endpoints

### Run Task

\`\`\`
POST /api/c/${config.id}/run
\`\`\`

**Request:**
\`\`\`json
{
  "task": "Your task description",
  "context": {},
  "options": {
    "timeout": 30000,
    "provider": "groq"
  }
}
\`\`\`

**Response:**
\`\`\`json
{
  "success": true,
  "result": "Task output",
  "metadata": {
    "duration_ms": 1234,
    "provider": "groq",
    "tokens_used": 500
  }
}
\`\`\`

### Learn

\`\`\`
POST /api/c/${config.id}/learn
\`\`\`

**Request:**
\`\`\`json
{
  "content": "Learning content",
  "source": "user_feedback",
  "confidence": 0.9
}
\`\`\`

### Status

\`\`\`
GET /api/c/${config.id}/status
\`\`\`

**Response:**
\`\`\`json
{
  "name": "${config.name}",
  "class": "${config.class}",
  "version": "${config.version}",
  "status": "active",
  "metrics": {
    "runs_today": 42,
    "success_rate": 0.95,
    "avg_latency_ms": 850
  }
}
\`\`\`

## Error Codes

| Code | Description |
|------|-------------|
| 400 | Invalid request |
| 401 | Authentication required |
| 429 | Rate limited |
| 500 | Internal error |

## Rate Limits

- 100 requests per minute per cognitive
- 10,000 requests per day per cognitive
`;
}

function generatePackageJson(config: ExportConfig): string {
  return JSON.stringify({
    name: `@cognitive/${config.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
    version: config.version,
    description: `${config.class} Cognitive - ${config.name}`,
    main: 'src/index.ts',
    scripts: {
      start: 'ts-node src/index.ts',
      build: 'tsc',
      test: 'vitest',
      deploy: 'npm run build && npx substrate deploy',
    },
    dependencies: {
      '@cmpsbl/sdk': '^2026.01',
    },
    devDependencies: {
      typescript: '^5.0.0',
      'ts-node': '^10.9.0',
      vitest: '^1.0.0',
    },
    keywords: ['cognitive', 'ai', 'bot', config.class.toLowerCase(), 'cmpsbl'],
    author: 'CMPSBL® Forge',
    license: 'MIT',
  }, null, 2);
}

function generateLicense(): string {
  return `MIT License

Copyright (c) ${new Date().getFullYear()} CMPSBL®

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;
}

export async function createExportBundle(config: ExportConfig): Promise<ExportBundle> {
  const { serializeCmpsblManifest } = await import('@/lib/export/cmpsbl-manifest');
  const zip = new JSZip();
  
  // Root files
  zip.file('bot.yaml', generateBotYaml(config));
  zip.file('README.md', generateReadme(config));
  zip.file('package.json', generatePackageJson(config));
  zip.file('LICENSE', generateLicense());
  zip.file('LICENSE.html', generateLicenseHTML(config.name));
  zip.file('README.html', generateReadmeHTML({
    name: config.name,
    description: `${config.class} cognitive bot — ${config.capabilities.join(', ')}`,
    category: 'Cognitive Bot',
    version: config.version,
    modules: config.capabilities,
    files: [
      { name: 'bot.yaml', purpose: 'Bot configuration manifest' },
      { name: 'README.md / README.html', purpose: 'Documentation and quick-start guide' },
      { name: 'LICENSE / LICENSE.html', purpose: 'License terms' },
      { name: 'DETAILS.html', purpose: 'Product specification certificate' },
      { name: 'src/index.ts', purpose: 'Main bot entry point' },
      { name: 'docs/', purpose: 'Usage and API documentation' },
    ],
    quickStart: `# Install\nnpm install\n\n# Run\nimport bot from './src/index';\nconst result = await bot.run('Your task here');`,
  }));
  zip.file('DETAILS.html', generateProductDetailsHTML({
    name: config.name,
    subtitle: `${config.class} cognitive bot with ${config.capabilities.length} capabilities`,
    kind: 'agent',
    tier: 'pro',
    price: 'Included',
    version: config.version,
    capabilities: config.capabilities,
  }));
  zip.file('manifest.json', serializeCmpsblManifest({
    name: config.name,
    targets: ['typescript'],
    version: config.version,
    source: 'forge-cognitive',
  }));
  
  // Documentation
  const docs = zip.folder('docs');
  docs?.file('usage.md', generateUsageMd(config));
  docs?.file('api.md', generateApiMd(config));
  
  // Source code
  const src = zip.folder('src');
  src?.file('index.ts', generateBotCode(config));
  
  const files = [
    'bot.yaml',
    'README.md',
    'README.html',
    'package.json',
    'LICENSE',
    'LICENSE.html',
    'DETAILS.html',
    'manifest.json',
    'docs/usage.md',
    'docs/api.md',
    'src/index.ts',
  ];
  
  const blob = await zip.generateAsync({ type: 'blob' });
  const slug = config.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
  
  return {
    blob,
    filename: `${slug}-cognitive-v${config.version}.zip`,
    files,
  };
}

export function downloadBundle(bundle: ExportBundle): void {
  const url = URL.createObjectURL(bundle.blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = bundle.filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
