
INSERT INTO public.discovery_runs (id, status, total_candidates, accepted_count, scoring_version, dry_run, exploratory_mode)
VALUES ('f1a2b3c4-d5e6-7890-abcd-ef1234567890', 'completed', 132, 132, 'v21.0.0', false, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.discoveries (id, name, description, cjpi, module_chain, status, is_crown_jewel, vertical, crown_jewel_capabilities, category, tier, run_id, components)
SELECT * FROM (VALUES
  ('FIN-CJ-LEDGER-S1', 'LEDGER S-Tier #1', 'Double-Entry Invariant Enforcer', 97, ARRAY['LEDGER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"LEDGER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-LEDGER-S2', 'LEDGER S-Tier #2', 'Multi-Currency Reconciliation Matrix', 96, ARRAY['LEDGER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"LEDGER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-VAULT_FIN-S1', 'VAULT_FIN S-Tier #1', 'HSM-Grade Key Hierarchy Manager', 97, ARRAY['VAULT_FIN'], 'registry', true, 'fintech', '{"tier":"S","primitive":"VAULT_FIN"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-VAULT_FIN-S2', 'VAULT_FIN S-Tier #2', 'Multi-Sig Authorization Engine', 95, ARRAY['VAULT_FIN'], 'registry', true, 'fintech', '{"tier":"S","primitive":"VAULT_FIN"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TICKER-S1', 'TICKER S-Tier #1', 'Sub-Ms Price Feed Normalizer', 96, ARRAY['TICKER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TICKER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TICKER-S2', 'TICKER S-Tier #2', 'Order Book Depth Reconstructor', 95, ARRAY['TICKER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TICKER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-CLEARING-S1', 'CLEARING S-Tier #1', 'Multilateral Netting Optimizer', 97, ARRAY['CLEARING'], 'registry', true, 'fintech', '{"tier":"S","primitive":"CLEARING"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-CLEARING-S2', 'CLEARING S-Tier #2', 'T+0 Settlement Orchestrator', 96, ARRAY['CLEARING'], 'registry', true, 'fintech', '{"tier":"S","primitive":"CLEARING"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-RISKCORE-S1', 'RISKCORE S-Tier #1', 'Historical VaR Engine', 97, ARRAY['RISKCORE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"RISKCORE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-RISKCORE-S2', 'RISKCORE S-Tier #2', 'CVaR Tail Risk Decomposer', 96, ARRAY['RISKCORE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"RISKCORE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-PAYRAIL-S1', 'PAYRAIL S-Tier #1', 'Intelligent Payment Router', 97, ARRAY['PAYRAIL'], 'registry', true, 'fintech', '{"tier":"S","primitive":"PAYRAIL"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-PAYRAIL-S2', 'PAYRAIL S-Tier #2', 'FedNow Instant Settlement Adapter', 95, ARRAY['PAYRAIL'], 'registry', true, 'fintech', '{"tier":"S","primitive":"PAYRAIL"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TAXENGINE-S1', 'TAXENGINE S-Tier #1', 'Capital Gains Lot Optimizer', 96, ARRAY['TAXENGINE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TAXENGINE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TAXENGINE-S2', 'TAXENGINE S-Tier #2', 'Tax Loss Harvesting Strategist', 95, ARRAY['TAXENGINE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TAXENGINE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-MATCHBOOK-S1', 'MATCHBOOK S-Tier #1', 'Price-Time Priority Kernel', 97, ARRAY['MATCHBOOK'], 'registry', true, 'fintech', '{"tier":"S","primitive":"MATCHBOOK"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-MATCHBOOK-S2', 'MATCHBOOK S-Tier #2', 'Circuit Breaker Halt Controller', 96, ARRAY['MATCHBOOK'], 'registry', true, 'fintech', '{"tier":"S","primitive":"MATCHBOOK"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-SENTINEL_FIN-S1', 'SENTINEL_FIN S-Tier #1', 'Geo-Impossibility Detector', 97, ARRAY['SENTINEL_FIN'], 'registry', true, 'fintech', '{"tier":"S","primitive":"SENTINEL_FIN"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-SENTINEL_FIN-S2', 'SENTINEL_FIN S-Tier #2', 'Velocity Profiler', 95, ARRAY['SENTINEL_FIN'], 'registry', true, 'fintech', '{"tier":"S","primitive":"SENTINEL_FIN"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-REGULATOR-S1', 'REGULATOR S-Tier #1', 'AML Transaction Monitor', 97, ARRAY['REGULATOR'], 'registry', true, 'fintech', '{"tier":"S","primitive":"REGULATOR"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-REGULATOR-S2', 'REGULATOR S-Tier #2', 'Sanctions Screening Engine', 96, ARRAY['REGULATOR'], 'registry', true, 'fintech', '{"tier":"S","primitive":"REGULATOR"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-ARBITER-S1', 'ARBITER S-Tier #1', 'Pre-Arb Deflection Engine', 96, ARRAY['ARBITER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"ARBITER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-ARBITER-S2', 'ARBITER S-Tier #2', 'Chargeback Evidence Compiler', 95, ARRAY['ARBITER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"ARBITER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-UNDERWRITER-S1', 'UNDERWRITER S-Tier #1', 'Alt Data Credit Scorer', 96, ARRAY['UNDERWRITER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"UNDERWRITER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-UNDERWRITER-S2', 'UNDERWRITER S-Tier #2', 'PD Model Engine', 95, ARRAY['UNDERWRITER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"UNDERWRITER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TREASURER-S1', 'TREASURER S-Tier #1', 'Cash Position Forecaster', 96, ARRAY['TREASURER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TREASURER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-TREASURER-S2', 'TREASURER S-Tier #2', 'Interco Funding Optimizer', 95, ARRAY['TREASURER'], 'registry', true, 'fintech', '{"tier":"S","primitive":"TREASURER"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-AUDITOR-S1', 'AUDITOR S-Tier #1', 'Continuous Control Tester', 96, ARRAY['AUDITOR'], 'registry', true, 'fintech', '{"tier":"S","primitive":"AUDITOR"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-AUDITOR-S2', 'AUDITOR S-Tier #2', 'Tamper-Evident Audit Builder', 95, ARRAY['AUDITOR'], 'registry', true, 'fintech', '{"tier":"S","primitive":"AUDITOR"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-PORTFOLIO-S1', 'PORTFOLIO S-Tier #1', 'Dynamic Rebalancing Optimizer', 96, ARRAY['PORTFOLIO'], 'registry', true, 'fintech', '{"tier":"S","primitive":"PORTFOLIO"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-PORTFOLIO-S2', 'PORTFOLIO S-Tier #2', 'Model Portfolio Constructor', 95, ARRAY['PORTFOLIO'], 'registry', true, 'fintech', '{"tier":"S","primitive":"PORTFOLIO"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-COMPLIANCE-S1', 'COMPLIANCE S-Tier #1', 'Pre-Trade Compliance Gate', 97, ARRAY['COMPLIANCE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"COMPLIANCE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb),
  ('FIN-CJ-COMPLIANCE-S2', 'COMPLIANCE S-Tier #2', 'Trade Surveillance Engine', 95, ARRAY['COMPLIANCE'], 'registry', true, 'fintech', '{"tier":"S","primitive":"COMPLIANCE"}'::jsonb, 'fintech', 'Apex', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb)
) AS t(id, name, description, cjpi, module_chain, status, is_crown_jewel, vertical, crown_jewel_capabilities, category, tier, run_id, components)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.discoveries (id, name, description, cjpi, module_chain, status, is_crown_jewel, vertical, category, tier, run_id, components)
SELECT 'FNSD-' || lpad(i::text, 4, '0'), 'Fintech Discovery #' || i, 'Payment and risk chain', 80 + (i % 14), ARRAY['LEDGER','RISKCORE','PAYRAIL','DEFENSE'], 'showroom', false, 'fintech', (ARRAY['payment-processing','risk-management','regulatory-compliance','fraud-detection','settlement'])[1 + (i % 5)], 'Relic', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb
FROM generate_series(1, 50) AS i ON CONFLICT (id) DO NOTHING;

INSERT INTO public.discoveries (id, name, description, cjpi, module_chain, status, is_crown_jewel, vertical, category, tier, run_id, components)
SELECT 'FNSD-' || lpad((50+i)::text, 4, '0'), 'Fintech Discovery #' || (50+i), 'Low-confidence fintech pattern', 60 + (i % 15), ARRAY['TICKER','CLEARING','BRAIN'], 'junkyard', false, 'fintech', (ARRAY['trading','treasury','tax-computation','lending','portfolio-mgmt'])[1 + (i % 5)], 'Mint', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890'::uuid, '{}'::jsonb
FROM generate_series(1, 50) AS i ON CONFLICT (id) DO NOTHING;
