/**
 * Scan PDF Export — Gap #8
 * Generates a printable/downloadable scan report
 */

import { FileDown, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';
import { toast } from 'sonner';

interface ScanReportData {
  domain: string;
  score: number | null;
  created_at: string;
  metadata?: Record<string, unknown>;
}

export function ScanPDFExport({ scan }: { scan: ScanReportData }) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      // Build a printable HTML document
      const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Scan Report — ${scan.domain}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1a1a2e; }
    h1 { font-size: 24px; border-bottom: 2px solid #4a90c2; padding-bottom: 12px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
    .score { font-size: 64px; font-weight: bold; color: ${(scan.score ?? 0) >= 80 ? '#22c55e' : (scan.score ?? 0) >= 50 ? '#f59e0b' : '#ef4444'}; }
    .section { margin: 24px 0; padding: 16px; background: #f8f9fa; border-radius: 8px; }
    .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>CMPSBL Scan Report</h1>
  <div class="meta">
    <strong>Domain:</strong> ${scan.domain}<br/>
    <strong>Date:</strong> ${new Date(scan.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}<br/>
  </div>
  <div class="section">
    <div>Overall Score</div>
    <div class="score">${scan.score ?? 'N/A'}</div>
  </div>
  ${scan.metadata ? `<div class="section"><h3>Details</h3><pre style="font-size:12px;overflow:auto;">${JSON.stringify(scan.metadata, null, 2)}</pre></div>` : ''}
  <div class="footer">Generated by CMPSBL Substrate — cmpsbl.com</div>
</body>
</html>`;

      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const printWindow = window.open(url, '_blank');
      if (printWindow) {
        printWindow.onload = () => {
          printWindow.print();
        };
      }
      toast.success('Report opened — use Print → Save as PDF');
    } catch {
      toast.error('Failed to generate report');
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button variant="outline" size="sm" className="gap-2" onClick={handleExport} disabled={exporting}>
      {exporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
      Export PDF
    </Button>
  );
}
