/**
 * Release Report Generator
 * Writes JSON + Markdown reports to /reports/release/
 */

import { mkdirSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import type { ReleaseReport, PassResult } from './types';

function getGitSha(): string {
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
  } catch {
    return 'unknown';
  }
}

function getGitBranch(): string {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim();
  } catch {
    return 'unknown';
  }
}

export function buildReport(passes: PassResult[]): ReleaseReport {
  const passed = passes.filter(p => p.status === 'PASS').length;
  const failed = passes.filter(p => p.status === 'FAIL').length;
  const skipped = passes.filter(p => p.status === 'SKIP').length;
  const allRequiredPassed = passes
    .filter(p => p.required)
    .every(p => p.status === 'PASS');

  return {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    gitSha: getGitSha(),
    gitBranch: getGitBranch(),
    environment: process.env.CI ? 'ci' : 'local',
    passes,
    summary: {
      total: passes.length,
      passed,
      failed,
      skipped,
      allRequiredPassed,
      totalDurationMs: passes.reduce((s, p) => s + p.durationMs, 0),
    },
    metadata: {
      nodeVersion: process.version,
      platform: process.platform,
      ci: !!process.env.CI,
    },
  };
}

function statusIcon(s: string): string {
  if (s === 'PASS') return '✅';
  if (s === 'FAIL') return '❌';
  return '⏭️';
}

export function toMarkdown(report: ReleaseReport): string {
  const lines: string[] = [
    '# Release Gate Report',
    '',
    `**Timestamp:** ${report.timestamp}`,
    `**Git:** ${report.gitBranch} @ ${report.gitSha}`,
    `**Environment:** ${report.environment}`,
    `**Duration:** ${(report.summary.totalDurationMs / 1000).toFixed(1)}s`,
    '',
    '## Scoreboard',
    '',
    '| # | Pass | Status | Required | Duration |',
    '|---|------|--------|----------|----------|',
  ];

  for (const p of report.passes) {
    lines.push(
      `| ${p.pass} | ${p.name} | ${statusIcon(p.status)} ${p.status} | ${p.required ? 'Yes' : 'No'} | ${p.durationMs}ms |`
    );
  }

  lines.push('');
  lines.push(`## Verdict: ${report.summary.allRequiredPassed ? '✅ RELEASE APPROVED' : '❌ RELEASE BLOCKED'}`);
  lines.push('');
  lines.push(`- **Passed:** ${report.summary.passed}`);
  lines.push(`- **Failed:** ${report.summary.failed}`);
  lines.push(`- **Skipped:** ${report.summary.skipped}`);
  lines.push('');

  // Details per pass
  for (const p of report.passes) {
    if (p.notes.length > 0) {
      lines.push(`### Pass ${p.pass}: ${p.name}`);
      for (const n of p.notes) {
        lines.push(`- ${n}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by CMPSBL Release Gate*');
  return lines.join('\n');
}

export function writeReports(report: ReleaseReport): { jsonPath: string; mdPath: string } {
  const dir = join(process.cwd(), 'reports', 'release');
  mkdirSync(dir, { recursive: true });

  const ts = report.timestamp.replace(/[:.]/g, '-');
  const jsonPath = join(dir, `release-gate-${ts}-${report.gitSha}.json`);
  const mdPath = join(dir, 'latest.md');

  writeFileSync(jsonPath, JSON.stringify(report, null, 2));
  writeFileSync(mdPath, toMarkdown(report));

  return { jsonPath, mdPath };
}
